### ISSUE TITLE
Dockerfile and docker image on dockerhub

### ISSUE THREAD

**Issue by andrii29** [Altinity/clickhouse-backup#10]
Hello,
could you add Dockerfile and docker image on dockerhub?  
(something like this)  

```
# Build container
FROM golang:1.12.1-stretch

RUN git clone https://github.com/AlexAkulov/clickhouse-backup.git /go/src/clickhouse-backup
WORKDIR /go/src/clickhouse-backup
RUN go get
RUN go build -o /clickhouse-backup .

# Run container
FROM ubuntu:18.04

RUN apt-get update
RUN apt-get install -yqq  \
    ca-certificates \
    curl \
    git \
    && rm -rf /var/lib/apt/lists/*
COPY --from=0 /clickhouse-backup /usr/local/bin/
RUN chmod +x /usr/local/bin/clickhouse-backup
ENTRYPOINT [ "clickhouse-backup" ]
CMD [ "--help" ]
```

**Comment by AlexAkulov** [comment]
Thank you!

**Comment by AlexAkulov** [comment]
'clickhouse-backup' requires connection and direct access to files of 'clickhouse-server' to manage them.
I can create docker image of 'clickhouse-backup' but I don't think that it will be convenient to use. I will be glad if you try it and write me how to do it.

**Comment by andrii29** [comment]
@AlexAkulo, hello. 
You can use docker volumes
https://docs.docker.com/storage/volumes/
for example
`docker run --rm -it --network host -v "/path/to/clickhouse/data/on/host:/path/to/clickhouse/data/on/container" -v "/path/to/config.yml:/etc/clickhouse-backup/config.yml"  --name clickhouse_backup alexakulov/clickhouse-backup freeze`
and repeat with `upload` and `clean` commands

**Comment by anuriq** [comment]
considering that clickhouse will run on linux, it is not clear, why someone would use docker images instead of native go binary.

**Comment by andrii29** [comment]
hello
I'm not familiar with go language, also have bad idea how to build binary from source files (also i need installed golang).
Downloaded binary releases possible will not run properly on all linux distributives.
But docker is famous, easy to use, independent of language tool, witch allows to build and deploy apps by single command.
It would be much comfortable to have ability to use docker image.

**Comment by AlexAkulov** [comment]
Done

**Comment by andrii29** [comment]
@AlexAkulov  hello.
Thank You!
Could you push image to dockerhub?

**Comment by AlexAkulov** [comment]
Hi @andrii29!
Done
https://hub.docker.com/r/alexakulov/clickhouse-backup

**Comment by andrii29** [comment]
@AlexAkulov Thank You!
