### ISSUE TITLE
--diff-from and backups_to_keep_remote 

### ISSUE THREAD

**Issue by jawr** [Altinity/clickhouse-backup#100]
If i do an initial create/upload I am left with a 5G backup which appears correct. Subsequent calls to create/upload with --diff-from look to create the correct increments. However, when I exceed backups_to_keep_remote, the original backup is deleted leaving just the increments, unless I'm missing something, does this not silently destroy the backup?

**Comment by DrissiReda** [comment]
It does destroy the backups, not silently though, I think you need to do backup rotations manually, that way you can choose when to do full backups and when to do incrementals and when to archive the full backups. (Some choose weekly/monthly or even bi-weekly it's up to you).

**Comment by jawr** [comment]
Well i would argue that it is silent, as there are no warnings anywhere (including docs), but i agree that its not within the scope of this to handle rotations.

I’m putting together a PR for FTP support, will make a separate one for the README as i believe there is a lot of good information missing.
