### ISSUE TITLE
Some errors while create backup using FTP

### ISSUE THREAD

**Issue by amakeenk** [Altinity/clickhouse-backup#1002]
OS: ALT Server 10.2 x86_64

Packages:
- clickhouse-server-24.8.2.3-alt1
- clickhouse-backup-2.5.20-alt1
- proftpd-1.3.9-alt0.3.rc2

When creating a backup using FTP, errors of the following type occur:
<pre>
# clickhouse-backup create_remote test_backup_ftp

2024/09/02 10:38:41.633930  warn MkdirAll MakeDir(test_backup_ftp) return error: 550 test_backup_ftp: Permission denied logger=FTP
2024/09/02 10:38:41.634300  warn MkdirAll MakeDir(test_backup_ftp/shadow) return error: 550 test_backup_ftp/shadow: No such file or directory logger=FTP
2024/09/02 10:38:41.635000  warn MkdirAll MakeDir(test_backup_ftp/shadow/test_db) return error: 550 test_backup_ftp/shadow/test_db: No such file or directory logger=FTP
2024/09/02 10:38:41.635161  warn MkdirAll MakeDir(test_backup_ftp/shadow/test_db/test_table) return error: 550 test_backup_ftp/shadow/test_db/test_table: No such file or directory logger=FTP
</pre>

But the backup is created and then restored successfully.

**Comment by Slach** [comment]
These are just a warning, during concurrently creation sub-folders during upload data parts
You could ignore it or you are welcome to make Pull Request to `ftp.go` to fix it
