### ISSUE TITLE
Overwrite backup file locally  if it already exists

### ISSUE THREAD

**Issue by Baitur5** [Altinity/clickhouse-backup#1011]
Problem: Currently, our backup system does not support the ability to overwrite existing backup files automatically, if saving it locally. This leads to the accumulation of redundant backup files and requires manual intervention to manage backup storage effectively.

Expected Behavior: When creating backups, the system should check if a backup file with the same name already exists. If it does, the system should offer an option to overwrite the existing file automatically.

**Comment by Slach** [comment]
if you try to create backup with name which already exists looks something wrong with your backup system design

could you provide more context?

which clickhouse-backup commands workflow do you use?
which is your backup storage?
which is your backup retention policy?

**Comment by Slach** [comment]
any news from your side?

**Comment by Slach** [comment]
close issue after topic started inactivity
