### ISSUE TITLE
Set path to /var/lib/clickhouse using properties

### ISSUE THREAD

**Issue by caffeine-mgn** [Altinity/clickhouse-backup#1014]
Need a way to specify path to `/var/lib/clickhouse` in properties. It can be useful for case when clickhouse-backup run as cmd (I mean not as docker)

**Comment by Slach** [comment]
sorry for late reply,
how exactly did you run clickhouse-server? is this standalone systemd service or container?

could you share
`SELECT * FROM system.disks FORMAT Vertical`?

**Comment by Slach** [comment]
/var/lib/clickhouse/backup/ path calculated depends on `default` disk `path` from `system.disks`

close issue after topic started inactivity
