### ISSUE TITLE
Error while uploading backup on QNAP S3

### ISSUE THREAD

**Issue by EmPRio93** [Altinity/clickhouse-backup#102]
![image](https://user-images.githubusercontent.com/55250036/84856707-9bde3900-b091-11ea-8b09-a9ecaf6b58ea.png)
Any ideas how to solve this?

**Comment by AlexAkulov** [comment]
I will check it out!

**Comment by EmPRio93** [comment]
My config now is 
s3:
  access_key: ******:*************
  bucket: backup
  compression_format: gzip
  compression_level: 1
  disable_cert_verification: true
  disable_ssl: false
  endpoint: http://<my-qnap-host>:8010
  force_path_style: false
  part_size: 104857600
  path: production
  region: us-east-1
  s3server: us-east-1
  secret_key: ***********************
And i see the data is loading on the device but it's always fails at the end.

**Comment by Slach** [comment]
@EmPRio93 look like your QNAP S3 storage version have some errors during multipart uploads
according to https://www.qnap.com/en/how-to/tutorial/article/quobjects-amazon-s3-openstack-swift-compatible-apis, multipart upload API should works

could you check latest clickhouse-backup release from https://github.com/Altinity/clickhouse-backup/releases/tag/1.0.16?
remove `part_size` from your `s3` section and run `clickhouse-backup upload <backup-name>` again?

if fail, please add 
```
s3:
  debug: true
```


to your config
run `clickhouse-backup upload <backup_name>` again and share the results

**Comment by Slach** [comment]
sorry for late response

**Comment by Slach** [comment]
I close issue cause inactivity, feel free to reopen if necessary
