### ISSUE TITLE
Empty shadow directory.

### ISSUE THREAD

**Issue by usero4eg** [Altinity/clickhouse-backup#103]
Hi, Alex!

Im using CH in a docker container with mapped /var/lib/clickhouse directory.
Im trying to make backup on local machine via clickhouse-backup:
clickhouse-backup --version
Version:	 0.5.2
Git Commit:	 f7975491a6c117f4ce03dc30975bce16fe619da6
Build Date:	 2020-05-19

, and it work's not so well. When backup was made:

2020/06/24 10:16:54 Create backup 'ch_backup_2020-06-24'
2020/06/24 10:16:54 Freeze `table1`.`events`
2020/06/24 10:16:54 Freeze `table1`.`hits`
2020/06/24 10:16:54 Freeze `table2`.`events`
2020/06/24 10:16:54 Freeze `table2`.`hits`
2020/06/24 10:16:54 Freeze `table2`.`postbackLogs`
2020/06/24 10:16:54 Skip `system`.`metric_log`
2020/06/24 10:16:54 Skip `system`.`trace_log`
2020/06/24 10:16:54 Copy metadata
2020/06/24 10:16:54   Done.
2020/06/24 10:16:54 Move shadow
2020/06/24 10:16:54   Done.

I saw only metadata directory and empty shadow dir:

drwxr-xr-x 4 root root 4096 Jun 24 10:16 .
drwxr-xr-x 3 root root 4096 Jun 24 10:16 ..
drwxr-xr-x 4 root root 4096 Jun 24 10:16 metadata
drwxr-xr-x 2 root root 4096 Jun 24 10:16 shadow (it's empty):

total 8
drwxr-xr-x 2 root root 4096 Jun 24 10:16 .
drwxr-xr-x 4 root root 4096 Jun 24 10:16 ..

Im used CH backup utility via bash script: 

#!/bin/bash

BACKUP_NAME=ch_backup_$(date -u +%Y-%m-%d)

/usr/bin/clickhouse-backup create $BACKUP_NAME --config /etc/clickhouse-backup/config.yml

here is config.yml part:

clickhouse:
  username: default
  password: "password"
  host: localhost
  port: 9000
  data_path: "/var/lib/clickhouse"
  skip_tables:
  - system.*

Also I checked permissions into a docker container and locally mounted volume (/var/lib/clickhouse), here is:

docker container:

drwxr-xr-x 12 clickhouse clickhouse       4096 Jun   16 11:32       .
drwxr-xr-x  1   root              root               4096 May   23 17:59      ..
drwxr-xr-x  3  root              root                4096 Jun   24 08:16      backup
drwxr-x---  7  clickhouse  clickhouse     4096 Jun   16 05:27       data
drwxr-x---  2  clickhouse  clickhouse     4096 Jun    4 14:17        dictionaries_lib
drwxr-x---  2  clickhouse  clickhouse     4096 Jun    4 14:17        flags
drwxr-xr-x  2  clickhouse  clickhouse     4096 Jun    4 14:17        format_schemas
drwxr-x---  6  clickhouse  clickhouse     4096 Jun   10 12:43      metadata
drwxr-x---  2  clickhouse  clickhouse     4096 Jun    4 14:17        preprocessed_configs
drwxr-x---  2  clickhouse  clickhouse     4096 Jun   24 08:16      shadow
-rw-r-----  1   clickhouse  clickhouse     55      Jun    4 14:27        status
drwxr-xr-x  2  clickhouse  clickhouse     4096 Jun    4 14:17         tmp
drwxr-xr-x  2  clickhouse  clickhouse     4096 Jun    4 14:17         user_files

local machine:

drwxr-xr-x 12    systemd-resolve systemd-journal 4096 Jun 16 13:32         .
drwxr-xr-x 38    root                       root                       4096  Jun  5 08:50     ..
drwxr-xr-x  3     root                       root                       4096  Jun 24 10:16     backup
drwxr-x---  7     systemd-resolve  systemd-journal  4096  Jun 16 07:27     data
drwxr-x---  2     systemd-resolve  systemd-journal  4096  Jun  4 16:17      dictionaries_lib
drwxr-x---  2     systemd-resolve  systemd-journal  4096  Jun  4 16:17      flags
drwxr-xr-x  2     systemd-resolve  systemd-journal  4096  Jun  4 16:17      format_schemas
drwxr-x---  6     systemd-resolve  systemd-journal  4096  Jun 10 14:43    metadata
drwxr-x---  2     systemd-resolve  systemd-journal  4096  Jun  4 16:17     preprocessed_configs
drwxr-x---  2     systemd-resolve  systemd-journal  4096  Jun 24 10:16    shadow
-rw-r-----  1      systemd-resolve  systemd-journal    55     Jun  4 16:27     status
drwxr-xr-x  2     systemd-resolve  systemd-journal  4096  Jun  4 16:17      tmp
drwxr-xr-x  2     systemd-resolve  systemd-journal  4096  Jun  4 16:17      user_files

Could you explain me, what Im doing wrong?

p.s. thank you

**Comment by AlexAkulov** [comment]
Hi, Dmitry!

Try to run clickhouse-backup as a 'root' user.

**Comment by usero4eg** [comment]
> Hi, Dmitry!
> 
> Try to run clickhouse-backup as a 'root' user.

Im run it as root

**Comment by usero4eg** [comment]
Solved.

**Comment by zidingyi94** [comment]
> Solved.
 I  have the same problem, How did you solve it

**Comment by Slach** [comment]
@shanfeiyang which clickhouse-backup version do you use?
could you provide details about your environment? 
do you run clickhouse-server inside docker? 
do you run clickhouse-backup inside docker?
