### ISSUE TITLE
Backup not working using azblob with use_embedded_backup_restore flag as true

### ISSUE THREAD

**Issue by hermeswaldemarin** [Altinity/clickhouse-backup#1031]
The backup for azure is not working like expected when using the use_embedded_backup_restore: true. 

This is the env variable I'm using. 

AZBLOB_ACCOUNT_NAME=myaccount
AZBLOB_ENDPOINT_SUFFIX=core.windows.net
AZBLOB_ACCOUNT_KEY=my_access_key
AZBLOB_CONTAINER=my-backup-bucket

In this method, used by clickhouse-backup to access the container, the BlobEndpoint is constructed correctly 
[azblob.go#L94](https://github.com/Altinity/clickhouse-backup/blob/5ff464865417a4dd54af8108cd94d4c6bb12e2fa/pkg/storage/azblob.go#L94)

But when it sends the backup command to clickhouse the BlobEndpoint constructed is different and we receive an error by clickhouse in the command. 
[backuper.go#L352](https://github.com/Altinity/clickhouse-backup/blob/5ff464865417a4dd54af8108cd94d4c6bb12e2fa/pkg/backup/backuper.go#L352)

This is how the command is created to send to clickhouse. 

`BACKUP TABLE `myschema`.`json_layouts` TO AzureBlobStorage('DefaultEndpointsProtocol=https;AccountName=myaccount;AccountKey=my_access_key;BlobEndpoint=https://core.windows.net/myaccount;','my-backup-bucket','/chi-clickhouse-clickhouse-0-1-full-2024-10-22-15-48-46/') SETTINGS allow_azure_native_copy=1`

![image](https://github.com/user-attachments/assets/288a4f94-1fd8-4bd6-995a-6af288718cc7)

the Blob endpoint is wrong, should be BlobEndpoint=https://myaccount.blob.core.windows.net; instead. 

`BACKUP TABLE myschema.json_layouts TO AzureBlobStorage('DefaultEndpointsProtocol=https;AccountName=myaccount;AccountKey=my_access_key;BlobEndpoint=https://myaccount.blob.core.windows.net;', 'my-backup-bucket', '/chi-clickhouse-clickhouse-0-1-full-2024-10-22-15-48-46/') SETTINGS allow_azure_native_copy = 1 `

I also tried omitting the BlobEndpoint in the config and it also works. This command bellow also works...

`BACKUP TABLE myschema.json_layouts TO AzureBlobStorage('DefaultEndpointsProtocol=https;AccountName=myaccount;AccountKey=my_access_key', 'my-backup-bucket', '/chi-clickhouse-clickhouse-0-1-full-2024-10-22-15-48-46/') SETTINGS allow_azure_native_copy = 1 `

**Comment by Slach** [comment]
which `clickhouse-server` version do you use?

**Comment by hermeswaldemarin** [comment]
Clickhouse Version: 24.8.4.13
clickhouse-backup Version: 2.6.0

**Comment by hermeswaldemarin** [comment]
Hi @Slach , I was locking at the changes. 

[This](https://github.com/Altinity/clickhouse-backup/blob/97fd5a4da136d2fd9e7fe9cacfdccd44aadbf629/pkg/backup/backuper.go#L352) should be 

azblobBackupURL.Host = b.cfg.AzureBlob.AccountName + ".blob." + b.cfg.AzureBlob.EndpointSuffix

instead correct?

I tried to run with BlobEndpoint=https://myaccount.core.windows.net and didn't work.. 
need to be https://myaccount.blob.core.windows.net

**Comment by Slach** [comment]
@hermeswaldemarin thanks for reporting, now should works

**Comment by hermeswaldemarin** [comment]
It's working now @Slach . I did the tests with the "altinity/clickhouse-backup:master" image.

Just to organize myself here, when will the release 2.6.3 be released?

**Comment by Slach** [comment]
i can't provide any ETA look to https://github.com/Altinity/clickhouse-backup/milestone/74
and watch the progress
