### ISSUE TITLE
add support s3:// in <endpoint> section during parse object disk configuration

### ISSUE THREAD

**Issue by Slach** [Altinity/clickhouse-backup#1035]

**Comment by mithunputhusseri** [comment]
Hi @Slach Is it possible for me to work on this enhancement?. If yes, can I get more context on the requirement, any details on the development life cycle and setting up the dev environment.

**Comment by Slach** [comment]
don't be shy make pull request
look `pkg/storage/object_disk/object_disk.go` -> `getObjectDisksCredentials`
add e2e test in `test/integration/` or `test/testflows`

**Comment by mithunputhusseri** [comment]
Hi @Slach Can you share steps i can follow to run integration test locally. All the containers are up except the clickhouse server container. Failing with AWS S3 auth error. Should i setup an external AWS S3 endpoint for testing. I thought i could test with minio S3 container.

**Comment by Slach** [comment]
you need only worked `docker compose`
```
RUN_TESTS=TestNameRegexp ./test/integration/run.sh
RUN_TESTS=TestNameRegexp ./test/testflows/run.sh
```

**Comment by Slach** [comment]
> Should i setup an external AWS S3 endpoint for testing.

Look .env.example
rename to .env
and provide some credentials
