### ISSUE TITLE
Error when restoring database

### ISSUE THREAD

**Issue by mithunnutanix** [Altinity/clickhouse-backup#1043]
I have deleted my database using command

`DROP DATABASE dbname ON CLUSTER 'cluster-name' SYNC
`
And I am trying to restore using 

## for replica 1
`clickhouse-backup restore_remote --schema --rm backup-replica-1`
## for replica 2
`clickhouse-backup restore_remote --schema --rm backup-replica-2
`
## on replica 1
`clickhouse-backup restore_remote --data backup-replica-1
`

But i get this error when executing it

error="one of restoreDataRegular go-routine return error: can't attach data parts for table 'default.table1': default.table1 can't restore cause system.replicas entries already exists and replication in progress from another replica

**Comment by Slach** [comment]
try
`CLICKHOUSE_CHECK_REPLICAS_BEFORE_ATTACH=0 clickhouse-backup restore_remote --data backup-replica-1`

which `clickhouse-backup version` do you use?

**Comment by mithunnutanix** [comment]
@Slach 
I am using 2.6.3 version. Setting CLICKHOUSE_CHECK_REPLICAS_BEFORE_ATTACH=0 resolved the issue

**Comment by Slach** [comment]
do you have logs for `clickhouse-backup restore_remote --data backup-replica-1` without `CLICKHOUSE_CHECK_REPLICAS_BEFORE_ATTACH=0`

could you grep `log_pointer` in these logs?

**Comment by mithunnutanix** [comment]
Hi @Slach 

2024-11-07 18:22:18.938 FTL cmd/clickhouse-backup/main.go:668 > error="one of restoreDataRegular go-routine return error: can't attach data parts for table 'default.table': default.tabl1 can't restore cause system.replicas entries already exists and replication in progress from another replica, log_pointer=562, log_max_index=561, absolute_delay=0, queue_size=0"

**Comment by Slach** [comment]
@mithunnutanix 
hm, 
` log_pointer=562, log_max_index=561`
too high values

Do you still insert data into `default.tabl1` during restore?

Could you share?
```SELECT engine_full FROM system.tables WHERE database='default' AND table='tabl1'```

**Comment by mithunnutanix** [comment]
Hi @Slach 
Sorry I don't have the logs now. I had several backup files present locally. I removed them all. And ran the commands again. It worked. And I am not able to reproduce the issue.

Also, in the examples. It was backing up data from all replicas. And then restoring the schema's on all the replicas. And data is restored on single replica. Can't we just backup from single replica. And the single backup can be used to backup schema and data on all replicas right?

**Comment by Slach** [comment]
you don't need backup data from all replicas
you can backup only one replica per shard, this is should be enough

**Comment by Slach** [comment]
Yep, look to https://github.com/Altinity/clickhouse-backup/blob/master/Examples.md#how-to-back-up--restore-a-sharded-cluster
