### ISSUE TITLE
The clickhouse-backup restore has become very slow

### ISSUE THREAD

**Issue by lyi61pd** [Altinity/clickhouse-backup#1049]
Previously, when I executed the clickhouse-backup restore command, it only took a few seconds to complete the restoration. However, recently, during restoration, even after waiting for 30 minutes, it still hasn't finished. The logs show a large number of UPDATE operations, as shown below.

```
2024-11-28 06:55:16.675 INF pkg/clickhouse/clickhouse.go:1071 > ALTER TABLE `vul_db`.`cveinfo_cve_info` UPDATE CVE_description =
```

Recently, I redeployed the ClickHouse database using Docker, and the data should not have changed significantly. I don't understand why the restoration speed has suddenly slowed down so much. I hope to get some help with this issue.

```
root@c15710c8eed0:/# clickhouse-backup --version
Version:         2.6.0
Git Commit:      b7faa4a9c273ece943e406ebcca663065f1c41db
Build Date:      2024-08-29
```

**Comment by Slach** [comment]
`ALTER TABLE ... UPDATE `
this is mutations which was in progress during backup procedure
you can skip it during backup if add `/etc/clickhouse-backup/config.yml`

```
clickhouse:
  backup_mutations: false
```

could you share full log of restore?

**Comment by Slach** [comment]
@lyi61pd any news from your side?

**Comment by lyi61pd** [comment]
I'll try it there days, thanks for your reply!

**Comment by lyi61pd** [comment]
When I tried to reproduce the issue, I found that the restore operation can now be completed within a few seconds, and the situation that took more than 30 minutes originally is no longer present, so it's not possible to reproduce it again.

**Comment by lyi61pd** [comment]
Should I close this issue?

**Comment by Slach** [comment]
did you figure out with mutations and applied settings from https://github.com/Altinity/clickhouse-backup/issues/1049#issuecomment-2505483295?

If yes, and it's help, then we can close the issue
