### ISSUE TITLE
How to specify the backup path?

### ISSUE THREAD

**Issue by oracle-sky** [Altinity/clickhouse-backup#1050]
Can I use clickhouse-backup to avoid backing up to the data directory and customize the backup file directory instead? For example, can I back up to /backup?

**Comment by Slach** [comment]
https://github.com/Altinity/clickhouse-backup/?tab=readme-ov-file#dont-run-clickhouse-backup-remotely

this is physical backup which make hard links (not copy)
this is not allocate extra disk space until original files deletion after background parts merge or mutations
after creation a local backup you could move it to /backup/
look `remote_storage: custom` examples in https://github.com/Altinity/clickhouse-backup/tree/master/test/integration/rsync and https://github.com/Altinity/clickhouse-backup/blob/master/test/integration/config-custom-rsync.yml#L21-L25
