### ISSUE TITLE
Compression setting is not available for custom method

### ISSUE THREAD

**Issue by mithunnutanix** [Altinity/clickhouse-backup#1055]
Is there any reason why for custom method there is no default compression methods. Even in the test for custom method we are just copying the backups to custom storage without compression. Is it possible expose some compression methods for custom storage as well?

**Comment by Slach** [comment]
because for custom method compression is internal details for method implementation

during upload command custom upload.sh shall get local backup files, hard links and metadata from /var/lib/clickhouse/backup/backup_name and can free to apply any compression method
