### ISSUE TITLE
How to backup and restore a distributed cluster?

### ISSUE THREAD

**Issue by AlexanderChiuluvB** [Altinity/clickhouse-backup#106]
Let's say I have a cluster with 3 shards, each 1 replica. How to use the tool to backup the cluster more user-friendly?

**Comment by AlexAkulov** [comment]
Hi @AlexanderChiuluvB!

You must to backup each shard in cluster so you must run clickhouse-backup on multiply servers at the same time. For this you can use various automation tools like 'ansible' or 'pssh'. 
A recent PR added an http server (not in release yet) so you can create and restore backups via curl too.

**Comment by muraveynovosibirsk** [comment]
Hi, @AlexAkulov.
У нас в k8s установлен clickhouse-кластер из двух shard и двух реплик. Правильно ли я понял, что clickhouse-backup может забирать snapshots только локально? Т.е. для "полноценного" бэкапа кластера clickhouse-backup должен иметь доступ к директории с данными clickhouse-server.

**Comment by AlexAkulov** [comment]
Да, clickhouse-backup работает с хардлинками которые создаются при запуске FREEZE. Ему нужен локальный доступ к файлам Clickhouse для создания бэкапа, загрузки и восстановления.
