### ISSUE TITLE
error API /backup/restore error: one of restoreDataRegular go-routine return error: can't copy data to detached

### ISSUE THREAD

**Issue by jjtjiang** [Altinity/clickhouse-backup#1061]
Can you please help to see this issue
```
2024/12/11 01:15:24.062244  info ALTER TABLE `dw`.`dwd_basic_wide_all_test_local` ATTACH PART 'all_53_11214_11_33627' logger=clickhouse
2024/12/11 01:15:24.064920  info done                      backup=shard03-increment-20241210020057 duration=1.612s operation=restore table=dw.dwd_basic_wide_all_test_local
2024/12/11 01:15:24.064981  info clickhouse connection closed logger=clickhouse
2024/12/11 01:15:24.064999 error metrics.ExecuteWithMetrics(restore) return error: one of restoreDataRegular go-routine return error: can't copy data to detached 'ods.ods_bigdata_monitor_hudi_spark_job_status_metric': error during filepath.Walk for part '20221218_0_102_10': lstat /data2/clickhouse/data/db/backup/shard03-increment-20241210020057/shadow/ods/ods_bigdata_monitor_hudi_spark_job_status_metric/20221218_0_102_10: no such file or directory logger=metrics
2024/12/11 01:15:24.065038 error API /backup/restore error: one of restoreDataRegular go-routine return error: can't copy data to detached 'ods.ods_bigdata_monitor_hudi_spark_job_status_metric': error during filepath.Walk for part '20221218_0_102_10': lstat /data2/clickhouse/data/db/backup/shard03-increment-20241210020057/shadow/ods/ods_bigdata_monitor_hudi_spark_job_status_metric/20221218_0_102_10: no such file or directory logger=server
```

**Comment by Slach** [comment]
could you share
```SELECT * FROM system.disks```

is part present on disk?

`ls -la /data2/clickhouse/data/db/backup/shard03-increment-20241210020057/shadow/ods/ods_bigdata_monitor_hudi_spark_job_status_metric/20221218_0_102_10`
?

**Comment by jjtjiang** [comment]
no, this part is sure not present  for both source  server and target server 
![image](https://github.com/user-attachments/assets/dae8a649-786b-46fc-b7e3-529e67d9036c)

**Comment by Slach** [comment]
Ok. Let's figure out. 

Next time, please share text as text, not as a picture.
If possible, use `clickhouse-client` in the terminal, to avoid errors on JetBrains IDE (this has low quality clickhouse support)

Ok. you have only one disk on the destination server, could you share 
`cat/data2/clickhouse/data/db/backup/shard03-increment-20241210020057/metadata.json`?

**Comment by jjtjiang** [comment]
i have clean last backup ,the below is the same issue ,just like the above one 
2024/12/11 21:14:49.362764 error metrics.ExecuteWithMetrics(restore) return error: one of restoreDataRegular go-routine return error: can't copy data to detached 'default.ods_ext_p1_log_rt': error during filepath.Walk for part '20241029_0_8_2': lstat /data2/clickhouse/data/db/backup/shard01-increment-20241212010956/shadow/default/ods_ext_p1_log_rt/20241029_0_8_2: no such file or directory logger=metrics
2024/12/11 21:14:49.362804 error API /backup/restore error: one of restoreDataRegular go-routine return error: can't copy data to detached 'default.ods_ext_p1_log_rt': error during filepath.Walk for part '20241029_0_8_2': lstat /data2/clickhouse/data/db/backup/shard01-increment-20241212010956/shadow/default/ods_ext_p1_log_rt/20241029_0_8_2: no such file or directory logger=server

/data2/clickhouse/data/db/backup/shard01-increment-20241212010956/metadata.json  file is big ,so  i upload it as the attach file
[metadata.json](https://github.com/user-attachments/files/18105880/metadata.json)

**Comment by jjtjiang** [comment]
we could see there is no  default dir in path  /data2/clickhouse/data/db/backup/shard01-increment-20241212010956/shadow
ll  /data2/clickhouse/data/db/backup/shard01-increment-20241212010956/shadow
total 16
drwxr-x---  4 clickhouse clickhouse   97 Dec 11 17:21 dim
drwxr-x---  4 clickhouse clickhouse   95 Dec 11 17:21 dm
drwxr-x--- 40 clickhouse clickhouse 4096 Dec 11 17:24 dw
drwxr-x--- 85 clickhouse clickhouse 8192 Dec 11 17:37 ods

**Comment by Slach** [comment]
ok. source server also have one disk
```
	"disk_types": {
		"default": "local"
	},
	"version": "2.4.33",
```

how exactly do you download your backup from remote storage?
could you share `clickhouse-backup print-config` on destination server without sensitive credentials?


Do you still use clickhouse-backup 2.4.33 for restore?
Could you upgrade it to latest `2.6.4` and share `LOG_LEVEL=debug clickhouse-backup restore shard01-increment-20241212010956` ?
no need to download again if backup contains lot of data

also could you share
`clickhouse-backup list remote`
and 
`cat /data2/clickhouse/data/db/backup/shard01-increment-20241212010956/default/ods_ext_p1_log_rt.json`

**Comment by jjtjiang** [comment]
1.  i just only  back  it to target  clickhouse node ,the target path is /data2/clickhouse/data/db/backup ,  so  don't need to download it. source server cofig is as below

there is upload clickhouse-backup
```yaml
sftp:
    address:  #targe clichouse node address
    port: 22
    username:  
    password: " 
    key: ""
    path: "/data2/clickhouse/data/db/backup"
```

2 . I will  try use   latest 2.6.4 to  have a try  now .
3.  on destination server it is as below

```yaml
general:
    remote_storage: sftp
    max_file_size: 0
    disable_progress_bar: true
    backups_to_keep_local: 1
    backups_to_keep_remote: 1
    log_level: info
    allow_empty_backups: false
    download_concurrency: 64
    upload_concurrency: 8
    use_resumable_state: true
    restore_schema_on_cluster: ""
    upload_by_part: true
    download_by_part: true
    restore_database_mapping: {}
    retries_on_failure: 3
    retries_pause: 30s
    watch_interval: 1h
    full_interval: 24h
    watch_backup_name_template: shard{shard}-{type}-{time:20060102150405}
    sharded_operation_mode: ""
    cpu_nice_priority: 15
    io_nice_priority: idle
    retriesduration: 30s
    watchduration: 1h0m0s
    fullduration: 24h0m0s
clickhouse:
    username: *********
    password: ***********
    host: localhost
    port: 9000
    disk_mapping: {}
    skip_tables:
        - system.*
        - INFORMATION_SCHEMA.*
        - information_schema.*
        - _temporary_and_external_tables.*
    skip_table_engines:
        - Kafka
        - MaterializedView
        - Memory
        - Hive
        - HDFS
        - MySQL
        - JDBC
        - Buffer
    timeout: 5m
    freeze_by_part: false
    freeze_by_part_where: ""
    use_embedded_backup_restore: false
    embedded_backup_disk: ""
    backup_mutations: true
    restore_as_attach: false
    check_parts_columns: true
    secure: false
    skip_verify: false
    sync_replicated_tables: false
    log_sql_queries: true
    config_dir: /data2/clickhouse/config/
    restart_command: 'exec: sh /data2/clickhouse/clickhouse-server.sh  restart'
    ignore_not_exists_error_during_freeze: true
    check_replicas_before_attach: true
    tls_key: ""
    tls_cert: ""
    tls_ca: ""
    max_connections: 16
    debug: false
api:
    listen: 0.0.0.0:7171
    enable_metrics: true
    enable_pprof: false
    username: ""
    password: ""
    secure: false
    certificate_file: ""
    private_key_file: ""
    ca_cert_file: ""
    ca_key_file: ""
    create_integration_tables: false
    integration_tables_host: ""
    allow_parallel: false
    complete_resumable_after_restart: true
sftp:
    address: 888888
    port: 22
    username: **********
    password: ***********
    key: ""
    path: /data/clickhouse/data/db/backup
    object_disk_path: ""
    compression_format: none
    compression_level: 1
    concurrency: 48
    debug: false
```

`/data2/clickhouse/data/db/backup/shard01-increment-20241212010956/default` is not exists 
so can't cat it 
`cat /data2/clickhouse/data/db/backup/shard01-increment-20241212010956/default/`

on target `list local` is as below
```json
{
    "name": "shard01-full-20241211092802",
    "created": "2024-12-11 09:57:49",
    "size": 2398491661952,
    "location": "local",
    "required": "",
    "desc": "directory, regular"
}
{
    "name": "shard01-increment-20241212010956",
    "created": "2024-12-12 01:20:22",
    "size": 2409519901906,
    "location": "local",
    "required": "shard01-full-20241211092802",
    "desc": "directory, regular"
}
```

**Comment by jjtjiang** [comment]
when i use  clickhouse-backup  latest 2.6.4  for restore this table and using debug mode  , it returns the below log 

```
2024-12-11 23:08:21.062 INF pkg/backup/restore.go:908 > done backup=shard01-increment-20241212010956 duration=3.407s operation=restore_schema
2024-12-11 23:08:21.069 DBG pkg/backup/restore.go:1309 > found 1 tables with data in backup
2024-12-11 23:08:21.069 INF pkg/clickhouse/clickhouse.go:1080 > SELECT name, count(*) as is_present FROM system.settings WHERE name IN (?, ?) GROUP BY name with args [show_table_uuid_in_table_create_query_if_not_nil display_secrets_in_show_and_select]
2024-12-11 23:08:21.074 INF pkg/clickhouse/clickhouse.go:1082 > SELECT name FROM system.databases WHERE engine IN ('MySQL','PostgreSQL','MaterializedPostgreSQL')
2024-12-11 23:08:21.076 INF pkg/clickhouse/clickhouse.go:1082 >    SELECT     countIf(name='data_path') is_data_path_present,     countIf(name='data_paths') is_data_paths_present,     countIf(name='uuid') is_uuid_present,     countIf(name='create_table_query') is_create_table_query_present,     countIf(name='total_bytes') is_total_bytes_present    FROM system.columns WHERE database='system' AND table='tables'  
2024-12-11 23:08:21.081 INF pkg/clickhouse/clickhouse.go:1082 > SELECT database, name, engine , data_paths , uuid , create_table_query , coalesce(total_bytes, 0) AS total_bytes   FROM system.tables WHERE is_temporary = 0 AND match(concat(database,'.',name),'^default\.ods_ext_p1_log_rt$')  AND NOT has(arrayMap(x->lower(x), ['Kafka','MaterializedView','Memory','Hive','HDFS','MySQL','JDBC','Buffer']), lower(engine)) ORDER BY total_bytes DESC SETTINGS show_table_uuid_in_table_create_query_if_not_nil=1
2024-12-11 23:08:21.165 INF pkg/clickhouse/clickhouse.go:1082 > SELECT metadata_path FROM system.tables WHERE database = 'system' AND metadata_path!='' LIMIT 1;
2024-12-11 23:08:21.167 INF pkg/clickhouse/clickhouse.go:1082 > SELECT sum(bytes_on_disk) as size FROM system.parts WHERE active AND database='default' AND table='ods_ext_p1_log_rt' GROUP BY database, table
2024-12-11 23:08:21.172 DBG pkg/filesystemhelper/filesystemhelper.go:162 > MkDirAll /data2/clickhouse/data/db/data/default/ods_ext_p1_log_rt/detached/20241029_0_8_2
2024-12-11 23:08:21.172 INF pkg/clickhouse/clickhouse.go:327 > clickhouse connection closed
2024-12-11 23:08:21.172 FTL cmd/clickhouse-backup/main.go:668 > error="one of restoreDataRegular go-routine return error: can't copy data to detached 'default.ods_ext_p1_log_rt': error during filepath.Walk for part '20241029_0_8_2': lstat /data2/clickhouse/data/db/backup/shard01-increment-20241212010956/shadow/default/ods_ext_p1_log_rt/default/20241029_0_8_2: no such file or directory"
```

**Comment by Slach** [comment]
```
api:
    listen: 0.0.0.0:7171
    enable_pprof: false
    username: ""
    password: ""
```

This is dangerous without authorization

and better `enable_pprof:true` this is don't allocate resources without request to `:7171/debug/pprof*`

**Comment by Slach** [comment]
> i just only back it to target clickhouse node ,the target path is /data2/clickhouse/data/db/backup , so don't need to download it. source server cofig is as below

iI think we found a root reason

`create` always create full backup, cause this is hard links to exists files, it doesn't allocate of disk space

increment calculates during `upload`, data parts which already present in --diff-from-remote <backup_name>, will mark in `backup_name/metadata/db/table.json` -> `parts` section as `required` and will skip during upload.

but, it requires resolving increment parts back during `download` operation
you skip the `download` operation and your part marked as `required` is not resolved and not downloaded

I would like to recommend using `remote_storage: custom`
and use `rsync` for your use case

look https://github.com/Altinity/clickhouse-backup/tree/master/test/integration/rsync/
and https://github.com/Altinity/clickhouse-backup/blob/master/test/integration/config-custom-rsync.yml

it allows upload backup and makes hard links to exists files on the destination server, it should allow avoid `download` to resolve increment
