### ISSUE TITLE
user --schema restore schema only and skip already exist table？

### ISSUE THREAD

**Issue by amsenhao** [Altinity/clickhouse-backup#1064]
Hello
clickhouse-backup
```
clickhouse-backup --v
Version:         2.5.23
Git Commit:      289b4b1f9c0926d16e0e3e569d387187b7910606
Build Date:      2024-08-04
```
Clickhouse Server

```
clickhouse-server --version
ClickHouse server version 23.8.15.35 (official build).
```
Clickhouse-backup config
```
clickhouse:
  backup_mutations: true
  check_parts_columns: true
  check_replicas_before_attach: true
  config_dir: /clickhouse/clickhouse-server
  debug: false
  disk_mapping:
    default: /data/clickhouse
  embedded_backup_disk: ''
  freeze_by_part: false
  freeze_by_part_where: ''
  ignore_not_exists_error_during_freeze: true
  log_sql_queries: true
  max_connections: 0
  restore_as_attach: false
  secure: false
  skip_table_engines: []
  skip_tables:
  - system.*
  - INFORMATION_SCHEMA.*
  - information_schema.*
  skip_verify: true
  sync_replicated_tables: true
  timeout: 5m
  use_embedded_backup_restore: false
```
and database and tables already exist in the environment，use --schema parameter to recover data，existing tables will be deleted.
![image](https://github.com/user-attachments/assets/97766f16-c64c-41d3-88c9-8c3dd27d0e2c)
How can skip existing tables？

**Comment by Slach** [comment]
upgrade your clickhouse-backup to 2.6.4
`--schema` means restore only schema from backup

as workaround
to avoid drop exists tables you need to get list of exists tables and add it to CLICKHOUSE_SKIP_TABLES

for CLI you could use something like that
```
clickhouse-backup restore --schema --env="CLICKHOUSE_SKIP_TABLES=$(clickhouse-client -q \"SELECT arrayStringConcat(groupArray(database || '.' || name), ',') AS tables_with_databases FROM system.tables WHERE database='your-database' FORMAT TSVRaw\")"
```

for API or SQL you need two separate requests
first
`SELECT arrayStringConcat(groupArray(database || '.' || name), ',') AS tables_with_databases FROM system.tables WHERE database='your-database' FORMAT TSVRaw`

second POST /backup/actions with `--env`
or `INSERT INTO system.backup_actions(command) VALUES('restore --schema --env=list_of_tables_comma_separated_from_previous_select')`
