### ISSUE TITLE
How to recover data with different field types in two tables

### ISSUE THREAD

**Issue by amsenhao** [Altinity/clickhouse-backup#1068]
Hello
clickhouse-backup

```
clickhouse-backup --v
Version:         2.5.23
Git Commit:      289b4b1f9c0926d16e0e3e569d387187b7910606
Build Date:      2024-08-04
```

Clickhouse Server
```
clickhouse-server --version
ClickHouse server version 23.8.15.35 (official build).
```
n the old table, there is a 'test_2'  of type String. In the new table, there is a field with the same field name but of type Int64. Can the data be backed up from the old table and restored only to the new table?

**Comment by amsenhao** [comment]
I tried using some test data and there were no errors when performing data recovery, but there were the following errors when opening the table
![image](https://github.com/user-attachments/assets/a6864943-e44c-45f4-9be8-3efc68f8aaa7)

**Comment by amsenhao** [comment]
I tried using some test data and there were no errors when performing data recovery, but there were the following errors when opening the table
![image](https://github.com/user-attachments/assets/623db64c-215d-4552-b33c-1426a69ae265)

**Comment by Slach** [comment]
please STOP SHARE text as pictures, this is mental degradation ...


>  the old table, there is a 'test_2' of type String. In the new table, there is a field with the same field name but of type Int64. Can the data be backed up from the old table and restored only to the new table?

no, this is not possible

use on new server
```sql
clickhouse-client -q "INSERT INTO new_table SELECT toInt64(test_2) FROM remote('old_server',db.old_table, 'user','password')
```

**Comment by Slach** [comment]
`attack100` is not valid Int64 value
