### ISSUE TITLE
Backup by using Datetime/timestamp or something

### ISSUE THREAD

**Issue by robingood556** [Altinity/clickhouse-backup#1069]
Hi , team)

I dont wanna create full backup, how can i create only by date? For last month/yeat e.t.c.

**Comment by Slach** [comment]
in common case, this is not `clickhouse-backup` use case

you can try to use `--partitions=XXXX,YYYY` parameter but this is not applicable if your table miss PARTITION BY clause or this clause is not related to your backup condition (partitions by months but need backup by last day data)

you could try

for backup
`clickhouse-client -q "SELECT * FROM db.table WHERE date_field >= now() - INTERVAL 7 DAY FORMAT Native" | gzip > db.table.last-week.gz`

and for restore
`zcat db.table.last-week.gz | clickhouse-client --echo --progress -q "INSERT INTO FORMAT Native"`

**Comment by robingood556** [comment]
Yeah, i know about standart method, but i think about maybe we should create functionality for interval backup? no?

**Comment by Slach** [comment]
`clickhouse-backup` make physical backup by creating file-system hard links to exist data files

with this approach, you can't make hard links to `part of file`
