### ISSUE TITLE
 unexpected EOF

### ISSUE THREAD

**Issue by kendn1993** [Altinity/clickhouse-backup#109]
clickhouse-backup verion
Version:	 0.5.2
Git Commit:	 f7975491a6c117f4ce03dc30975bce16fe619da6
Build Date:	 2020-05-19

minio-version
minio version RELEASE.2020-07-13T18-09-56Z

clickhouse-version
ClickHouse server version 20.6.3.28 (official build).

when I use download from minio,it  work for a while ,then i got this error, unexpected EOF,hao can I did with it.

![image](https://user-images.githubusercontent.com/27141040/90090377-6f276480-dd56-11ea-9f32-30e441d05d94.png)

**Comment by kendn1993** [comment]
I tried many times, it always like this.

**Comment by kendn1993** [comment]
![image](https://user-images.githubusercontent.com/27141040/90092216-ebbc4200-dd5a-11ea-8e72-1f5a2071565a.png)
when i use small file.it can work.

**Comment by kendn1993** [comment]
As I add this param proxy_max_temp_file_size 0  to nginx ,it works fine;I think it isnginx that hava limited the file size.

**Comment by AlexAkulov** [comment]
Thanks a lot for describing the solution!
