### ISSUE TITLE
API_LISTEN_ADDR has no effect

### ISSUE THREAD

**Issue by juris** [Altinity/clickhouse-backup#113]
If I set API_LISTEN_ADDR="0.0.0.0:7171" process still starts with
```
2020/09/01 08:46:31 Starting API server on localhost:7171
```
and I'm unable to connect to API from remote hosts.

**Comment by juris** [comment]
Figured it out. It's `API_LISTEN` rather that `API_LISTEN_ADDR` in the code. Please update docs or `pkg/chbackup/config.go`

Cheers!

**Comment by AlexAkulov** [comment]
Thank you!
Fixed in https://github.com/AlexAkulov/clickhouse-backup/commit/7d7df1e36575f0d94d330c7bfe00aef7a2100276
