### ISSUE TITLE
unable to create server [no server flag]

### ISSUE THREAD

**Issue by manish-useriq** [Altinity/clickhouse-backup#118]
`clickhouse-backup server` errors out saying 
`Error. Unknown command: 'server'`

the build `v0.5.2` does not list the `server` flag, is it not currently supported? I see it in the [code](https://github.com/AlexAkulov/clickhouse-backup/blob/master/main.go#L207) though.

[API Section](https://github.com/AlexAkulov/clickhouse-backup#api)

`Version:	 0.5.2`
`Git Commit:	 f7975491a6c117f4ce03dc30975bce16fe619da6`
`Build Date:	 2020-05-19`

<img width="1094" alt="ch_no_server_option" src="https://user-images.githubusercontent.com/66319502/94776709-d15c2780-03df-11eb-9673-4f3c9c62314c.png">

**Comment by AlexAkulov** [comment]
This added in [v0.6.0](https://github.com/AlexAkulov/clickhouse-backup/releases/tag/v0.6.0)
