### ISSUE TITLE
Restore not possible for table with name containing '-'

### ISSUE THREAD

**Issue by LH-Datarocks** [Altinity/clickhouse-backup#119]
When a table contains a '-' in its name (for example `test-1`), restoration doesn't work.

Steps to reproduce : 

1. create table : 
```
CREATE TABLE `test-1` (id String) \  
ENGINE = MergeTree()  \
ORDER BY (id)  \
SETTINGS index_granularity = 8192;
```
2. insert data : 
```
insert into `test-1` values ('a');
```
3. backup : 
```
$ sudo clickhouse-backup --config clickhouse-backup/config.yml create test
```
4. drop table : 
```
DROP TABLE `test-1`
```
5. restore : 
```
$ sudo clickhouse-backup --config clickhouse-backup/config.yml restore test
```
Error : 
```
2020/10/08 07:45:00 Create table 'default.test-1'  
2020/10/08 07:45:00 Prepare data for restoring 'default.test-1'  
2020/10/08 07:45:00 ALTER TABLE `default`.`test-1` ATTACH PART 'all_1_1_0'  
2020/10/08 07:45:00 can't attach partitions for table 'default.test-1': code: 233, message: Detached part "all_1_1_0" not found  
```

The error seems to happen because the '-' character is hex encoded in the backup table directory name : 

```
$ ls backup/test/shadow/default/
test%2D1
```

Thanks in advance for fixing this issue.

**Comment by LH-Datarocks** [comment]
Actually, the directory name is ok as it is stored that way by clickhouse.

The name is ok when restoring schema : 

```
$sudo clickhouse-backup --config clickhouse-backup/config.yml restore test --schema
2020/10/08 10:07:37 Create table 'default.test-1'
$ ls clickhouse-data/data/default/ -al                                           total 12
drwxr-x--- 3 systemd-resolve systemd-journal 4096 Oct  8 10:07 .
drwxr-x--- 4 systemd-resolve systemd-journal 4096 Oct  8 07:43 ..
drwxr-x--- 3 systemd-resolve systemd-journal 4096 Oct  8 10:07 test%2D1
```

The directory name is however not hex encoded hence wrong when restoring data :

```  
$ sudo clickhouse-backup --config clickhouse-backup/config.yml restore test --data
2020/10/08 10:07:52 Prepare data for restoring 'default.test-1'
2020/10/08 10:07:52 ALTER TABLE `default`.`test-1` ATTACH PART 'all_1_1_0'
2020/10/08 10:07:52 can't attach partitions for table 'default.test-1': code: 233, message: Detached part "all_1_1_0" not found
$ ls clickhouse-data/data/default/ -al                                           total 16
drwxr-x--- 4 systemd-resolve systemd-journal 4096 Oct  8 10:07 .
drwxr-x--- 4 systemd-resolve systemd-journal 4096 Oct  8 07:43 ..
drwxr-x--- 3 systemd-resolve systemd-journal 4096 Oct  8 10:07 test%2D1
drwxr-x--- 3 root            root            4096 Oct  8 10:07 test-1
```

If I move data from **test-1** to **test%2D1**, the restoration works fine.

Hope it'll make things clearer.

**Comment by LH-Datarocks** [comment]
A solution would be to add the '-' to '%2D' replacement  in  [https://github.com/AlexAkulov/clickhouse-backup/blob/7d7df1e36575f0d94d330c7bfe00aef7a2100276/pkg/chbackup/utils.go#L195](https://github.com/AlexAkulov/clickhouse-backup/blob/7d7df1e36575f0d94d330c7bfe00aef7a2100276/pkg/chbackup/utils.go#L195)

such as : 

```
strings.ReplaceAll(strings.ReplaceAll(url.PathEscape("/a/test-1"), ".", "%2E"), "-", "%2D"))
```
This doesn't explain however why the restore --schema and --data behave differently.

To be complete, best would probably be to do the same replacement clickhouse does, maybe here :  

[https://github.com/ClickHouse/ClickHouse/blob/ea6f90b4f2c3cc2f7d8b846c769b7f3e84907e47/src/Common/escapeForFileName.cpp](https://github.com/ClickHouse/ClickHouse/blob/ea6f90b4f2c3cc2f7d8b846c769b7f3e84907e47/src/Common/escapeForFileName.cpp)

**Comment by AlexAkulov** [comment]
Thank you for detailed description of issue!
You solution works great!
