### ISSUE TITLE
Backup/restore of other object than tables ?

### ISSUE THREAD

**Issue by Stephane987** [Altinity/clickhouse-backup#121]
Hi, I'm wondering if

- databases will be created on restore ? Or do we need to create each database manualy before ?
- Will Access Control and Account Management (User account, Role,  Row Policy, Settings Profile, Quota) also be backed-up and restored ? 

Or is there another solution to backup and restore the entire server DDL ?

Thanks

**Comment by AlexAkulov** [comment]
Hi @Stephane-Thales 
- Yes, databases will be created on restore
- ACL is new function in ClickHouse and I have not look at i yet. Maybe it will be supported in future versions of clickhouse-backup.
