### ISSUE TITLE
Support for Atomic database engine

### ISSUE THREAD

**Issue by AlexAkulov** [Altinity/clickhouse-backup#126]
Atomic is the default database engine since ClickHouse 20.10

**Comment by fzyzcjy** [comment]
Hi, I wonder when will it be supported? Thanks!

**Comment by AlexAkulov** [comment]
Added in [v1.0.0-alpha1](https://github.com/AlexAkulov/clickhouse-backup/releases/tag/v1.0.0-alpha1)
