### ISSUE TITLE
Replicated merge tree

### ISSUE THREAD

**Issue by DrissiReda** [Altinity/clickhouse-backup#127]
I have a kubernetes cluster of multiple nodes running replicated merge tree. Which of these nodes data should clickhouse-backup run on? (which /var/lib/clickhouse). Do I need both? or any of them will do?

And during restore, will it create back replicated tables properly synchronized? (ON cluster). I'm only using this for disaster recovery, so I don't mind being able to only do full restore on an empty database.

**Comment by AlexAkulov** [comment]
Hi @DrissiReda 
If the replica is synchronized, you only need to have a backup on one replica host. But is better to have backup on all hosts, just in case.
For restoring you must create table on all hosts in replica. Its not important if the table was created via one query with 'ON CLUSTER' or via running `clickhouse-backup restore --schema` on all hosts.  
Data must be restored only one host and clickhouse itself copies data to all other hosts in replica.

**Comment by Slach** [comment]
question is answered so i close issue due inactivity
