### ISSUE TITLE
driver: bad connection on large backup

### ISSUE THREAD

**Issue by fassisrosa** [Altinity/clickhouse-backup#128]
Hi there,

I am using clickhouse-backup on a large table. Info as follows:

* Table size in number of records:  15,607,334,104
* Table size in disk: over 1Tb

When calling clickhouse-backup I eventually get:

```
2020/11/10 18:43:50 Freeze `mydb`.`mytable` 
2020/11/10 18:46:50 can't freeze `mydb`.`mytable` with: driver: bad connection
```

This happens at exactly three minutes running. Looking online it seems like this could be a timeout issue. Do you know if we should change any clickhouse config to support this? Or should clickhouse-backup pass along any other url param to prevent these bad connection issues?

Thanks.

**Comment by fassisrosa** [comment]
Would the 'freeze_by_part' param in config file help here?

I wonder if that reduces the interaction time. In the example above, we do have several parts for the table, one part per day and tenant. We have maybe around 90 days of data and several tenants.

**Comment by fassisrosa** [comment]
I am using 0.5.1, will try latest version with both 'freeze_by_part' and 'timeout' param see if it addresses it.

**Comment by AlexAkulov** [comment]
Yes 'freeze_by_part' and 'timeout' have been added for your case. 
Try to use 0.6.1 with `freeze_by_part: true`

**Comment by fassisrosa** [comment]
Yes, makes sense. Tried 0.6.1 this is running against CH version 19.1.13, I see:

```
2020/11/12 18:01:17 code: 47, message: Unknown identifier: hash_of_uncompressed_files, context: required_names: 'uncompressed_hash_of_compressed_files' 'name' 'database' 'path' 'active' 'hash_of_all_files' 'table' 'partition' 'hash_of_uncompressed_files' source_tables: 'system.parts' table_aliases: private_aliases: column_aliases: public_columns: 'uncompressed_hash_of_compressed_files' 'name' 'path' 'active' 'hash_of_all_files' 'partition' 'hash_of_uncompressed_files' masked_columns: array_join_columns: source_columns: 'partition' 'name' 'active' 'database' 'table' 'path'
```
It looks like columns did not exist in my CH version. Backup does seem to succeed. What is the impact on the backup/restore process of not having the parts hash metadata?

**Comment by AlexAkulov** [comment]
This message means that this backup cannot be restored using the new "flashback" command. But it can be restored correctly with the usual "restore" command.

**Comment by fassisrosa** [comment]
Thanks @AlexAkulov ! This answers my question perfectly. Will close accordingly as new params and new version seem to address it.

Really nice clickhouse backup tool!!!
