### ISSUE TITLE
Expose default database name in config

### ISSUE THREAD

**Issue by telubeer** [Altinity/clickhouse-backup#13]
My clickhouse setup do not contain database with name 'default'.
and  i can not create backup with 'can't connect to clickouse with: code: 81, message: Database default doesn't exist' error. 
and config file does not contain database option.
am i miss something?

**Comment by anuriq** [comment]
hi @telubeer 
`default` db is usually present after first installation of Clickhouse. it may be that you deleted it afterwards. i recommend you just create it and leave empty. it is not used to store data or anything, it's just a default database to connect to.

**Comment by AlexAkulov** [comment]
Now clickhouse-backup will connect to 'system' database. Please, try version from last commit.

**Comment by telubeer** [comment]
hello, @anuriq! Thank you for response.
I set up another default database name in clickhouse config.xml.
So database with named 'default' never be created or deleted on my server.
I expect this option will be respected in connections without database name provided directly.
Is this behavior related to clickhouse-backup tool or relative to go clickhouse driver?  
Where is should post issue?

**Comment by telubeer** [comment]
Hello @AlexAkulov! Thank you for quick response.
I think, 'system' database should resolve my issue, i will try master branch.
