### ISSUE TITLE
Notification when user has no access to tables

### ISSUE THREAD

**Issue by dmlogv** [Altinity/clickhouse-backup#130]
I've tried to use `clickhouse-backup` for the first time and have faced difficulty: there are absolutely no messages if the connection user does not have permissions to tables nor system catalog (e. g. `default`).

Of course, I've tried to connect running `clickhouse-backup` under `clickhouse` and `root` system users.

It took a long time until I guessed that I need to specify a database user with all permissions :)

**Comment by AlexAkulov** [comment]
Yes, clickhouse-backup connects to 'system' database and its assumed that backup user have permissions for this database.
Access to tables in 'system' database needs for backup creation.

**Comment by Slach** [comment]
@dmlogv is the issue still relevant for you?
according to the current state of source code any clickhouse SQL errors should be logged, if you currently have user which not have privileges could you try to https://github.com/Altinity/clickhouse-backup/releases/tag/1.0.16 and share the results of
```
clickhouse-backup create
```
and
```
LOG_LEVEL=debug clickhouse-backup create
```

**Comment by dmlogv** [comment]
@Slach thanks for your answer. Unfortunately, I no longer administer ClickHouse and I can't check your option, but I take on trust it works 😄

**Comment by Slach** [comment]
@dmlogv thanks for feedback, lets close the issue
