### ISSUE TITLE
Tool creating 0 B backup file or part hash only file without table backup. 

### ISSUE THREAD

**Issue by renjithtr** [Altinity/clickhouse-backup#131]
Hi Alex,

Thanks for creating this wonderful tool. 

And we are just started using Clickhouse cluster in Kubernetes using operator. And I was configured clickhouse-backup tool to take backup every 24 hours and upload it in to CEPH storage s3 bucket. It was working fine in the first time (not checked the download from s3 remote storage option)  after few weeks when I check the backup data it is a 0 B file and there is no metadata folder and table details. Below is the run result.

2020/11/19 07:02:31 Create backup '2020-11-19'
2020/11/19 07:02:31 Skip 'system.asynchronous_metric_log'
2020/11/19 07:02:31 Skip 'system.metric_log'
2020/11/19 07:02:31 Skip 'system.query_log'
2020/11/19 07:02:31 Skip 'system.trace_log'
2020/11/19 07:02:31 Copy part hashes
2020/11/19 07:02:31 Skip 'system.asynchronous_metric_log'
2020/11/19 07:02:31 Skip 'system.metric_log'
2020/11/19 07:02:31 Skip 'system.query_log'
2020/11/19 07:02:31 Skip 'system.trace_log'
2020/11/19 07:02:31 Writing part hashes
2020/11/19 07:02:31 Copy metadata
2020/11/19 07:02:31   Done.
2020/11/19 07:02:31 Move shadow
2020/11/19 07:02:31   Done.
2020/11/19 07:02:31 Upload backup '2020-11-19'
 2 B / 2 B  100.00% 1s
2020/11/19 07:02:33   Done.

After I just upgraded the version from 0.6.0 to 0.6.1 started creating part hashes file. And using the same backup I am getting the below error.

2020/11/24 05:25:07 stat /var/lib/clickhouse/backup/XX-test/metadata: no such file or directory

**Run the below docker and command**

apiVersion: v1
kind: Pod
metadata:
  name: clh-backup-exp
spec:
  restartPolicy: Never
  containers:
  - name: clh-backup-exp
    image: harbor.XXXX.XXXX.com/syseng/clickhouse-backup@sha256:8f6cc5138b18eb9cdc6d1f7a2468b1b782e542ec3c3b90e4cb243cbfdc614a8e
    imagePullPolicy: IfNotPresent
    command: ["/bin/sh","-c"]
    args: [" clickhouse-backup download remote  2020-11-17 ; clickhouse-backup download restore  2020-11-17"]
    volumeMounts:
      - mountPath: /etc/clickhouse-backup/
        name: config-volume

  volumes:
  - name: config-volume
    secret:
        defaultMode: 420
        secretName: backup-config

**Log**

2020/11/19 09:46:16 stat /var/lib/clickhouse/backup/2020-11-17/metadata: no such file or directory

**Configuration used.**

# default: "/etc/clickhouse-backup/config.yml"
general:
  remote_storage: s3           # REMOTE_STORAGE
  disable_progress_bar: false  # DISABLE_PROGRESS_BAR
  backups_to_keep_local: 0     # BACKUPS_TO_KEEP_LOCAL
  backups_to_keep_remote: 2    # BACKUPS_TO_KEEP_REMOTE
clickhouse:
  username: XXXXX            # CLICKHOUSE_USERNAME
  password: XXXXXX   # CLICKHOUSE_PASSWORD
  host: XXXXXX      # CLICKHOUSE_HOST
  port: 9000                   # CLICKHOUSE_PORT
  timeout: 5m                  # CLICKHOUSE_TIMEOUT
  data_path: "/var/lib/clickhouse"  # CLICKHOUSE_DATA_PATH
  skip_tables:                 # CLICKHOUSE_SKIP_TABLES
    - system.*
  freeze_by_part: false        # CLICKHOUSE_FREEZE_BY_PART
s3:
  access_key: "XXXXXXX"  # S3_ACCESS_KEY
  secret_key: "XXXXXXXXX"    # S3_SECRET_KEY
  bucket: "clh-backup"          # S3_BUCKET
  endpoint: "http://s3.ceph.atl.XXXX.XXXX.XXX"      # S3_ENDPOINT
  region: us-east-1                # S3_REGION
  acl: private                     # S3_ACL
  force_path_style: false          # S3_FORCE_PATH_STYLE
  path: ""                         # S3_PATH
  disable_ssl: true               # S3_DISABLE_SSL
  part_size: 104857600             # S3_PART_SIZE
  compression_level: 1             # S3_COMPRESSION_LEVEL
  # supports 'tar', 'lz4', 'bzip2', 'gzip', 'sz', 'xz'
  compression_format: gzip         # S3_COMPRESSION_FORMAT
  # empty (default), AES256, or aws:kms
  aws: kms                      # S3_SSE
  disable_cert_verification: true  # S3_DISABLE_CERT_VERIFICATION
  debug: false                     # S3_DEBUG

**So could you please let me know what will be the route case of this? And the Clickhouse version we are using is 20.6.3.28 and it is 5 shard cluster with zookeeper configured.**

**Comment by renjithtr** [comment]
I was tried to run the clickhouse-backup from one of the cluster shard server and still facing the same issue it is creating a part hash file and most of the time a empty shadow directory. Not creating metadata folder. Also I am using the latest version of clickhouse-backup tool. Still is is not creating metadata folder in the backup. 

Configured the data_path is /var/lib/clickhouse/ and running the tool as root user.

- '2020-11-30.tar.gz'   518.16 MiB      (created at 01-12-2020 06:38:16)
 518.16 MiB / 518.16 MiB  100.00% 39s01s
2020/12/01 06:48:52   Done.
2020/12/01 06:48:53 stat /var/lib/clickhouse/backup/2020-11-30/metadata: no such file or directory
command terminated with exit code 1

**Comment by yonj1e** [comment]
I have the same problem

**Comment by AlexAkulov** [comment]
Hi @renjithtr 
Is the backup log in the first message complete or is it a part? This log doesn't have tables for backup. Try to create table not in 'system' db.

**Comment by yonj1e** [comment]
[root@vm1 clickhouse-backup]# ./clickhouse-backup create mybackup
2020/12/03 10:48:44 Create backup 'mybackup'
2020/12/03 10:48:44 Skip 'system.asynchronous_metric_log'
2020/12/03 10:48:44 Skip 'system.metric_log'
2020/12/03 10:48:44 Skip 'system.query_log'
2020/12/03 10:48:44 Skip 'system.query_thread_log'
2020/12/03 10:48:44 Skip 'system.trace_log'
2020/12/03 10:48:44 Freeze 'tutorial.hits_v1'
2020/12/03 10:48:44 Freeze 'tutorial.visits_v1'
2020/12/03 10:48:44 Copy part hashes
2020/12/03 10:48:44 Skip 'system.asynchronous_metric_log'
2020/12/03 10:48:44 Skip 'system.metric_log'
2020/12/03 10:48:44 Skip 'system.query_log'
2020/12/03 10:48:44 Skip 'system.query_thread_log'
2020/12/03 10:48:44 Skip 'system.trace_log'
2020/12/03 10:48:44 Writing part hashes
2020/12/03 10:48:44 Copy metadata
2020/12/03 10:48:44   Done.
2020/12/03 10:48:44 Move shadow
2020/12/03 10:48:44   Done.
[root@vm1 clickhouse-backup]# ll /data1/data/clickhouse/backup/
total 4
drwxr-xr-x 3 root root 4096 Dec  3 10:48 mybackup
[root@vm1 clickhouse-backup]# ll /data1/data/clickhouse/backup/mybackup/
total 24
-rw-r--r-- 1 root root 17740 Dec  3 10:48 parts.hash
drwxr-xr-x 4 root root  4096 Dec  3 10:48 shadow
[root@vm1 clickhouse-backup]# ./clickhouse-backup list
Local backups:
- 'mybackup'	(created at 03-12-2020 10:48:44)
[root@vm1 clickhouse-backup]# ./clickhouse-backup restore mybackup
2020/12/03 10:49:28 stat /data1/data/clickhouse/backup/mybackup/metadata: no such file or directory

**Comment by renjithtr** [comment]
@AlexAkulov  Thanks for your response. After running the tool inside the cluster host, I can't reproduce the issue. But as per you said one of my cluster has no tables in any DB's but in a development cluster there is lots of tables with more than 2 GB data , but still I faced the same issue in that also. 

I will cross check it on it and come back to you if I facing any issues. 

And one more doubt I have is  , while backup process the tables are going to freeze state so this will impact in cluster performance ?

**Comment by yonj1e** [comment]
My path is not /var/lib/clickhouse. Does this make a difference？
[root@vm1 clickhouse]# ll
total 64
drwxr-x---  2 clickhouse clickhouse 4096 Dec  2 20:46 access
drwxr-xr-x  3 clickhouse clickhouse 4096 Dec  4 11:53 backup
drwxr-x---  2 clickhouse clickhouse 4096 Dec  2 20:46 cores
drwxr-x---  6 clickhouse clickhouse 4096 Dec  4 11:46 data
drwxr-x---  2 clickhouse clickhouse 4096 Dec  2 20:46 dictionaries_lib
drwxr-x---  2 clickhouse clickhouse 4096 Dec  2 20:46 flags
drwxr-x---  2 clickhouse clickhouse 4096 Dec  2 20:46 format_schemas
drwxr-x---  2 clickhouse clickhouse 4096 Dec  3 10:27 metadata
drwxr-x---  2 clickhouse clickhouse 4096 Dec  3 21:09 metadata_dropped
drwxr-x---  2 clickhouse clickhouse 4096 Dec  2 20:46 preprocessed_configs
drwxr-xr-x  3 clickhouse clickhouse 4096 Dec  2 20:46 run
drwxr-x---  2 clickhouse clickhouse 4096 Dec  4 11:53 shadow
-rw-r-----  1 clickhouse clickhouse   59 Dec  2 20:46 status
drwxr-x--- 29 clickhouse clickhouse 4096 Dec  4 10:15 store
drwxr-x---  3 clickhouse clickhouse 4096 Dec  3 10:45 tmp
drwxr-x---  2 clickhouse clickhouse 4096 Dec  2 20:46 user_files
[root@vm1 clickhouse]# pwd
/data1/data/clickhouse

**Comment by renjithtr** [comment]
I think , yes. The tool is trying to copy the data from metadata and shadow folder inside the server using hard links. So I believe we need to give the path /var/lib/clickhouse/. And I found that my  issue has been resolved by running the tool inside a shard node.

Before I run the tool in a separate container so I think that caused the issue.

**Comment by yonj1e** [comment]
My data directory is not /var/lib/clickhouse/. How can I fix this?

**Comment by yonj1e** [comment]
Looks like it only supports single nodes, right?

**Comment by AlexAkulov** [comment]
Hi @yonj1e 
Does your clickhouse use multiple storage drives?

**Comment by AlexAkulov** [comment]
clickhouse-backup gets data_path from clickhouse and must have access to files in data_path. If you run clickhouse and clichouse-backup in separate containers, you must provide the same mount point to data_path in both containers.
If data_path in /etc/clickhouse-backup/config.yml is /data1/data/clickhouse then
clickhouse-server container must be have /data1/data/clickhouse mount point and
clickhouse-backup container must be have /data1/data/clickhouse mount point with the same data

**Comment by yonj1e** [comment]
I did not use containers, just physical machine deployment, and modified the data directory, clickHouse source compilation and installation, did not use yum,

**Comment by yonj1e** [comment]
I have started using Clickhouse 20.11.4.13, is there any above problem, I have tested 20.8.7.15 again, can normal backup.

**Comment by AlexAkulov** [comment]
I added test for Clickhouse 20.11.4.13 and it passed successfully https://travis-ci.com/github/AlexAkulov/clickhouse-backup/jobs/456106118. 
Maybe you use Atomic databases that not supported yet.
Please, check your current database engine by command `SHOW CREATE DATABASE tutorial`

**Comment by Steuf** [comment]
Yes I can confirm that metadata are not backup and restore process don't work with default Atomic database.

But it works when the database is forced to Ordinary engine.

Have you an ETA (approx.) for support of Atomic database ?

**Comment by AlexAkulov** [comment]
I plan on adding support for atomic databases this year
https://github.com/AlexAkulov/clickhouse-backup/milestone/1

**Comment by gowth** [comment]
Hey i have been trying to check for clickhouse backup method in more traditional way, since i see a blog from the altinity to follow some thirdparty bakcuptool which stores the backup in the cloud. do we have any methods to do a backup for clickhouse from local host to some other host which is running same clickhouse version??.

**Comment by Slach** [comment]
@gowth look to clickhouse-copier
https://altinity.com/blog/2018/8/22/clickhouse-copier-in-practice
or use
```INSERT INTO table SELECT * FROM remote(..)``` on destination host
https://clickhouse.tech/docs/en/sql-reference/table-functions/remote/

**Comment by gowth** [comment]
slach, i think clcikhouse-copier works for only replicated or merge tree engines since we are following distributed engines. does that work with a incremental backup ??

**Comment by Slach** [comment]
@gowth distributed tables doesn't contains any data itself (only temporary data before insert it to underlying table)

clickhouse-backup backup only schema for distributed table

**Comment by gowth** [comment]
so since backup-tool is not useful for my requirement ??

**Comment by Slach** [comment]
you don't publish your "requirements"
so we don't know what exactly you need
