### ISSUE TITLE
Add SSL support

### ISSUE THREAD

**Issue by therealnb** [Altinity/clickhouse-backup#133]
I'm in an environment where non-encrypted ports are not enabled. I don't think clickhouse-backup currently supports SSL. Are there any plans for this?

**Comment by AlexAkulov** [comment]
TLS is not supported now. I can add TLS if needed in next release.

**Comment by therealnb** [comment]
That sounds great.

Do you have any idea of timelines for that?

**Comment by AlexAkulov** [comment]
Added in 3a8f061

**Comment by therealnb** [comment]
Excellent. Thanks!

**Comment by therealnb** [comment]
I tried ssl support and it works. Thanks.
