### ISSUE TITLE
Reducing number of partition in backup

### ISSUE THREAD

**Issue by mayankkandari** [Altinity/clickhouse-backup#135]
Hi,
There is no document is available  ON this and document pointing to this is empty. https://github.com/AlexAkulov/clickhouse-backup/blob/master/Examples.md#How-to-reduce-number-of-partitions. My requirement is either I pass number of partition to backup or I can pass name of partition to be backup  but not all partition.

**Comment by mayankkandari** [comment]
Hi,
Can someone please help me in resolving this ?

**Comment by AlexAkulov** [comment]
Some research is required to answer this question.
I SUPPOSE that if you make a backup and manually create a schema with a different partitioning key and restore only the data from the backup, then it may work.
Perhaps some improvements of clickhouse-backup will be required. 
Maybe this can be done with the regular clickhouse queries like 
```
INSERT INTO xxx SELECT * FROM table WHERE column BETWEEN 1 and 10000;
```

**Comment by aadant** [comment]
I think the idea is to only backup the partitions that we are actively written to, for example the ones that are on hot storage.
or just one partition at a time rather than the full table.

see for example : https://www.percona.com/doc/percona-xtrabackup/2.3/howtos/recipes_ibkx_partition.html

**Comment by Slach** [comment]
feature already implemented with `create --partitions=XXX,YYY` try latest 1.6.2
