### ISSUE TITLE
miss meta directory

### ISSUE THREAD

**Issue by tangjunhuelva** [Altinity/clickhouse-backup#137]
When data's directory is a soft link, copying the meta directory fails. like this home -> /data/store/147/14782f0a-ee9f-41f0-a271-329e656b03e5. home is database name.

**Comment by tangjunhuelva** [comment]
it don't support default database engine Atomic.

**Comment by AlexAkulov** [comment]
Yes, Atomic Engine is currently not supported. Wait for version 1.0.0.

**Comment by LB-J** [comment]
+1
