### ISSUE TITLE
Support backup schema only

### ISSUE THREAD

**Issue by therealnb** [Altinity/clickhouse-backup#138]
Hi Alex,

This is a suggestion based on my recent experience with testing backups. I'd like your thoughts on it.

Assume two replicated servers s1 and s2. I backup a table in s1.

If I then drop the table in s1 and restore it, it also replicates from s2. I get double the records. (I know, I don't need to restore the data in this case)

If I drop on cluster, or drop the table on both servers manually, then restore to s1, s2 is still missing a schema. I could recreate the schema by hand, but that requires some coordination between ddl and backups. I can also download the backup and restore the schema only and let replication take care of the data - which works perfectly.

The only problem with the last approach is that I have to download the whole of the data, just to get the schema, which seems wasteful.

This proposal is to allow the backup of the schema only, so that I can backup the schema and data on s1 and schema only on s2. Hope this makes sense.

Alternatively, there may be a simpler way of doing this. I'll update here if I find something.

**Comment by AlexAkulov** [comment]
Added in [v1.0.0-beta1](https://github.com/AlexAkulov/clickhouse-backup/releases/tag/v1.0.0-beta1)
