### ISSUE TITLE
Improve of "archive" backup strategy

### ISSUE THREAD

**Issue by andrii29** [Altinity/clickhouse-backup#14]
@AlexAkulov Hello,
it looks like new archive strategy is using only one cpu core. It works very slow and can't be used for terabyte range backups (gzip, level 7)
![image](https://user-images.githubusercontent.com/31315876/55456690-68c89a80-55f0-11e9-86c3-c40b2d562ad1.png)

**Comment by andrii29** [comment]
@AlexAkulov  hi, any planes about this issue?
it would be nice to reduce size of backups using higher levels of backup - now it is impossible due to 1 cpu core limitation

**Comment by AlexAkulov** [comment]
I created this issue
https://github.com/mholt/archiver/issues/159

**Comment by AlexAkulov** [comment]
Available in [v0.4.1](https://github.com/AlexAkulov/clickhouse-backup/releases/tag/v0.4.1)
