### ISSUE TITLE
When will `Atomic` engine be supported?

### ISSUE THREAD

**Issue by fzyzcjy** [Altinity/clickhouse-backup#141]
Hi thanks for this lib! As we know `20.10` has been released for quite a while. However, `'Atomic' database engine enabled by default in ClickHouse 20.10 IS NOT SUPPORTED`. Thus I wonder when will new versions be released that support this engine? Thanks!

**Comment by dongshanlang** [comment]
I'm waiting for this, too. How lazy am I.

**Comment by fzyzcjy** [comment]
@dongshanlang Why lazy?

**Comment by hohaftf** [comment]
The issue #126

**Comment by AlexAkulov** [comment]
Added in [v1.0.0-alpha1](https://github.com/AlexAkulov/clickhouse-backup/releases/tag/v1.0.0-alpha1)

**Comment by fzyzcjy** [comment]
@AlexAkulov Congrats!

**Comment by fzyzcjy** [comment]
@AlexAkulov Hi, I wonder when will it be on stable (such that I can use it in production env?)

**Comment by AlexAkulov** [comment]
In next month, i think.

**Comment by fzyzcjy** [comment]
@AlexAkulov Looking forward to it!
