### ISSUE TITLE
Validation error with environment variables configuration

### ISSUE THREAD

**Issue by asaarashi** [Altinity/clickhouse-backup#143]
I have environment variables as the below in file `.env` and export them via command `export $(grep -v '#.*' ./.env | xargs)`
```
CLICKHOUSE_SKIP_TABLES="system.*,default.*_archive"
REMOTE_STORAGE=azblob
AZBLOB_ACCOUNT_NAME="SAMPLE"
AZBLOB_ACCOUNT_KEY="SAMPLE"
AZBLOB_SAS="SAMPLE"
AZBLOB_CONTAINER="backup-test"
CLICKHOUSE_DATA_PATH="/var/lib/docker/volumes/9ec13ba6405e85e4538a188ace07c30bebeb28a774c1e962d18121d4bee06a6b/_data"
```
When I execute `sudo ./clickhouse-backup list`, I can get a local backup list but fail to get a remote backup list,
```
Remote backups:
2021/01/22 17:31:29 InvalidParameter: 1 validation error(s) found.
- minimum field size of 1, ListObjectsV2Input.Bucket.
```
What's the possible reason?

Thanks for your great works.

**Comment by kushagra391** [comment]
@oathexodus how did you fix this ? am getting a similar issue for aws s3

**Comment by Chikanz** [comment]
bump 👀

**Comment by Slach** [comment]
@kushagra391 @Chikanz 
https://stackoverflow.com/a/19331521/1204665
