### ISSUE TITLE
Download and restore rest coordination

### ISSUE THREAD

**Issue by therealnb** [Altinity/clickhouse-backup#144]
A common task would be to download a backup and then restore it. Currently download via the rest api is asynchronous. So, we have to try the restore repeatedly until it succeeds.

One or more of the following might be a helpful enhancement 
* It would be good to have a UID to link the download to the ops in the status call.
* A synchronous download option would be helpful.
* A download and restore option

**Comment by AlexAkulov** [comment]
Good idea!
This is will be added in 1.x version.

**Comment by therealnb** [comment]
It would be good if this extended to uploads as well - it is nice to know if they succeed or not.

**Comment by Slach** [comment]
@therealnb 
already implements on 1.0.0 rest API
step 1
`POST /backup/actions`
with request body `{"command":"restore_remote backup_name"}`

step 2 poll in loop until status switched from InProgress to "success" or "error"
`GET /backup/actions`
and watch `status` for {"command":"restore_remote backup_name","status": ...}

**Comment by Slach** [comment]
@AlexAkulov i think we could close issue
