### ISSUE TITLE
Support create dictionary before regular table when restore schema

### ISSUE THREAD

**Issue by wilsonlun** [Altinity/clickhouse-backup#147]
I have dictionary and tables using dictionary engine in my schema. When I restore the schema, it show following error:

> 2021/01/29 04:20:15 Create table 'test.table'
> 2021/01/29 04:20:15 can't create table 'test.table': code: 36, message: external dictionary 'test.table_dict' not found

Followings are the definition for test.table and test.table_dict:
```
CREATE DICTIONARY test.table_dict
(
    id UInt64,
    name String
)
PRIMARY KEY id
SOURCE(odbc(connection_string 'DSN=test' table 'test_table'))
LAYOUT(HASHED())
LIFETIME(MIN 300 MAX 360);

CREATE TABLE test.table
(
    id UInt64,
    name String
) Engine = Dictionary(test.table_dict);
```

For my schema, dictionary is required to be created before other tables. Is it possible to create dictionary before other regular tables when restore schema?

Thanks for your great work.

**Comment by AlexAkulov** [comment]
Good point, thank you!

**Comment by AlexAkulov** [comment]
Done in [1.0.0-beta2](https://github.com/AlexAkulov/clickhouse-backup/releases/tag/1.0.0-beta2)
