### ISSUE TITLE
add backup rotation option

### ISSUE THREAD

**Issue by barazbay** [Altinity/clickhouse-backup#148]
in wal-g we can do delete retain 
[walg github](https://github.com/wal-g/wal-g)
please add an option to keep N latest backups 
this will be useful in cronjobs to automatically rotate local/remote backups

**Comment by AlexAkulov** [comment]
You can use these options for enable auto cleaning feature
```
general:
  backups_to_keep_local: 0       # BACKUPS_TO_KEEP_LOCAL
  backups_to_keep_remote: 0      # BACKUPS_TO_KEEP_REMOTE
```
Local backups will be cleaned after creating a new backup.
Remote backups will be cleaned after uploading.
