### ISSUE TITLE
Broken "region" variable 

### ISSUE THREAD

**Issue by andrii29** [Altinity/clickhouse-backup#15]
Hello,
i got this error in latest release
 can't upload with 400:"The authorization header is malformed; the region 'us-east-1' is wrong; expecting 'eu-west-1'
Config:
...
s3:
  region: "eu-west-1"
...

**Comment by AlexAkulov** [comment]
Hello! 
Try latest release again, please.

**Comment by andrii29** [comment]
Hello,
it works good now!
Thank you!

Can you create release for all new changes (for example v0.1.1 ) ?

**Comment by AlexAkulov** [comment]
I want to fix this bug https://github.com/AlexAkulov/clickhouse-backup/issues/8 before create new release.
