### ISSUE TITLE
Create prometheus metrics about backup size and `restore` status

### ISSUE THREAD

**Issue by Slach** [Altinity/clickhouse-backup#150]
Could you create `clickhouse_backup_last_backup_size_local` and `clickhouse_backup_last_backup_size_remote` which will show size of latest backup (doesn't matter successful or failed)

Also 
`clickhouse_backup_last_restore_duration` count
`clickhouse_backup_last_restore_success` 0= failed, 1=success,  2=unknown
`clickhouse_backup_failed_restores` count
`clickhouse_backup_successful_restores` count

**Comment by AlexAkulov** [comment]
Done in [1.0.0-beta2](https://github.com/AlexAkulov/clickhouse-backup/releases/tag/1.0.0-beta2)
