### ISSUE TITLE
TotalPartsExceeded

### ISSUE THREAD

**Issue by therealnb** [Altinity/clickhouse-backup#151]
On a big upload we get 
```
Feb 15 11:16:13 ch-event05-1.sv5.nskope.net clickhouse-backup[24470]: 2021/02/15 11:16:13 Upload backup '2021_02_12_16_10_ch-event05-1.sv5.nskope.net_ns_v2_event_page_local'
Feb 15 12:33:15 ch-event05-1.sv5.nskope.net clickhouse-backup[24470]:         upload id: fc2c08ba-2dd1-46f0-8a12-304744812a01
Feb 15 12:33:15 ch-event05-1.sv5.nskope.net clickhouse-backup[24470]: caused by: TotalPartsExceeded: exceeded total allowed configured MaxUploadParts (10000). Adjust PartSize to fit in this limit
```
This looks like it is similar to this [https://github.com/concourse/s3-resource/issues/87].

I can fix this with
```
  part_size: 104857600             # S3_PART_SIZE
```
But is there a reason clickhouse-backup can't work this out from the initial file size?

**Comment by AlexAkulov** [comment]
In [v1.0.0-beta1](https://github.com/AlexAkulov/clickhouse-backup/releases/tag/v1.0.0-beta1), you can define general.max_file_size (default 1 TB) for partitioning files on S3.
