### ISSUE TITLE
Huge memory usage with S3 upload

### ISSUE THREAD

**Issue by Steuf** [Altinity/clickhouse-backup#153]
The backup on S3 consume too many RAM compared to the file to backup I think.

My use case :

- CH cluster on Kubernetes
- All node have a sidecar with clickhouse-backup
- A manager call the K8S API to find clickhouse nodes and call API of clickhouse-backup to backup all nodes to an S3 provider

**My problem :**

- yesterday, CH Backup have crashed because all node have approx 100Go of database to backup and my S3 provider limit parts to 1000.

So, I have up the part size from 100Mb (the default) to 1Gb and there the drama... Clickhouse backup try to allocate >30Gb of ram (!?!) on upload and it have been OMM by the system.

After some search, the formula for RAM usage are :

- Part Size x Concurrency (hard coded to 10) x 4/5 (don't known why it a a factor to 4/5...)

So for part size at 1Go, the RAM used are : 1 x 10 x 4/5 = 40 to 50Gb. It's really huge :/ Don't know if the problem is on CH Backup project or on  S3 SDK project.... But it's really a problem.

**My only solution at this time :**

- fork this project
- add config S3_CONCURRENCY
- reduce concurrency to 1
- now the memory allocation is between 4/5Go

**NB:** I have tried to set a config S3_MAX_UPLOAD_PARTS to reduce defaults parts limits to S3 SDK to 1000, because in theory, S3 SDK auto adjust part size with function initSize() if parts needed are greater than this config. But it's not work, possibly the file object passed by Clickhouse Backup dont pass the total size of the file ?

**Comment by AlexAkulov** [comment]
Hi @Steuf!
Thank you for detailed description. I'll think about how to fix this.

**Comment by Steuf** [comment]
Hi @AlexAkulov 

Thank you for your answer ;)

**Comment by AlexAkulov** [comment]
Fixed in [v1.0.0](https://github.com/AlexAkulov/clickhouse-backup/releases/tag/v1.0.0)
