### ISSUE TITLE
Adding support to clickhouse 21.10

### ISSUE THREAD

**Issue by DrissiReda** [Altinity/clickhouse-backup#155]
I'm interested in adding support for newer clickhouse versions.

I want to know all the problems that need to be addressed, the only one I noticed is that metadata is now stored using symlinks, and go walk function doesn't explore symlinks it only identifies them. I've managed to solve this by a custom function that uses walk and goes into symlinks (will add a depth parameter to avoid infinite loops).

@AlexAkulov any other problems I should know about?

**Comment by sas1024** [comment]
This issue is resolved in v1.0.0-alpha1

**Comment by AlexAkulov** [comment]
Added in [v1.0.0-alpha1](https://github.com/AlexAkulov/clickhouse-backup/releases/tag/v1.0.0-alpha1)
