### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by michaeltex** [Altinity/clickhouse-backup#159]
Столкнулся с проблемой бекапов кликхауса на нескольких дисках.
Нашел совет в одном из issues https://github.com/AlexAkulov/clickhouse-backup/issues/96#issuecomment-768478396.
Меня устраивает возможность только create. Собрал из дев ветки бинарник он выдает Segmentation fault=(
Подскажите куда можно копать?

**Comment by AlexAkulov** [comment]
Попробуйте использовать релиз [v1.0.0-alpha1](https://github.com/AlexAkulov/clickhouse-backup/releases/tag/v1.0.0-alpha1)

**Comment by michaeltex** [comment]
Александр, спасибо вам огромное. Все работает как надо.
