### ISSUE TITLE
Custom disk mapping not working in 1.0.0-alpha1

### ISSUE THREAD

**Issue by sas1024** [Altinity/clickhouse-backup#162]
Hello!

I set in config.yml this value:
`disk_mapping: { "default": "/data/clickhouse/" }`, but clickhouse-backup always use default clickhouse data location (`/var/lib/clickhouse/`).

As I see, [GetDisks() function](https://github.com/AlexAkulov/clickhouse-backup/blob/f460a0e16231852aef80d3fd9acd5f672562790a/pkg/clickhouse/clickhouse.go#L58) not read disk mapping values from clickhouse-backup config in v1.0.0-alpha1.

**Comment by AlexAkulov** [comment]
Thank you! 
I will fix it.
