### ISSUE TITLE
[BUG] Running on Kubernetes picks up wrong env vars

### ISSUE THREAD

**Issue by electrical** [Altinity/clickhouse-backup#165]
Hi,

I'm trying to run the backup container on kubernetes but getting the following error:

```
2021/03/15 11:59:44 envconfig.Process: assigning CLICKHOUSE_CLICKHOUSE_PORT to Port: converting 'tcp://10.43.234.97:8123' to type uint. details: strconv.ParseUint: parsing "tcp://10.43.234.97:8123": invalid syntax
```
For some reason it's picking up the env var and trying to use it which obviously fails.
Is there a way to disable it picking up env vars?

**Comment by AlexAkulov** [comment]
Thank you!
