### ISSUE TITLE
connection to Clickhouse is being initialised to quickly

### ISSUE THREAD

**Issue by electrical** [Altinity/clickhouse-backup#169]
Getting the following error when starting up the container in the same kubernetes POD as my clickhouse server instance

```
Wed, Mar 17 2021 11:43:15 am | 2021/03/17 11:43:15 error can't connect to clickhouse: dial tcp 127.0.0.1:9000: connect: connection refused
```

This causes the backup container to exit directly.
It would be nice if it would either wait or retry.
Is there a specific reason it tries to connect at startup while no commands have been executed yet?

**Comment by AlexAkulov** [comment]
Done.
