### ISSUE TITLE
Download of an incremental backup that is locally available

### ISSUE THREAD

**Issue by rodrigargar** [Altinity/clickhouse-backup#175]
Downloading from cloud storage an incremental backup that is already available locally ends in error, as clickhouse-backup tries to recreate the hard links (which already exist).

```
clickhouse-backup download incremental-backup
2021/03/31 01:17:11 Backup 'incremental' required 'full'. Downloading.
2021/03/31 01:17:22 link /var/lib/clickhouse/backup/full/<first_hardlink>
  /var/lib/clickhouse/backup/incremenal/<first_hardlink>: file exists
```

I would expect the command to completely replace the local backup with the downloaded backup or give a more descriptive error.

**Comment by AlexAkulov** [comment]
Fixed in [1.0.0-beta2](https://github.com/AlexAkulov/clickhouse-backup/releases/tag/1.0.0-beta2)
