### ISSUE TITLE
Restore of old-schema MaterializedView (20.8 LTS) on the new (21.3 LTS)

### ISSUE THREAD

**Issue by Felixoid** [Altinity/clickhouse-backup#179]
Hello. I've tried to take the backup from the classic defined `data` and `metadata` server and restore it to a new one.

Unfortunately, it didn't work in any way I've tried:

- `sudo -u clickhouse clickhouse-backup restore backup --rm`
- `sudo -u clickhouse clickhouse-backup restore backup --data`
- `sudo -u clickhouse clickhouse-backup restore backup --rm --schema --data`

I am pretty sure, it's because `.inner.name` is looking now as `.inner_id.6a112f15-1551-4d06-836e-72729b4d02f5`

I'll gladly give more information if you need it!

upd: one thing definitely worth mentioning: the backup was done by `0.5.1.c6.g518e72a` version. Is the usage of 1.0.0.alpha would help with it?

**Comment by Slach** [comment]
quick workaround setup default database engine as Ordinal
create `/etc/clickhouse-server/users.d/disable_atomic.xml`
with following content
```xml
<yandex>
<profiles>
  <default>
    <default_database_engine>Ordinary</default_database_engine>
  </default>
</profiles>
</yandex>
```
and try to restore

If you want to migrate to Atomic
remove /etc/clickhouse-server/users.d/disable_atomic.xml

```sql
CREATE DATABASE new_database ENGINE=Atomic;
RENAME TABLE old_database.table TO new_database.table, old_database.table2 TO new_database.table2 ...; /* https://clickhouse.tech/docs/en/sql-reference/statements/rename/ */
DROP DATABASE old_database;
RENAME DATABASE new_database TO old_database;

**Comment by AlexAkulov** [comment]
If you want to restore backup with v0.6.4 you have to create database with 'Ordinary' engine manually. 
Or you can try to restore your backup with v1.0.0-alpha1

**Comment by Felixoid** [comment]
@Slach for some reason when I tried to execute `RENAME TABLE old_database.table TO new_database.table, old_database.table2 TO new_database.table2 ...;` it stuck horribly and hasn't done anything in 5-10 minutes..

**Comment by Slach** [comment]
@Felixoid hm, from disk side it should just move data to /var/lib/clickhouse/store/new_database/table/ and create symlinks
do you have INSERTS into old_database.table during RENAME?

**Comment by Felixoid** [comment]
It's MV with the Replicated engine, so it receives updates constantly.

**Comment by Slach** [comment]
@Felixoid it's a MV without `TO db.table` clause?
bad corner case ...

so, ALTER TABLE RENAME will try to lock `.inner.<mv_name>` ReplicatedMergeTree table which underhood MV, and it stuck query
