### ISSUE TITLE
Unable to download from S3 on 1.0.0-alpha1

### ISSUE THREAD

**Issue by carlosmoyamrf** [Altinity/clickhouse-backup#180]
Seems that clickhouse-backup uploads the backup correctly but it's not able to download it.

Steps to reproduce:
- Clickhouse created following the **[official clickhouse tutorial](https://clickhouse.tech/docs/en/getting-started/tutorial/)** 
- Create a backup with clickhouse backup
```
create testbackup
.
.
.
.
2021/04/08 12:48:37  info done                      backup=testbackup operation=create
```

- Upload to S3
```
upload testbackup
.
.
.
.
2021/04/08 12:49:08  info done                      backup=testbackup operation=upload
```

- We can verify that the backup exists in S3
- Then try to download it
```
download testbackup
2021/04/08 12:49:14 error 'testbackup' is not found on remote storage
```

-----------------------
clickhouse-backup version:  dockerhub image alexakulov/clickhouse-backup:1.0.0-alpha1
ClickHouse server version 21.3.3 revision 54447

config.yml
```
general:
  remote_storage: s3
  disable_progress_bar: false
  backups_to_keep_local: 0
  backups_to_keep_remote: 10

clickhouse:
  username: clickhouseuser
  password: "***********"
  host: localhost
  port: 9000
  timeout: 5m
  data_path: "/var/lib/clickhouse"
  skip_tables:
    - system.*
  freeze_by_part: false

s3:
  access_key: "********"
  secret_key: "********"
  bucket: "mys3bucket"
  endpoint: "s3.eu-west-1.amazonaws.com"
  region: "eu-west-1"
  acl: private
  force_path_style: true
  path: "/"
  disable_ssl: false
  part_size: 104857600
  compression_level: 1
  # supports 'tar', 'lz4', 'bzip2', 'gzip', 'sz', 'xz'
  compression_format: gzip
  # empty (default), AES256, or aws:kms
  sse: AES256
  disable_cert_verification: false
  debug: true
  storage_class: STANDARD
```

**Comment by markonen** [comment]
I encountered this same issue on 1.0.0-beta1 and managed to debug it using my server access logs.

The issue is reproducible when the `path` parameter in the s3 config is set to either "" (the default) or "/" (as in @carlosmoyamrf's config). In these cases, clickhouse-backup tries to list the prefix "//" and gets no results. If any other prefix is set, listings work as expected.

**Comment by AlexAkulov** [comment]
Must work in [1.0.0-beta2](https://github.com/AlexAkulov/clickhouse-backup/releases/tag/1.0.0-beta2)
