### ISSUE TITLE
Unable to restore backups on 1.0.0-alpha1

### ISSUE THREAD

**Issue by carlosmoyamrf** [Altinity/clickhouse-backup#181]
clickhouse-backup 1.0.0-alpha1 is unable to restore it's own backups on clickhouse server 21.3.3 revision 54447.

Steps to reproduce:
- Create clickhouse database following the **[official clickhouse tutorial](https://clickhouse.tech/docs/en/getting-started/tutorial/)** 
- Create a backup for tutorial tables with clickhouse backup
```
create tutorialtablesbackup -t tutorial.*
2021/04/08 14:51:54  info done                      backup=tutorialtablesbackup operation=create table=tutorial.hits_v1
2021/04/08 14:51:54  info done                      backup=tutorialtablesbackup operation=create table=tutorial.visits_v1
2021/04/08 14:51:54  info done                      backup=tutorialtablesbackup operation=create
```

- Drop tutorial database
` clickhouse-client -h127.0.0.1 -u admin --password "*********" --query "DROP DATABASE tutorial"`

- Try to restore de recently created backup
```
restore tutorialtablesbackup
2021/04/08 14:55:28 error can't restore 'tutorial.hits_v1': error during filepath.Walk for partition '/var/lib/clickhouse/store/5d8/5d83f0d5-6111-42f9-a48e-de4793471556/201403_1_31_2/': lstat /var/lib/clickhouse/backup/tutorialtablesbackup/shadow/tutorial/hits_v1/201403_1_31_2: no such file or directory
```

-----------------------
clickhouse-backup version:  **dockerhub image** alexakulov/clickhouse-backup:1.0.0-alpha1
ClickHouse server version 21.3.3 revision 54447

config.yml
```
general:
  remote_storage: s3
  disable_progress_bar: false
  backups_to_keep_local: 0
  backups_to_keep_remote: 10

clickhouse:
  username: clickhouseuser
  password: "***********"
  host: localhost
  port: 9000
  timeout: 5m
  data_path: "/var/lib/clickhouse"
  skip_tables:
    - system.*
  freeze_by_part: false

s3:
  access_key: "********"
  secret_key: "********"
  bucket: "mys3bucket"
  endpoint: "s3.eu-west-1.amazonaws.com"
  region: "eu-west-1"
  acl: private
  force_path_style: true
  path: "/"
  disable_ssl: false
  part_size: 104857600
  compression_level: 1
  # supports 'tar', 'lz4', 'bzip2', 'gzip', 'sz', 'xz'
  compression_format: gzip
  # empty (default), AES256, or aws:kms
  sse: AES256
  disable_cert_verification: false
  debug: true
  storage_class: STANDARD
```

**Comment by AlexAkulov** [comment]
Hi @carlosmoyamrf !
Please, show commands which you run clickhouse and clickhouse-backup containers. I think the problem is incorrectly mounting volumes. clickhouse-backup must have full access to clickhouse's files.

**Comment by carlosmoyamrf** [comment]
Hi @AlexAkulov,

The complete command is:
`docker run --privileged --rm -i --network host -v "/opt/docker-compose/clickhouse/backup/config.yml:/etc/clickhouse-backup/config.yml"     -v "clickhouse-db-data:/var/lib/clickhouse" alexakulov/clickhouse-backup:1.0.0-alpha1 create tutorialtablesbackup`

Thanks in advance.

**Comment by carlosmoyamrf** [comment]
Hi @AlexAkulov , seems that the volume that I was binding for "/var/lib/clickhouse" was not she same used by clickhouse I was trying to do the backup and this is a requirement, after binding the correct volume it's working. 

Now my only issue is that I can upload the backups to S3 but not download them. https://github.com/AlexAkulov/clickhouse-backup/issues/180

Sorry for the inconvenience.
