### ISSUE TITLE
May I ask if ClickHouse-Backup supports 21.3 version? I hope to get the reply from the relevant person

### ISSUE THREAD

**Issue by liwanjie1020** [Altinity/clickhouse-backup#182]
Hello, I would like to know whether ClickHouse-Backup currently supports the 21.3(LTS) version. Because I saw in the readme.md that "Limitations" includes "ClickHouse above 1.1.54390 and before 20.10 is supported", but my current version is not within this range, so I hope you can inform me, thank you very much.

**Comment by Slach** [comment]
look to https://github.com/AlexAkulov/clickhouse-backup/releases/tag/v1.0.0-alpha1 and https://github.com/AlexAkulov/clickhouse-backup/tree/dev

**Comment by AlexAkulov** [comment]
This resolved in [v1.0.0-beta1](https://github.com/AlexAkulov/clickhouse-backup/releases/tag/v1.0.0-beta1)
