### ISSUE TITLE
node doesn't exist (No node)

### ISSUE THREAD

**Issue by bilalbayasut** [Altinity/clickhouse-backup#183]
Hi folks, I created one replicated table schema (without data), then I create backup, but it said that node is not found. I use zookeeper with 1 shard and 2 replicas
```
can't sync 'default.my_table': code: 999, message: Can't get data for node /clickhouse/my/clickhouse/tables/0/default/my_table/replicas/chi-my-clickhouse-0-1/log_pointer: node doesn't exist (No node)
```

**Comment by Slach** [comment]
look like you also  use Kubernetes and clickhouse-operator
could you suggest, when you run CREATE TABLE .. ENGINE=ReplicatedMergeTree()

did you add `ON CLUSTER 'my-clickhouse'`  expression to the end of `CREATE TABLE ..` query?

**Comment by bilalbayasut** [comment]
yes, this was solved, turns out wrong family engine
