### ISSUE TITLE
Can't attach partition for specific table during restore command execution

### ISSUE THREAD

**Issue by mescudi21** [Altinity/clickhouse-backup#187]
Backed up database and saved it on S3 compatible storage. During the tests of restoring this backup we had this error:

```
clickhouse-backup restore test-backup-1 -d
---------------------------------------------
...
2021/04/27 12:14:36 ALTER TABLE `somedb`.`sometable` ATTACH PART '20200622_12905_12905_0'
2021/04/27 12:14:36 can't attach partitions for table 'somedb.sometable': code: 233, message: Detached part "20200622_12905_12905_0" not found
```

Is it an issue of a tool or did we do something wrong?

**Comment by AlexAkulov** [comment]
Hi! 
#172 is the similar issue. Try the same solution set `freeze_by_part` to `true`

**Comment by mescudi21** [comment]
Tried to backup with `freeze_by_part: true` - didn't help. Maybe the issue is at CH or CH-backup version? CH version: 21.2.9.41, CH-backup version: 0.6.4

**Comment by mescudi21** [comment]
My bad, clickhouse-server served metadata and data in a fault place instead of `/var/lib/clickhouse`. Started a docker container and ran a backup restoration and everything works like charm. Thanks for help!
