### ISSUE TITLE
При заливке на S3 в итоговый архив попадают не все партиции таблицы

### ISSUE THREAD

**Issue by AlexKneev** [Altinity/clickhouse-backup#188]
На шаге clickhouse-backup create создается локальный бэкап.
Папка /var/lib/clickhouse/backup/2021-04-28/shadow/<table>/audit/default содержит 66 каталогов-партиций
После шага clickhouse-backup upload на S3 в архив попадает только 48 каталогов-партиций
Соответственно при восстановлении ругается на невозможность восстановления.
Проверялось на версиях: v1.0.0-beta1 и v1.0.0-alpha1
ClickHouse - 21.4.4.30

**Comment by Slach** [comment]
а можно логи расшарить для create + upload и для download  + restore?

**Comment by AlexKneev** [comment]
Create:
Create daily local backup...
2021/04/28 10:28:07  info done                      backup=2021-04-28-daily operation=create table=mybond.audit
2021/04/28 10:28:07  info done                      backup=2021-04-28-daily operation=create table=mybond.audit_proxy
2021/04/28 10:28:07  info done                      backup=2021-04-28-daily operation=create table=mybond.reversion_proxy
2021/04/28 10:28:07  info done                      backup=2021-04-28-daily operation=create
Upload daily full backup...
 163.25 MiB / 207.91 MiB [======================================================================================================>---------------------------]  78.52% 3s
2021/04/28 10:28:11  info done                      backup=2021-04-28-daily operation=upload table=mybond.audit
2021/04/28 10:28:11  info done                      backup=2021-04-28-daily operation=upload table=mybond.audit_proxy
2021/04/28 10:28:11  info done                      backup=2021-04-28-daily operation=upload table=mybond.reversion_proxy
2021/04/28 10:28:11  info done                      backup=2021-04-28-daily operation=upload

Download к сожалению не работает
Restore:
clickhouse-backup restore -t mybond.audit -c /etc/clickhouse-backup/config-daily.yml 2021-04-28-daily
2021/04/28 10:33:15 error can't restore 'mybond.audit': error during filepath.Walk for partition '202002_49_49_0': lstat /var/lib/clickhouse/backup/2021-04-28-daily/shadow/mybond/audit/202002_49_49_0: no such file or directory

**Comment by AlexAkulov** [comment]
Это уже третий issue c подобной проблемой. 
У меня такое предположение. Может быть это связано с тем, что сначала делается фриз, а затем берутся сведенья о партициях из system.tables. И вот парт который появился в промежутке между этими двумя действиями информация о его существовании будет в бэкапе, а его данных нет. Поэтому при восстановлении происходит такая ошибка. 
Я попробую тогда сначала брать список партов, а потом делать фриз.

**Comment by AlexKneev** [comment]
В локальной версии бэкапа все партиции есть.
В момент бэкапа новые данные не поступали.
Ощущение что на стадии upload  архивируются не все партиции.

**Comment by AlexAkulov** [comment]
А какой compression_format?

**Comment by AlexKneev** [comment]
tar

**Comment by AlexAkulov** [comment]
Должно быть исправленно в [1.0.0-beta2](https://github.com/AlexAkulov/clickhouse-backup/releases/tag/1.0.0-beta2)
