### ISSUE TITLE
azblob should support system assigned identity

### ISSUE THREAD

**Issue by roman-vynar** [Altinity/clickhouse-backup#197]
Hello,

First of all, Thanks for the tool!

There are 4 methods to auth to get into az storage account:
1. account key
2. SAS
3. oauth credentials (AD > App registrations > credentials: app id and secret token)
4. system assigned identity

clickhouse-backup supports only 1-2 methods.

4th method is when you assign a role (e.g. Storage Blob Data Contributor) to the Service Principal of a VM instance on a scope of some blob container. Then from that instance you can do "az login --identity" (in case of az CLI) and just work directly with the container w/o any credentials. This is the simplest method and more secure than sharing an account key for example (1st method).

**Comment by Slach** [comment]
closed by https://github.com/AlexAkulov/clickhouse-backup/pull/267
