### ISSUE TITLE
Problem with restore

### ISSUE THREAD

**Issue by free6k** [Altinity/clickhouse-backup#20]
I try restore:

```
2019/04/10 10:38:33 Attach partitions for xxxx increment 175:
2019/04/10 10:38:33 ALTER TABLE xxxx ATTACH PARTITION 201901
2019/04/10 10:38:33 can't attach partitions for table xxx.xxx with code: 228, message: /var/lib/clickhouse/data/xxx/xxxx/detached/20190101_20190118_9742_9747_1/date.bin has unexpected size: 62464 instead of 1408782
```

**Comment by AlexAkulov** [comment]
Maybe download process has been interrupted?

**Comment by andrii29** [comment]
@AlexAkulov  hello,i got error with restore too.
I tried to download and restore backup (got error for 2 backups)
lz4 -d 2019-04-18T02-03-31.tar.lz4 
Decoding file 2019-04-18T02-03-31.tar 
Decompressed : *** MB  Error 66 : Decompression error : ERROR_contentChecksum_invalid

**Comment by free6k** [comment]
I resolved the my problem. It is was be bug in clickhouse https://github.com/yandex/ClickHouse/issues/4959

**Comment by AlexAkulov** [comment]
Hi @andrii29 
Do you get this error with lz4 tool only? Does `clickhouse-backup download 2019-04-18T02-03-31` work correctly?
What compression_level do you use?

**Comment by andrii29** [comment]
Hi @AlexAkulov. I tried only lz4 with level 1 compression (because of  https://github.com/AlexAkulov/clickhouse-backup/issues/14). I manually downloaded backup and tried to unarchive it with https://github.com/lz4/lz4

**Comment by AlexAkulov** [comment]
I found this issue https://github.com/pierrec/lz4/issues/27 but it has been fixed in v2.0.3, I use v2.0.5
Also, I found this issue https://github.com/lz4/lz4/issues/560 for compression level 9 but you use level 1
Anyway bug in the interaction of these libraries
Try use `clickhouse-backup download 2019-04-18T02-03-31` it must works rigth

**Comment by andrii29** [comment]
@AlexAkulov  hello, works good with this command - no errors

**Comment by AlexAkulov** [comment]
Good!
