### ISSUE TITLE
create backup with diff-from

### ISSUE THREAD

**Issue by juanvasquezreyes** [Altinity/clickhouse-backup#202]
Normally diff-from is being used when uploading

Will be nice to be used also when creating a backup, so we just backup locally only the diff from previous backup, to save some resources locally

is this something possible?

**Comment by AlexAkulov** [comment]
Hi @juanvasquezreyes !
Local backups already consist of hard links and only contain diff from your current state in ClickHouse.

**Comment by juanvasquezreyes** [comment]
> Hi @juanvasquezreyes !
> Local backups already consist of hard links and only contain diff from your current state in ClickHouse.

Ok, thank you alex
