### ISSUE TITLE
Limit resource usage

### ISSUE THREAD

**Issue by konstantin-schura** [Altinity/clickhouse-backup#209]
Hi there.

Ubuntu 18
CH version - 0.6.4

I have little issue with clickhouse-backup tool. It occupy resources during upload to s3 so high, even ssh stops responding.

Is it possible to limit numbers of threeds  or just set upload speed limit?

I didn't find it in docs. 

Thank you.

**Comment by Slach** [comment]
hm, could you try to latest `1.0.0`?
how many CPU cores do you have on clickhouse installation?

**Comment by konstantin-schura** [comment]
> hm, could you try to latest `1.0.0`?
> how many CPU cores do you have on clickhouse installation?

Oh, of course. I didn't know about it.
2 cpu on CH server.

**Comment by Slach** [comment]
ok. let's try to https://github.com/AlexAkulov/clickhouse-backup/releases/tag/v1.0.0

currently, clickhouse-backup doesn't implement any throttling mechanism
but you can try to use `taskset 1 clichouse-backup upload <backup_name>` to affinity clickhouse-backup to vCPU0 only
or `nice -n 19 clichouse-backup upload <backup_name>` to allow other processes eat CPU with more high priority than clickhouse-backup

**Comment by konstantin-schura** [comment]
Thank you.

**Comment by DrissiReda** [comment]
I have the same problem but with RAM. During upload to s3, used ram isn't freed, so after a few backups, ram usage goes through the roof.

Using 1.0.0

**Comment by Slach** [comment]
@DrissiReda try to decrease part_size parameter in s3 section on config.yaml

**Comment by DrissiReda** [comment]
That only delays the problem, the limit will be reached in 10 days instead of a single day, but it still never frees the ram it uses for an upload.

**Comment by Slach** [comment]
@DrissiReda could you try to use docker image `alexakulov/clickhouse-backup:master` and share docker container memory usage graph?

**Comment by DrissiReda** [comment]
@Slach how to draw the container memory graph easily? I'm not using a grafana

**Comment by DrissiReda** [comment]
> @DrissiReda could you try to use docker image `alexakulov/clickhouse-backup:master` and share docker container memory usage graph?

Thanks @Slach, this works a lot better, any idea why it manages ram better in container mode? even with a 500Mb part size, it doesn't go over 1.5Gb, despite having launched around 50 back to back backups/uploads.

**Comment by Slach** [comment]
@DrissiReda did you run 'alexakulov/clickhouse-backup:master' in "clickhouse-bakcup server" mode when backup started as REST server?

I not sure I understand what you exactly doing
could you describe your environment?

**Comment by DrissiReda** [comment]
@Slach I hope this is enough detail.
Running a debian 10 machine.

#### Scenario 1
launch a clickhouse server instance with : 
```
docker run <proper ports and volumes etc> clickhouse-server:21.3.14..1 
```

launch clickhouse-backup binary :
```
clickhouse-backup --config /conf.yaml server
```

launch around 10 backups and uploads with curl.


Ram usage at the end: around 4Gb.

#### Scenario 2
launch a clickhouse server instance with : 
```
docker run <proper ports and volumes etc> clickhouse-server:21.3.14..1 
```

launch clickhouse-backup inside docker :
```
docker run <proper volumes and docker params> alexakulov/clickhouse-backup:master server
```

launch around 10 backups and uploads with curl.

Ram usage at the end: <100Mb

**Comment by Slach** [comment]
look like after 1.0.0 was released some memory usage bug just was fixed you can continue use `master` in docker
or wait next release

**Comment by DrissiReda** [comment]
I don't think so, I obtain the binary using the command:

```
GO111MODULE=on go get github.com/AlexAkulov/clickhouse-backup/cmd/clickhouse-backup
```

which looks like it's obtaining it from master.

**Comment by Slach** [comment]
@DrissiReda do you mean your "go get ..." clickhouse-backup binary is the same by sha256 with `clickhouse-backup` inside "alexakulov/clickhouse-backup:master"?
or different?

**Comment by DrissiReda** [comment]
From source: 6198116c58994b5b5f8f84511cdbffd595b2740035330dc4cec20861c5cdee38
From docker: 01628e3c39e60823ed5112599a5913838d0848f8369cbdd373d755db5e507792

**Comment by Slach** [comment]
which version of golang do you use?
please share
`go env`

**Comment by DrissiReda** [comment]
```
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/root/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/go-1.13"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go-1.13/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="0"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build103182074=/tmp/go-build -gno-record-gcc-switches"

```

**Comment by Slach** [comment]
@DrissiReda try to upgrade go `1.16.6`, maybe some memory leaks was fixed in golang standard library

**Comment by DrissiReda** [comment]
@Slach  Didn't change anything, any idea when the next version will be released?

**Comment by Slach** [comment]
@DrissiReda you cant try to extract clickhouse-bakcup binary from http://hub.docker.com/r/alexakulov/clickhouse-backup/
or use docker image alexakulov/clickhouse-backup:master

**Comment by DrissiReda** [comment]
yeap I know, I just want to know when I can use a docker image with a proper tag that's all :)
