### ISSUE TITLE
The `clean` command disappears in 1.0

### ISSUE THREAD

**Issue by fzyzcjy** [Altinity/clickhouse-backup#210]
Hi thanks for the tool! When upgrading to 1.0, I find that /backup/clean says 404. in addition, `clickhouse-backup clean` also does not work.

**Comment by AlexAkulov** [comment]
Hi @fzyzcjy!
v1.0.0 makes the freeze in a unique path and no longer requires the "clear" command.

**Comment by fzyzcjy** [comment]
get it, thanks
