### ISSUE TITLE
"clickhouse-backup tables -c config.yml" command hangs

### ISSUE THREAD

**Issue by ljinde** [Altinity/clickhouse-backup#223]
Hello All,

I have just downloaded the clickhouse-backup tool release v1.0.0 and trying to list tables that needs to be backed up. This commands is trying to execute the following select statement and gets hung here.. Any one has any idea about this ?

14:33:23 xxxxx@xxxxx:~/test_new/clickhouse-backup # clickhouse-backup tables -c config.yml
2021/07/19 14:33:26 debug SELECT count() FROM system.settings WHERE name = 'show_table_uuid_in_table_create_query_if_not_nil'
2021/07/19 14:33:26 debug SELECT * FROM system.tables WHERE is_temporary = 0 SETTINGS show_table_uuid_in_table_create_query_if_not_nil=1

**Comment by AlexAkulov** [comment]
Do you have data in ClickHouse? Maybe there is nothing to backup?

**Comment by ljinde** [comment]
YES, I have a table in Clickhouse that I am using to backup.. 

SHOW TABLES

Query id: da3719c0-ed9b-4a34-babe-83f78348a82f

┌─name─────────────┐
│ ty_price_history │
└──────────────────┘

1 rows in set. Elapsed: 0.003 sec.

**Comment by AlexAkulov** [comment]
What output of `SHOW CREATE TABLE ty_price_history`?

**Comment by ljinde** [comment]
The process hangs at this stage.. 

13:44:04 xxx@xxxxxxxxx:~/test_new/clickhouse-backup # clickhouse-backup create table ty_price_history -c config.yml
2021/07/22 13:44:36 debug SELECT name, engine FROM system.databases WHERE name != 'system'
2021/07/22 13:44:36 debug SHOW CREATE DATABASE `backup`
2021/07/22 13:44:36 debug SHOW CREATE DATABASE `default`
2021/07/22 13:44:36 debug SHOW CREATE DATABASE `mysql_tyre24`
2021/07/22 13:44:36 debug SHOW CREATE DATABASE `mysql_tyre24_archive`
2021/07/22 13:44:48 debug SHOW CREATE DATABASE `tyre24`
2021/07/22 13:44:48 debug SELECT count() FROM system.settings WHERE name = 'show_table_uuid_in_table_create_query_if_not_nil'
2021/07/22 13:44:48 debug SELECT * FROM system.tables WHERE is_temporary = 0 SETTINGS show_table_uuid_in_table_create_query_if_not_nil=1

**Comment by AlexAkulov** [comment]
Can you run query `SELECT * FROM system.tables WHERE is_temporary = 0 SETTINGS show_table_uuid_in_table_create_query_if_not_nil=1` manually? Do it works?

**Comment by ljinde** [comment]
I tried this it just hangs or processing is very slow. 

b1cf9bc89494 :) SELECT * FROM system.tables WHERE is_temporary = 0 SETTINGS show_table_uuid_in_table_create_query_if_not_nil=1;

SELECT *
FROM system.tables
WHERE is_temporary = 0
SETTINGS show_table_uuid_in_table_create_query_if_not_nil = 1

Query id: 2a256d4e-7c91-4059-9ba8-76043fcc70fc



*****************************************************************************************************************
Also, I can see that there are only 7907 rows in system.tables and it took 8.706 sec to display the results. 

`b1cf9bc89494 :) select count(*) FROM system.tables

SELECT count(*)
FROM system.tables

Query id: 0026511e-c083-4193-a59e-bbecb2f02419

┌─count()─┐
│    7907 │
└─────────┘

1 rows in set. Elapsed: 8.706 sec. Processed 7.91 thousand rows, 7.91 KB (908.17 rows/s., 908.17 B/s.) 

b1cf9bc89494 :) `

***************************************************************************************************************************************
I tried to get the result for just 1 row, even this does not give the result, 

`b1cf9bc89494 :) SELECT * FROM system.tables WHERE is_temporary = 0 limit 1

SELECT *
FROM system.tables
WHERE is_temporary = 0
LIMIT 1

Query id: bcdc6389-504d-4665-a544-9b3a8008299d

`

**Comment by Slach** [comment]
let's try 

```CLICKHOUSE_TIMEOUT=1m clickhouse-backup create table ty_price_history -c config.yml```?

if successful, change `config.yml`
```yaml
clickhouse:
    timeout: 1m
```

**Comment by ljinde** [comment]
I tried the above command, still the same 

15:00:27 xxxxx@xxxxxx:~/test_new/clickhouse-backup # CLICKHOUSE_TIMEOUT=1m clickhouse-backup create table ty_price_history -c config.yml
2021/07/22 15:00:31 debug SELECT name, engine FROM system.databases WHERE name != 'system'
2021/07/22 15:00:31 debug SHOW CREATE DATABASE `backup`
2021/07/22 15:00:31 debug SHOW CREATE DATABASE `default`
2021/07/22 15:00:31 debug SHOW CREATE DATABASE `mysql_tyre24`
2021/07/22 15:00:31 debug SHOW CREATE DATABASE `mysql_tyre24_archive`
2021/07/22 15:00:31 debug SHOW CREATE DATABASE `tyre24`
2021/07/22 15:00:31 debug SELECT count() FROM system.settings WHERE name = 'show_table_uuid_in_table_create_query_if_not_nil'
2021/07/22 15:00:31 debug SELECT * FROM system.tables WHERE is_temporary = 0 SETTINGS show_table_uuid_in_table_create_query_if_not_nil=1

**Comment by ljinde** [comment]
This is the processlist details 

dfcbc1bb5c4 :) show processlist\G

SHOW PROCESSLIST

Query id: e9599e9a-6cae-4564-95c4-ca9e944986dc

Row 1:
──────
is_initial_query:     1
user:                 xxxxx
query_id:             5b9d247d-7eff-43f9-a7a7-0610d5694802
address:              ::ffff:xxx.xxx.xxx.xxx
port:                 37470
initial_user:         xxxxx
initial_query_id:     5b9d247d-7eff-43f9-a7a7-0610d5694802
initial_address:      ::ffff:xxx.xxx.xxx.xxx
initial_port:         37470
interface:            1
os_user:              xxxxxx
client_hostname:      xxxxxxx
client_name:          Golang SQLDriver
client_revision:      54213
client_version_major: 1
client_version_minor: 1
client_version_patch: 54213
http_method:          0
http_user_agent:      
http_referer:         
forwarded_for:        
quota_key:            
elapsed:              527.737945498
is_cancelled:         0
read_rows:            0
read_bytes:           0
total_rows_approx:    0
written_rows:         0
written_bytes:        0
memory_usage:         0
peak_memory_usage:    0
query:                SELECT * FROM system.tables WHERE is_temporary = 0 SETTINGS show_table_uuid_in_table_create_query_if_not_nil=1
thread_ids:           [48,88]
ProfileEvents.Names:  ['Query','SelectQuery','FileOpen','ReadBufferFromFileDescriptorRead','ReadBufferFromFileDescriptorReadBytes','IOBufferAllocs','IOBufferAllocBytes','FunctionExecute','DiskReadElapsedMicroseconds','NetworkSendElapsedMicroseconds','SelectedRows','SelectedBytes','ContextLock','RWLockAcquiredReadLocks']
ProfileEvents.Values: [1,1,1,2,228,1,32783,4,6,337261,1578486,52509870,21,517]
Settings.Names:       ['receive_timeout','send_timeout','use_uncompressed_cache','load_balancing','log_queries','max_memory_usage','show_table_uuid_in_table_create_query_if_not_nil']
Settings.Values:      ['60','60','0','random','0','2000000000','1']

1 rows in set. Elapsed: 0.006 sec.

**Comment by Slach** [comment]
SELECT Version() ?

look like when clickhouse try read someone table related data, query is freeze...

'SelectedRows','SelectedBytes'
1578486, 52509870
is too much

could you share
`find /var/lib/clickhouse/metadata -name *.sql | wc -l` ?

**Comment by ljinde** [comment]
bdfcbc1bb5c4 :) select version()

SELECT version()

Query id: 0d21ec2d-6a38-40fc-85d2-d0ce9351189d

┌─version()─┐
│ 21.3.4.25 │
└───────────┘

1 rows in set. Elapsed: 0.002 sec. 


16:55:13 xxxxx@xxxxxx:/oci/clickhouse-server/persistance/metadata # ll *.sql
-rw-r----- 1 101 101  78 Jul 19 09:53 backup.sql
-rw-r----- 1 101 101  78 Apr  1 10:29 default.sql
-rw-r----- 1 101 101 177 Apr  7 11:24 mysql_tyre24_archive.sql
-rw-r----- 1 101 101 161 Apr  7 11:16 mysql_tyre24.sql
-rw-r----- 1 101 101  78 Apr  1 10:29 system.sql
-rw-r----- 1 101 101  78 Apr  7 11:16 tyre24.sql

**Comment by Slach** [comment]
@ljinde 
please run
find /var/lib/clickhouse/metadata -name *.sql | wc -l

I need to know how much "real" tables you have

as you described https://github.com/AlexAkulov/clickhouse-backup/issues/223#issuecomment-884885473
it was 7 thousand tables

**Comment by Slach** [comment]
also, could you share results of following queries?
```
SELECT database, engine, count() FROM system.tables GROUP BY database
SELECT name, engine FROM system.databases 
```

if your query is stuck, try to run `KILL QUERY WHERE query_id='XXX' SYNC`
where query_id contains in `system.processes`

**Comment by ljinde** [comment]
> find /var/lib/clickhouse/metadata -name *.sql | wc -l

I have the metadata diretory under /oci/clickhouse-server/persistance/metadata

20:14:12 xxxx@xxxxxx:/oci/clickhouse-server/persistance # ll
total 4
drwxr-x---  2 101 101 164 Jul 19 09:57 access
drwxr-x---  6 101 101  63 Jul 22 15:00 data
drwxr-x---  2 101 101   6 Apr  1 10:29 dictionaries_lib
drwxr-x---  2 101 101   6 Apr  1 10:29 flags
drwxr-xr-x  2 101 101   6 Apr  1 10:29 format_schemas
drwxr-x---  4 101 101 240 Jul 19 09:53 metadata
drwxr-x---  2 101 101   6 Apr  1 10:29 metadata_dropped
drwxr-x---  2 101 101  41 Apr  1 10:29 preprocessed_configs
-rw-r-----  1 101 101  56 Jul 22 15:00 status
drwxr-x--- 13 101 101 127 Jul 19 09:55 store
drwxr-xr-x  3 101 101  19 Apr  3 19:06 tmp
drwxr-xr-x  2 101 101   6 Apr  1 10:29 user_files


20:11:50 xxxxx@xxxxx:/oci/clickhouse-server/persistance/metadata # find /oci/clickhouse-server/persistance/metadata -name '*.sql' | wc -l
6

**Comment by ljinde** [comment]
bdfcbc1bb5c4 :) SELECT database, engine, count() FROM system.tables GROUP BY database

SELECT
    database,
    engine,
    count()
FROM system.tables
GROUP BY database

Query id: f44440e9-3a88-4d00-b893-af566293ec88


0 rows in set. Elapsed: 0.002 sec. 

Received exception from server (version 21.3.4):
Code: 215. DB::Exception: Received from localhost:9000. DB::Exception: Column `engine` is not under aggregate function and not in GROUP BY: While processing database, engine, count(). 

*************************************************************************************************************************************

bdfcbc1bb5c4 :) SELECT name, engine FROM system.databases

SELECT
    name,
    engine
FROM system.databases

Query id: 8f5c8ea8-bf67-4b35-893a-4f8d1b00b9f4

┌─name─────────────────┬─engine─┐
│ backup               │ Atomic │
│ default              │ Atomic │
│ mysql_tyre24         │ MySQL  │
│ mysql_tyre24_archive │ MySQL  │
│ system               │ Atomic │
│ tyre24               │ Atomic │
└──────────────────────┴────────┘

6 rows in set. Elapsed: 0.009 sec. 

bdfcbc1bb5c4 :)

**Comment by Slach** [comment]
Could you share
```
SELECT * FROM system.disks;
SELECT database, engine, count() FROM system.tables GROUP BY database, engine
```

**Comment by Slach** [comment]
ohh, i see

```
mysql_tyre24 │ MySQL 
mysql_tyre24_archive │ MySQL 
```

this database engine mean proxy SQL queries from clickhouse to MySQL
https://clickhouse.tech/docs/en/engines/database-engines/mysql/

possible when you run
SELECT * FROM system.tables
it create and proxy around 7000 queries SHOW CREATE TABLE or something like that to MySQL

do you want to backup only ```tyre24.ty_price_history ``` ?

**Comment by ljinde** [comment]
yes I would like to only backup  only "tyre24.ty_price_history "

**Comment by AlexAkulov** [comment]
Hi @ljinde!

We have not tested MySQL engines or thought about how it would work. I'll think about how to fix this. Thank you!

**Comment by ljinde** [comment]
Also, while trying to create backup, SHOW CREATE executes fines for mysql_tyre24 and mysql_tyre24_archive but is stuck at tyre24. 

15:00:27 xxxxx@xxxxxx:~/test_new/clickhouse-backup # CLICKHOUSE_TIMEOUT=1m clickhouse-backup create table ty_price_history -c config.yml
2021/07/22 15:00:31 debug SELECT name, engine FROM system.databases WHERE name != 'system'
2021/07/22 15:00:31 debug SHOW CREATE DATABASE backup
2021/07/22 15:00:31 debug SHOW CREATE DATABASE default
**2021/07/22 15:00:31 debug SHOW CREATE DATABASE mysql_tyre24
2021/07/22 15:00:31 debug SHOW CREATE DATABASE mysql_tyre24_archive
2021/07/22 15:00:31 debug SHOW CREATE DATABASE tyre24**
2021/07/22 15:00:31 debug SELECT count() FROM system.settings WHERE name = 'show_table_uuid_in_table_create_query_if_not_nil'
2021/07/22 15:00:31 debug SELECT * FROM system.tables WHERE is_temporary = 0 SETTINGS show_table_uuid_in_table_create_query_if_not_nil=1

**Comment by ljinde** [comment]
> Hi @ljinde!
> 
> We have not tested MySQL engines or thought about how it would work. I'll think about how to fix this. Thank you!

Thank you @AlexAkulov
