### ISSUE TITLE
Performance issue v1.0.0

### ISSUE THREAD

**Issue by freemanlutsk** [Altinity/clickhouse-backup#229]
Hello!

Are there any recommendations for performance tuning in the v.1.0.0 ?

I’ve switched to v1.0.0 but currently uploading to S3 is not more 600Mbps (gzip,5), with version 0.6.4 was about 2000Mbps.

Thank You for any advices!

**Comment by AlexAkulov** [comment]
Hi @freemanlutsk
Did you use gzip compression too in v0.6.4?

**Comment by freemanlutsk** [comment]
@AlexAkulov Sure, the same settings for both

**Comment by AlexAkulov** [comment]
I added S3_CONCURRENCY option in https://github.com/AlexAkulov/clickhouse-backup/commit/4b7103527d323fb2edfc020f60b7a60e844428e7
Try to increase it on latest docker image.
Note that memory usage is S3_PART_SIZE * S3_CONCURRENCY + some buffers. Reduce S3_PART_SIZE to 100Mb for save memory.

**Comment by freemanlutsk** [comment]
Works like a charm! With `S3_CONCURRENCY: 5` uploading is even better then in the **v0.6.4**.
Many thanks for quick fix!
