### ISSUE TITLE
Q: Do we need to backup ZooKeeper metadata for ClickHouse cluster?

### ISSUE THREAD

**Issue by leiless** [Altinity/clickhouse-backup#231]
Hi, @AlexAkulov.

I recently came across clickhouse backup related issues, I have a ClickHouse cluster that has three clickhouse instances, three ZooKeeper nodes.

My question are:
* Do we need to backup ZooKeeper metadata for this ClickHouse cluster?
* If we need to(backup ZooKeeper metadata), how can we?

Sorry, it may not be strictly related to ClickHouse backup, but I struggled for a while, glad if you can help.

**Comment by Slach** [comment]
@leiless 
Zookeeper contains only replication queue with list data parts names which is not replicated between replicas, and distributed DDL queries

you don't need to backup Zookeeper data during run `clickhouse-backup`

when you will restore clickhouse tables via `clickhouse-backup`, your newly attached data parts for the table with ReplicatedMergeTree engine will register in Zookeeper and will replicate if not exists to another replicas

**Comment by leiless** [comment]
Thank you! @Slach
So you mean that for ClickHouse backup, we don't need to care about ZooKeeper metadata at all?

**Comment by Slach** [comment]
@leiless, when you restore in the new fresh server which have a new value 'replica' macro in `system.macros` 
you can just restore

if you try to restore in old server which already have the same ZK path and already registered replica

use 
`clickhouse-backup restore --rm <backup_name>`
to avoid conflicts

**Comment by leiless** [comment]
Thank you! @Slach
