### ISSUE TITLE
clickhouse-backup tables -c config.yml is hung 

### ISSUE THREAD

**Issue by smpa0321** [Altinity/clickhouse-backup#237]
i did the below steps on ubuntu 18.0.4 LTS (windows subsystem)

 wget https://github.com/AlexAkulov/clickhouse-backup/releases/download/v1.0.0/clickhouse-backup.tar.gz
tar -xf clickhouse-backup.tar.gz 
cd clickhouse-backup/ 
sudo cp clickhouse-backup /usr/local/bin 
clickhouse-backup -v

after executing clickhouse-backup tables -c config.yml 

It is hung not ablt to see any log/info ( log_level: debug)

Please suggest

**Comment by smpa0321** [comment]
however with docker command i see below response
sudo docker run --rm -it --network host  -v "/var/lib/clickhouse:/var/lib/clickhouse" -e CLICKHOUSE_PASSWORD="<>" -e S3_BUCKET="clickhouse-backup" -e S3_ACCESS_KEY="access_key" -e S3_SECRET_KEY="secret"  alexakulov/clickhouse-backup:1.0.0 tables --config config.yml

prom.test  346B  default

Please point am i missing something

**Comment by Slach** [comment]
@smpa0321 please provide more context
```
cat config.yml
LOG_LEVEL=debug clickhouse-backup tables -c config.yml
```

**Comment by AlexAkulov** [comment]
I didn't try to run it on Windows subsystem.

**Comment by Slach** [comment]
@AlexAkulov I'm tried, it works fine
but the initial topic starter didn't provide more context

clickhouse-backup can hang cause can't connect to clickhouse with long timeout
or can hung cause `system.databases` contains some integration engines (PostgreSQL, MySQL etc.), cause can't get metadata from MySQL \ PostgreSQL databases

**Comment by Slach** [comment]
@smpa0321 is issue still actual for you?

could you try to use https://github.com/Altinity/clickhouse-backup/releases/tag/1.0.16?

**Comment by Slach** [comment]
@smpa0321 do you have Engine=MySQL() or Engine=PostgreSQL() tables in your `system.tables`?

**Comment by Slach** [comment]
close issue after topic starter inactivity, feel free comment and we will re-open if issue still relevant for you
