### ISSUE TITLE
Encryption before upload?

### ISSUE THREAD

**Issue by freeyoung** [Altinity/clickhouse-backup#24]
It would be nice that the archive is encrypted before sending to S3.

**Comment by AlexAkulov** [comment]
PR are welcomed!

**Comment by therealnb** [comment]
We were thinking about something similar. The requirement would be to have some sort of plug-in framework that could preprocess the uploads, handle auth and distribution to multiple sites. We haven't specified this in any detail yet.

Another option is to use some sort of s3 proxy.
