### ISSUE TITLE
how to change default backup path 'var/lib/clickhouse'

### ISSUE THREAD

**Issue by zidingyi94** [Altinity/clickhouse-backup#245]
default backup path : 'var/lib/clickhouse',
my clickhouse volume path :'/etc/cs/clickhouse'
I want to modify backup path  to  '/etc/cs/clickhouse'

**Comment by Slach** [comment]
try to modify your `/etc/clickhouse-backup/config.yml` `clickhouse` -> `disk_mapping` section

which clickhouse-backup version do you use? try to use 1.0.0

**Comment by zidingyi94** [comment]
> try to modify your `/etc/clickhouse-backup/config.yml` `clickhouse` -> `disk_mapping` section
> 
> which clickhouse-backup version do you use? try to use 1.0.0

it work , thank you！
