### ISSUE TITLE
remote_storage: none leads to config validation failure

### ISSUE THREAD

**Issue by widders** [Altinity/clickhouse-backup#246]
With remote_storage set to 'none' all functions exit with: "error 'none' is unsupported compression format"

I tracked it to line 201 of config/config.go where the check on remote_storage was removed in commit ab563711c89a781d58fabf8839b934ca46e37caf

**Comment by AlexAkulov** [comment]
Thank you! It will be fixed in next version.

**Comment by Slach** [comment]
@widders did you try the latest 1.1.0+ clickhouse-backup release? 

I tried to reproduce your issue with following config
```
general:
  remote_storage: none
```

`clickhouse-backup list` and `clickhouse-backup list local` works ok
all command which related to remote_srorage aborted with properly error message

I close issue, feel free to make comment or reopen if necessary
