### ISSUE TITLE
restore fails even after db dropping 

### ISSUE THREAD

**Issue by susa0421** [Altinity/clickhouse-backup#249]
Hi , 
I am facing this issues and below is my understanding:

Steps i followed: 
1. Backup took 
2. Dropping dbs (default, test(table-watchlog))
3. hit restore api - initially it fails with below error 
4. after 20-30 min when i hit 'restore' again it is successful as seems like it gets clear form clickhouse-watchdog
--> clickhouse-watchdog        --config-file /etc/clickhouse-server/config.xml --pid-file /var/run/clickhouse-server/clickhouse-server.pid --daemon

Error:
2021/08/20 11:51:46  warn can't create table 'default.WatchLog_old': code: 57, message: Directory for table data store/017/017185e2-f2a0-4560-8171-85e2f2a0a560/ already exists, will try again
2021/08/20 11:51:46 error **Download error: can't create table `test`.`WatchLog_old`: code: 57, message: Directory for table data store/766/76643462-6cdb-458f-b664-34626cdb958f/ already exists after 2 times, please check your schema depencncies**

2021/08/20 12:33:17  info done                      backup=2021-08-20T11-16-02 operation=restore table=default.WatchLog_old
2021/08/20 12:33:17  info done                      backup=2021-08-20T11-16-02 operation=restore table=test.WatchLog_old
2021/08/20 12:33:17  info done                      backup=2021-08-20T11-16-02 operation=restore

Question is : how to do restore and if there any workaround to resolve this!

**Comment by AlexAkulov** [comment]
@susa0421 
If you use an Atomic database engine and you manually drop this table without of `SYNC` flag. The old directory will still last for about 6 minutes. Use the `--rm` flag to restore the backup or use `SYNC` flag if you drop tables manually.

**Comment by Slach** [comment]
I close the issue due to inactivtiy, @susa0421 if the issue is still relevant for you, please feel free to comment and it will re-open
also, try to use https://github.com/Altinity/clickhouse-backup/releases/tag/1.0.16
