### ISSUE TITLE
Fail to restore

### ISSUE THREAD

**Issue by KELiON** [Altinity/clickhouse-backup#251]
My `clickhouse-backup restore` fails with an error:

```
2021/08/24 14:34:39 error can't restore '...': error during filepath.Walk for partition 'all_1229_1279_4': failed to crete hard link '/var/lib/clickhouse/backup/...all_1229_1279_4/%24insert_id.bin' -> '/var/lib/clickhouse/store/...all_1229_1279_4/%24insert_id.bin': link /var/lib/clickhouse/backup/...%24insert_id.bin /var/lib/clickhouse/store/...%24insert_id.bin: file exists
```

I've created backup on one instance and try to restore it to another (remote instance in yandex.cloud). I had another issue before but looks like after changing `freeze_by_part` to `true` I have new one.

So, any suggestions what can help to restore the backup?

**Comment by Slach** [comment]
do you use the same clickhouse-backup version for backup and restore?

**Comment by KELiON** [comment]
@Slach yes, `clickhouse-backup --version` is 

```
Version:	 1.0.0
Git Commit:	 37f3bd78adec2aadc1de10f9323fe426a5e12dc4
Build Date:	 2021-06-16
```

**Comment by KELiON** [comment]
@Slach btw, I decided to check clickhouse version and it is different. I've created backup of clickhouse 20.12.5 (revision 54442) and try to restore it to the 21.8.4 (revision 54449). Could be be the reason? If so, any ideas how can I move the data using `clickhouse-backup`?

**Comment by Slach** [comment]
ok. look like you just try to restore backup on new server where data already exists

try to use
```LOG_LEVEL=debug clickhouse-backup restore --rm <backup_name>```

and share logs if it failed

**Comment by KELiON** [comment]
@Slach it fails immediately with error:

```
> LOG_LEVEL=debug sudo ./clickhouse-backup restore --rm 2021-08-24-18-00 -c config.yml
2021/08/25 07:31:45 error can't connect to clickhouse: dial tcp 127.0.0.1:9000: connect: connection refused
```

FYI: in config.yml I've changed clickhouse config so it works with remote clickhouse

**Comment by Slach** [comment]
did you check `systemctl clickhouse-server status`?
how you run clickhouse? it's a docker container or standalone server?

**Comment by Slach** [comment]
@KELiON you shall run clickhouse-backup on the same host where you will restore data
cause restoring data is going via create hardlinks

**Comment by KELiON** [comment]
@Slach I see. I don't think it is possible for clickhouse instances in cloud.yandex.ru (I can't ssh and install clickhouse-backup there). Is there any way to restore backup to remote instance?

**Comment by AlexAkulov** [comment]
Hi @KELiON 
I think the most likely reason for this error is that clickhouse is getting new data while restoring from a backup. Clickhouse writes this data to the part with the same name as the part from the backup before clickhouse-backup tried to restore it. 

`freeze_by_part: true` can also result in a broken backup, but usually this error looks like "could not create a hard link because the file was not found". I don't recommend using this option for no reason.

**Comment by AlexAkulov** [comment]
And one more question. 
Do you use `--rm` flag on backup restore?

**Comment by Slach** [comment]
> Is there any way to restore backup to remote instance?
No, it's not possible


you can try to use
`INSERT INTO ... SELECT FROM remote()`

if you need to just move data from your clickhouse to yandex cloud
look https://clickhouse.tech/docs/en/sql-reference/table-functions/remote/ for details

**Comment by KELiON** [comment]
@Slach ok, going to try! Thank you!
