### ISSUE TITLE
I have clickhouse cluster with 2 shard 1 replicated, when i run clickhouse-backup has error

### ISSUE THREAD

**Issue by cntsp** [Altinity/clickhouse-backup#253]
./clickhouse-backup --config config.yml create tables
2021/08/31 03:28:42 error cat't get tables from clickhouse: code: 999, message: Session expired (Session expired): While executing Tables

The clickhouse cluster has 3 clickhouse  instances of docker deploying(shard1 \shard2\replicated1), the some tables engine of is distributed. about the  parts configuration of the cluster's config.xml

![image](https://user-images.githubusercontent.com/26156442/131446674-0955d48e-72ec-4069-a0d7-347782286d7d.png)

**Comment by Slach** [comment]
could you share
`LOG_LEVEL=debug ./clickhouse-backup --config config.yml create test_backup`
result?

**Comment by cntsp** [comment]
LOG_LEVEL=debug ./clickhouse-backup --config config.yml tables
2021/08/31 07:21:37 debug SELECT count() FROM system.settings WHERE name = 'show_table_uuid_in_table_create_query_if_not_nil'
2021/08/31 07:21:37 debug SELECT * FROM system.tables WHERE is_temporary = 0 SETTINGS show_table_uuid_in_table_create_query_if_not_nil=1
2021/08/31 07:21:37 error can't get tables: code: 999, message: Session expired (Session expired): While executing Tables


![image](https://user-images.githubusercontent.com/26156442/131461424-0df1b765-7d3b-4a64-9a5b-3914fc0e481a.png)

**Comment by Slach** [comment]
could you share the results of
```
SELECT name, engine FROM system.databases WHERE name !='system'
```
?

**Comment by Slach** [comment]
also, could you try to use `alexakulov/clickouse-backup:master` docker image instead of standalone binary?

**Comment by cntsp** [comment]
![image](https://user-images.githubusercontent.com/26156442/131478621-abd96fc2-3185-4eda-8ce7-25b0532f3a88.png)

**Comment by cntsp** [comment]
![image](https://user-images.githubusercontent.com/26156442/131478705-86626dee-92d6-4b59-94d2-e3f067756ec6.png)

**Comment by Slach** [comment]
is `SELECT * FROM system.tables WHERE is_temporary = 0 SETTINGS show_table_uuid_in_table_create_query_if_not_nil=1`
works from `clickhouse-client` ?

**Comment by cntsp** [comment]
dev8 :) SELECT * FROM system.tables WHERE is_temporary = 0 SETTINGS show_table_uuid_in_table_create_query_if_not_nil=1

SELECT *
FROM system.tables
WHERE is_temporary = 0
SETTINGS show_table_uuid_in_table_create_query_if_not_nil = 1

Query id: 19c8ec72-eb87-4773-b56f-2a734440fc4b


Received exception from server (version 20.11.4):
Code: 999. DB::Exception: Received from localhost:9000. DB::Exception: Session expired (Session expired): While executing Tables.

0 rows in set. Elapsed: 0.406 sec.

**Comment by Slach** [comment]
let's try to execute
```sql
SELECT engine, name FROM system.tables WHERE engine NOT LIKE  '%MergeTree' AND is_temporary = 0
```

**Comment by cntsp** [comment]
dev8 :) SELECT engine, name FROM system.tables WHERE engine NOT LIKE  '%MergeTree' AND is_temporary = 0

SELECT
    engine,
    name
FROM system.tables
WHERE (engine NOT LIKE '%MergeTree') AND (is_temporary = 0)

Query id: 3adf4cb2-7699-44b9-82a3-ea92902552be

┌─engine─────────────────────────────┬─name───────────────────────────┐
│ MaterializedView                   │ daf2_local_batch               │
│ View                               │ daf2n                          │
│ MaterializedView                   │ daf2n_local_batch              │
│ Distributed                        │ daf2na                         │
│ MaterializedView                   │ daf2np_local_batch             │
│ MaterializedView                   │ daf2npr_local_batch            │
│ MaterializedView                   │ daf2nr_local_batch             │
│ View                               │ fact_rsk_brm_bad_tag_v         │
│ View                               │ ms_bad_tag_final_v             │
│ Distributed                        │ test1_distributed              │
│ MaterializedView                   │ idi_key_join_v                 │
│ Log                                │ lcw_records                    │
│ Distributed                        │ AccountRecovery                │
│ Distributed                        │ AddACH                         │
│ Distributed                        │ AddAddress                     │
│ Distributed                        │ AddCC                          │
│ Distributed                        │ AddEmail                       │
│ Distributed                        │ AddPhone                       │
│ Distributed                        │ AsyncLogin                     │
│ Distributed                        │ ChangePinDC                    │
│ Distributed                        │ ChangeShippingAddressDC        │
│ Distributed                        │ ConsentCreation                │
│ Distributed                        │ ConsolidatedFunding            │
│ Distributed                        │ Deposit                        │
│ Distributed                        │ DisputeLifecycleAdjudication   │
│ Distributed                        │ DisputeLifecycleInitiation     │
│ Distributed                        │ Eval3DSAuth                    │
│ Distributed                        │ EvalACHReturnsRisk             │
│ Distributed                        │ EvalBestCustomerSupportAction  │
│ Distributed                        │ FundingPOS                     │
│ Distributed                        │ FundingPartnerPayments         │
│ Distributed                        │ GenericFailedPayment           │
│ Distributed                        │ GenericIdentity                │
│ Distributed                        │ GenericTransaction             │
│ Distributed                        │ HoldsAssessment                │
│ Distributed                        │ Login                          │
│ Distributed                        │ PartnerWithdrawal              │
│ Distributed                        │ PostSignup                     │
│ Distributed                        │ RemoveACH                      │
│ Distributed                        │ RemoveAddress                  │
│ Distributed                        │ RemoveCC                       │
│ Distributed                        │ RemoveEmail                    │
│ Distributed                        │ RemovePhone                    │
│ Distributed                        │ ReportLostStolenDC             │
│ Distributed                        │ RiskLiteLogin                  │
│ Distributed                        │ RouteWorkItem                  │
│ Distributed                        │ WithdrawalAttempt              │
│ View                               │ ct_mapping_v                   │
│ MaterializedView                   │ genesys_routeworkitem_view     │
│ SystemAggregateFunctionCombinators │ aggregate_function_combinators │
│ SystemAsynchronousMetrics          │ asynchronous_metrics           │
│ SystemBuildOptions                 │ build_options                  │
│ SystemClusters                     │ clusters                       │
│ SystemTableCollations              │ collations                     │
│ SystemColumns                      │ columns                        │
│ SystemContributors                 │ contributors                   │
│ SystemCurrentRoles                 │ current_roles                  │
│ SystemTableDataTypeFamilies        │ data_type_families             │
│ SystemDatabases                    │ databases                      │
│ SystemDetachedParts                │ detached_parts                 │
│ SystemDictionaries                 │ dictionaries                   │
│ SystemDisks                        │ disks                          │
│ SystemDistributionQueue            │ distribution_queue             │
│ SystemEnabledRoles                 │ enabled_roles                  │
│ SystemErrors                       │ errors                         │
│ SystemEvents                       │ events                         │
│ SystemFormats                      │ formats                        │
│ SystemFunctions                    │ functions                      │
│ SystemGrants                       │ grants                         │
│ SystemGraphite                     │ graphite_retentions            │
│ SystemLicenses                     │ licenses                       │
│ SystemMacros                       │ macros                         │
│ SystemMergeTreeSettings            │ merge_tree_settings            │
│ SystemMerges                       │ merges                         │
│ SystemMetrics                      │ metrics                        │
│ SystemModels                       │ models                         │
│ SystemMutations                    │ mutations                      │
│ SystemNumbers                      │ numbers                        │
│ SystemNumbers                      │ numbers_mt                     │
│ SystemOne                          │ one                            │
│ SystemParts                        │ parts                          │
│ SystemPartsColumns                 │ parts_columns                  │
│ SystemPrivileges                   │ privileges                     │
│ SystemProcesses                    │ processes                      │
│ SystemQuotaLimits                  │ quota_limits                   │
│ SystemQuotaUsage                   │ quota_usage                    │
│ SystemQuotas                       │ quotas                         │
│ SystemQuotasUsage                  │ quotas_usage                   │
│ SystemReplicas                     │ replicas                       │
│ SystemReplicatedFetches            │ replicated_fetches             │
│ SystemReplicatedMergeTreeSettings  │ replicated_merge_tree_settings │
│ SystemReplicationQueue             │ replication_queue              │
│ SystemRoleGrants                   │ role_grants                    │
│ SystemRoles                        │ roles                          │
│ SystemRowPolicies                  │ row_policies                   │
│ SystemSettings                     │ settings                       │
│ SystemSettingsProfileElements      │ settings_profile_elements      │
│ SystemSettingsProfiles             │ settings_profiles              │
│ SystemStackTrace                   │ stack_trace                    │
│ SystemStoragePolicies              │ storage_policies               │
│ SystemTableEngines                 │ table_engines                  │
│ SystemTableFunctions               │ table_functions                │
│ SystemTables                       │ tables                         │
│ SystemTimeZones                    │ time_zones                     │
│ SystemUserDirectories              │ user_directories               │
│ SystemUsers                        │ users                          │
│ SystemZeros                        │ zeros                          │
│ SystemZeros                        │ zeros_mt                       │
│ SystemZooKeeper                    │ zookeeper                      │
│ View                               │ ms_bad_tag_final_v1            │
│ Distributed                        │ test1_distributed              │
│ MaterializedView                   │ test_view                      │
└────────────────────────────────────┴────────────────────────────────┘

112 rows in set. Elapsed: 0.008 sec.

**Comment by cntsp** [comment]
Excuse me, I need to make some marks！
![image](https://user-images.githubusercontent.com/26156442/131642940-f6d15a09-f233-47ca-8b11-c974c116b82a.png)
![image](https://user-images.githubusercontent.com/26156442/131643041-c2831d8a-6d49-486a-9965-9a6b16148411.png)

**Comment by Slach** [comment]
ok. let's try to do something like this to detect which table is root cause of error:

```bash
clickhouse-client -mn --echo <$( clickhouse-client -q "SELECT concat('SELECT * FROM system.tables WHERE name=\\'',name,'\\' AND is_temporary = 0 SETTINGS show_table_uuid_in_table_create_query_if_not_nil=1') FROM system.tables WHERE is_temporary = 0 " )
```

**Comment by cntsp** [comment]
Sorry, I need to make some marks！
![image](https://user-images.githubusercontent.com/26156442/131768098-7101d76c-f74e-4811-831a-a4b6fc0fd507.png)

**Comment by cntsp** [comment]
sh: 2: cannot open SELECT * FROM system.tables WHERE name=\'.inner.daf2_local_batch\' AND is_temporary = 0 SETTINGS show_table_uuid_in_table_create_query_if_not_nil=1
Is the table .inner.daf2_local_batch root cause of error?

**Comment by Slach** [comment]
no, I don't think so ;) sorry for a little bit bash misleads
try to run
```
clickhouse-client -q "SELECT concat('SELECT * FROM system.tables WHERE database=',char(0x27),database,char(0x27),' AND name=',char(0x27),name,char(0x27),' AND is_temporary = 0 SETTINGS show_table_uuid_in_table_create_query_if_not_nil=1 FORMAT Vertical;') FROM system.tables WHERE is_temporary = 0 FORMAT TSVRaw" | clickhouse-client -mn --echo
```

and share the results

**Comment by Slach** [comment]
@cntsp is the issue still relevant for you?
Did you try the latest releases 1.1.0+?

Let's close issue, during inactivity, feel free to reopen if necessary
