### ISSUE TITLE
Can't use with s3 + temporary credentials

### ISSUE THREAD

**Issue by silverbullet1** [Altinity/clickhouse-backup#259]
So in my org I have the concept of [temporary credentials in IAM ](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_temp_use-resources.html), so to access S3(or any other service) I also need to set **session token** apart from access key and secret, otherwise it doesn't work.

But there is no option to set this parameter in clickhouse-backup, and setting just key and secret gives me this error : error InvalidAccessKeyId: The AWS Access Key Id you provided does not exist in our records.

Would love to know if there's any workaround for this!

Thanks.

**Comment by Slach** [comment]
currently is no workaround for this use-case
look like good candidate
to feature request

**Comment by silverbullet1** [comment]
Okay, thanks for the heads up. It would be great if we can have it in future :)

**Comment by Slach** [comment]
so, as I understood which credentials do you have on start?
do you have AWS_SECRET_KEY, AWS_ACCESS_KEY and IAM ARN role? 

or you have only IAM on start?

according to https://docs.aws.amazon.com/sdk-for-go/api/aws/credentials/stscreds/
you still need AWS_SECRET_KEY, AWS_ACCESS_KEY  to try to call AssumeRole

**Comment by silverbullet1** [comment]
I only have temporary AWS_SECRET_KEY & AWS_ACCESS_KEY.
As a workaround, I have got a headless IAM user so I can have permanent credentials.

**Comment by Slach** [comment]
@silverbullet1 do you have ARN role for assume?
look like your issue duplicated with https://github.com/AlexAkulov/clickhouse-backup/issues/42? am I right?

**Comment by silverbullet1** [comment]
Yes that's the same issue.

**Comment by Slach** [comment]
ok. great lest close duplicated  issue
