### ISSUE TITLE
Can't  restore from backup

### ISSUE THREAD

**Issue by andrewmillion** [Altinity/clickhouse-backup#26]
The metadata was restored. After that try restore data:

sudo ./clickhouse-backup -c ./config.yml restore-data $BACKUP_NAME

2019/05/03 15:16:55 Prepare data for restoring 'analytics.events'
2019/05/03 15:16:55 ALTER TABLE analytics.events ATTACH PARTITION ID '201905'
2019/05/03 15:16:55 can't attach partitions for table 'analytics.events' with code: 226, message: No columns in part 201905_1_1128_227

**Comment by AlexAkulov** [comment]
Hi!
Check files permissions, please.
I fixed similar bug in v0.3.1

**Comment by AlexAkulov** [comment]
Did you manage to restore your data?

**Comment by tangyong** [comment]
from https://github.com/AlexAkulov/clickhouse-backup/blob/master/integration_test.go, seems that restoring data has been supported, right? 

if true, the project name should be modified not only backing up.

**Comment by AlexAkulov** [comment]
@tangyong 
Right! Do you have any ideas for a new project name? :-)

**Comment by AlexAkulov** [comment]
Outdated
