### ISSUE TITLE
couldn't restore data from local backup(v1.0.0-beta2 and v1.0.0)

### ISSUE THREAD

**Issue by michael-liumh** [Altinity/clickhouse-backup#265]
Like title, I make a simple test, create local backup first, then drop database, then try to restore local backup.
### 1. create local backup
![image](https://user-images.githubusercontent.com/40595864/133414268-b07b7aed-bd16-4494-b20e-be04b58f0812.png)
### 2. drop database
![image](https://user-images.githubusercontent.com/40595864/133414310-ab352179-2087-4515-91a9-972f680a1191.png)
### 3. try to restore local backup
![image](https://user-images.githubusercontent.com/40595864/133414372-938bd306-7b19-48c0-b51f-19a22551b1a7.png)

The test data comes from :
https://clickhouse.tech/docs/en/getting-started/example-datasets/metrica/
https://datasets.clickhouse.tech/visits/tsv/visits_v1.tsv.xz

**Comment by michael-liumh** [comment]
I try to use other release packet to test, I found v1.0.0-beta1 and v1.0.0-alpha1 is ok for backup and restore test data.

**Comment by goto217** [comment]
@michael-liumh  
I find last clickhouse table data folder(uuid) not be immediately deleted after drop database. I usually wait a while and restore backup.  or  i  restart clickhouse server,  table data folder will disappear.

Is there a better way? make sure table data folder be immediately deleted?

**Comment by Slach** [comment]
@goto217 @michael-liumh 
if you run manual `DROP DATABASE db.table`, use `DROP DATABASE db.table NO DELAY`
or use `clickhouse-backup restore --rm <backup_name>`
