### ISSUE TITLE
[QUESTION/BUG] Freezing query is failed due syntax error: CH version is 19.5.3

### ISSUE THREAD

**Issue by alexandrst88** [Altinity/clickhouse-backup#27]
Hi!

I have clickhouse version: 19.5.3, and the the query is failed

```
ALTER TABLE db_test.test_table FREEZE PARTITION ID '201905'
```

Error output:

```
Code: 368. DB::Exception: Received from localhost:9000, 127.0.0.1. DB::Exception: std::bad_typeid.
```

So basically, if remove **ID** from query everything works fine.

Is this issue caused by clickhouse-server version? 

UPDATE:

Also, I've checked official docs and few links, and indeed **ID** is omitted.

**Comment by AlexAkulov** [comment]
Hello!
Please, write output of these commands:
```
select create_table_query,partition_key,primary_key from system.tables where name='test_table'
select * from system.parts where table='test_table' limit 100
```

**Comment by alexandrst88** [comment]
can be closed
