### ISSUE TITLE
warn can't sync replica: driver: bad connection

### ISSUE THREAD

**Issue by 825644691** [Altinity/clickhouse-backup#271]
2021/09/22 01:09:42  info done                      backup=2021-09-21T17-09-42 operation=create table=log..inner_id.0f5c667a-c624-423d-8f5c-667ac624b23d
2021/09/22 01:09:42  info done                      backup=2021-09-21T17-09-42 operation=create table=log..inner_id.93e77347-2ee1-4c91-93e7-73472ee1bc91
2021/09/22 01:09:42  info done                      backup=2021-09-21T17-09-42 operation=create table=log..inner_id.d9adc34c-0d8e-4650-99ad-c34c0d8e0650
2021/09/22 01:09:42  info done                      backup=2021-09-21T17-09-42 operation=create table=log.ainoah_domain_statis_global
2021/09/22 01:09:42  info done                      backup=2021-09-21T17-09-42 operation=create table=log.ainoah_domain_statis_local
2021/09/22 01:09:42  info done                      backup=2021-09-21T17-09-42 operation=create table=log.biglog_domain_statis_global
2021/09/22 01:09:42  info done                      backup=2021-09-21T17-09-42 operation=create table=log.biglog_domain_statis_local
2021/09/22 01:09:42  info done                      backup=2021-09-21T17-09-42 operation=create table=log.default_domain_statis_global
2021/09/22 01:09:42  info done                      backup=2021-09-21T17-09-42 operation=create table=log.default_domain_statis_local
2021/09/22 01:09:42  info done                      backup=2021-09-21T17-09-42 operation=create table=log.log_ai_noah_all_3
2021/09/22 01:09:42  info done                      backup=2021-09-21T17-09-42 operation=create table=log.log_ai_noah_all_7
2021/09/22 01:09:42  info done                      backup=2021-09-21T17-09-42 operation=create table=log.log_ai_noah_global_read_3
2021/09/22 01:12:42  warn can't sync replica: driver: bad connection
2021/09/22 01:12:42  info done                      backup=2021-09-21T17-09-42 operation=create table=log.log_ai_noah_local_3
2021/09/22 01:12:42  info done                      backup=2021-09-21T17-09-42 operation=create table=log.log_ai_noah_local_7
2021/09/22 01:12:42  info done                      backup=2021-09-21T17-09-42 operation=create table=log.log_biglog_global
2021/09/22 01:12:42  info done                      backup=2021-09-21T17-09-42 operation=create table=log.log_biglog_global_read

SHOW SETTINGS LIKE '%distributed_ddl_task_timeout%'

Query id: 0c2f2242-316a-41eb-9ca2-888cdd50663e

┌─name─────────────────────────┬─type──┬─value─┐
│ distributed_ddl_task_timeout │ Int64 │ 86400 │
└──────────────────────────────┴───────┴───────┘

config.xml
general:
  remote_storage: sftp
  max_file_size: 1099511627776
  disable_progress_bar: false
  backups_to_keep_local: 0
  backups_to_keep_remote: 0
  log_level: info
  allow_empty_backups: false
clickhouse:
  username: default
  password: ""
  host: localhost
  port: 9000
  disk_mapping: {}
  skip_tables:
  - system.*
  timeout: 500m
  freeze_by_part: True
  secure: false
  skip_verify: false

It looks like clickhouse close the connection? every 180s

**Comment by Slach** [comment]
No, it looks like `clickhouse-backup` get timeout after run `SYNC REPLICA db.table` for table `log.log_ai_noah_global_read_3` with `*ReplicatedMergeTree` engine
It means,  you actively insert into this table during run `clickhouse-backup`
and new data parts metadata created in ZK queue before all old data parts fetched
you could try to increase more rows per one insert statement 
https://clickhouse.com/docs/en/sql-reference/statements/insert-into/#performance-considerations

it is not related to `distributed_ddl_taks_timeout`

It's WARNING, not error, so your backup created successfully

**Comment by 825644691** [comment]
OH， Thank you
