### ISSUE TITLE
Make S3 partSize as config option

### ISSUE THREAD

**Issue by vanyasvl** [Altinity/clickhouse-backup#273]
Default partSize calculation `partSize := cfg.General.MaxFileSize / 10000` isn't work good with some S3 compatible storages like Swift. Swift has a low performance with a small chunks and doesn't accept chunks more than 5Gb. 

So it will be good to have S3 partSize in config.

**Comment by Slach** [comment]
thanks a lot for reporting, it make sense, and could be implements
