### ISSUE TITLE
Can't upload backup via SFTP 

### ISSUE THREAD

**Issue by Philippians413** [Altinity/clickhouse-backup#274]
Hello!
SFTP configs:
```
SFTP_PATH=backup/clickhouse/development
SFTP_PASSWORD=11223344
SFTP_USERNAME=username
SFTP_PORT=2232
SFTP_ADDRESS=x.x.x.x
```
`clickhouse-backup create` finished successfully, but upload not.
```
$ LATEST_BACKUP=$(clickhouse-backup list local latest)
$ echo $LATEST_BACKUP
2021-09-23T15-39-36
$ clickhouse-backup upload $LATEST_BACKUP
2021/09/23 16:00:41 error can't connect to SFTP: open 11223344: no such file or directory
```
I have no idea why password is reading as file.
Could you take a look, please?

Regards,
Bohdan

**Comment by Slach** [comment]
Thanks a lot for reporting
I found root reason 
![image](https://user-images.githubusercontent.com/105560/137267484-04e4e833-0147-4c5e-ae74-1e9d70e52248.png)
as quick workaround could you define /etc/clickhouse-backup/config.yml with
```yaml 
general:
  remote_storage: sftp
sftp:
  password: 111223344
  username: username
...
```

**Comment by besteffects** [comment]
@Slach Is there a typo? 
 `remote_stroage: sftp`
Did you mean `remote_storage`?

**Comment by Slach** [comment]
@besteffects yep, sorry `remote_storage: sftp`

**Comment by Slach** [comment]
fixed on https://github.com/AlexAkulov/clickhouse-backup/pull/288
