### ISSUE TITLE
Add FREEZE LAST N PARTS 

### ISSUE THREAD

**Issue by dsemenischev** [Altinity/clickhouse-backup#275]
For Increment backup of  Insert Only Table add possibility to FREEZE only last partitions.

**Comment by Slach** [comment]
implemented via `--partition=XXXX,YYYY` parameter for create backup in 1.3.0
you can calculate last partition in your backup script and pass parameter

**Comment by Slach** [comment]
cause PARTITION BY .. could be not only date based expression, and you can insert data into multiple partitions, we can't detect properly "last" partitions
