### ISSUE TITLE
Trying to migrate my 1.X database to 2.X 

### ISSUE THREAD

**Issue by DipalPrajapati** [Altinity/clickhouse-backup#277]
- I have a scenario where I need to migrate older  application version of db to new application version  db.
- Where I do have changes in schema(mostly fields length) plus there is difference of shard and replica macro name. 
Before we were using per cluster macro (replicaC1 and replicaC2) but now we have containerized clickhouse and came to know that it automatically map the macro name from cluster given. 
- Can you suggest how to restore my 1.x backup to 2.X app db ?

**Comment by Slach** [comment]
You cannot restore data from schema 1.x to schema 2.x via `clickhouse-backup` and any other tool

**Comment by DipalPrajapati** [comment]
Well , in the schema , there is only difference of column types.  We have not introduced new columns in existing tables. then also is it not possible?

**Comment by Slach** [comment]
But the physical representation is different
and during restore via ATTACH with data in other type schema you will go error in any database, not only ClickHouse

schema and physical level should be consistent

**Comment by DipalPrajapati** [comment]
OK thank you.
