### ISSUE TITLE
OOM Killer v1.1.0

### ISSUE THREAD

**Issue by freemanlutsk** [Altinity/clickhouse-backup#279]
Hello!

I've faced the following problem after upgrading to **v1.1.0**:

Do you have any advice on how to avoid this behavior?

`[ RESPONSE ]--------------------------------------\nHTTP/1.1 200 OK\r\nContent-Length: 0\r\nDate: Thu, 07 Oct 2021 07:15:15 GMT\r\nEtag: \"5e4374ab4eedec9d5c560ac3f92d0f3e\"\r\nServer: AmazonS3\r\nX-Amz-Id-2: ciYv8lv1VIMxVPXfdfixcufNUNU+F8X+ZLFLQ8Vpg3MRmvSF2TLpuEUeR8DIs2txuRrs1L0xdgE=\r\nX-Amz-Request-Id: ZTF3ZBKE95K2PE8C\r\n\r\n\n-----------------------------------------------------\n2021/10/07 07:15:14  info done                      backup=clickhouse-2021-10-07-1633590683 duration=779ms operation=upload size=2.17KiB table=db.xxx\n", "status": 137}`

`[Thu Oct  7 07:15:43 2021] Out of memory: Killed process 3560879 (clickhouse-back) total-vm:444723572kB, anon-rss:136014520kB, file-rss:0kB, shmem-rss:0kB, UID:0 pgtables:266868kB oom_score_adj:0
[Thu Oct  7 07:15:46 2021] oom_reaper: reaped process 3560879 (clickhouse-back), now anon-rss:0kB, file-rss:0kB, shmem-rss:0kB`

**Comment by Slach** [comment]
how much RAM do you have?
how much vCPU ?
do you run clickhouse-backup as CLI? or run `clickhouse-backup server` REST API?

**Comment by freemanlutsk** [comment]
>how much RAM do you have?
**256GB** 

>how much vCPU ?
**72**

>do you run clickhouse-backup as CLI? or run clickhouse-backup server REST API?
**CLI**

**Comment by Slach** [comment]
ok, currently, by default `clickhouse-backup` use UPLOAD_CONCURRENCY as `vCPU / 2`, so let's restrict it:

```
general:
  upload_concurrency: 4
  donwload_concurrency: 4 
``` 

Also, do you monitor clickhouse-backup memory usage? could you share some graphs?

**Comment by freemanlutsk** [comment]
It seems in my case, the best `upload_concurrency ` is `1`, `2` and above is very aggressive for RAM and CPU

>ok, currently, by default clickhouse-backup use UPLOAD_CONCURRENCY as vCPU / 2, so let's restrict it:

I think would be better to set **UPLOAD_CONCURRENCY** equal to **1** as the default instead of as `vCPU / 2`

@Slach Thank You for your help!

**Comment by Slach** [comment]
Which `S3_CONCURRENCY` value do you have?

I tested UPLOAD_CONCURRENCY=4  + S3_CONCURRENCY = 1, and it allocates only 2Gb RAM

**Comment by freemanlutsk** [comment]
S3_CONCURRENCY = 5

**Comment by Slach** [comment]
Could you check S3_CONCURRENCY=1 and setup `upload_concurrency` to 5 from config (vCPU/2) and compare how much RAM it will allocate and time to upload your backup? We got 10x improvement in our measures on `github` events data.

**Comment by freemanlutsk** [comment]
Yes, I can
What the difference between those two parameters?

**Comment by Slach** [comment]
S3_CONCURRENCY internal parameter for Amazon golang S3 SDK it allows concurrent upload inside one "compressed stream" one table create one or more 
in versions prior `1.1.0`
and memory allocation depends on MAX_FILE_SIZE / 10 000 
and can be restricted by S3_PART_SIZE

UPLOAD_CONCURRENCY / DONWLOAD_CONCURRENCY allow concurrency independent on `remote_storage` type
and allow upload/download multiple tables simultaneously and multiple disks inside one table 
This allocates fixed buffers 4Mb per one spawned go routine (for vCPU 72 / 2 and one disk in system.disks) it should allocate 144Mb fixed buffers and around  1Gb RAM for S3, let's check?

**Comment by freemanlutsk** [comment]
The same aggressive behavior with: 

```
cat config.yml |grep conc
  upload_concurrency: 4
  donwload_concurrency: 1
  concurrency: 1
```

```
docker stats clickhouse_backup_upload --no-stream
CONTAINER ID   NAME                       CPU %      MEM USAGE / LIMIT   MEM %     NET I/O   BLOCK I/O    PIDS
d678fde1143d   clickhouse_backup_upload   6310.38%   82.71GiB / 113GiB   73.22%    0B / 0B   142GB / 0B   86
```


BTW, whole config, maybe there is something wrong 

```
---
general:
  remote_storage: s3
  disable_progress_bar: true
  backups_to_keep_local: 2
  backups_to_keep_remote: 31
  upload_concurrency: 4
  donwload_concurrency: 1
clickhouse:
  username: "yyy"
  password: "xxx"
  host: 127.0.0.1
  port: 9000
  data_path: "/var/lib/clickhouse"
  timeout: "7m"
  read_timeout: "1200"
  skip_tables:
    - system.*
    ...
s3:
  access_key: "zzz"
  secret_key: "xxx"
  bucket: "xxx-clickhouse-backup"
  endpoint: ""
  region: "eu-west-1"
  acl: private
  force_path_style: false
  path: "clickhouse_backups_inc/xxx-clickhouse-r1-s3"
  disable_ssl: false
  overwrite_strategy: always
  part_size: 5300000000
  compression_format: gzip
  compression_level: 5
  strategy: archive
  concurrency: 1
  debug: false
  ```

**Comment by Slach** [comment]
could you remove 
```
s3:
  part_size: 5300000000
```
look, like too much size near 5Gb
default limits for s3 is between 5Mb and 5Gb, you use maximul, this is size of part which used for multipart s3 upload
and currently it calculated automatically

**Comment by freemanlutsk** [comment]
Much better! 
I've tried with `gzip` and `zstd` compression 

```
gzip
CONTAINER ID   NAME                       CPU %      MEM USAGE / LIMIT   MEM %     NET I/O   BLOCK I/O     PIDS
35707459ccb6   clickhouse_backup_upload   3036.23%   9.944GiB / 113GiB   8.80%     0B / 0B   1.12TB / 0B   86
zstd
CONTAINER ID   NAME                       CPU %      MEM USAGE / LIMIT   MEM %     NET I/O   BLOCK I/O    PIDS
fa0b9e855ff0   clickhouse_backup_upload   2259.75%   2.948GiB / 113GiB   2.61%     0B / 0B   683GB / 0B   60

```

**Comment by Slach** [comment]
Ok. I think we figure out with root cause reason, big value for S3_PART_SIZE, so let's close issue
