### ISSUE TITLE
Incorrect prometheus metric measurement

### ISSUE THREAD

**Issue by vanyasvl** [Altinity/clickhouse-backup#280]
Time duration metrics has incorrect description
For example 
```# HELP clickhouse_backup_last_upload_duration Backup upload duration in nanoseconds
# TYPE clickhouse_backup_last_upload_duration gauge
clickhouse_backup_last_upload_duration 1113
```
But in fact this metric seems in seconds, not nanoseconds

**Comment by vanyasvl** [comment]
Hm, seems upload duration values is incorrecnt if it in seconds too
Look at the graph with absolute numbers
![image](https://user-images.githubusercontent.com/7232780/136762242-a918a652-34fb-4a04-b9dc-d833441326a8.png)

And clickhuse-backup log with upload durations
```Oct 04 12:49:23 clickhouse clickhouse-backup[9955]: 2021/10/04 12:49:23  info done                      backup=1.2.3.2_04-10-2021_11:23:13 duration=1h26m6.836s operation=upload size=189.23GiB
Oct 05 02:19:57 clickhouse clickhouse-backup[9955]: 2021/10/05 02:19:57  info done                      backup=1.2.3.2_05-10-2021_02:10:11 duration=9m42.315s operation=upload size=22.09GiB
Oct 07 02:33:46 clickhouse clickhouse-backup[9955]: 2021/10/07 02:33:46  info done                      backup=1.2.3.2_07-10-2021_02:10:11 duration=23m31.24s operation=upload size=49.21GiB
Oct 08 02:32:56 clickhouse clickhouse-backup[9955]: 2021/10/08 02:32:56  info done                      backup=1.2.3.2_08-10-2021_02:10:11 duration=22m40.235s operation=upload size=50.57GiB
Oct 09 02:29:29 clickhouse clickhouse-backup[9955]: 2021/10/09 02:29:29  info done                      backup=1.2.3.2_09-10-2021_02:10:11 duration=19m12.071s operation=upload size=39.16GiB
Oct 10 02:32:39 clickhouse clickhouse-backup[9955]: 2021/10/10 02:32:39  info done                      backup=1.2.3.2_10-10-2021_02:10:11 duration=22m22.492s operation=upload size=46.48GiB
Oct 11 08:29:15 clickhouse clickhouse-backup[84770]: 2021/10/11 08:29:15  info done                      backup=1.2.3.2_11-10-2021_08:25:39 duration=3m31.633s operation=upload size=58.59GiB```

**Comment by Slach** [comment]
`clickhouse_backup_last_upload_duration` metric have a `nanoseconds` measurement unit 
look to https://github.com/AlexAkulov/clickhouse-backup/blob/master/pkg/server/server.go#L572

How exactly you run your `clickhouse upload` do you use HTTP rest api?

**Comment by nahsi** [comment]
I noticed that `clickhouse_backup_last_create_duration` is in nanoseconds, but it is time that took clickhouse-backup to copy shadow directory content to backup directory, not time from start of create command to finish, I think, which is strange.
![image](https://user-images.githubusercontent.com/28529663/136780050-b66d2caf-02cd-4af6-ba1f-892f732ba7ef.png)

**Comment by vanyasvl** [comment]
> `clickhouse_backup_last_upload_duration` metric have a `nanoseconds` measurement unit look to https://github.com/AlexAkulov/clickhouse-backup/blob/master/pkg/server/server.go#L572
> 
> How exactly you run your `clickhouse upload` do you use HTTP rest api?

Yes, via rest-api, you can find logs in the fist post with real upload duration time, it's about 20min, but clickhouse_backup_last_upload_duration return about 1500 nanosec

**Comment by Slach** [comment]
`create_duraction` and `upload_duration` it's a two separate and different metric which represent two different command
when you call create, you just spawn go-routine which will create backup shadow directory
![image](https://user-images.githubusercontent.com/105560/136784079-5e30e5f2-f8d3-43f0-abed-e8a46abc93fe.png)

**Comment by Slach** [comment]
so, if you want you can call
`POST /backup/actions`
with request body
```json
{"command":"create_remote <backup_name>"}
```
and look to `clickhouse_backup_last_create_remote_duration` in nanoseconds

**Comment by nahsi** [comment]
@Slach should I create a separate ticket about incorrect `create_duration` then?

In my case from the start to finish backup create took around 10 minutes, but metric reports ~900 nanoseconds.

**Comment by Slach** [comment]
What exactly is incorrect?
Why are you sure metric measured wrong?

Let's figure out how you exactly run backup and how you scrape and visualize scraped metrics?

Which version clickhouse-backup do you use? Could you upgrade to `alexakulov/clickhouse-backup:1.1.0`?

**Comment by vanyasvl** [comment]
Ok, l've done upload via api, here is results:
Log from clickhouse-backup api server:
```Oct 11 12:36:24 clickhouse clickhouse-backup[84770]: 2021/10/11 12:36:24  info done                      backup=10.10.10.10_11-10-2021_12:32:48 duration=3m29.929s operation=upload size=48.92GiB```
duration=3m29.929s
Prom metric after upload:
```clickhouse_backup_last_upload_duration 1230```

1230ns != 3m29.929s

Version is latest 1.1.0

**Comment by nahsi** [comment]
@Slach 
I use version 1.1.0, I run clickhouse-backup as a server and use API to create backup.


From logs of clickhouse-backup:
start at 13:47 MSK: `2021/10/11 10:47:03  info SELECT name, engine FROM system.databases WHERE name != 'system'` 
finish at 13:56 MSK: `2021/10/11 10:56:01  info done  backup=2021-10-11-test1 duration=8m57.788s operation=create`

Metric reports 1003 nanoseconds `clickhouse_backup_last_create_duration 1003`

**Comment by Slach** [comment]
@nahsi @vanyasvl 

thanks a lot for reporting
looks like I found root reason

could you confirm, if you run

```bash
echo '{"command":"create test_backup"}' | curl -XPOST --data-binary @- http://127.0.0.1:7171/actions
```
wait
and after it run
```bash
echo '{"command":"upload test_backup"}' | curl -XPOST --data-binary @- http://127.0.0.1:7171/actions
```
Are metric measurements is correct?

**Comment by vanyasvl** [comment]
Yes, via /backup/actions api call it works correctly, but incorrect via backup/upload.
Thanks, I'm going to fix my script to use /backup/actions
