### ISSUE TITLE
FR: synchronous api calls

### ISSUE THREAD

**Issue by vanyasvl** [Altinity/clickhouse-backup#281]
Hello.
I will  be grate to add synchronous api calls for commands.
It make sense to write simple scripts (eg. bash + curl) without finish waiting logic in a script.
Of course we can use cli command in the script, but we loose prometheus metrics and monitoring if use cli.

Other better option, add option to the cli tool to work via api server to save all metrics.

**Comment by Slach** [comment]
Unfortunatelly sync api for upload / download API is not possible for implements, cause upload / download of 1Tb could be one or more hour

So, you shall call `POST /backup/upload/backup_name` after it you need poll `GET /backup/status` or `GET /backup/actions?filter=backup_name` and poll `"status": "success" `or `"status": "error"` on json
