### ISSUE TITLE
How to backup and restore correctly the cluster with distributed tables

### ISSUE THREAD

**Issue by malcolm061990** [Altinity/clickhouse-backup#286]
Hi. Thanks for your product first of all :)
This "issue" is not issue but it's just a question.
There is a cluster with such config (2 shards with 2 nodes in each shard):
```xml
    <remote_servers replace="true">
        <sdns>
            <!-- shard 01 -->
            <shard>
                <internal_replication>true</internal_replication>
                <replica>
                    <host>${ch1}</host>
                    <port>9000</port>
                </replica>
                <replica>
                    <host>${ch2}</host>
                    <port>9000</port>
                </replica>
            </shard>

            <!-- shard 02 -->
            <shard>
                <internal_replication>true</internal_replication>
                <replica>
                    <host>${ch3}</host>
                    <port>9000</port>
                </replica>
                <replica>
                    <host>${ch4}</host>
                    <port>9000</port>
                </replica>
            </shard>
        </sdns>
    </remote_servers>

    <zookeeper replace="true">
        <node index="1">
            <host>${zk1}</host>
            <port>2181</port>
        </node>
        <node index="2">
            <host>${zk2}</host>
            <port>2181</port>
        </node>
        <node index="3">
            <host>${zk3}</host>
            <port>2181</port>
        </node>
    </zookeeper>
```

I am not so familiar with clickhouse backups :) Hope for your help.
Question is how to backup and restore the data? There are several approaches. What is the correct one?
We use s3 to upload remote backups.
1) We can run backup **on each of 4 nodes**. So it will create 4 separated backups. After that we can restore the specific backup file only on specific node (node1 will get backup only from node1, node2 - from node2). In summary: 4 backup processes, 4 restoring processes because of 4 nodes.
2) We can run backup **only on one node in each shard**. After that we can restore specific backup on specific shard (any node in shard1 will get the backup from any node in shard1). In summary: 2 backup processes, 2 restoring processes because of 2 shards.
3) We can run backup i**n any single node**. After that we can restore this backup **on any single node**. In summary: 1 backup process, 1 restoring process.

**Comment by Slach** [comment]
Ii @malcolm061990. Thank you so much for your words of support.

Distributed tables don't contain data itself, so, the right approach depends on which engine do you use for underlying table inside distributed, `MergeTree` or `ReplicatedMergeTree`
if you use only `ReplicatedMergeTree` right approach will the second variant
if you use MergeTree in underlying table, right approach will the first variant
the third variant is not applicable

Look to https://github.com/AlexAkulov/clickhouse-backup/blob/master/Examples.md#how-to-use-clickhouse-backup-in-kubernetes for related Kubernetes manifest examples
