### ISSUE TITLE
Checking backup

### ISSUE THREAD

**Issue by justewg** [Altinity/clickhouse-backup#287]
How can I check my backup creation?
I've run clickhouse-backup as root user using script, that was written in your readme.
Although `clickhouse-backup list` shows all tables that I want to backup and backup has been created - It's just empty.
```
root@db-2:/home/ewg# clickhouse-backup list
Local backups:
- 'my_backup_2021-10-24T09-46-50'	(created at 24-10-2021 09:46:50)
Remote backups:
2021/10/24 09:57:35 storage type 'none' not supported

root@db-2:/home/ewg# ls -al /var/lib/clickhouse/store/backup/my_backup_2021-10-24T09-46-50/
total 12
drwxr-xr-x 3 root root 4096 Oct 24 09:46 .
drwxr-xr-x 3 ewg  ewg  4096 Oct 24 09:46 ..
drwxr-xr-x 2 root root 4096 Oct 24 09:46 shadow

root@db-2:/home/ewg# ls -al /var/lib/clickhouse/store/backup/my_backup_2021-10-24T09-46-50/shadow/
total 8
drwxr-xr-x 2 root root 4096 Oct 24 09:46 .
drwxr-xr-x 3 root root 4096 Oct 24 09:46 ..
```

**Comment by Slach** [comment]
@justewg did you run `clickhouse-backup` at the same server where `clickhouse-server` run?

**Comment by justewg** [comment]
А можно по-русски поизъясняться?

**Comment by Slach** [comment]
вы запустили `clickhouse-backup create` на том же сервере где запущен `clickhouse-server`?

ls -la /var/lib/clickhouse/store/backup/my_backup_2021-10-24T09-46-50/shadow
тут тоже пусто?

**Comment by justewg** [comment]
Да, тут тоже пусто, вероятно именно потому что я не запускал докер с сервисом, поскольку решил что можно запускать _либо_ clickhouse-backup, скаченный и разархивированный, либо установленный через докер. А докер нужен для работы API, если есть потребность в использовании именно API.
Похоже я плохо осознал документацию в README.
То есть для работы бэкапа _необходим_ докер-сервер ?

**Comment by Slach** [comment]
Нет, докер сервер для бекапа не нужен, перечитайте пожалуйста мой вопрос

Давайте разбираться
как у вас запущен clickhouse-server? В докере или просто как systemd service?
Как вы запускаете создание backup просто `clickhouse-backup create`? 

Можете запустить
`LOG_LEVEL=debug clickhouse-backup create` и показать вывод?

**Comment by justewg** [comment]
Да. КХ запущен обычным системным демоном.
```
root@db-2:/home/ewg# LOG_LEVEL=debug clickhouse-backup create
2021/10/24 13:49:38 Create backup '2021-10-24T13-49-38'
2021/10/24 13:49:38 Freeze `testdb`.`users`
2021/10/24 13:49:39 Freeze `testdb`.`test`
2021/10/24 13:49:39 Freeze `testdb`.`address`
2021/10/24 13:49:39 Freeze `testdb`.`city`
2021/10/24 13:49:39 Skip `system`.`asynchronous_metric_log`
2021/10/24 13:49:39 Skip `system`.`metric_log`
2021/10/24 13:49:39 Skip `system`.`part_log`
2021/10/24 13:49:39 Skip `system`.`query_log`
2021/10/24 13:49:39 Skip `system`.`query_thread_log`
2021/10/24 13:49:39 Skip `system`.`trace_log`
2021/10/24 13:49:39 Copy metadata
2021/10/24 13:49:39   Done.
2021/10/24 13:49:39 Move shadow
2021/10/24 13:49:39   Done.
root@db-2:/home/ewg#
```

**Comment by Slach** [comment]
что показывает
`clickhouse-backup version` ?

**Comment by Slach** [comment]
что показывает
`clickhouse-client -q "SELECT version()"`

**Comment by justewg** [comment]
`clickhouse-backup version` ничего не показывает,

```
root@db-2:/home/ewg# clickhouse-backup --version
Version:	 0.5.2
Git Commit:	 f7975491a6c117f4ce03dc30975bce16fe619da6
Build Date:	 2020-05-19
root@db-2:/home/ewg# clickhouse-client -q "SELECT version()"
"SELECT version()"
21.9.4.35
root@db-2:/home/ewg#
```

**Comment by Slach** [comment]
У вас очень старая версия `clickhouse-backup`, и очень новая версия `clickhouse-server`  в ней движок базы данных Atomic, который не поддерживается clickhouse-backup 0.5.2

обновите clickhouse-backup до 1.1.1

**Comment by justewg** [comment]
Благодарю, похоже что теперь сбэкапилось.
```
root@db-2:/home/ewg# clickhouse-backup list
2021/10/24 15:29:02  info SELECT value FROM `system`.`build_options` where name='VERSION_INTEGER'
2021/10/24 15:29:02  info SELECT * FROM system.disks;
my_backup_2021-10-24T15-28-40   5.16GiB   24/10/2021 15:28:40   local
```
