### ISSUE TITLE
Implements --diff-from-remote option for `upload` command and properly fix `required` with upload_by_part in `download` command

### ISSUE THREAD

**Issue by Slach** [Altinity/clickhouse-backup#289]
Need refactoring backup remote storage format to store each partition in separate file

**Comment by vanyasvl** [comment]
And it would be great to have a possibility to restore only particular partitions from the backup. Imagine you have a 100Tb yearly backup (clickhouse has daily partitions), and after disaster you need to restore latest day as soon as possible.
