### ISSUE TITLE
[question] new tagging structure

### ISSUE THREAD

**Issue by javigs82** [Altinity/clickhouse-backup#295]
hello,
we are facing issues downloading the new version of the tool (1.2.0) because the tag does not contain the letter v.

is it an issue or you have decided to remove the v from the tag. We need to know to change our currently automate mechanism of downloading

thanks in advacen,
Javi.

**Comment by Slach** [comment]
fixed, thanks a lot for reporting

**Comment by javigs82** [comment]
thanks a lot for your prompt support
