### ISSUE TITLE
Support incremental backups

### ISSUE THREAD

**Issue by prog8** [Altinity/clickhouse-backup#3]
Hi,
Does ClickhouseBackup support incremental backups? I mean when I execute it the first I expect it to send full dump but when I call this second time a couple hours later I'd expect the tool to send only new blocks? I saw mentiones of increments in code but I wanted to double check the tool really works as I described.

Thanks,
Paweł

**Comment by otisg** [comment]
I think this is an absolute must... 🤞

**Comment by AlexAkulov** [comment]
Hi!
This is very demanded feature. 
Every time at partitions freezing ClickHouse creates hard links and even for partitions that weren't changed new hard links will be created.
```
# find /var/lib/clickhouse -samefile ./FlightDate.bin
/var/lib/clickhouse/shadow/10/data/default/ontime/2000_1_1_0/FlightDate.bin
/var/lib/clickhouse/shadow/1/data/default/ontime/2000_1_1_0/FlightDate.bin
/var/lib/clickhouse/shadow/19/data/default/ontime/2000_1_1_0/FlightDate.bin
/var/lib/clickhouse/shadow/28/data/default/ontime/2000_1_1_0/FlightDate.bin
```
S3 doesn't support hard link and clickhouse-backup doesn't distinguish hard links from regular files becase every time it will upload the same files.

I don't know how to make this feature quite fine.
I've PR that tries to solve this problem via archive backup strategy. New strategy archives shadow and metadata folders to tar.gz with all hard links and upload archive to S3. But it's not in master now it requires some changes. 

I think clickhouse-backup can create file that contains list of file paths, hard links, maybe hash and skip files that already exist on S3 on upload.  

I'd be glad to get ideas or PRs.

**Comment by otisg** [comment]
I would imagine CH dev team is working on this or at least has incremental backup on the roadmap, no?

**Comment by blinkov** [comment]
> I would imagine CH dev team is working on this or at least has incremental backup on the roadmap, no?

Not really, incremental backups are possible to be done externally with current ClickHouse features. For example, Yandex.Cloud provides it as a service and they use vanilla ClickHouse without any additional patches: https://cloud.yandex.com/docs/managed-clickhouse/concepts/backup

**Comment by AlexAkulov** [comment]
Done for 'archive' strategy.
Use flag --diff-from for uploading only differences between backups, like: `clickhouse-backup upload <backup_name> --diff-from=<old_backup_name>`. On downloading clickhouse-backup detects required backups and downloads their automatically.

**Comment by prog8** [comment]
Thanks @AlexAkulov
