### ISSUE TITLE
Upload to S3 from Yandex Cloud

### ISSUE THREAD

**Issue by molchanovdp** [Altinity/clickhouse-backup#30]
Hi!
Tell me, should the backup upload work in S3 from Yandex Cloud? I have a error:
`can't upload with 403: "There were headers present in the request which were not signed"`

**Comment by AlexAkulov** [comment]
Yes. It is bug in s3gof3r library.

**Comment by blinkov** [comment]
> Yes. It is bug in s3gof3r library.

Has it been filed? Can you link to it?

**Comment by AlexAkulov** [comment]
Там автор похоже только AWS хочет поддерживать. Я заводил ему issue по другой проблеме с minio.
Можно поправить это в моём форке https://github.com/AlexAkulov/s3gof3r но у меня пока времени нету.

**Comment by AlexAkulov** [comment]
Fixed in v0.4.0
