### ISSUE TITLE
panic: invalid log level

### ISSUE THREAD

**Issue by stkubr** [Altinity/clickhouse-backup#302]
Just following this guide: https://habr.com/ru/post/569282/
version used is 1.2.1

panic: invalid log level

goroutine 1 [running]:
github.com/apex/log.MustParseLevel({0x0, 0xff})
	/home/runner/go/pkg/mod/github.com/apex/log@v1.9.0/levels.go:77 +0x7b
github.com/apex/log.SetLevelFromString(...)
	/home/runner/go/pkg/mod/github.com/apex/log@v1.9.0/pkg.go:29
github.com/AlexAkulov/clickhouse-backup/config.LoadConfig({0x129ac75, 0x21})
	/home/runner/work/clickhouse-backup/clickhouse-backup/config/config.go:229 +0x23e
main.getConfig(0x2)
	/home/runner/work/clickhouse-backup/clickhouse-backup/cmd/clickhouse-backup/main.go:328 +0x1e
main.main.func3(0xc0000f0160)
	/home/runner/work/clickhouse-backup/clickhouse-backup/cmd/clickhouse-backup/main.go:61 +0x1e
github.com/urfave/cli.HandleAction({0x106b340, 0x12d1a60}, 0x6)
	/home/runner/go/pkg/mod/github.com/urfave/cli@v1.22.5/app.go:524 +0xa8
github.com/urfave/cli.Command.Run({{0x12774b4, 0x6}, {0x0, 0x0}, {0x0, 0x0, 0x0}, {0x1286f79, 0x14}, {0x128cd6f, ...}, ...}, ...)
	/home/runner/go/pkg/mod/github.com/urfave/cli@v1.22.5/command.go:173 +0x652
github.com/urfave/cli.(*App).Run(0xc00043b500, {0xc000126040, 0x4, 0x4})
	/home/runner/go/pkg/mod/github.com/urfave/cli@v1.22.5/app.go:277 +0x705
main.main()
	/home/runner/work/clickhouse-backup/clickhouse-backup/cmd/clickhouse-backup/main.go:321 +0x2025

**Comment by Slach** [comment]
could you share your `/etc/clickhouse-backup/config.yaml`?

**Comment by Slach** [comment]
@stkubr which `log_level` do you have in your configuration?

**Comment by Slach** [comment]
@stkubr is the issue still relevant for you?
Could you try to use https://github.com/AlexAkulov/clickhouse-backup/releases/tag/v1.3.1 ?
If issue still relevant, could you share `clickhouse-backup print-config` command result?
