### ISSUE TITLE
[question] restore backup -- only schema

### ISSUE THREAD

**Issue by javigs82** [Altinity/clickhouse-backup#305]
hey, 

if a backup generated with `-s` (only schema) is restored, is the data erased?

thanks in advance,
Javi.

**Comment by Slach** [comment]
If you run `clickhouse-backup restore --schema backup_name` on exists database, you should get the error like a `table db.table already exists` if exists database contains the same tables schema

if you want to restore without data and clean existing data, try to run `clickhouse-backup --rm --schema`

be careful, if exists database contains tables which not contains in backup, they will stay on server
