### ISSUE TITLE
Data cannot be recovered during backup restoration

### ISSUE THREAD

**Issue by 9mlcy7** [Altinity/clickhouse-backup#307]
Installed using the official ClickHouse Docker image,No problem occurred during the backup, but only the table structure was restored during the recovery, and the table data was not restored.Clickhouse backup and restore operations in Docker are not supported.，

**Comment by Slach** [comment]
@chenyongjie0909 could you provide more context?

Do you use a standalone installation via `.deb, .rpm` or you run clickhouse-backup in docker?
How exactly do you ran `clickhouse-backup restore`?

When you said, “Installed using the official ClickHouse Docker image” it means do you install `clickhouse/clickhouse-server` docker image or `AlexAkulov/clickhouse-backup` docker image?

**Comment by 9mlcy7** [comment]
Sorry, my English is not very good. I use Clickhouse backup to back up the Clickhouse in docker, but there is no shadow folder in the generated backup file, only SQL for table creation statements

**Comment by 9mlcy7** [comment]
I installed Clickhouse backup using the GZ file

**Comment by Slach** [comment]
If run `clickhouse-server` inside docker and run `clickhouse-backup` on HOST OS outside container

you should define volume inside your docker container, which will map `/var/lib/clickhouse` into host OS.
something like this `docker run -d --name clickhouse -v /var/lib/clickhouse:/var/lib/clickhouse yandex/clickhouse-server:latest`

Thereafter, you can use `clickhouse-backup create <backup_name>`
and look to `/var/lib/clickhouse/backup/` to ensure backup created successfully.

**Comment by 9mlcy7** [comment]
I see. Thank you very much

**Comment by infynity** [comment]
> If run `clickhouse-server` inside docker and run `clickhouse-backup` on HOST OS outside container
> 
> you should define volume inside your docker container, which will map `/var/lib/clickhouse` into host OS. something like this `docker run -d --name clickhouse -v /var/lib/clickhouse:/var/lib/clickhouse yandex/clickhouse-server:latest`
> 
> Thereafter, you can use `clickhouse-backup create <backup_name>` and look to `/var/lib/clickhouse/backup/` to ensure backup created successfully.

how can i  use backup just like  mysqldump  ,export  full data , which means i need to backup clickhouse-server in docker  from remote  host (can not use volume),

thank you

**Comment by Slach** [comment]
@infynity `clickhouse-backup` itself doesn't support `logical backup`, it looks like `xtrabackup` instead of `mysqldump`

If you want to try to make remote logical backup
you can use clickhouse-client something like that https://github.com/YtvwlD/clickhouse-backup/blob/main/backup.sh
But, you want to avoid trying this way, cause when you have big data size (clickhouse typical workload) it will work slow.

**Comment by infynity** [comment]
@Slach 
thanks  a lot,  and i have a new question,

thus  , i have   2 servers  ,both has clickhouse-server ,

 server1  has data , server2 has none  ,they don't have any mount relations

  i create a backup on server1   `./clickhouse-backup -c config.yml create 888
`         ,and the  `/var/lib/clickhouse/backup/888`  already has  shadow directory  ,

then i `cp`  888  to server2's  `/var/lib/clickhouse/backup/`

and  on server2 ,i use restore  cmd :  `./clickhouse-backup -c config.yml restore 888 -d -s --rm`  , it seems worked to me to restore the data from server1 


is that usage ok?   thanks a lot  :-)

**Comment by Slach** [comment]
@infynity 
Yep, this worklfow looks good

**Comment by infynity** [comment]
@Slach   Thank you very much
