### ISSUE TITLE
"Data compressed with different methods" when restoring Array with skip indexes

### ISSUE THREAD

**Issue by ctlaltdefeat** [Altinity/clickhouse-backup#308]
When restoring a table that includes an Array datatype, the restoration "works" but I cannot select any of these column's values when the select would use skip indexes. I receive the following error:

```
Code: 271. DB::Exception: Received from localhost:9000. DB::Exception: Data compressed with different methods, given method byte 0x01, previous method byte 0x82: (while reading column features): (while reading from part /var/lib/clickhouse/store/5d2/5d2c1c3f-1711-4ce1-9d2c-1c3f17
110ce1/202109_85_85_21/ from mark 121856 with max_rows_to_read = 5824): While executing MergeTreeReverse. (CANNOT_DECOMPRESS)
```

the schema in the "query" field of `/var/lib/clickhouse/backup/backup_name/metadata/db/table_name.json` is:
```
CREATE TABLE default.events 
(
`id` String, 
`timestamp` DateTime64(3), 
.... (other working fields) ... ,
`features` Array(String)
)
ENGINE = ReplacingMergeTree() PARTITION BY toYYYYMM(timestamp) ORDER BY (timestamp, id)
```

Selects when using `settings use_skip_indexes=0;` always seem to work, while selects that would use a skip index always seem to not work.

The clickhouse version on the source server is `v20.4.2.9-stable`. The version on target is `21.11.3`.

**Comment by Slach** [comment]
Unfortunately, we can't resolve this issue on `clickhouse-backup` side
clickhouse-backup create backup `as is` and just creates hard-links to exist files

This misbehavior looks like incompatible behavior on ClickHouse side 

v2 version could allow BACKUP / RESTORE which implemented for ClickHouse 22.7+
maybe it could resolve this issue
