### ISSUE TITLE
Error while creating backups of tables of type MergeTree

### ISSUE THREAD

**Issue by venkatBala** [Altinity/clickhouse-backup#31]
Been trying to use this tool to test backups of tables of different types
./clickhouse-backup --config config.yml create --tables=default.test_mergeTree back4

I get this error
2019/06/01 00:46:43 Create backup 'back4'
2019/06/01 00:46:43 Freeze 'default.test_mergeTree'
2019/06/01 00:46:43   partition '201906'
2019/06/01 00:46:43 can't freeze partition '201906' on 'default.test_mergeTree' with: code: 368, message: std::bad_typeid

Been following the readme closely, not sure what might be causing this!

**Comment by AlexAkulov** [comment]
What version of ClickHouse and clickhouse-backup do you use?

I use the mergeTree tables in the integration test and it works correctly.

**Comment by venkatBala** [comment]
I used the latest release for clickhouse-backup (v0.3.4)

I carried out my testing using the following docker stack

version: "3.3"
services:
  minio:
    image: minio/minio:latest
    container_name: minio
    environment:
      MINIO_ACCESS_KEY: access-key
      MINIO_SECRET_KEY: it-is-my-super-secret-key
    entrypoint: sh
    command: -c 'mkdir -p doc_gen_minio/export/clickhouse && minio server doc_gen_minio/export'
    ports:
      - 9010:9000
    networks:
      - clickhouse-backup

  clickhouse:
    image: yandex/clickhouse-server:latest
    container_name: clickhouse
    volumes:
      - ${PWD}/clickhouse_backup/clickhouse-backup:/usr/bin/clickhouse-backup
      - ${PWD}/config.yml:/etc/clickhouse-backup/config.yml
    network_mode: host

networks:
  clickhouse-backup:

Created tables as follows:
* "create table if not exists default.test_Log (Date Date, TimeStamp DateTime, data String) engine=Log"
* "create table if not exists default.test_TinyLog (Date Date, TimeStamp DateTime, data String) engine=TinyLog"
* "create table if not exists default.test_mergeTree (Date Date, TimeStamp DateTime, data String) engine=MergeTree(Date, (TimeStamp, data), 8192)"

and filled all of them with some test data

To test creating backups, I ran
docker-compose exec clickhouse clickhouse-backup freeze

and got the following:
2019/06/01 23:53:45 Freeze 'default.test_Log'
2019/06/01 23:53:45 Freeze 'default.test_TinyLog'
2019/06/01 23:53:45 Freeze 'default.test_mergeTree'
2019/06/01 23:53:45   partition '201906'
2019/06/01 23:53:45 can't freeze partition '201906' on 'default.test_mergeTree' with: code: 368, message: std::bad_typeid

However, when I replaced it with an older version of the clickhouse server i.e 1.1.54236 (the only change) and tried to run the my test again... the error was:
2019/06/02 00:13:05 can't get Clickhouse tables with: code: 47, message: Unknown identifier: metadata_path

I'd appreciate if you can tell me where I went wrong or what I missed.
thanks

**Comment by AlexAkulov** [comment]
Hello @venkatBala!
Did you manage to solve your issue?
clickhouse-backup v0.3.4 supports versions of ClickHouse between 1.1.54390 and 19.4.4.33
clickhouse-backup v0.3.6 must support ClickHouse newer than 19.4.4.33

**Comment by venkatBala** [comment]
Hi @AlexAkulov 

I am yet to give this another go... will look into it again. thanks :)
