### ISSUE TITLE
Error. Unknown command: 'clickhouse-backup'

### ISSUE THREAD

**Issue by JunfengLi88886666** [Altinity/clickhouse-backup#311]
I tried this command:

docker run --rm -it --network host -v "/var/lib/clickhouse:/var/lib/clickhouse" alexakulov/clickhouse-backup

**Comment by Slach** [comment]
@JunfengLi88886666 I made some change in `entrypoint.sh`

Could you check the following command?
```bash
docker run --rm -it --network host -v "/var/lib/clickhouse:/var/lib/clickhouse" altinity/clickhouse-backup:master
```

**Comment by JunfengLi88886666** [comment]
> @JunfengLi88886666 I made some change in `entrypoint.sh`
> 
> Could you check the following command?
> 
> ```shell
> docker run --rm -it --network host -v "/var/lib/clickhouse:/var/lib/clickhouse" altinity/clickhouse-backup:master
> ```

it works, thanks so mush
