### ISSUE TITLE
list-remote is slow when the number of backups is high

### ISSUE THREAD

**Issue by filimonov** [Altinity/clickhouse-backup#318]
On GCP it list all objects recursively (?) (probably, need to be confirmed)
Even on aws it do HEAD & GET metadata object for every backup (confirmed by logs).

**Comment by Slach** [comment]
We need to get metadata.json to show backup size

"backup number is high" mean thousand backups in the same paths?

**Comment by filimonov** [comment]
> We need to get metadata.json to show backup size
> 
> "backup number is high" mean thousand backups in the same paths?

Let's add some flag to get it without sizes. Or get the size only for the last backup.

**Comment by filimonov** [comment]
> "backup number is high" mean thousand backups in the same paths? 

yep. Backups every 2 hours. 90 days retention.

**Comment by Slach** [comment]
Need local disk cache (can't remote cache cause will broke file layout) for slow only on first time
