### ISSUE TITLE
only metadata is getting backed up, no hard links to data in the shadow folder

### ISSUE THREAD

**Issue by venkatBala** [Altinity/clickhouse-backup#32]
Tried backing up a Log table
./clickhouse-backup --config config.yml create --tables=default.test_Log

Output
2019/06/01 00:54:05 Create backup '2019-06-01T04-54-05'
2019/06/01 00:54:05 Freeze 'default.test_Log'
2019/06/01 00:54:05 Copy metadata
2019/06/01 00:54:05   Done.
2019/06/01 00:54:05 Move shadow
2019/06/01 00:54:05   Done.

However, only metadata was backup under /var/lib/clickhouse/backup. Where is the contents of shadow being moved to?

**Comment by AlexAkulov** [comment]
May be the 'default.test_Log' do not contains data?

**Comment by venkatBala** [comment]
I did create the tables and fill them with test data before running the tests

**Comment by anuriq** [comment]
Table engine is Log? maybe there is the issue?

**Comment by AlexAkulov** [comment]
No way to backup the Log-engine tables without restarting the Clickhouse server, so 'clickhouse-backup' will most likely never be support backup for Log-engine tables.
