### ISSUE TITLE
Clickhouse backup folder total size issue 

### ISSUE THREAD

**Issue by kishorer00** [Altinity/clickhouse-backup#322]
Hi Alex,

After compleating the click house Backup total amount of folder size is showing 9.2M.
But original backup size is 101 GB

# du -sh *
9.2M    v122-backup

#cd v122-backup
1.3M    metadata
20K     metadata.json
100G   shadow   ------> Files size is 100 GB - Not calculated in total size.

Suspecting some issue total size and calculation. 

Environment details:- 
-----------------------
OS version :CentOS Linux release 7.6 (Core)
ClickHouse version: ClickhouseDB version 2.11
Backup tool version: v1.2.2 from the release versions: https://github.com/AlexAkulov/clickhouse-backup/releases .

Please help in fixing the same. Observed the same issue with older versions also ...

**Comment by Slach** [comment]
@kishorer00 when you call `clickhouse-backup create`
it creates `hardlinks` from `/var/lib/clickhouse/backup/backup_name/shadow/XXXX/` to `/var/lib/clickhouse/data/db/table/shadow/XXXX/`

So, it doesn't allocate disk space itself, only `inodes` it just allows us to avoid corner case when `clickhouse-server` delete data part after background parts merge or mutations complete

if you have intensive background merge process, it could allocate disk space, cause `hardlinks` will stay on disk

**Comment by kishorer00** [comment]
Explanation helps a lot !!!.
Thanks ...
