### ISSUE TITLE
Best practice to backup and restore sharding clickhouse

### ISSUE THREAD

**Issue by wheatdog** [Altinity/clickhouse-backup#326]
Thanks for providing this great tool! I have read these issues (https://github.com/AlexAkulov/clickhouse-backup/issues/286, https://github.com/AlexAkulov/clickhouse-backup/issues/299). It seems the suggested way is to perform backup and restore per shard.

I am concern about the synchronization and atomicity of the operation. For example, does it matter that the backup time of different shard are slightly different?

**Comment by Slach** [comment]
`shard` mean separate part of data, which have only the same structure.
`shards` used only on Engine=Distributed tables for SELECT and INSERTS (data stored in tmp folder in Distributed not backuped)

so, you can to back up and restore shards separately and better to use different remote path in `/etc/clickhouse-backup/config.yml`

Moreover, you should choose only one replica for upload
best algorithm is:
- run `clickhouse-backup create` on each replica in shard
- run `clickhouse-backup upload` on first replica in shard, if failed, then run on next replica, if success move to next step 
- run `clickhouse-backup delete local` on each replica in shard

**Comment by Slach** [comment]
Clickhouse have eventually consistency. If you stop data ingestion and wait when data will sync between replicas (SYSTEM SYNC REPLICA) inside shard, then during backup, you will have consistent snapshot.

If you won't stop data inserting, then you will have always inconsistent data between replicas inside shards
