### ISSUE TITLE
Failed to restore the backup for the columns type LowCardinality(Nullable(String)) 

### ISSUE THREAD

**Issue by kishorer00** [Altinity/clickhouse-backup#329]
Hi Alex,

We have an issue while restoring a backup with columns type -  " LowCardinality(Nullable(String)) ".
Primary key applied to the same column.

Env Details : -

OS version :CentOS Linux release 7.6 (Core)
ClickHouse version: ClickhouseDB version 21.4.4.30
Backup tool version: v1 from the release versions: https://github.com/AlexAkulov/clickhouse-backup/releases .

Error: -
--------

2021/12/17 12:06:19 error can't attach partitions for table 'test.status': code: 226, message: Marks file '/var/lib/clickhouse/data/test.status/detached/attaching_202107_2_16102_10600_99786/Name.dict.null.mrk2' doesn't exist

Able to restore the columns after removing the type " Nullable " 
" LowCardinality(String) ".

Is there any issue with type "Nullable" - Backup restore? any fix for this ?

**Comment by Slach** [comment]
Look like issue is not related to clickhouse-backup itself

Do you try to restore on the same version `ClickHouse` as source server?
Did you change type for `Name` column via ALTER TABLE on your source database?

Try to materialize nullable before call `clickhouse-backup create`

```
SET mutations_sync=2;
ALTER TABLE `data`.`test.status` UPDATE Name=Name WHERE 1=1;
```

**Comment by kishorer00** [comment]
Do you try to restore on the same version ClickHouse as source server?
==>  Yes. Tried restoring the same version of ClickHouse on both Source and Destination Hosts

Did you change type for Name column via ALTER TABLE on your source database?
==> I have created the table Column with type " LowCardinality(Nullable(String)) ". 

3 to 4 tables were created with the same column type. All the tables are failing with same error.

**Comment by Slach** [comment]
Ok. Let's clarify
Did you add `LowCardinality(Nullable(String))` columns later than call `CREATE TABLE`? 

Or you use something like that:
```sql
CREATE TABLE t1 (
 field LowCardinality(Nullable(String)))
 ) ENGINE = ...
 ```

**Comment by kishorer00** [comment]
Created the tables using below Query,

CREATE TABLE t1 (
 field LowCardinality(Nullable(String)))
 ) ENGINE = ...

**Comment by Slach** [comment]
could you share
```bash
find -name Name.dict.null.mrk2 /var/lib/clickhouse/backup
```

**Comment by kishorer00** [comment]
trying to reproduce the issue. I will update you with the exact details soon.

I think , we are getting Name.dict.null.mrk2 value from the below path ,

/var/lib/clickhouse/backup/NEW-BACKUP/shadow/DBName/TEST_table/default/202107_5_5_0/Name.dict.null.mrk2

**Comment by Slach** [comment]
Issue is still actual for you?

**Comment by Slach** [comment]
close issue after inactivity
