### ISSUE TITLE
Frequent restore error:  Detached part "xxx" not found

### ISSUE THREAD

**Issue by vanyasvl** [Altinity/clickhouse-backup#333]
Hello.
We are experiencing errors like this very often during backup restoring:

2021/12/27 06:05:19 error can't attach partitions for table 'db.table': code: 233, message: Detached part "20211126_9362808_9506877_13" not found

Second attempt to restore the same backup usually works good.
It happens on different servers with different data.

**Comment by Slach** [comment]
@vanyasvl which `clickhouse-backup` version do you use?
Could you share your config.yaml with anonymized credentials?

**Comment by vanyasvl** [comment]
Version 1.2.0, because 1.2.2 has a bug https://github.com/AlexAkulov/clickhouse-backup/issues/331#issuecomment-998062796

```
api:
    enable_metrics: true
    listen: 0.0.0.0:7171
clickhouse:
    freeze_by_part: true
    host: 127.0.0.1
    password: ''
    port: 9000
    secure: false
    skip_tables:
    - system.*
    - default.*
    - INFORMATION_SCHEMA.*
    - information_schema.*
    skip_verify: false
    sync_replicated_tables: true
    timeout: 1s
    username: default
general:
    backups_to_keep_local: 2
    disable_progress_bar: false
    download_concurrency: 10
    log_level: debug
    max_file_size: 1073741824
    remote_storage: s3
    upload_concurrency: 10
s3:
    access_key: 111
    acl: private
    bucket: bbbb
    debug: false
    disable_cert_verification: false
    disable_ssl: false
    endpoint: https://aaaa
    force_path_style: true
    part_size: 1073741824
    path: ''
    secret_key: 123
```

**Comment by Slach** [comment]
Please remove ```freeze_by_part: true``` in `clickhouse` section
it should avoid detached parts related error

and remove `part_size` in `s3` section (or reduce it to 10485760)
it should decrease memory allocation during upload / download

**Comment by vanyasvl** [comment]
`freeze_by_part: true` was added for tests, I had same issue without that line.
I can't remove `part_size` becuse defult part_size calculation is `file_size / 10000` and our storage (Swift) supports maximum 1000 parts per object. And how object storage setting can influence to clickhouse partition attach? I do backup download first, then run restore, as two different commands and restore fails sometimes, but if I run restore again (without redownload) it's ok.

**Comment by Slach** [comment]
ok. sorry for misunderstanding

let's try to debug
could you share logs for failed restore with debug?
```
LOG_LEVEL=debug clickhouse-backup restore <backup_name>
```

**Comment by Slach** [comment]
@vanyasvl any news about this error? it still reproduce?

**Comment by vanyasvl** [comment]
Haven't reproduced it again
