### ISSUE TITLE
 backup to antoher directory

### ISSUE THREAD

**Issue by goto217** [Altinity/clickhouse-backup#336]
[clikchouse-backup] backup default directory is /var/lib/clickhouse/backup

 How to directly backup to antoher directory?

 I not find any parameter which specified directory when execute backup command 
 (./clickhouse-backup --config ./config.yml create backupName)

**Comment by Slach** [comment]
`clickhouse-backup create backupName` just create hardlinks in the same disks path from as `SELECT name. path FROM system.disks`
so, you don't need redefine backup path, you can try to modify `clickhouse->disk_mapping` config section
but it has sense only after upload + download when destination server will have another volume mappings for system.disks than server where you create backup
