### ISSUE TITLE
We can support MaterialView in clickhouse-backup remote-restore.

### ISSUE THREAD

**Issue by wangzhen11aaa** [Altinity/clickhouse-backup#344]
This is the error.

2022/01/06 20:52:44 **_**debug ATTACH MATERIALIZED VIEW default.download_daily_mv UUID '44484b9c-5058-4871-8448-4b9c50582871' TO INNER UUID 'dae7dc57-d0bc-4ef6-9ae7-dc57d0bcdef6' (`day` DateTime, `userid` UInt32, `downloads` UInt64, `bytes` Float64) ENGINE = SummingMergeTree PARTITION BY toYYYYMM(day) ORDER BY (userid, day) SETTINGS index_granularity = 8192 AS SELECT toStartOfDay(when) AS day, userid, count() AS downloads, sum(bytes)**_** AS bytes FROM default.download GROUP BY userid, day
2022/01/06 20:52:44 debug SELECT * FROM system.disks;
2022/01/06 20:52:44 debug SELECT value FROM `system`.`build_options` where name='VERSION_INTEGER'
2022/01/06 20:52:44 debug SELECT * FROM system.disks;
2022/01/06 20:52:44 debug found 1 tables with data in backup backup=download_daily_mv_backup-19 operation=restore
2022/01/06 20:52:44 debug SELECT count() FROM system.settings WHERE name = 'show_table_uuid_in_table_create_query_if_not_nil'
2022/01/06 20:52:44 debug SELECT name FROM system.databases WHERE engine IN ('MySQL','PostgreSQL')
2022/01/06 20:52:44 debug 
                SELECT 
                        countIf(name='data_path') is_data_path_present, 
                        countIf(name='data_paths') is_data_paths_present, 
                        countIf(name='uuid') is_uuid_present, 
                        countIf(name='create_table_query') is_create_table_query_present, 
                        countIf(name='total_bytes') is_total_bytes_present 
                FROM system.columns WHERE database='system' AND table='tables'
        
2022/01/06 20:52:44 debug SELECT database, name, engine , data_paths , uuid , create_table_query , coalesce(total_bytes, 0) AS total_bytes   FROM system.tables WHERE is_temporary = 0 SETTINGS show_table_uuid_in_table_create_query_if_not_nil=1
2022/01/06 20:52:44 debug SELECT * FROM system.disks;
_**2022/01/06 20:52:44 debug dstDataPaths=map[] disks=[{default ./ local}] tableDataPaths=[]**_

--------------
----------------------------
--------------------------------------------------------

Clickhouse-backup can support freeze the parts of materialView table with ReplicatedReplacingTree Engine, but when restores, some errors happened.

“dae7dc57-d0bc-4ef6-9ae7-dc57d0bcdef6” stands for data directory, If we can get this data path, then move data to the detached dir, Attach may succeed.

**Comment by Slach** [comment]
`clickouse-backup` already support MATERIALIZED VIEW with inner or destination table
look to 
https://github.com/AlexAkulov/clickhouse-backup/blob/master/test/integration/integration_test.go#L189-L234

Could you share `SELECT * FROM system.disks` from your destination server?

**Comment by wangzhen11aaa** [comment]
│ default │ ./   │ 97644584960 │ 250685575168 │               0 │ local │

**Comment by wangzhen11aaa** [comment]
> `clickouse-backup` already support MATERIALIZED VIEW with inner or destination table look to https://github.com/AlexAkulov/clickhouse-backup/blob/master/test/integration/integration_test.go#L189-L234
> 
> Could you share `SELECT * FROM system.disks` from your destination server?

│ default │ ./   │ 97644584960 │ 250685575168 │               0 │ local │.

I do not think we support view, for the code in backup.go

`	if !(strings.HasSuffix(table.Engine, "MergeTree")) {
		log.WithField("engine", table.Engine).Debug("skip table backup")
		return nil, nil, nil
	}`

We skip tables without suffix "MergeTree" directly.

**Comment by Slach** [comment]
> │ default │ ./ │ 97644584960 │ 250685575168 │ 0 │ local │

relative path is not look good
do you changed "path" setting in your config.xml ?
