### ISSUE TITLE
New policy about incremental backup.

### ISSUE THREAD

**Issue by wangzhen11aaa** [Altinity/clickhouse-backup#349]
Hi   
   When backups incrementally, under current policy, it will compare all the part names in the part of the TableMetadata structure, that's ok, But when parts merged after the last backup,  it is not ok, because it will take the merged part as new part.

   So I want to add new feature to solve this problem, only parts in new partition can be taken as new parts.
To be compatible with origin version, I think it is ok to add new option to clickhouse-backup. what do you think.

**Comment by wangzhen11aaa** [comment]
For we do not have context to store all the options of clickhouse_backup, I want to add this variable into the config,yaml and can avoid change many functions. 

  remote_storage: s3
  max_file_size: 107374182400
  disable_progress_bar: true
  backups_to_keep_local: 10
  backups_to_keep_remote: 10
  log_level: debug
  allow_empty_backups: false
  download_concurrency: 1
  upload_concurrency: 4 

  **`parts_based_incremental: true // default is true for compatibility of current policy`**
Or add a new tag in the config.yml like this.

policy:
`  parts_based_incremental: true // default is true for compatibility of current policy`

**Comment by Slach** [comment]
>  But when parts merged after the last backup, it is not ok, because it will take the merged part as new part.

Current incremental backup implementation `clickhouse-backup upload --diff-from`
need local base backup present on disk, which contains all parts as hard-links, even part will delete during background merge, hardlink stay exist and will allocate disk space after original part merge.

We plan to change backup format in https://github.com/AlexAkulov/clickhouse-backup/issues/324 to allow adding `--diff-from-remote` option. Which will compare current part list with part list on remote backup and allow us to avoid allocate extra local disk space for `base` backup after background merge.


> So I want to add new feature to solve this problem, only parts in new partition can be taken as new parts.

Could you provide more details about planning implementation?

How will you detect which partition is new? PARTITION BY clause could be anything.
Moreover, you can insert data for past period which will create new parts in "old" partitions and it's not good create backup which not contains all "new data".

**Comment by wangzhen11aaa** [comment]
F

> > But when parts merged after the last backup, it is not ok, because it will take the merged part as new part.
> 
> Current incremental backup implementation `clickhouse-backup upload --diff-from` need local base backup present on disk, which contains all parts as hard-links, even part will delete during background merge, hardlink stay exist and will allocate disk space after original part merge.
> 
> We plan to change backup format in #324 to allow adding `--diff-from-remote` option. Which will compare current part list with part list on remote backup and allow us to avoid allocate extra local disk space for `base` backup after background merge.
> 
> > So I want to add new feature to solve this problem, only parts in new partition can be taken as new parts.
> 
> Could you provide more details about planning implementation?
> 
> How will you detect which partition is new? PARTITION BY clause could be anything. Moreover, you can insert data for past period which will create new parts in "old" partitions and it's not good create backup which not contains all "new data".

For example, 
old parts:
               2021_01_02_1
               2021_03_07_4  
new parts:
               2021_01_07_5 (merged, data included in (2021_01_02_1, 2021_03_07_4) , not upload)
               2022_01_01_1 (new partition, upload)
We can compare the first part (split by "\_"), then we will get the new partition and will not take 2021_ as new partition.

**Comment by Slach** [comment]
```
For example,
old parts:
2021_01_02_1
2021_03_07_4
new parts:
2021_01_07_5 (merged)
2022_01_01_1 (new)
```

> We can compare the first part (split by "_"), then we will get the new partition and will not take 2021_ as new partition.

Could you explain:

for first backup will upload 
```
2021_01_02_1
2021_03_07_4
```
for second upload will upload only
```
2022_01_01_1 (new)
```

??

Look like wrong decision
Cause after download and `ATTACH TABLE ... PART XXXX` during restore
you will get a lot of background merges and will get a lot of disk i/o.

**Comment by wangzhen11aaa** [comment]
> 
In current policy, we will upload the 2021_01_07_5 , which makes data duplicated , right? because, now, we do not support clean 2021_01_02_1 and 2021_03_07_4 in incremental mode.

If we only upload the latest partition, data is correct.

**Comment by wangzhen11aaa** [comment]
> > 
> 
> In current policy, we will upload the 2021_01_07_5 again, which makes data duplicated.



> ```
> For example,
> old parts:
> 2021_01_02_1
> 2021_03_07_4
> new parts:
> 2021_01_07_5 (merged)
> 2022_01_01_1 (new)
> ```
> 
> > We can compare the first part (split by "_"), then we will get the new partition and will not take 2021_ as new partition.
> 
> Could you explain:
> 
> for first backup will upload
> 
> ```
> 2021_01_02_1
> 2021_03_07_4
> ```
> 
> for second upload will upload only
> 
> ```
> 2022_01_01_1 (new)
> ```
> 
> ??
> 
> Look like wrong decision Cause after download and `ATTACH TABLE ... PART XXXX` during restore you will get a lot of background merges and will get a lot of disk i/o.

If we only want to restore some partitions (last 7 days), partition-based incremental policy is exact what we want.

**Comment by Slach** [comment]
> If we only want to restore some partitions (last 7 days), partition-based incremental policy is exact what we want.

Usually, we prefer not to restore `last 7 days`, usually we want to restore the whole table.
And for your policy you will get disk i/o for all merges which you already made last 7 days.

Moreover, you should guarantee, we do not lose data when we have the following events sequence:

### stage one 
- insert two separate inserts one block in each
```
202201_01_01_0
202201_02_02_0
```
- call `clickhouse-backup create_remote base_backup` 

### stage two
- insert yet another block 
```
202201_03_03_0
```
- merge 3 blocks to one
```
202201_01_03_1
```
- call `clickhouse-backup create_remote diff_backup --diff-from=base_backup`


---
you should upload `202201_01_03_1` data part and it will contains data from `202201_01_01_0` and `202201_02_02_0`

**Comment by wangzhen11aaa** [comment]
> > If we only want to restore some partitions (last 7 days), partition-based incremental policy is exact what we want.
> 
> Usually, we prefer not to restore `last 7 days`, usually we want to restore the whole table. And for your policy you will get disk i/o for all merges which you already made last 7 days.
> 
> Moreover, you should guarantee, we do not lose data when we have the following events sequence:
> 
> ### stage one
> * insert two separate inserts one block in each
> 
> ```
> 202201_01_01_0
> 202201_02_02_0
> ```
> 
> * call `clickhouse-backup create_remote base_backup`
> 
> ### stage two
> * insert yet another block
> 
> ```
> 202201_03_03_0
> ```
> 
> * merge 3 blocks to one
> 
> ```
> 202201_01_03_1
> ```
> 
> * call `clickhouse-backup create_remote diff_backup --diff-from=base_backup`
> 
> you should upload `202201_01_03_1` data part and it will contains data from `202201_01_01_0` and `202201_02_02_0`

Ok, actually I know that case, but our scenario is that when we execute backup, the data we backuped is a snapshot and will not change. Backup whole data is not feasible, especially when the data is very huge. We only care the new data instead of the "old" data.

**Comment by wangzhen11aaa** [comment]
> > > If we only want to restore some partitions (last 7 days), partition-based incremental policy is exact what we want.
> > 
> > 
> > Usually, we prefer not to restore `last 7 days`, usually we want to restore the whole table. And for your policy you will get disk i/o for all merges which you already made last 7 days.
> > Moreover, you should guarantee, we do not lose data when we have the following events sequence:
> > ### stage one
> > 
> > * insert two separate inserts one block in each
> > 
> > ```
> > 202201_01_01_0
> > 202201_02_02_0
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > * call `clickhouse-backup create_remote base_backup`
> > 
> > ### stage two
> > 
> > * insert yet another block
> > 
> > ```
> > 202201_03_03_0
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > * merge 3 blocks to one
> > 
> > ```
> > 202201_01_03_1
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > * call `clickhouse-backup create_remote diff_backup --diff-from=base_backup`
> > 
> > you should upload `202201_01_03_1` data part and it will contains data from `202201_01_01_0` and `202201_02_02_0`


Ok, actually I know that case, but our scenario is that when we execute backup, the data we backuped is a snapshot and will not change. Backup whole data is not feasible, especially when the data is very huge. We only care the new data instead of the "old" data. So I named the policy PartitionBasedIncremental, clickhouse_backup will not change its parts-based-incremental by default.

**Comment by Slach** [comment]
> Ok, actually I know that case, but our scenario is that when we execute backup, the data we backuped is a snapshot and will not change. Backup whole data is not feasible, especially when the data is very huge. We only care the new data instead of the "old" data. So I named the policy PartitionBasedIncremental, clickhouse_backup will not change its parts-based-incremental by default.

"new" inserted data merge with exists "old" data permanently in background 

I say again, you can't control which partition will updated during each insert
you can modify multiple partition in one INSERT statement (look to max_partition_per_insert_block parameter https://clickhouse.com/docs/en/operations/settings/query-complexity/#max-partitions-per-insert-block)


Your approach, have too much tradeoffs.

Another test case

### Stage 1
- INSERT INTO table
`202201_01_01_0` created

- call clickhouse-backup create + upload

### Stage 2
- INSERT INTO table
`202201_02_02_0` created

- call clickhouse-backup create + upload --diff-from

### Result
`202201_02_02_0` will not upload cause 202201 paratition exists in your `partitionExistsMap`
you will lose data
