### ISSUE TITLE
Exclude tables

### ISSUE THREAD

**Issue by andrii29** [Altinity/clickhouse-backup#35]
Hello,
It would be nice to add **--exclude** option to backup all tables, except specified. Is it possible to add this?

Example
`clickhouse-backup create --exclude=<db>.<table1>,<db>.<table2>`

Regards,
Andrii

**Comment by AlexAkulov** [comment]
Hello!
This feature already exists. You can specify tables list for skip in config file by option `clickhouse.skip_tables` or use env `CLICKHOUSE_SKIP_TABLES`.
For example:
If you want to ignore `db.table1` and `db.table2` you have to set these in config.yml
```
clickhouse:
  skip_tables:
    - db.table1
    - db.table2
    - db.table*  # or table patterns
```
or
`> CLICKHOUSE_SKIPTABLES="db.table1,db.table2" clickhouse-backup create`

**Comment by andrii29** [comment]
Hello,
thank You for explanation

Regards,
Andrii
