### ISSUE TITLE
can this project donate to clickhouse official orgnazation?

### ISSUE THREAD

**Issue by ghost** [Altinity/clickhouse-backup#359]
The clickhouse-backup looks awesome, but i have a bit worried about the project . 
These days you may know the fakejs was drop by origin author. 
So i wonder, is it possible to donate this project to clickhouse official , and be  a real sub project of clickhouse.

**Comment by Slach** [comment]
Don't worry, currently project developed mostly by Altinity Inc (altinity.com) and available for puplic PRs.

I think in future ClickHouse Inc. will develop their solution under https://github.com/ClickHouse
