### ISSUE TITLE
Bug: After restart server doesnt show list of backups

### ISSUE THREAD

**Issue by dima-altinity** [Altinity/clickhouse-backup#368]
Hi

 we run chbackup as server process and use it via "system.backup_actions". It works fine however if I restart  chbackup process then  "system.backup_actions" table becomes empty. But local backups exist and you could see them using "clickhouse-backup list local | remote" command.

Looks like server process show read local & remote backups after it starts and save it in memory ( variable).

@Slach @AlexAkulov

**Comment by Slach** [comment]
`system.backup_actions` it's a just memory log, and not store persistent, if you restart server all current running actions will break, and after restart no one action will not launch without API call

`system.backup_list` works after restart, as expected
