### ISSUE TITLE
Upload exiting "silently" with no errors when REMOTE_STORAGE is not defined

### ISSUE THREAD

**Issue by ercanucan** [Altinity/clickhouse-backup#375]
Hi @Slach,

We've been using clickhouse-backup for some time and recently found out that our backups to s3 were not taking place. We have then realized that we did not set the REMOTE_STORAGE="s3" (which was defaulting to `none`).

We see that the `Upload` function is exiting silently without any errors, if the remote storage is not set.

We mean the following line here:
https://github.com/AlexAkulov/clickhouse-backup/blob/master/pkg/backup/upload.go#L32

Was this a deliberate choice to exit "silently" without errors if remote storage is not set? This causes some difficulties in automated backup environments as the commands executed do not return with an exit code.

If this was not a deliberate choice, please let me know and I'll submit a PR.

Thanks!

(might also be related to https://github.com/AlexAkulov/clickhouse-backup/issues/365)

/cc @max-wittig @dlouzan @bufferoverflow

**Comment by Slach** [comment]
Issue is not related to #365 
but thanks for reporting, we will return error and non zero exit code for remote_storage=none corner case on 1.3.0 release

**Comment by ercanucan** [comment]
@Slach great! thanks a lot for the quick response and the clarification!
