### ISSUE TITLE
How can I restore to another table

### ISSUE THREAD

**Issue by 555chy** [Altinity/clickhouse-backup#376]
For example
clickhouse-backup create -t test.tableA backup_tableA
clickhouse-backup restore -t test.tableB backup_tableA

But this will report a error :  error no have found schemas by test.tableB in backup_tableA

**Comment by Slach** [comment]
Why do you need this strange use case?

May be 
```sql
INSERT INTO test.tableB SELECT * FROM test.tableA
INSERT INTO test.tableB SELECT * FROM remote('old-server',test.tableA)
```
Will better approach for you?
Look to documentation
https://clickhouse.com/docs/en/sql-reference/table-functions/remote/
