### ISSUE TITLE
Return `clean` command to avoid disk space allocation for corner case when `create` failed during `moveShadow`

### ISSUE THREAD

**Issue by jfcarino** [Altinity/clickhouse-backup#379]

**Comment by Slach** [comment]
Could you provide more context?

When you call `clickhouse-backup create` then clickhouse-backup will move your files from `/var/lib/clickhouse/shadow`
to `/var/lib/clickhouse-backup/backup/<backup_name>/shadow`, so /shadow should be clean after it
if you want to remove local backup, just call `clickhouse-backup delete local <backup_name>`

**Comment by jfcarino** [comment]
Okay so just to give you a context, previously we are using `clickhouse-backup clean` command to clean shadow data but after the upgrade with the latest version the said command has been removed. May I know the reason for that? and in case what would be the alternative? Should we just run manual delete using `rm -rf /var/lib/clickhouse/shadow/*`?

**Comment by Slach** [comment]
Which clickhouse-backup version did you use before upgrade?

**Comment by jfcarino** [comment]
I am using v0.5.2 before the upgrade

**Comment by Slach** [comment]
Ok ;) too old version, could you check your old format backups could be restored by the new clickhouse-backup 1.2.2 version?

In altinity.cloud we tested only legacy 0.6.5 version backup restoring, feel free open separate issue if it will fail

as answer your question
`freeze` and `clean` commands removed as unnecessary by @AlexAkulov during prepare 1.x version.

https://github.com/AlexAkulov/clickhouse-backup/commit/edd370e048eaa92be96e55ef614765d70f39849f#diff-1fdbab9bbc83a9dd11d65842a5febe641bcecc1243a4cf2c76035ebf48347721L228-L249

as I said before
now you should use following workflow
```bash
# will move /var/lib/clickhouse/shadow to  /var/lib/clickhouse/backup/<backup_name>/shadow/
clickhouse-backup create <backup_name> 
# will upload local backup to remote_storage
clickhouse-backup upload <backup_name> 
# will clean /var/lib/clickhouse/backup/<backup_name>
clickhouse-backup delete local <backup_name> 
```

##  and you are right!
when create backup fail, during call function `moveShadow`, we need to call `clickhouse-backup clean` command to avoid disk space allocation after background  part merges
thanks a lot for reporting

**Comment by jfcarino** [comment]
Ok that actually make sense. I got the answer I needed. Thanks you so much! :)
