### ISSUE TITLE
找不到 shadow 文件

### ISSUE THREAD

**Issue by MataSong** [Altinity/clickhouse-backup#386]
用docker方式安装部署的，备份clickhouse数据时，只有有数据结构文件，没有数据文件，未找到 shadow文件夹

**Comment by Slach** [comment]
`clickhouse-backup` необходим прямой доступ до той же самой папки /var/lib/clickhouse/ как и у `clickhouse-server`
`clickhouse-backup` не позволяет делать бекап с удаленного clickhouse-server, поскольку использует ALTER TABLE ... FREZZE during backup

используйте
volumes_from в docker-compose
https://github.com/compose-spec/compose-spec/blob/master/spec.md#volumes_from

или используйте `-v /var/lib/clickhouse:/var/lib/clickhouse` когда запускаете `clickhouse-server` и `clickhouse-backup` в docker на одном и том же хосте
