### ISSUE TITLE
【error can't attach partitions for table】Failed to restore after remove UUID from backup_name/metadata/db/table.json

### ISSUE THREAD

**Issue by Yoshihiro-jp** [Altinity/clickhouse-backup#393]
Hello,
I can't restore from my backup.
My backup and restore procedure was like below.

1. #clickhouse-backup create

2. #clickhouse-backup list
data_dump             120.74KiB   10/02/2022 08:39:34   local
2022-02-14T02-27-59   8.28GiB     14/02/2022 02:27:59   local

3.Delete "UUID XXXXXX" from json files from "/var/lib/clickhouse/backup/2022-02-14T02-27-59/metadata/ntopng/.
For example,
From:
 "query": "CREATE TABLE ntopng.active_monitoring_alerts UUID '4b6c0dcc-70d8-4609-9bb6-d4ae9d6a92d6' (`rowid` UUID, `alert_id` UInt32, `alert_status` UInt8, `interface_id` Nullable(UInt16),
To:
 "query": "CREATE TABLE ntopng.active_monitoring_alerts (`rowid` UUID, `alert_id` UInt32, `alert_status` UInt8, `interface_id` Nullable(UInt16),

4. #clickhouse-backup restore 2022-02-14T02-27-59
2022/02/14 13:03:28.266134  info done                      backup=2022-02-14T02-27-59 operation=restore table=ntopng.active_monitoring_alerts
2022/02/14 13:03:28.266173  info done                      backup=2022-02-14T02-27-59 operation=restore table=ntopng.network_alerts
2022/02/14 13:03:28.292984 error can't attach partitions for table 'ntopng.flow_alerts': code: 481, message: Cannot set modification time for file: /var/lib/clickhouse/store/ce1/ce133930-540f-4b29-aa2b-44ed7833fcc6/detached/attaching_20220127_1_1922_70/, errno: 1, strerror: Operation not permitted

Could you tell me what is wrong with me?

regards,
Yoshihiro

**Comment by Slach** [comment]
Why do you need `step 3`?

`UUID XXX` is necessary for Atomic database engine, because your data now store on /var/lib/clickhouse/store and your /var/lib/clickhouse/data only contains hard links to `store` directory

What you do between step 3 and step 4? Did you download `2022-02-14T02-27-59` from `remote_storage`?
If yes, could you check try this debug build: 
https://github.com/AlexAkulov/clickhouse-backup/files/8042179/clickhouse-backup.zip
unpack  clickhouse-backup.zip into /tmp/

and run the following commands
```bash
/tmp/clickhouse-backup delete local 2022-02-14T02-27-59
find /var/lib/clickhouse -type d -name "detached" -exec rm -r "{}" \;
LOG_LEVEL=debug /tmp/clickhouse-backup download 2022-02-14T02-27-59
LOG_LEVEL=debug /tmp/clickhouse-backup restore 2022-02-14T02-27-59
```

and share the results

**Comment by Yoshihiro-jp** [comment]
Dear @Slach ,
Thank you for your comments.

>Why do you need step 3?

My procedure was wrong.
1. #clickhouse-backup create

2. #clickhouse-backup list
data_dump             120.74KiB   10/02/2022 08:39:34   local
2022-02-14T02-27-59   8.28GiB     14/02/2022 02:27:59   local
2022-02-15T06-55-59   8.55KiB     15/02/2022 06:55:59   local

3. ntopng: ) DROP database ntopng;    ※Delete the database what I want to execute the restore

4. #clickhouse-backup restore 2022-02-15T06-55-59  
I got the error like below.
```bash
root@ntopng:~# clickhouse-backup restore 2022-02-15T06-55-59
2022/02/15 16:01:27.488995  warn can't create table 'ntopng.network_alerts': code: 57, message: Directory for table data store/c52/c52c5faa-121a-448f-852c-5faa121ae48f/ already exists, will try again backup=2022-02-15T06-55-59 operation=restore
2022/02/15 16:01:27.491524  warn can't create table 'ntopng.flow_alerts': code: 57, message: Directory for table data store/f32/f325a87e-228f-4076-b325-a87e228f1076/ already exists, will try again backup=2022-02-15T06-55-59 operation=restore
2022/02/15 16:01:27.494105  warn can't create table 'ntopng.flows': code: 57, message: Directory for table data store/eed/eed59d5b-ded1-476c-aed5-9d5bded1b76c/ already exists, will try again backup=2022-02-15T06-55-59 operation=restore
2022/02/15 16:01:27.496595  warn can't create table 'ntopng.host_alerts': code: 57, message: Directory for table data store/838/8380d868-324d-45a0-8380-d868324de5a0/ already exists, will try again backup=2022-02-15T06-55-59 operation=restore
2022/02/15 16:01:27.498806  warn can't create table 'ntopng.interface_alerts': code: 57, message: Directory for table data store/1cc/1ccdd96e-2eb1-41c3-9ccd-d96e2eb151c3/ already exists, will try again backup=2022-02-15T06-55-59 operation=restore
2022/02/15 16:01:27.501435  warn can't create table 'ntopng.mac_alerts': code: 57, message: Directory for table data store/458/4580c332-3d8e-49a5-8580-c3323d8ef9a5/ already exists, will try again backup=2022-02-15T06-55-59 operation=restore
2022/02/15 16:01:27.503940  warn can't create table 'ntopng.snmp_alerts': code: 57, message: Directory for table data store/b3d/b3d86395-ee60-499a-b3d8-6395ee60399a/ already exists, will try again backup=2022-02-15T06-55-59 operation=restore
2022/02/15 16:01:27.506251  warn can't create table 'ntopng.system_alerts': code: 57, message: Directory for table data store/7b6/7b6e6d73-128b-4d99-bb6e-6d73128bbd99/ already exists, will try again backup=2022-02-15T06-55-59 operation=restore
2022/02/15 16:01:27.508613  warn can't create table 'ntopng.user_alerts': code: 57, message: Directory for table data store/32d/32d71eed-6a84-4fe2-b2d7-1eed6a84bfe2/ already exists, will try again backup=2022-02-15T06-55-59 operation=restore
2022/02/15 16:01:27.512249 error can't create table `ntopng`.`all_alerts`: code: 57, message: Mapping for table with UUID=510b8fd5-0c23-4883-ac9b-82092782c251 already exists. It happened due to UUID collision, most likely because some not random UUIDs were manually specified in CREATE queries. after 10 times, please check your schema dependencies
```

So I deleted the UUID according to the below URL.
https://www.51cto.com/article/681609.html

Could you tell me the correct procedure when I got above errors?


>What you do between step 3 and step 4? Did you download 2022-02-14T02-27-59 from remote_storage?

I don't use the remote storage. It is local like below.

#clickhouse-backup list
data_dump             120.74KiB   10/02/2022 08:39:34   local
2022-02-14T02-27-59   8.28GiB     14/02/2022 02:27:59   local
2022-02-15T06-55-59   8.55KiB     15/02/2022 06:55:59   local

regards,
Yoshihiro

**Comment by Slach** [comment]
> ntopng: ) DROP database ntopng; 

for Atomic database engine use `DROP DATABASE ntopng SYNC`
look to https://clickhouse.com/docs/en/engines/database-engines/atomic/
