### ISSUE TITLE
clickhouse-backup 1.3 ignores max_file_size option

### ISSUE THREAD

**Issue by vanyasvl** [Altinity/clickhouse-backup#394]
clickhouse-backup 1.3 ignores max_file_size in the new format backups and doesn't split large partitions to tar files
In result with `max_file_size: 1073741824` I have tar files on the storage with size larger 1Gb (for example I have 14Gb tar)

**Comment by vanyasvl** [comment]
And in result clickhouse-backup 1.3 has large memory consumption I believe

**Comment by Slach** [comment]
`clickhouse-backup 1.3` `upload_by_part` true by default, so max_file_size could be used only in calculation of s3_part_size
we can't split a single large part file, and never split it in past (max_file_size was 100Gb by default), it allows us more granularity for incremental backup downloading.

Which `upload_concurrency` value do you have in `clickhouse-backup print-config`?

I say again high `upload_concurrency` value + high value for `s3_part_size` will allocate memory
We don't buffer the whole file in memory, and use streaming compressions algorithm

**Comment by Slach** [comment]
@vanyasvl is high memory usage still relevant for you?

**Comment by vanyasvl** [comment]
> @vanyasvl is high memory usage still relevant for you?

I fixed high memory usage by decreasing s3 part_size from 1Gb to 100Mb. Thanks

**Comment by Slach** [comment]
what about upload / download speed?

**Comment by vanyasvl** [comment]
I gonna test it on Monday

**Comment by Slach** [comment]
@vanyasvl Any test results available from your side?

**Comment by vanyasvl** [comment]
Speed it the same with previous versions. I think you can close this issue
