### ISSUE TITLE
Missing persistent stats/metrics

### ISSUE THREAD

**Issue by nahsi** [Altinity/clickhouse-backup#4]
When running as a server, after restart all metrics are zeroed.
Maybe stats can be stored in a file and loaded after restart, if file is present?

**Comment by vanyasvl** [comment]
Agreed, it's pain to restart clickhouse-backup and get bunch of alerts in monitoring because all metrics were reset

**Comment by nahsi** [comment]
Author of clickhouse-backup proposed arguments against metrics persistence and some workarounds.

I will close this issue since developement is happening in the original repository I think

https://github.com/AlexAkulov/clickhouse-backup/issues/285
