### ISSUE TITLE
Can't restore from backup 

### ISSUE THREAD

**Issue by r3b-fish** [Altinity/clickhouse-backup#41]
Hi! 

I can't restore from backup table (ReplicatedReplacingMergeTree). 

```Shell
clickhouse-backup restore-data -t marketing.a_events "2019-07-31T16-27-49"
```

CLI:

Prepare data for restoring 'marketing.a_events'
ALTER TABLE `marketing`.`a_events` ATTACH PARTITION 200812
can't attach partitions for table 'marketing.a_events' with code: 33, message: Cannot read all data. Bytes read: 27. Bytes expected: 74.

ClickHouse logs:

0. /usr/bin/clickhouse-server(StackTrace::StackTrace()+0x22) [0x781c272]
1. /usr/bin/clickhouse-server(DB::Exception::Exception(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int)+0x22) [0x3a0a3e2]
2. /usr/bin/clickhouse-server(DB::ReadBuffer::readStrict(char*, unsigned long)+0x181) [0x3a19f71]
3. /usr/bin/clickhouse-server(DB::DataTypeString::deserializeBinary(DB::IColumn&, DB::ReadBuffer&) const+0x194) [0x66e9334]
4. /usr/bin/clickhouse-server(DB::MergeTreeDataPart::loadIndex()+0x22c) [0x6a5ffec]
5. /usr/bin/clickhouse-server(DB::MergeTreeDataPart::loadColumnsChecksumsIndexes(bool, bool)+0x58) [0x6a612d8]
6. /usr/bin/clickhouse-server(DB::MergeTreeData::loadPartAndFixMetadata(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)+0x172) [0x6a3b432]
7. /usr/bin/clickhouse-server(DB::StorageReplicatedMergeTree::attachPartition(std::shared_ptr<DB::IAST> const&, bool, DB::Context const&)+0x237) [0x69c6ac7]
8. /usr/bin/clickhouse-server(DB::StorageReplicatedMergeTree::alterPartition(std::shared_ptr<DB::IAST> const&, DB::PartitionCommands const&, DB::Context const&)+0x193) [0x69c93a3]
9. /usr/bin/clickhouse-server(DB::InterpreterAlterQuery::execute()+0x578) [0x6dc1b18]
10. /usr/bin/clickhouse-server() [0x688ca65]
11. /usr/bin/clickhouse-server(DB::executeQuery(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, DB::Context&, bool, DB::QueryProcessingStage::Enum, bool)+0x74) [0x688e6d4]
12. /usr/bin/clickhouse-server(DB::TCPHandler::runImpl()+0x830) [0x3a15c20]
13. /usr/bin/clickhouse-server(DB::TCPHandler::run()+0x2b) [0x3a1627b]
14. /usr/bin/clickhouse-server(Poco::Net::TCPServerConnection::start()+0xf) [0x725666f]
15. /usr/bin/clickhouse-server(Poco::Net::TCPServerDispatcher::run()+0xe9) [0x7256da9]
16. /usr/bin/clickhouse-server(Poco::PooledThread::run()+0x81) [0x7927e41]
17. /usr/bin/clickhouse-server(Poco::ThreadImpl::runnableEntry(void*)+0x38) [0x7924248]
18. /usr/bin/clickhouse-server() [0xb2ac5bf]
19. /lib/x86_64-linux-gnu/libpthread.so.0(+0x76db) [0x7f2dc4f9a6db]
20. /lib/x86_64-linux-gnu/libc.so.6(clone+0x3f) [0x7f2dc472188f]

**Comment by AlexAkulov** [comment]
Check that the scheme of table that is being restored correspondence the data that is being restored.

**Comment by AlexAkulov** [comment]
Suppose it is bug of ClickHouse
https://github.com/yandex/ClickHouse/issues/4959
