### ISSUE TITLE
SSL Clickhouse error: can't connect to clickhouse: x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by DipalPrajapati** [Altinity/clickhouse-backup#410]
I am not able to take the backup of containerised plus secure clickhouse. It is giving below error.

clickhouse-backup  create
2022/03/09 17:45:53.501070 error can't connect to clickhouse: x509: certificate signed by unknown authority

**Comment by Slach** [comment]
Currently, clickhouse-backup doesn't support custom CA and self-signed certs

as quick workaround, you can apply follow configuration: 
```yaml
clickhouse:
  skip_verify: true
```

**Comment by DipalPrajapati** [comment]
Worked , thanks. Please move to close.
