### ISSUE TITLE
clickhouse-backup-metadata.cache.S3 not found

### ISSUE THREAD

**Issue by karimennassiri** [Altinity/clickhouse-backup#413]
I installed clickhouse-backup in my cluster and I am ready to use it. I wanted to test the command line before creating a cron job that will automate all operations.

So, I launched a first command to create a first backup, then I launched the command to upload it to my s3 bucket. An error blocks the upload operation

`2022/03/11 13:51:28.196587 debug /tmp/.clickhouse-backup-metadata.cache.S3 not found, load 0 elements`

I can't find an explanation in the docs or anywhere.

**Comment by Slach** [comment]
it's just debug logs, we use local backup metadata cache
