### ISSUE TITLE
system.backup_actions is this part of latest clickhouse release ? 

### ISSUE THREAD

**Issue by DipalPrajapati** [Altinity/clickhouse-backup#417]
**system.backup_actions** is this part of latest clickhouse release ?  
I do not see this in Clickhouse 20.12 version.

**Comment by Slach** [comment]
No, it's a part of `clickhouse-backup`, and works only if you run all commands via API

check your config
and setup
```
api:
 create_integration_tables: true # false by default
```
after it
read https://github.com/AlexAkulov/clickhouse-backup/#api for details
