### ISSUE TITLE
A way to limit bandwidth?

### ISSUE THREAD

**Issue by nahsi** [Altinity/clickhouse-backup#418]
We have Clickhouse and MINIO in two differtent datacenters, link bandwidth is 5Gbit. When uploading backup to MINIO bandwidth between two datacenters is consumed by clickhouse-backup.

What is a best reliable way to limit upload/download speed to/from s3? How about an option to limit bandwidth?

**Comment by Slach** [comment]
You could setup the following config options:
```
general:
  upload_concurrency: 1
s3:
  s3_concurrency: 1
```
it not restricts bandwidth, but restrict parallel uploading to only one TCP connection and I didn't see use cases when single TCP connection can utilize 5Gbit

**Comment by Slach** [comment]
As quick workaround
let's do something like that
```
sudo apt-get install trickle
# restrict bandwidth to 1024 KB/s
tickle -u 1024 clickhouse-backup upload backup_name
```

**Comment by minguyen9988** [comment]
this does work because golang doesnt to libc
 
please implement with something different

https://stackoverflow.com/questions/40386936/why-doesnt-the-trickle-utility-affect-my-dynamically-linked-golang-program

example: https://github.com/ConduitIO/bwlimit
