### ISSUE TITLE
Download remote backups from diff recursively

### ISSUE THREAD

**Issue by DrissiReda** [Altinity/clickhouse-backup#419]
I tried using the new command `restore_remote`. With `--diff-from-remote` . But it only downloads the first backup it depends on.

I have 5 backups on remote, that each depend on the next:

```
       E
diff   |
       v    
       D
diff   |
       v   
       C 
diff   |
       v   
       B 
diff   |
       v   
       A 
```

Now I need to restore backup E and I execute the command: `restore_remote E --diff-from-remote=D`. This only downloads the backups E and D. 

Is there a reason why it doesn't download the backups A, B, C ?

I notice the same behavior when I use: `create_backup --diff-from-remote=E` . It only downloads the backup E. Which means my backup F will contain the data that was stored in all backups A,B,C,D except what was stored in backup E.

**Comment by Slach** [comment]
could you shre
`clickhouse-backup --version` results?


>  I use: create_backup --diff-from-remote=E

Do you mean `clickhouse-backup create_remote --diff-from-remote=remote_backup_name`?


> I tried using the new command restore_remote. With --diff-from-remote . But it only downloads the first backup it depends on.

`restore_remote` doesn't have --diff-from-remote parameter

when you run `clickhouse-backup restore_remote backup-name`, this do following algorithm
- download `backup-name/metadata.json` with list of presents table and disks and link to name "required" backup (which used when you cal --diff-from-remote=remote_backup_name
- download all `db_name/table_name.json` table metadata files
- read each table_name.json and get list of *.tar files presents for table
- download and unpack each *.tar file
- for parts which marked as required, try to find it in "required" backup, and all backup in sequence, will download from remote required backup and make hardlinks to downloaded parts from current backup

could you share `ls -la /var/lib/clickhouse/backups`
after clickhouse-backup restore_remote backup_name finish?

**Comment by DrissiReda** [comment]
I’m using the docker image for clickhouse-backup version 1.3.1. Running it as server then using `curl -XPOST /backup/actions -d ‘{“command”:”…”}’ `. 

`ls /var/lib/clickhouse/backup ` returns `E D`.

**Comment by Slach** [comment]
If you attempt to restore E, then `C, A, B` backups will download only if contains table data parts which shall present in E.

Could you share logs from your docker container?

**Comment by DrissiReda** [comment]
After examining the backups they are indeed not dependent. Because when I created backup `E` only the backup `D` was pulled. Which means that despite the backup `D` depending on `C` it did not matter and all the data inside `C,A,B` was backed up again in `E`. How can I create backup `E` with a single command and ask it to download remote diffs recursively.

**Comment by Slach** [comment]
I'm sorry, I don't understand what exactly you are trying to do.
could. you share your clickhouse-backup docker container logs?

**Comment by DrissiReda** [comment]
Sure I'll get home and send them to you

**Comment by Slach** [comment]
any news? did you figure out with backup diff sequences?

**Comment by DrissiReda** [comment]
I'm doing it right now. It seems that my backups were poorly created using 1.0.0 and classic `create --diff-from` with manual download/upload scripts

**Comment by Slach** [comment]
I say again `create --diff-from` not exist, only `upload --diff-from` or `create_remote --diff-from` 

Even if you run clickhouse-backup 1.0.0 `upload --diff-from` was run, it shall work corre
so, just share your docker clickhouse-backup for last 7 days
or i will close issue, cause don't understnad what exactly do you do

**Comment by DrissiReda** [comment]
> I say again `create --diff-from` not exist, only `upload --diff-from` or `create_remote --diff-from`
> 
> Even if you run clickhouse-backup 1.0.0 `upload --diff-from` was run, it shall work corre so, just share your docker clickhouse-backup for last 7 days or i will close issue, cause don't understnad what exactly do you do

My bad I meant `upload --diff-from` My problem has been resolved by starting again from scratch. Can't reproduce my old problem so I assume I did something wrong.
