### ISSUE TITLE
Support for assuming AWS roles?

### ISSUE THREAD

**Issue by spoofedpacket** [Altinity/clickhouse-backup#42]
Is it possible to configure clickhouse-backup to use an AWS IAM role when accessing an S3 bucket?

https://docs.aws.amazon.com/cli/latest/topic/config-vars.html#using-aws-iam-roles

I'm trying to use an S3 bucket for clickhouse backup that was created with a specific `role_arn`, so the keys alone are not enough to access it unfortunately.

**Comment by AlexAkulov** [comment]
Hello! 
I don't use s3 from AWS. It will be cool if you create PR with this feature.
