### ISSUE TITLE
Backing up FUNCTIONS 

### ISSUE THREAD

**Issue by aleclerc-sonrai** [Altinity/clickhouse-backup#420]
Does clickhouse-backup deal with function backup/restore?

From what I can tell they are stored in system.functions table but sunce we skip those tables (which seems like it's the right thing to do) but the only way I'm found to then restore the function is to manually re-run the "CREATE FUNCTION" command again.

**Comment by Slach** [comment]
`system.functions` it's a not MergeTree table, so you can only backup schema, but can't backup data, this table built on the fly 

currently, clickhouse-backup allow schema backup for all tables/dictionaries which present in `system.tables`, and I would strongly recommend don't backup any `system.*` table

I attempt to implement backup `SELECT * FROM system.functions WHERE create_query != ''`, but only in 2.0.0 version

I would suggest manage functions and table schema itself with something like https://github.com/golang-migrate/migrate/tree/master/database/clickhouse/README.md
