### ISSUE TITLE
remote backup is broken: `broken (can't stat metadata.json)` and `is empty backup` while the file is really there

### ISSUE THREAD

**Issue by fzyzcjy** [Altinity/clickhouse-backup#422]
Hi thanks for the wonderful tool! However it is having a bug.

I made a backup and upload to s3 (and delete the local backup for testing). But it has error:

```
bash-5.1# clickhouse-backup list | grep 2022-04-08T03-17-38
2022-04-08T03-17-38   ???          01/01/0001 00:00:00   remote      broken (can't stat metadata.json)

bash-5.1# clickhouse-backup download 2022-04-08T03-17-38
2022/04/08 03:32:57.332190 error '2022-04-08T03-17-38' is empty backup
```

using 1.3.1 latest version

The file is indeed there:

![image](https://user-images.githubusercontent.com/5236035/162358251-ab286456-392f-4e1a-9ef4-ab094554748a.png)

**Comment by Slach** [comment]
could you share?
```
LOG_LEVEL=debug clickhouse-backup list remote
```

**Comment by fzyzcjy** [comment]
Sure.

```
bash-5.1# LOG_LEVEL=debug clickhouse-backup list remote
2022/04/08 09:08:19.174589 debug /tmp/.clickhouse-backup-metadata.cache.S3 load 29 elements
2022/04/08 09:08:19.467753 debug /tmp/.clickhouse-backup-metadata.cache.S3 save 29 elements

... some other records ...

2022-04-08T03-17-38   ???         01/01/0001 00:00:00   remote      broken (can't stat metadata.json)
```

**Comment by fzyzcjy** [comment]
Interestingly, when I clear that cache, everything is fine now.

```
bash-5.1# rm/tmp/.clickhouse-backup-metadata.cache.S3

bash-5.1# LOG_LEVEL=debug clickhouse-backup list remote
2022/04/08 09:09:30.943689 debug /tmp/.clickhouse-backup-metadata.cache.S3 not found, load 0 elements
2022/04/08 09:09:31.917328 debug /tmp/.clickhouse-backup-metadata.cache.S3 save 29 elements

...

2022-04-08T03-17-38   1.13GiB     08/04/2022 03:18:16   remote      gzip
```

**Comment by fzyzcjy** [comment]
However, indeed I am triggering using the REST api, so I cannot touch the docker container and let it `rm` the file. So this workaround indeed does not work for me.

**Comment by Slach** [comment]
Ok! look like we found root cause , thanks a lot for reporting

Cache file which saved during backup is incomplete!
broken (or partially uploaded) backup should not be saved to cache

**Comment by fzyzcjy** [comment]
Congratulations, and happy to hear that you find out the cause! Looking forward to your bugfix and update to the new version!

**Comment by fzyzcjy** [comment]
🎉
