### ISSUE TITLE
Use UNFREEZE TABLE in ClickHouse after backup finished to allow s3 disks unlock and delete remote keys during merge

### ISSUE THREAD

**Issue by filimonov** [Altinity/clickhouse-backup#423]
We need to be sure we do UNFREEZE to release the files which were freezed.

**Comment by Slach** [comment]
could you explain what exactly you mean?

**Comment by filimonov** [comment]
I didn't test that (need to be checked) but it looks like that:

If we have s3 disk configured in clickhouse, then freeze command create a 'hardlinks' in shadow dir (both in local FS and in S3) which increment the refcount to the target object. 

Even if you remove the file from the local filesystem (or move it to backup subfolder), the 'hardlink' in the virtual filesystem (in s3) stays in place. And it don't allow the data files to be deleted after the part go away (because refcount never goes back to zero).

There is 'unfreeze' command introduced for that (?)

**Comment by Slach** [comment]
got it

**Comment by Slach** [comment]
currently when we setup
```yaml
clickhouse:
  use_embedded_backup_restore: true
```  

s3 disks should be also supported
