### ISSUE TITLE
Problem when restoring --partition, try to DROP TABLE

### ISSUE THREAD

**Issue by nrukavkov** [Altinity/clickhouse-backup#424]
Hello. I got a some strange behaviour while restoring partition. I want just restore a one parition in table, but clickhouse-backup is trying to delete a whole table. What do I miss?

`clickhouse-backup restore_remote --tables=mego_prod_stats_flights.search_result_gds_local --partitions=202011 mego_prod_stats_flights.search_result_gds_local_shard02_202011`

<img width="1164" alt="image" src="https://user-images.githubusercontent.com/54890287/162727488-e6b2b17f-0f6f-4d5f-adb8-16675deae792.png">

**Comment by Slach** [comment]
Unfortunately, `DROP TABLE` here is right behavior we try to just restore backup, we need restore table schema the same as we store schema in backup to restore data properly.
and `--partition` here it's just a filter for data parts during restore data phase

to achieve your goal, try to use something like that:

```bash
clickhouse-client -q "ALTER TABLE mego_prod_stats_flights.search_result_gds_local DROP PARTITION 202011"
clickhouse-backup restore_remote --data --tables=mego_prod_stats_flights.search_result_gds_local --partitions=202011
```

`--data` parameter means skip `restoreSchema` and call `DROP TABLE` and just try to execute `ATTACH PART` for parts which contains in backup and have name prefix `202011*`
