### ISSUE TITLE
Problem when creating multiply partitions

### ISSUE THREAD

**Issue by nrukavkov** [Altinity/clickhouse-backup#425]
When creating a backup, if you pass a few partitions as a parameter, you will get a tiny backup without data. Everything works fine if you pass a one partition.

**Comment by Slach** [comment]
are you sure your partitions contains data?
could you share
```
LOG_LEVEL=debug clickhouse-backup create backup_name --partition=<your-partitions-list>
```

**Comment by Slach** [comment]
@nrukavkov could you provide more context?
Is the issue still relevant for you?

**Comment by kingboung** [comment]
solved?

**Comment by Slach** [comment]
@kingboung no additional context provided from @nrukavkov 
I not sure partitions contained data, will close issue if author not response

**Comment by kingboung** [comment]
Version: 1.4.0
Storage: s3
Command: clickhouse-backup create_remote --table xxx --partitions xx,xx,xx xx
Result: No data backup without any error log

But if I specify only one partition, the backup command works.
@Slach

**Comment by kingboung** [comment]
Version 1.3.2 has the same problem. What should I do to avoid it?
@Slach

**Comment by kingboung** [comment]
How is the thing going on?

**Comment by Slach** [comment]
Sorry fellows, i wrong interpret 
https://github.com/urfave/cli/blob/v1.22.9/docs/v1/manual.md
comma separated works only for envrironment variable

as quick workaround use `clickhouse-backup create_remote --partitions part1 --partitions part2 backup_name`

**Comment by Slach** [comment]
@kingboung @nrukavkov try to 1.4.2 release
