### ISSUE TITLE
Action restore remote fails if backup is available locally

### ISSUE THREAD

**Issue by DrissiReda** [Altinity/clickhouse-backup#427]
Running the action `restore_remote` works perfectly if I start from an empty clickhouse cluster, with backups in my s3 bucket.

But if I run a backup, then a restore I get an error:

```
backup is already exists
```

And the restore fails.

Can't the `restore_remote` action just skip the download and restore the already present backup?

**Comment by Slach** [comment]
before run `restore_remote` second time, you need run clickhouse-backup delete local <backup_name>

moreover, use `restore_remote --rm <backup_name>` if your current database is not empty and contains old invalid data whcih not match with backup data in /var/lib/clickhouse/backups/
