### ISSUE TITLE
Ignore schema

### ISSUE THREAD

**Issue by Camamber** [Altinity/clickhouse-backup#43]
When i ignore some tables, it looks like okay. But then while, try restore-schema it still try to create them.
ch: 19.3.8
CLICKHOUSE_SKIP_TABLES=system.*,default.test1,default..inner.*

**Comment by Camamber** [comment]
I found that you dont deal with skiping table during copying metadata. Why?

```
log.Println("Copy metadata")  
if err := copyPath(path.Join(dataPath, "metadata"), path.Join(backupPath, "metadata"), dryRun); err != nil {
    return fmt.Errorf("can't backup metadata with %v", err)
}
log.Println("  Done.")
```

**Comment by AlexAkulov** [comment]
I will fix this in the next version
