### ISSUE TITLE
problem when using Clickhouse backup restore

### ISSUE THREAD

**Issue by zhanghanwei2008** [Altinity/clickhouse-backup#436]
Hello, I have some problem when using Clickhouse backup restore。
- An error occurred while executing  clickhouse-backup restore -d -s -rm bak-ICC command. The error message is error can't attach partitions。
- clickhouse version is  21.10.5.3, 
- clickhouse-backup version is v1.3.2。

**Comment by Slach** [comment]
could you share result for the following command?
```
LOG_LEVEL=debug  clickhouse-backup restore -d -s -rm bak-ICC
```

**Comment by zhanghanwei2008** [comment]
![Snipaste_2022-05-01_09-15-43](https://user-images.githubusercontent.com/26110709/166128190-8433c59c-d24e-46df-b045-3531027f11e1.png)
Sorry, our computer can only take screenshots of errors. Please take a look. Thank you.

**Comment by Slach** [comment]
Please stop lie about you can't take screenshot, use https://www.i2ocr.com/ and share your screenshots as text

Which type of `remote_storage` do you use?

```
2022/05/01 09:10: 34.478122 error can't attach partitions for table 'icc.DAY FLIGHT SCHEDULE': code: 233. message: Detached part "0064ea438670602a842210d584baec92_92832_94715_94" not found
```

Could you share results of the following command?
```
ls -la /var/lib/clickhouse/backup/bak_220430/shadow/icc/DAY_FLIGHT_SCHEDULE/default/0064ea438670602a842210d584baec92_92832_94715_94
```

Are you sure  your `clickhouse-backup download bak_220430` was successful?
Could you run the following commands?

```bash
clickhouse-backup delete local bak_220430
LOG_LEVEL=debug clickhouse-backup restore_remote bak_220430 > restore_remote.log
echo $? >> restore_remote.log
```
and share restore_remote.log?

**Comment by zhanghanwei2008** [comment]
- "Which type of remote_storage do you use? "   No,I didn't, `remote_storage : none`

**Comment by zhanghanwei2008** [comment]
- "Which type of remote_storage do you use? "   No,I didn't, `remote_storage : none`   

- the following command was executed

  ```bash
  ls -la /var/lib/clickhouse/backup/bak_220430/shadow/icc/DAY_FLIGHT_SCHEDULE/default/0064ea438670602a842210d584baec92_92832_94715_94
  total 200									
  									
  drwxr-x-		―  2	root	root	4096	Apr	30	15:21 .	
  drwxr-x-		―449	root	root	40960	Apr	30	15:21 ..	
  	r—	―  5	clickhouse	clickhouse	266	Apr	28	13:55	checksums.txt
  	r—	—  5	clickhouse	clickhouse	312	Apr	28	13:55	columns.txt
  	r—	5	clickhouse	clickhouse	5	Apr	28	13:55	count.txt
  	r—	―  5	clickhouse	clickhouse	125829	Apr	28	13:55	data.bin
  	r—	―  5	clickhouse	clickhouse	2072	Apr	28	13:55	data.mrk3
  	r—	―  5	clickhouse	clickhouse	10	Apr	28	13:55	default_compressi on_codec.txt
  	r—	―  5	clickhouse	clickhouse	18	Apr	28	13:55	minmax_AFFERENT_DATE.1dx
  -r-_	r—	―  5	clickhouse	clickhouse	9	Apr	28	13:55	partition.dat
  -r--	r—	―  5	clickhouse	clickhouse	49	Aor	28	13:55	orimarv.idx
  
  
  ```

- Are you sure your `clickhouse-backup download bak_220430` was successful?  no，I didn't ` use clickhouse-backup download bak_220430` command,I had copied backup files from source CH Database server 。Then I put the files to  the path of target CH database‘s server ,The path is `/var/lib/clickhouse/backup`

- The following command was executed,But restore_remote.log is empty.

  ```bash
  clickhouse-backup delete local bak_220430
  LOG_LEVEL=debug clickhouse-backup restore_remote bak_220430 > restore_remote.log
  echo $? >> restore_remote.log

**Comment by zhanghanwei2008** [comment]
We migrate the database from the source database to the target database. We package the backup of the original ch database into a tar file. We copy the tar file to the target database server. And extract the tar file to the path of  `var\lib\clickhouse\backup` .

**Comment by Slach** [comment]
@zhanghanwei2008 is target database have the same path and name in `SELECT * FROM system.disks` as source database?

**Comment by Slach** [comment]
@zhanghanwei2008 is issue still relevant for you?

**Comment by Slach** [comment]
@zhanghanwei2008 did you run upload operation only for one server or from multiple servers with the same time?

**Comment by Slach** [comment]
@zhanghanwei2008 is issue still relevant for you?
