### ISSUE TITLE
clickhouse-backup restore --rm failed

### ISSUE THREAD

**Issue by zengxiangjiang** [Altinity/clickhouse-backup#444]
clickhouse-backup create  --tables=tz.ipfix ipfix_1

2022/05/19 17:07:04.106598  info SELECT name, engine FROM system.databases WHERE name NOT IN ('system', 'INFORMATION_SCHEMA', 'information_schema')
2022/05/19 17:07:04.109230  info SHOW CREATE DATABASE `default`
2022/05/19 17:07:04.683851  info SHOW CREATE DATABASE `tz`
2022/05/19 17:07:04.874091  info SELECT count() FROM system.settings WHERE name = 'show_table_uuid_in_table_create_query_if_not_nil'
2022/05/19 17:07:04.876524  info SELECT name FROM system.databases WHERE engine IN ('MySQL','PostgreSQL')
2022/05/19 17:07:04.880050  info
                SELECT
                        countIf(name='data_path') is_data_path_present,
                        countIf(name='data_paths') is_data_paths_present,
                        countIf(name='uuid') is_uuid_present,
                        countIf(name='create_table_query') is_create_table_query_present,
                        countIf(name='total_bytes') is_total_bytes_present
                FROM system.columns WHERE database='system' AND table='tables'

2022/05/19 17:07:04.885705  info SELECT database, name, engine , data_paths , uuid , create_table_query , coalesce(total_bytes, 0) AS total_bytes   FROM system.tables WHERE is_temporary = 0 AND match(concat(database,'.',name),'tz\.ipfix')  SETTINGS show_table_uuid_in_table_create_query_if_not_nil=1
2022/05/19 17:07:04.896740  info SELECT value FROM `system`.`build_options` where name='VERSION_INTEGER'
2022/05/19 17:07:04.898281  info SELECT * FROM system.disks;
2022/05/19 17:07:05.066582  info ALTER TABLE `tz`.`ipfix` FREEZE WITH NAME '3f5e8ca55e8447d29bb62ad06fca33e2';
2022/05/19 17:07:05.893835  info done                      backup=ipfix_1 operation=create table=tz.ipfix
2022/05/19 17:07:05.893873  info SELECT toUInt8(count()) udf_presents FROM system.columns WHERE database='system' AND table='functions' AND name='create_query'
2022/05/19 17:07:05.897510  info SELECT name, create_query FROM system.functions WHERE create_query!=''
2022/05/19 17:07:05.900589  info SELECT value FROM `system`.`build_options` where name='VERSION_DESCRIBE'
2022/05/19 17:07:05.903228  info done                      backup=ipfix_1 duration=1.799s operation=create

clickhouse-backup restore --rm --data --table=tz.ipfix  ipfix_1
2022/05/19 17:08:32.579414  info SELECT value FROM `system`.`build_options` where name='VERSION_INTEGER'
2022/05/19 17:08:32.581123  info SELECT * FROM system.disks;
2022/05/19 17:08:32.582830  info CREATE DATABASE IF NOT EXISTS default
ENGINE = Atomic
2022/05/19 17:08:32.585509  info CREATE DATABASE IF NOT EXISTS tz
ENGINE = Atomic
2022/05/19 17:08:32.984254  info SELECT count() FROM system.settings WHERE name = 'show_table_uuid_in_table_create_query_if_not_nil'
2022/05/19 17:08:32.988690  info SELECT name FROM system.databases WHERE engine IN ('MySQL','PostgreSQL')
2022/05/19 17:08:32.990281  info
                SELECT
                        countIf(name='data_path') is_data_path_present,
                        countIf(name='data_paths') is_data_paths_present,
                        countIf(name='uuid') is_uuid_present,
                        countIf(name='create_table_query') is_create_table_query_present,
                        countIf(name='total_bytes') is_total_bytes_present
                FROM system.columns WHERE database='system' AND table='tables'

2022/05/19 17:08:32.996309  info SELECT database, name, engine , data_paths , uuid , create_table_query , coalesce(total_bytes, 0) AS total_bytes   FROM system.tables WHERE is_temporary = 0 AND match(concat(database,'.',name),'tz\.ipfix')  SETTINGS show_table_uuid_in_table_create_query_if_not_nil=1
2022/05/19 17:08:33.247998  info ALTER TABLE `tz`.`ipfix` ATTACH PART 'all_18814973_23568900_104'
2022/05/19 17:08:33.907556  info ALTER TABLE `tz`.`ipfix` ATTACH PART 'all_1_18814972_900'
2022/05/19 17:08:34.665639  info ALTER TABLE `tz`.`ipfix` ATTACH PART 'all_23568901_27705316_101'
2022/05/19 17:08:35.646995  info ALTER TABLE `tz`.`ipfix` ATTACH PART 'all_27705317_28985628_115'
2022/05/19 17:08:36.607219  info ALTER TABLE `tz`.`ipfix` ATTACH PART 'all_28985629_29186633_111'
2022/05/19 17:08:38.201029  info ALTER TABLE `tz`.`ipfix` ATTACH PART 'all_29186634_29243896_84'
2022/05/19 17:08:38.707349  info ALTER TABLE `tz`.`ipfix` ATTACH PART 'all_29243897_29283343_92'
2022/05/19 17:08:39.628317  info ALTER TABLE `tz`.`ipfix` ATTACH PART 'all_29283344_29390024_87'
2022/05/19 17:08:40.741455  info ALTER TABLE `tz`.`ipfix` ATTACH PART 'all_29390025_29429019_87'
2022/05/19 17:08:40.881719  info ALTER TABLE `tz`.`ipfix` ATTACH PART 'all_29429020_29442258_70'
2022/05/19 17:08:41.088271  info ALTER TABLE `tz`.`ipfix` ATTACH PART 'all_29442259_29454608_89'
2022/05/19 17:08:41.131427  info ALTER TABLE `tz`.`ipfix` ATTACH PART 'all_29454609_29463176_82'
2022/05/19 17:08:41.295952  info ALTER TABLE `tz`.`ipfix` ATTACH PART 'all_29463177_29469581_93'
2022/05/19 17:08:41.311776  info ALTER TABLE `tz`.`ipfix` ATTACH PART 'all_29469582_29472309_75'
2022/05/19 17:08:41.391924  info ALTER TABLE `tz`.`ipfix` ATTACH PART 'all_29472310_29472466_24'
2022/05/19 17:08:41.486986  info done                      backup=ipfix_1 operation=restore table=tz.ipfix
2022/05/19 17:08:41.487672  info done                      backup=ipfix_1 duration=8.898s operation=restore
2022/05/19 17:08:41.487697  info done                      backup=ipfix_1 operation=restore

**Comment by zengxiangjiang** [comment]
The actual data is appended

**Comment by zengxiangjiang** [comment]
”IPFIX“ The actual data is appended

**Comment by zengxiangjiang** [comment]
[root@localhost ~]# clickhouse-backup -v
Version:         1.4.0
Git Commit:      e549da93400f9101ea3d88861d94fea63000acf8
Build Date:      2022-05-17

**Comment by zengxiangjiang** [comment]
[root@localhost ~]# clickhouse-server -V
ClickHouse server version 21.13.1.9250 (official build).

**Comment by Slach** [comment]
`clickhouse-backup restore --rm --table=tz.ipfix ipfix_1`
instead of
`clickhouse-backup restore --rm --data --table=tz.ipfix ipfix_1`

--rm ignored when --data used, feel free to PR for change documentation in main.go

**Comment by zengxiangjiang** [comment]
thank you
