### ISSUE TITLE
can't calculate max(bytes_on_disk): code: 47, message: Missing columns: 'data_by_disk' while processing query

### ISSUE THREAD

**Issue by kingboung** [Altinity/clickhouse-backup#454]
ClickHouse Version: 22.2.3.5
ClickHouse-Backup Version: 1.4.2
Command: create_remote --table {DATABASE}.{TABLE} --partitions {PARTITIONS} {BACKUP_NAME}

Get error message: 
` can't calculate max(bytes_on_disk): code: 47, message: Missing columns: 'data_by_disk' while processing query: 'SELECT max(data_by_disk) AS max_file_size FROM (SELECT disk_name, max(toInt64(bytes_on_disk)) FROM system.parts GROUP BY disk_name)', required columns: 'data_by_disk' 'data_by_disk' `

I checked table system.parts and there is not a column named data_by_disk exactly.

**Comment by kingboung** [comment]
I think the SQL should be
`
SELECT max(data_by_disk) AS max_file_size FROM (SELECT disk_name, max(toInt64(bytes_on_disk) AS data_by_disk) FROM system.parts GROUP BY disk_name)
`

**Comment by kingboung** [comment]
@Slach I can fix it, any permission?

**Comment by Slach** [comment]
Looks like you use `upload_by_part: false` in your configuration, as quick workaround just change from `false`  to `true`

**Comment by Slach** [comment]
try https://github.com/AlexAkulov/clickhouse-backup/releases/tag/v1.4.3
