### ISSUE TITLE
Ability to add tags to remotes backups

### ISSUE THREAD

**Issue by paolostancato** [Altinity/clickhouse-backup#458]
It would be good to be able to add tags to remote backups so, for example, we can create lifecycle policies to expire the whole chain of dependencies.

For more context: let's say we create a full backup the first day of the month and then incremental the rest. Once we expire the full backup, all the incremental ones are useless because we won't be able to reconstruct the whole chain. By tagging backups with, for example, the name of the first full backup, we can then expire the whole chain and avoid paying for useless  storage.

**Comment by Slach** [comment]
Not all remote storage types could support tags and have built-in data retention policy like S3

current implementation contains option `backups_to_keep_remote` which  respect incremental backups and don't remove full backup if it should delete by retention

**Comment by paolostancato** [comment]
Thanks for your prompt response, I'll tune that parameter then.
