### ISSUE TITLE
Ability to change clickhouse-backup path

### ISSUE THREAD

**Issue by Angel0r** [Altinity/clickhouse-backup#478]
When clickhouse-backup is run, in the end, creates a directory in /var/lib/clickhouse/backup. Since in our implementation, we use a different clickhouse path, we have "error mkdir /var/lib/clickhouse/backup: no such file or directory".

Is there any way that we can change this path? In the config.yml for example?

**Comment by Slach** [comment]
could you share your
```SELECT * FROM system.disks```

**Comment by Angel0r** [comment]
Yes!

name:            default
path:            /var/lib/clickhouse/
free_space:      38446157824
total_space:     41567858688
keep_free_space: 0
type:            local

The problem is that clickhouse is installed in docker and I want to run clickhouse-backup from VM host. So in the docker container, we have /var/lib/clickhouse which is mounted to /srv/clickhouse in the VM host.

**Comment by Slach** [comment]
use `docker run -d --name clickhouse -v /var/lib/clickhouse clickhouse/clickhouse-server:latest`
and bind your data volume to host os to the same path

clickhouse-backup need direct access to /var/lib/clickhouse which used for clickhouse-server

**Comment by Angel0r** [comment]
@Slach Shouldn't disk_mapping in the config.yml work? For example I configured like this:
`disk_mapping: {"/srv/clickhouse/backup/"}  `
but still doesn't work.

**Comment by Slach** [comment]
try to
```
disk_mapping: 
 default: /srv/clickhouse/backup
```

**Comment by Angel0r** [comment]
The clickhouse-backup create works fine but when I reinstall clickhouse and do 
`clickhouse-backup restore bckup1` I have the following error:
`error can't attach partitions for table 'db.table1': code: 233, message: Detached part "202207_0_0_0" not found
`
The same test with the same backups works fine with /var/lib/clickhouse

**Comment by Slach** [comment]
so, i already answered the question
https://github.com/AlexAkulov/clickhouse-backup/issues/478#issuecomment-1195120930
