### ISSUE TITLE
download backuptest2 which depneds on backuptest1 failed

### ISSUE THREAD

**Issue by wzisheng** [Altinity/clickhouse-backup#484]
node1:
> clickhouse-backup create --table default.test1 backuptest1
> clickhouse-backup create --table default.test1 backuptest2
> clickhouse-backup upload backuptest1
> clickhouse-backup upload backuptest2 --diff-from backuptest1

node2:
> clickhouse-backup download backuptest2
2022/07/29 18:14:57.065003 error one of Download go-routine return error: one of downloadDiffParts go-routine return error: not found on remote storage

**Comment by wzisheng** [comment]
now the problem is gone... seems it's because node2 can't get the lastest backup list as the remote.
below is my guess here

node1:
![image](https://user-images.githubusercontent.com/87692633/181743762-5a378cb2-4055-4041-a576-0ca0acda043f.png)

node2:
![image](https://user-images.githubusercontent.com/87692633/181744722-baca9aca-e8ef-4cc9-a877-d55fbf815bbc.png)


### **here's the ops timeline:**
1)node1: create & upload backuptest1
2)node1: create & upload backuptest2
3)node2: list
4)node1: delete backuptest2
5)node1: create & upload backuptest2 diff-from backuptest1
6)node2: list (still the same with step 3)

node2 cant' refresh the real backup list as node1&remote, finally i delete remote backuptest2 and then upload it again from node1, everything goes fine.

**Comment by Slach** [comment]
look like duplicate with https://github.com/AlexAkulov/clickhouse-backup/issues/470

try to use 1.4.9+ version

**Comment by wzisheng** [comment]
@Slach  sorry but i did this test with version 1.4.9-1

**Comment by Slach** [comment]
Don't worry, just try to 1.4.9 or 1.5.0, it should work, thank you in advance for reporting

Make comment if not work, i will reopen issue

**Comment by Slach** [comment]
ok. lets try to reproduce

**Comment by Slach** [comment]
doens't reproduce on my side
when you run `create & upload backuptest2` you upload full backup instead of increments
use --diff-from (or --diff-from-remote) if you want upload backup as incremental

could you share
```SHOW CREATE TABLE default.test1 ```?

**Comment by Slach** [comment]
@wzisheng issue still reproduce in your environment?

**Comment by Slach** [comment]
close issue cause issue is not reproduced and author doesn't tell anything else
