### ISSUE TITLE
Why is there no shadow or data directory generated after create? Only metadata

### ISSUE THREAD

**Issue by hellonickyangdx** [Altinity/clickhouse-backup#490]
drwxr-x--- 3 root root 4096 Aug 10 11:42 .
drwxr-x--- 3 root root 4096 Aug 10 11:42 ..
drwxr-x--- 3 root root 4096 Aug 10 11:42 metadata
-rw-r----- 1 root root  587 Aug 10 11:42 metadata.json

clickhouse-backup tables

bigo.dwm_adhoc_beans_by_country   2.46MiB    default  
bigo.dwm_adhoc_beans_by_streamer  710.53MiB  default  
bigo.dwm_adhoc_by_country         1.29MiB    default  
bigo.dwm_adhoc_by_liveroom        1.52GiB    default  
bigo.dwm_adhoc_by_streamer        473.78MiB  default

**Comment by Slach** [comment]
`clickhouse-backup` require direct access to the same /var/lib/clickhouse as `clickhouse-server`
if you use docker / docker-compose use the same volume mounts

if you try to run `clickhouse-backup` on different remote host, don't do it, run `clickhouse-backup` on the same server with `clickhouse-server` and change  /etc/clickhouse-backup/config.yml

```yaml
clickhouse:
  host: 127.0.0.1
```

**Comment by hellonickyangdx** [comment]
Thank you very much. I succeeded
