### ISSUE TITLE
Restore replicated data with error, after modify the column name or type

### ISSUE THREAD

**Issue by taotaizhu-pw** [Altinity/clickhouse-backup#491]
we update the column type in the cluster (1 share, 3 replica):  Decimal(30, 14) ---> nullable(Decimal(30, 14)), replicated partition table

steps:
1. clickhouse-backup create -c config_60191.yml pw_test_0811
2. clickhouse-backup restore -c config_1.yml --rm -s pw_test_0811
3. clickhouse-backup restore -c config_2.yml --rm -s pw_test_0811
4. clickhouse-backup restore -c config.yml -d pw_test_0811

error can't attach partitions for table 'chdb.dwd_mkt_stock': code: 53, message: Type mismatch for column PE_TTM. Column has type Nullable(Decimal(30, 14)), got type Decimal(30, 14)

And we found it works fine with no replicated table.

**Comment by Slach** [comment]
why do you use different configs for backup and restore?
which differences between these configs?

**Comment by Slach** [comment]
Why do you run `restore --rm --schema` twice?

**Comment by taotaizhu-pw** [comment]
> Why do you run `restore --rm --schema` twice?

it should be 3 config files. each file point to one node:

config1.yml:

   clickhouse:
      username: test
      password: test
      host: chserver1
      port: 9000

config2.yml:

   clickhouse:
      username: test
      password: test
      host: chserver2
      port: 9000

config2.yml:

   clickhouse:
      username: test
      password: test
      host: chserver2
      port: 9000


steps:

   1.  clickhouse-backup create -c config_1.yml pw_test_0811
   2. clickhouse-backup restore -c config_1.yml --rm -s pw_test_0811
   3. clickhouse-backup restore -c config_2.yml --rm -s pw_test_0811
   4. clickhouse-backup restore -c config_3.yml --rm -s pw_test_0811
   5.  clickhouse-backup restore -c config.yml -d pw_test_0811

**Comment by taotaizhu-pw** [comment]
> Why do you run `restore --rm --schema` twice?

I used 3 commonds to recreate tables for three cluster nodes. Is it correct?

**Comment by Slach** [comment]
Do you run your steps in the same server or on the different hosts?
remote hosts to clickhouse connection will not work
because `clickhouse-backup` need direct access to the same /var/lib/clickhouse/ as `clickhouse-server`

**Comment by taotaizhu-pw** [comment]
> un your steps in the same server or on the different hosts?

The three servers have the same structure.  I executed my steps in the same server.  I used 3 config files to create the tables remote success. And then insert into the data into local server, the data would be synchronized to the other two nodes.

Is it correct with my steps? what is the correct step to backup the replicated database? thanks!

**Comment by taotaizhu-pw** [comment]
> Do you run your steps in the same server or on the different hosts? remote hosts to clickhouse connection will not work because `clickhouse-backup` need direct access to the same /var/lib/clickhouse/ as `clickhouse-server`

The three servers have the same structure. I executed my steps in the same server. I used 3 config files to create the tables remote success. And then insert into the data into local server, the data would be synchronized to the other two nodes.

Is it correct with my steps? 
what is the correct steps to backup the replicated cluster database? thanks!

**Comment by taotaizhu-pw** [comment]
I found the reason, after "alter table modify column", need to optimize, then do backup

**Comment by Slach** [comment]
> Is it correct with my steps?

Yes, your steps are correct, you can restore schema on remote servers  and restore data on local server

> I found the reason, after "alter table modify column", need to optimize, then do backup

great, glad to see it

Thank you so much for reporting, maybe we need to add it to Readme.md in restriction section, could you make PR?
