### ISSUE TITLE
API Server add an http api for updating configuration files?

### ISSUE THREAD

**Issue by Fkylwj** [Altinity/clickhouse-backup#495]
I need to use clickhouse-backup as an http api server to back up data on the ftp server. 
Since the ftp-related configuration may need to be changed, can I submit a PR to add an http interface to update the configuration file?

**Comment by Slach** [comment]
`clickhouse-backup server` reload config every time when you try to execute command
so just change your config on the disk and it will apply automatically when next command will executed via API
