### ISSUE TITLE
error can't attach partitions for table 'foo.bar': code: 233, message: Detached part "all_1_1_0" not found

### ISSUE THREAD

**Issue by empeekdev** [Altinity/clickhouse-backup#496]
Hi, we have ClickHouse cluster in K8s backed up with clickhouse-backup tool using this doc https://github.com/AlexAkulov/clickhouse-backup/blob/master/Examples.md#how-to-use-clickhouse-backup-in-kubernetes
Backup are stored on remote s3 storage. During restore process it fails with the following error:
```
2022/08/16 08:50:12.020988  info ALTER TABLE `epe`.`AMI` ATTACH PART 'all_1_1_0'
2022/08/16 08:50:12.029186 error can't attach partitions for table 'epe.AMI': code: 233, message: Detached part "all_1_1_0" not found
```

Clickhouse version: 
`altinity/clickhouse-server:21.3.20.2.altinitystable`
Clickhouse-backup tool version:
```
Version:         f67d23fd3b775f887683d3d3fdea1b1500419987
Git Commit:      f67d23fd3b775f887683d3d3fdea1b1500419987
Build Date:      2022-08-08
```

print-config output:
```
general:
  remote_storage: s3
  max_file_size: 0
  disable_progress_bar: true
  backups_to_keep_local: 0
  backups_to_keep_remote: 0
  log_level: info
  allow_empty_backups: false
  download_concurrency: 4
  upload_concurrency: 4
  restore_schema_on_cluster: ""
  upload_by_part: true
  download_by_part: true
clickhouse:
  username: user
  password: password
  host: foo.bar.com
  port: 30538
  disk_mapping: {}
  skip_tables:
  - system.*
  - INFORMATION_SCHEMA.*
  - information_schema.*
  timeout: 5m
  freeze_by_part: true
  freeze_by_part_where: ""
  secure: false
  skip_verify: false
  sync_replicated_tables: false
  log_sql_queries: true
  config_dir: /etc/clickhouse-server/
  restart_command: systemctl restart clickhouse-server
  ignore_not_exists_error_during_freeze: true
  check_replicas_before_attach: true
  tls_key: ""
  tls_cert: ""
  tls_ca: ""
  debug: false
s3:
  access_key: *****
  secret_key: +****
  bucket: s3bucketname
  endpoint: s3.amazonaws.com
  region: us-east-2
  acl: private
  assume_role_arn: ""
  force_path_style: false
  path: clickhouse/foo.bar.com
  disable_ssl: false
  compression_level: 1
  compression_format: tar
  sse: ""
  disable_cert_verification: false
  use_custom_storage_class: false
  storage_class: STANDARD
  concurrency: 1
  part_size: 0
  max_parts_count: 10000
  allow_multipart_download: false
  debug: false
gcs:
  credentials_file: ""
  credentials_json: ""
  bucket: ""
  path: ""
  compression_level: 1
  compression_format: tar
  debug: false
  endpoint: ""
cos:
  url: ""
  timeout: 2m
  secret_id: ""
  secret_key: ""
  path: ""
  compression_format: tar
  compression_level: 1
  debug: false
api:
  listen: localhost:7171
  enable_metrics: true
  enable_pprof: false
  username: ""
  password: ""
  secure: false
  certificate_file: ""
  private_key_file: ""
  create_integration_tables: false
  integration_tables_host: ""
  allow_parallel: false
ftp:
  address: ""
  timeout: 2m
  username: ""
  password: ""
  tls: false
  path: ""
  compression_format: tar
  compression_level: 1
  concurrency: 4
  debug: false
sftp:
  address: ""
  port: 22
  username: ""
  password: ""
  key: ""
  path: ""
  compression_format: tar
  compression_level: 1
  concurrency: 1
  debug: false
azblob:
  endpoint_suffix: core.windows.net
  account_name: ""
  account_key: ""
  sas: ""
  use_managed_identity: false
  container: ""
  path: ""
  compression_level: 1
  compression_format: tar
  sse_key: ""
  buffer_size: 0
  buffer_count: 3
  max_parts_count: 10000
  timeout: 15m
```

I have tried to use `freeze_by_part: true` as it mentioned in other isses, but it still failing, also no custom path for mapping data to volume was used.

**Comment by Slach** [comment]
sorry for late response

could you share your clickhouse-backup container log
for `upload` command?

your config contains
```yaml
api:
  create_integration_tables: false
```

are you sure environment variable which described in the following link https://github.com/AlexAkulov/clickhouse-backup/blob/master/Examples.md#how-to-use-clickhouse-backup-in-kubernetes was applied?

```yaml
  - name: API_CREATE_INTEGRATION_TABLES
    value: "true"
```

could run clickhouse-client inside clickhouse-pod container and share results for the following query?
```
SELECT * FROM cluster('all-sharded',system.backup_actions)
```

**Comment by empeekdev** [comment]
Hi @Slach , thx for your response 

> sorry for late response
> 
> could you share your clickhouse-backup container log for `upload` command?
> 

I suppose this is what you asking for:
[clickhouse-backup-upload.log](https://github.com/AlexAkulov/clickhouse-backup/files/9438536/clickhouse-backup-upload.log)

> are you sure environment variable which described in the following link https://github.com/AlexAkulov/clickhouse-backup/blob/master/Examples.md#how-to-use-clickhouse-backup-in-kubernetes was applied?
> 
> ```yaml
>   - name: API_CREATE_INTEGRATION_TABLES
>     value: "true"
> ```

Yes, that environment is applied for backups.


> could run clickhouse-client inside clickhouse-pod container and share results for the following query?
> 
> ```
> SELECT * FROM cluster('all-sharded',system.backup_actions)
> ```

result:

```
SELECT *
FROM cluster('all-sharded', system.backup_actions)

Query id: 5d4f7320-01d9-47fa-88b1-03ebdda77fc1

┌─command───────────────────────────────────────────────────────────────┬───────────────start─┬──────────────finish─┬─status──┬─error─┐
│ create chi-epe-clickhouse-epe-clickhouse-0-0-full-2022-08-15-14-38-48 │ 2022-08-15 14:38:48 │ 2022-08-15 14:38:50 │ success │       │
│ upload chi-epe-clickhouse-epe-clickhouse-0-0-full-2022-08-15-14-38-48 │ 2022-08-15 14:38:51 │ 2022-08-15 15:13:17 │ success │       │
│ create chi-epe-clickhouse-epe-clickhouse-0-0-full-2022-08-16-00-00-21 │ 2022-08-16 00:00:21 │ 2022-08-16 00:00:24 │ success │       │
│ upload chi-epe-clickhouse-epe-clickhouse-0-0-full-2022-08-16-00-00-21 │ 2022-08-16 00:00:24 │ 2022-08-16 00:36:27 │ success │       │
│ create chi-epe-clickhouse-epe-clickhouse-0-0-full-2022-08-17-00-00-01 │ 2022-08-17 00:00:01 │ 2022-08-17 00:00:05 │ success │       │
│ upload chi-epe-clickhouse-epe-clickhouse-0-0-full-2022-08-17-00-00-01 │ 2022-08-17 00:00:06 │ 2022-08-17 00:37:49 │ success │       │
│ create chi-epe-clickhouse-epe-clickhouse-0-0-full-2022-08-18-00-00-01 │ 2022-08-18 00:00:01 │ 2022-08-18 00:00:05 │ success │       │
│ upload chi-epe-clickhouse-epe-clickhouse-0-0-full-2022-08-18-00-00-01 │ 2022-08-18 00:00:06 │ 2022-08-18 00:37:19 │ success │       │
│ create chi-epe-clickhouse-epe-clickhouse-0-0-full-2022-08-19-00-00-01 │ 2022-08-19 00:00:01 │ 2022-08-19 00:00:05 │ success │       │
│ upload chi-epe-clickhouse-epe-clickhouse-0-0-full-2022-08-19-00-00-01 │ 2022-08-19 00:00:06 │ 2022-08-19 00:41:44 │ success │       │
│ create chi-epe-clickhouse-epe-clickhouse-0-0-full-2022-08-20-00-00-01 │ 2022-08-20 00:00:01 │ 2022-08-20 00:00:05 │ success │       │
│ upload chi-epe-clickhouse-epe-clickhouse-0-0-full-2022-08-20-00-00-01 │ 2022-08-20 00:00:06 │ 2022-08-20 00:41:39 │ success │       │
│ create chi-epe-clickhouse-epe-clickhouse-0-0-full-2022-08-21-00-00-01 │ 2022-08-21 00:00:01 │ 2022-08-21 00:00:05 │ success │       │
│ upload chi-epe-clickhouse-epe-clickhouse-0-0-full-2022-08-21-00-00-01 │ 2022-08-21 00:00:06 │ 2022-08-21 00:39:50 │ success │       │
│ create chi-epe-clickhouse-epe-clickhouse-0-0-full-2022-08-22-00-00-01 │ 2022-08-22 00:00:01 │ 2022-08-22 00:00:04 │ success │       │
│ upload chi-epe-clickhouse-epe-clickhouse-0-0-full-2022-08-22-00-00-01 │ 2022-08-22 00:00:06 │ 2022-08-22 00:38:49 │ success │       │
│ create chi-epe-clickhouse-epe-clickhouse-0-0-full-2022-08-23-00-00-01 │ 2022-08-23 00:00:01 │ 2022-08-23 00:00:04 │ success │       │
│ upload chi-epe-clickhouse-epe-clickhouse-0-0-full-2022-08-23-00-00-01 │ 2022-08-23 00:00:05 │ 2022-08-23 00:43:34 │ success │       │
│ create chi-epe-clickhouse-epe-clickhouse-0-0-full-2022-08-24-00-00-22 │ 2022-08-24 00:00:22 │ 2022-08-24 00:00:26 │ success │       │
│ upload chi-epe-clickhouse-epe-clickhouse-0-0-full-2022-08-24-00-00-22 │ 2022-08-24 00:00:27 │ 2022-08-24 00:43:56 │ success │       │
│ create chi-epe-clickhouse-epe-clickhouse-0-0-full-2022-08-25-00-00-01 │ 2022-08-25 00:00:01 │ 2022-08-25 00:00:04 │ success │       │
│ upload chi-epe-clickhouse-epe-clickhouse-0-0-full-2022-08-25-00-00-01 │ 2022-08-25 00:00:06 │ 2022-08-25 00:43:21 │ success │       │
│ create chi-epe-clickhouse-epe-clickhouse-0-0-full-2022-08-26-00-00-01 │ 2022-08-26 00:00:01 │ 2022-08-26 00:00:05 │ success │       │
│ upload chi-epe-clickhouse-epe-clickhouse-0-0-full-2022-08-26-00-00-01 │ 2022-08-26 00:00:06 │ 2022-08-26 00:43:11 │ success │       │
│ create chi-epe-clickhouse-epe-clickhouse-0-0-full-2022-08-27-00-00-01 │ 2022-08-27 00:00:01 │ 2022-08-27 00:00:05 │ success │       │
│ upload chi-epe-clickhouse-epe-clickhouse-0-0-full-2022-08-27-00-00-01 │ 2022-08-27 00:00:06 │ 2022-08-27 00:41:38 │ success │       │
└───────────────────────────────────────────────────────────────────────┴─────────────────────┴─────────────────────┴─────────┴───────┘

26 rows in set. Elapsed: 0.017 sec. 
```

**Comment by Slach** [comment]
could you provide more context, where you try to restore your backup?
this is the different kuberenetes `chi` or same `chi` where you create backup or standalone server without kubernetes?

**Comment by empeekdev** [comment]
This is different Kubernetes chi in the same cluster and the same namespace

**Comment by Slach** [comment]
ok.  do you try to restore in each replicas inside shards in parallel?

**Comment by empeekdev** [comment]
despite the fact ClickHouse is in Kubernetes cluster, it’s not sharded. There is only one instance of clickhouse

**Comment by Slach** [comment]
According to your `system.backup_actions` I would like recommends adding to your command sequence `delete local <backup-name>` to avoid useless disk space allocation
call it only after `upload` command `success`

Moreover, looks wierd
your print-config show 
s3:
 debug: false
 
but shared upload logs is not full and contain output with `S3_DEBUG=true`

only one backup you can't restore? on all other backups also can't be restored?

how do you try to restore?
do you execute INSERT INTO system.backup_actions ? or other way?

**Comment by empeekdev** [comment]
@Slach 
> Moreover, looks wierd your print-config show s3: debug: false
> 
> but shared upload logs is not full and contain output with `S3_DEBUG=true`

You are right, reason of this thing is the logs I send you are from clickhouse backup container and that container has `S3_DEBUG=true` enabled.  

> only one backup you can't restore? on all other backups also can't be restored?

I can’t restore any of them.

> how do you try to restore?
> do you execute INSERT INTO system.backup_actions ? or other way?

I’m running this command:

`sudo docker run --name clickhouse-b -e CLICKHOUSE_USERNAME=foo -e CLICKHOUSE_PASSWORD=bar -e CLICKHOUSE_HOST=foobar.com -e CLICKHOUSE_PORT=31790 -e S3_BUCKET=s3bucket -e S3_PATH="clickhouse/foobar.com" -e S3_ENDPOINT=s3.amazonaws.com -e S3_ACCESS_KEY=*** -e S3_SECRET_KEY="***" -e S3_REGION=us-east-2 -e REMOTE_STORAGE=s3 -e S3_ALLOW_MULTIPART_DOWNLOAD=true -e API_CREATE_INTEGRATION_TABLES=true --rm altinity/clickhouse-backup:master restore_remote chi-epe-clickhouse-epe-clickhouse-0-0-full-2022-08-27-00-00-01`

**Comment by Slach** [comment]
> sudo docker run --name clickhouse-b -e CLICKHOUSE_USERNAME=foo -e CLICKHOUSE_PASSWORD=bar -e CLICKHOUSE_HOST=foobar.com -e CLICKHOUSE_PORT=31790 -e S3_BUCKET=s3bucket -e S3_PATH="clickhouse/foobar.com" -e S3_ENDPOINT=s3.amazonaws.com -e S3_ACCESS_KEY=*** -e S3_SECRET_KEY="***" -e S3_REGION=us-east-2 -e REMOTE_STORAGE=s3 -e S3_ALLOW_MULTIPART_DOWNLOAD=true -e API_CREATE_INTEGRATION_TABLES=true --rm altinity/clickhouse-backup:master restore_remote chi-epe-clickhouse-epe-clickhouse-0-0-full-2022-08-27-00-00-01


ok we found root reason, you need use clickhouse-backup which have direct access to the same /var/lib/clickhouse as destination server, it required during `ALTER TABLE ... ATTACH PART ...` because data will attach from local `clickhouse-server` disks

so `docker run CLICKHOUSE_HOST=XXX` is wrong way

add `clickhouse-backup` container into your destination `kind: ClickHouseInstallation` manifest
and use 
```bash
kubectl exec -n <dst_ns> <dst_clickhouse_pod> -c clickhouse-backup -- bash -c 'S3_BUCKET=s3bucket S3_PATH="clickhouse/foobar.com" S3_ENDPOINT=s3.amazonaws.com S3_ACCESS_KEY=*** S3_SECRET_KEY="***" S3_REGION=us-east-2  REMOTE_STORAGE=s3  S3_ALLOW_MULTIPART_DOWNLOAD=true clickhouse-backup restore_remote chi-epe-clickhouse-epe-clickhouse-0-0-full-2022-08-27-00-00-01'
```
