### ISSUE TITLE
allow to GCP JSON access credentials Base64 encoded

### ISSUE THREAD

**Issue by navi86** [Altinity/clickhouse-backup#498]
Hello, I am trying to create backup to remote google storage bucket.
My config is
```
  - name: REMOTE_STORAGE
     value: "gcs"
  - name: GCS_BUCKET
     value: "bucket-name"
  - name: GCS_PATH
     value: "clickhouse"
  - name: GCS_DEBUG
     value: "true"
  - name: GCS_CREDENTIALS_JSON
     value: "base64 encoded string that contains credentials json data"
```
however, I am getting error 
`error	can\'t connect to GCS: googleHTTPTransport.NewClient error: invalid character \'e\' looking for beginning of value`
I believe that I passing wrong values in "GCS_CREDENTIALS_JSON". How can I fix it ?

**Comment by Slach** [comment]
i propose to use
```yaml
  - name: GCS_CREDENTIALS_JSON
    value: |
       JSON without base64 encoding
```     
look to https://github.com/AlexAkulov/clickhouse-backup/search?q=QA_GCS_CRED_JSON for details

**Comment by datavisorzhizhu** [comment]
@navi86 please refer to this article https://mitchum.blog/how-to-store-json-in-an-environment-variable/
for how to pass json content as base64 encoded string

**Comment by navi86** [comment]
@datavisorzhizhu 
it's not support encoded string
