### ISSUE TITLE
v1.6.2 docker image's storage size: 968MB, v1.6.1 docker image's storage size: 55.8MB

### ISSUE THREAD

**Issue by kingboung** [Altinity/clickhouse-backup#507]
Hello,
![image](https://user-images.githubusercontent.com/22000541/188048920-ec5b1edd-9387-40d8-9ba0-06d739134153.png)
Please help explain the amazing difference

**Comment by Slach** [comment]
we plan to use clickhouse-local for some external CLI utilities integrations for upload \ download which we plan release in v2
in 1.6.3 we will release two separate images
clickhouse-backup:1.6.3-full ubuntu based from clickhouse/clickhouse-server
clickhouse-backup:1.6.3 return alpine based image without any integration

**Comment by Slach** [comment]
feel free to make PR for proper Dockerfile

**Comment by kingboung** [comment]
Does the larger image provide more features than the other one?

**Comment by Slach** [comment]
for v2 it will provide clickhouse-local, rsync, kopia and restic to alllow `remote_storage: custom` integrations

**Comment by Slach** [comment]
moreover, according to

https://hub.docker.com/r/altinity/clickhouse-backup/tags
https://hub.docker.com/r/alexakulov/clickhouse-backup/tags

images size is 300Mb not 900Mb

**Comment by Slach** [comment]
maybe, after extract image size looks bigger
