### ISSUE TITLE
Backups only metadata (want all)

### ISSUE THREAD

**Issue by amatsumara** [Altinity/clickhouse-backup#511]
Trying to do backups as described in https://github.com/AlexAkulov/clickhouse-backup/blob/master/Examples.md#how-to-use-clickhouse-backup-in-kubernetes but for some reason it backups only metadata:
```
clickhouse-backup list | tail -n2
2022-09-05T14-28-31   73.71KiB   05/09/2022 14:28:47   local       
2022-09-05T14-28-31   73.71KiB   05/09/2022 14:29:03   remote      tar, regular
```
While a single table is megabytes in size. In backup itself I can see only metadata dir. Am I missing something?

**Comment by Slach** [comment]
`clickhouse-backup` require the direct access to the same /var/lib/clickhouse with `clickhouse-server`
sorry, we miss `spec.templates.volumeClaimTemplates` and `spec.defaults.templates.dataVolumeClaimTemplate` definitions in Example

**Comment by Slach** [comment]
look https://github.com/AlexAkulov/clickhouse-backup/blob/master/Examples.md#how-to-use-clickhouse-backup-in-kubernetes again
or https://github.com/AlexAkulov/clickhouse-backup/commit/2280a773bdccad3436f2e2e43ff9dab0fbe3304a for differences details
