### ISSUE TITLE
Clickhouse-backup restores empty databases

### ISSUE THREAD

**Issue by amatsumara** [Altinity/clickhouse-backup#513]
Looks like I have another novice issue. Asked help on https://stackoverflow.com/questions/73641416/clickhouse-backup-restore-empty-databases but looks like no one knows the answer. Will just copy it here:

Trying to setup clickhouse-backup in k8s (GCS storage) according to this manual https://github.com/AlexAkulov/clickhouse-backup/blob/master/Examples.md#how-to-use-clickhouse-backup-in-kubernetes

All look good to me but when I decided to wipe & restore to test - restore doesn't work.

Remote look like this:
```
clickhouse-backup list
2022-09-05T14-28-31   73.71KiB    05/09/2022 14:29:03   remote      tar, regular
2022-09-05T23-47-29   541.83MiB   05/09/2022 23:48:46   remote      tar, regular
2022-09-06T20-43-43   52.16MiB    06/09/2022 20:44:15   remote      tar, regular
```
First 73.71KiB backup was made with wrong setup and was backing up only metadata (no full access to /var/lib/clickhouse).

Then I try this sequence of commands described in the same doc https://github.com/AlexAkulov/clickhouse-backup/blob/master/Examples.md#restore

My clickhouse configuration shardsCount: 1, replicasCount: 5

So I connect to pods and do
All replicas
```
clickhouse-backup restore_remote --rm --schema 2022-09-05T23-47-29
clickhouse-backup delete local 2022-09-05T23-47-29
```
1st replica
```
clickhouse-backup restore_remote --rm 2022-09-05T23-47-29
clickhouse-backup delete local 2022-09-05T23-47-29
```
Then a number of warning like this arise:
```
2022/09/07 20:34:20.890442  info CREATE TABLE foo.bar (`project` String, `taskId` String, `addedAt` Nullable(DateTime('Europe/Copenhagen')), `metadata` String, `userId` String, `domain` String) ENGINE = ReplicatedMergeTree('/clickhouse/{installation}/{cluster}/tables/{shard}/foo/bar', '{replica}') PARTITION BY project ORDER BY (domain, project) SETTINGS index_granularity = 8192
2022/09/07 20:34:21.016010  warn can't create table 'foo.bar': code: 253, message: Replica /clickhouse/clickhouse/app-staging/tables/0/foo/bar/replicas/chi-clickhouse-app-staging-0-2 already exists, will try again backup=2022-09-05T23-47-29 operation=restore
```

`clickhouse-backup tables` shows a number of 0B tables.

I'm not the person who created all the tables but I guess they worked fine before I started experimenting with backups. Would be nice to know what I'm missing.

**Comment by Slach** [comment]
maybe you have multiple tables with the same ReplicatedMergeTree path?

```sql
SELECT database, name, engine_full FROM system.tables WHERE engine_full ILIKE '%/clickhouse/{installation}/{cluster}/tables/{shard}/foo/bar%'
```

**Comment by amatsumara** [comment]
I connected to 0-0 instance /play. This returns no rows (replaced actual names with foo-bar):
```SQL
SELECT database, name, engine_full FROM system.tables WHERE engine_full ILIKE '%/clickhouse/{installation}/{cluster}/tables/{shard}/foo/bar%'
```
Then I try to run commands from restore log manually:
`CREATE DATABASE IF NOT EXISTS foo`
`Ok.`
```SQL
CREATE TABLE foo.bar (`project` String, `taskId` String, `addedAt` Nullable(DateTime('Europe/Copenhagen')), `metadata` String, `userId` String, `domain` String) ENGINE = ReplicatedMergeTree('/clickhouse/{installation}/{cluster}/tables/{shard}/foo/bar', '{replica}') PARTITION BY project ORDER 
BY (domain, project) SETTINGS index_granularity = 8192
```
```
Code: 253. DB::Exception: Replica /clickhouse/clickhouse/app-staging/tables/0/foo/bar/replicas/chi-clickhouse-app-staging-0-0 already exists. (REPLICA_IS_ALREADY_EXIST) (version 22.4.5.9 (official build))
```

```SQL
select * from foo.bar limit 1
```
```
Code: 60. DB::Exception: Table foo.bar doesn't exist. (UNKNOWN_TABLE) (version 22.4.5.9 (official build))
```

**Comment by Slach** [comment]
looks weird
when you apply --rm --schema
it shall call DROP TABLE IF EXISTS... NO DELAY
and it shall clear replica in Zookeeper

Do you have another clickhouse cluster which use the same zookeeper server?

**Comment by amatsumara** [comment]
We have several clickhouse clusters including sandbox I created but all of them in their own k8s namespace and use own zookeeper. While experimenting with clickhouse image versions I noticed in 22.8 that Ordinary DB Engine deprecated:
```
2022/09/12 20:50:07.843493  info CREATE DATABASE IF NOT EXISTS `foo` ENGINE = Ordinary with args [[]]
2022/09/12 20:50:07.861576 error code: 336, message: Ordinary database engine is deprecated (see also allow_deprecated_database_ordinary setting)
```
So I downgraded back to 22.4.5.9:
```
2022/09/26 10:21:12.902185  info CREATE DATABASE IF NOT EXISTS `foo` ENGINE = Ordinary with args [[]]
2022/09/26 10:21:12.911495  info SELECT engine FROM system.databases WHERE name = 'foo'                                                                       2022/09/26 10:21:12.917433  info DROP TABLE IF EXISTS `foo`.`bar`
2022/09/26 10:21:12.989632  info CREATE DATABASE IF NOT EXISTS `foo`
2022/09/26 10:21:12.994865  info CREATE TABLE foo.bar (`project` String, `taskId` String, `addedAt` Nullable(DateTime('Europe/Copenhagen')), `metadata` String, `userId` String, `domain` String) ENGINE = ReplicatedMergeTree('/clickhouse/{installation}/{cluster}/tables/{shard}/foo/bar', '{replica}') P
ARTITION BY project ORDER BY (domain, project) SETTINGS index_granularity = 8192                                                                                     2022/09/26 10:21:13.001523  warn can't create table 'foo.bar': code: 81, message: Database foo doesn't exist, will try again backup=prod1 operation=restore
```
First I was trying to restore staging where developers experiment but they have a number of databases with the same set of tables. Now I'm trying to backup prod to GCS and restore it in my sandbox so only one DB and one set of tables.

**Comment by Slach** [comment]
> error code: 336, message: Ordinary database engine is deprecated (see also allow_deprecated_database_ordinary setting)


Add  to your `chi` manifest

```yaml
spec:
  configuration:
     allow_deprecated_database_ordinary: 1
```

**Comment by sliontc** [comment]
> > error code: 336, message: Ordinary database engine is deprecated (see also allow_deprecated_database_ordinary setting)
> 
> Add to your `chi` manifest
> 
> ```yaml
> spec:
>   configuration:
>      allow_deprecated_database_ordinary: 1
> ```
Hi, where should I set this config? In the config.yaml?

**Comment by Slach** [comment]
> Hi, where should I set this config? In the config.yaml?


@sliontc, this is part of kubernetes `kind: ClickHouseIntalation`

if you don't use kubernetes and clickhouse-operator
then use
`/etc/clickhouse-server/config.d/allow_deprecated_database_ordinary.xml`
with following content
```xml
<clickhouse><allow_deprecated_database_ordinary>1</allow_deprecated_database_ordinary></clickhouse>
```
