### ISSUE TITLE
backup only metadata

### ISSUE THREAD

**Issue by hbzhu** [Altinity/clickhouse-backup#518]
clickhouse backup data directory mount NFS ，“ 192.168.*.*:/volume1/clickhouse-bak     /data/backup  nfs     defaults      0 0 ”，
when I used clickhouse-backup create ，the result is only metadata & metadata.json，not store

**Comment by Slach** [comment]
Your local backup will create as file system hard links to exists data and don't allocate disk space 

You need to run `clickhouse-backup` with direct access same disk where run `clickhouse-server` it required by `ALTER TABLE ... FREEZE`
local backup dir can't be NFS
look to 
```SELECT * FROM system.disks```
to check where data will stored
for example default disk is /var/lib/clickhouse then backup will create hardlinks in /var/lib/clickhouse/backup/backup_name/
after create backup, you can use rsync to move data to your nfs folder
look to 
https://github.com/AlexAkulov/clickhouse-backup/tree/master/test/integration/rsync
https://github.com/AlexAkulov/clickhouse-backup/blob/master/test/integration/config-custom-rsync.yml
for examples
