### ISSUE TITLE
error can't attach partitions for table 'smartxxxx.xx': code: 233, message: Detached part "all_0_0_0" not found

### ISSUE THREAD

**Issue by luugh** [Altinity/clickhouse-backup#519]
When I use this tool, there is always a prompt that the detached part cannot be found, but it exists when I look in the data directory

`2022/09/22 18:46:10.495189 debug MkDirAll /var/lib/clickhouse/store/e80/e8007ba1-1a7d-4de5-b724-6d753e564574/detached/all_0_0_0 operation=CopyDataToDetached
2022/09/22 18:46:10.495310 debug MkDir /var/lib/clickhouse/store/e80/e8007ba1-1a7d-4de5-b724-6d753e564574/detached/all_0_0_0 operation=CopyDataToDetached
2022/09/22 18:46:10.495334 debug Link /var/lib/clickhouse/backup/2022-09-22T09-54-03/shadow/smartx_car/ehiairportcode/default/all_0_0_0/checksums.txt -> /var/lib/clickhouse/store/e80/e8007ba1-1a7d-4de5-b724-6d753e564574/detached/all_0_0_0/checksums.txt operation=CopyDataToDetached
2022/09/22 18:46:10.495366 debug Link /var/lib/clickhouse/backup/2022-09-22T09-54-03/shadow/smartx_car/ehiairportcode/default/all_0_0_0/columns.txt -> /var/lib/clickhouse/store/e80/e8007ba1-1a7d-4de5-b724-6d753e564574/detached/all_0_0_0/columns.txt operation=CopyDataToDetached
2022/09/22 18:46:10.495398 debug Link /var/lib/clickhouse/backup/2022-09-22T09-54-03/shadow/smartx_car/ehiairportcode/default/all_0_0_0/count.txt -> /var/lib/clickhouse/store/e80/e8007ba1-1a7d-4de5-b724-6d753e564574/detached/all_0_0_0/count.txt operation=CopyDataToDetached
2022/09/22 18:46:10.495432 debug Link /var/lib/clickhouse/backup/2022-09-22T09-54-03/shadow/smartx_car/ehiairportcode/default/all_0_0_0/data.bin -> /var/lib/clickhouse/store/e80/e8007ba1-1a7d-4de5-b724-6d753e564574/detached/all_0_0_0/data.bin operation=CopyDataToDetached
2022/09/22 18:46:10.495476 debug Link /var/lib/clickhouse/backup/2022-09-22T09-54-03/shadow/smartx_car/ehiairportcode/default/all_0_0_0/data.mrk3 -> /var/lib/clickhouse/store/e80/e8007ba1-1a7d-4de5-b724-6d753e564574/detached/all_0_0_0/data.mrk3 operation=CopyDataToDetached
2022/09/22 18:46:10.495505 debug Link /var/lib/clickhouse/backup/2022-09-22T09-54-03/shadow/smartx_car/ehiairportcode/default/all_0_0_0/default_compression_codec.txt -> /var/lib/clickhouse/store/e80/e8007ba1-1a7d-4de5-b724-6d753e564574/detached/all_0_0_0/default_compression_codec.txt operation=CopyDataToDetached
2022/09/22 18:46:10.495529 debug Link /var/lib/clickhouse/backup/2022-09-22T09-54-03/shadow/smartx_car/ehiairportcode/default/all_0_0_0/primary.idx -> /var/lib/clickhouse/store/e80/e8007ba1-1a7d-4de5-b724-6d753e564574/detached/all_0_0_0/primary.idx operation=CopyDataToDetached
2022/09/22 18:46:10.495545 debug done                      duration=0s operation=CopyDataToDetached
2022/09/22 18:46:10.495572 debug copied data to 'detached' backup=2022-09-22T09-54-03 operation=restore table=smartx_car.ehiairportcode
2022/09/22 18:46:10.495611  info SELECT sum(log_pointer + log_max_index + absolute_delay + queue_size)  AS replication_in_progress FROM system.replicas WHERE database=? and table=? SETTINGS empty_result_for_aggregation_by_empty_set=0 with args [smartx_car ehiairportcode]
2022/09/22 18:46:10.529488  info replication_in_progress status = [0]
2022/09/22 18:46:10.529521  info ALTER TABLE `smartx_car`.`ehiairportcode` ATTACH PART 'all_0_0_0'
2022/09/22 18:46:10.538115 error can't attach partitions for table 'smartx_car.ehiairportcode': code: 233, message: Detached part "all_0_0_0" not found
`

**Comment by luugh** [comment]
root@clickhouse-2:/# clickhouse-backup -v
Version:         2.0.0
Git Commit:      93f6c2f168b63db4ab7c8cd51fcc317884752b84
Build Date:      2022-09-04

**Comment by luugh** [comment]
Now I get no error when I test using the -t parameter to perform a single table restore, I don't know why

**Comment by Slach** [comment]
Do you try to restore in multiple servers in parallel?

**Comment by luugh** [comment]
No, I want to do data migration, and migrate the data from the old cluster to the new cluster. I backed up the data in the old cluster and uploaded it to s3, and used the same config.yml to perform recovery in the new cluster, but it always prompts me: error can't attach partitions for table 'smartx_car.ehiairportcode': code : 233, message: Detached part "all_0_0_0" not found, I went to the data directory to check, this part exists, and it can also be attached directly in the database. Now I use -t to restore a single table, and this error will also be prompted.

**Comment by luugh** [comment]
> Do you try to restore in multiple servers in parallel?

How to judge that it is parallel recovery in multiple servers, is there any parameter to prohibit it?

**Comment by luugh** [comment]
> Do you try to restore in multiple servers in parallel?

Thanks for the tip, I found the problem. I used the headless address without specifying the pod, all of which are indeed in line with what you said about restore in multiple servers in parallel. After I modified the host, it could be restored normally. thank you very much

**Comment by Slach** [comment]
Glad to know it
Would you kindly clarify which address exactly you change?

Do you mean `host` in clickhouse section of clickhouse backup config?
It usually shall 127.0.0.1, clickhouse-backup always need direct access to the same disks which used for clickhouse-server Unfortunately, I can't hard-code it because we can have use cases when need restore only schema on remote clickhouse-server.

> How to judge that it is parallel recovery in multiple servers, is there any parameter to prohibit it?

It was just Assumption
`check_replicas_before_attach` shall to avoid concurrent ATTACH PART on multiple replicas during restore,

**Comment by luugh** [comment]
> Glad to know it Would you kindly clarify which address exactly you change?
> 
> Do you mean `host` in clickhouse section of clickhouse backup config? It usually shall 127.0.0.1, clickhouse-backup always need direct access to the same disks which used for clickhouse-server Unfortunately, I can't hard-code it because we can have use cases when need restore only schema on remote clickhouse-server.
> 
> > How to judge that it is parallel recovery in multiple servers, is there any parameter to prohibit it?
> 
> It was just Assumption `check_replicas_before_attach` shall to avoid concurrent ATTACH PART on multiple replicas during restore,
The wrong configuration is as follows
`clickhouse:
  host: clickhouse-headless.clickhouse `
Modified configuration：
`clickhouse:
  host: localhost`

**Comment by luugh** [comment]
> Glad to know it Would you kindly clarify which address exactly you change?
> 
> Do you mean `host` in clickhouse section of clickhouse backup config? It usually shall 127.0.0.1, clickhouse-backup always need direct access to the same disks which used for clickhouse-server Unfortunately, I can't hard-code it because we can have use cases when need restore only schema on remote clickhouse-server.
> 
> > How to judge that it is parallel recovery in multiple servers, is there any parameter to prohibit it?
> 
> It was just Assumption `check_replicas_before_attach` shall to avoid concurrent ATTACH PART on multiple replicas during restore,

The wrong configuration is as follows
`clickhouse:
  host: clickhouse-headless.clickhouse `
Modified configuration：
`clickhouse:
  host: localhost`
