### ISSUE TITLE
Help with incremental backup for kubernetes hosted clickhouse

### ISSUE THREAD

**Issue by akash123-eng** [Altinity/clickhouse-backup#523]
please help with what command we need to add in cronjob for  implementing incremental backup for clickhouse

**Comment by Slach** [comment]
something like that

- detect last full backup name
```bash
LAST_FULL_BACKUP=$(clickhouse-client --echo -mn -q "SELECT name FROM system.backup_list WHERE location='remote' AND name LIKE '%full%' AND desc NOT LIKE 'broken%' ORDER BY created DESC LIMIT 1" --host="$SERVER" --port="$CLICKHOUSE_PORT" --user="$BACKUP_USER" $BACKUP_PASSWORD);
```

- detect previous backup name
```bash
PREV_BACKUP_NAME=$(clickhouse-client --echo -mn -q "SELECT name FROM system.backup_list WHERE location='remote' AND desc NOT LIKE 'broken%' ORDER BY created DESC LIMIT 1" --host="$SERVER" --port="$CLICKHOUSE_PORT" --user="$BACKUP_USER" $BACKUP_PASSWORD);
```

- decide shall we run full backup or increment
```bash
# make full backup every monday

DIFF_FROM=""
if [[ "1" == "$(date +%u)" || "" == "$PREV_BACKUP_NAME" || "" == "$LAST_FULL_BACKUP"   ]]; then 
  BACKUP_NAME="full-$BACKUP_DATE"
else 
  BACKUP_NAME="increment-$BACKUP_DATE"
  DIFF_FROM="--diff-from-remote=$PREV_BACKUP_NAME" 
fi
```

- execute upload with --diff-from-remote
```bash
clickhouse-client --echo -mn -q "INSERT INTO system.backup_actions(command) VALUES('upload ${DIFF_FROM} 
 ${SERVER}-${BACKUP_NAME}')" --host="$SERVER" --port="$CLICKHOUSE_PORT" --user="$BACKUP_USER" $BACKUP_PASSWORD;
```

- check upload in progress
```bash
$(clickhouse-client -mn -q "SELECT status FROM system.backup_actions WHERE command='upload ${DIFF_FROM} ${SERVER}-${BACKUP_NAME}'" --host="$SERVER" --port="$CLICKHOUSE_PORT" --user="$BACKUP_USER" $BACKUP_PASSWORD)
```


please don't hesitate to make pull request to `Examples.md` to adopt these changes

**Comment by akash123-eng** [comment]
@Slach Thank you very much
but  What is $BACKUP_DATE in if else loop ?

**Comment by Slach** [comment]
look to 
https://github.com/Altinity/clickhouse-backup/blob/master/Examples.md#how-to-use-clickhouse-backup-in-kubernetes

**Comment by akash123-eng** [comment]
oh.. got it
@Slach 
I executed above commands and status shows error ?
How we can troubleshoot this error ?

`clickhouse@chi-clickhouse-server-default-0-0-0:/$ PREV_BACKUP_NAME=$(clickhouse-client -q "SELECT name FROM system.backup_list WHERE location='remote' AND desc NOT LIKE 'broken%' ORDER BY created DESC LIMIT 1" --user="$CLICKHOUSE_USERNAME" --password=$CLICKHOUSE_PASSWORD;)`

`clickhouse@chi-clickhouse-server-default-0-0-0:/$ LAST_FULL_BACKUP=$(clickhouse-client  -q "SELECT name FROM system.backup_list WHERE location='remote' AND name LIKE '%full%' AND desc NOT LIKE 'broken%' ORDER BY created DESC LIMIT 1" --user="$CLICKHOUSE_USERNAME" --password=$CLICKHOUSE_PASSWORD)`

`clickhouse@chi-clickhouse-server-default-0-0-0:/$ if [[ "1" == "$(date +%u)" || "" == "$PREV_BACKUP_NAME" || "" == "$LAST_FULL_BACKUP"   ]]; then    BACKUP_NAME="full-$BACKUP_DATE"; else    BACKUP_NAME="increment-$BACKUP_DATE";   DIFF_FROM="--diff-from-remote=$PREV_BACKUP_NAME" ; fi`


```
clickhouse@chi-clickhouse-server-default-0-0-0:/$ clickhouse-client --echo -mn -q "INSERT INTO system.backup_actions(command) VALUES('upload ${DIFF_FROM} ${SERVER}-${BACKUP_NAME}')" --user="$CLICKHOUSE_USERNAME" --password=$CLICKHOUSE_PASSWORD;
INSERT INTO system.backup_actions(command) VALUES('upload --diff-from-remote=chi-clickhouse-server-default-0-0-full-2022-09-27-11-50-00 chi-clickhouse-server-default-0-0-increment-2022-09-27-11-49-16')
```

```
clickhouse@chi-clickhouse-server-default-0-0-0:/$ clickhouse-client -mn -q "SELECT status FROM system.backup_actions WHERE command='upload ${DIFF_FROM} ${SERVER}-${BACKUP_NAME}'" --user="$CLICKHOUSE_USERNAME" --password=$CLICKHOUSE_PASSWORD
error
```

**Comment by Slach** [comment]
look details about error in 
`SELECT * FROM system.backup_actions FORMAT Vertical`
and `kubectl logs pod chi-clickhouse-server-default-0-0-0 -c clickhouse-backup --since=24h`

examples on 
https://github.com/Altinity/clickhouse-backup/blob/master/Examples.md#how-to-use-clickhouse-backup-in-kubernetes
tested before publish
