### ISSUE TITLE
Is my backups empty or not !

### ISSUE THREAD

**Issue by karimennassiri** [Altinity/clickhouse-backup#531]
I don not have an issue but I do have a question 

I'v installed Clickhouse server and Clickhouse backup to restore and backup my OLAP database data.

I run a daily CronJob to do the backup, but I do not have any idea if my backups are empty or not. 

I'm looking into the result, and all what I see is the table schema with no data.

Can you please tell how backup should looks like.

```{
	"table": "events",
	"database": "test-krm",
	"parts": {},
	"query": "CREATE TABLE resalocal.events UUID '26ff6b70-e812-455d-a6ff-6b70e812755d' (`name` String, `domain` String, `user_id` UInt64, `session_id` UInt64, `hostname` String, `pathname` String, `referrer` String, `referrer_source` String, `country_code` LowCardinality(FixedString(2)), `screen_size` LowCardinality(String), `operating_system` LowCardinality(String), `browser` LowCardinality(String), `timestamp` DateTime, `utm_medium` String, `utm_source` String, `utm_campaign` String, `meta.key` Array(String), `meta.value` Array(String), `browser_version` LowCardinality(String), `operating_system_version` LowCardinality(String)) ENGINE = MergeTree PARTITION BY toYYYYMM(timestamp) ORDER BY (name, domain, user_id, timestamp) SAMPLE BY user_id SETTINGS index_granularity = 8192",
	"size": {},
	"total_bytes": 1167448,
	"metadata_only": false
}```

**Comment by Slach** [comment]
CronJob mean kubernetes CronJob or something else?

`clickhouse-backup` provides embedded `/metrics` endpoint with `prometheus` format

you can use `clickouse-backup list remote` if you want to check backup list manually or `SELECT * FROM system.backup_list` if your run `clickhouse-backup server`


empty `"parts": {}` sections looks stange, after upload on remote storage it should contains "parts" and "files" section

**Comment by karimennassiri** [comment]
Yes, is a Kubernetes CronJob who simply runs the command `clickhouse-backup create_remote`. I do have the metada folder but that's it, there is no other folders.

What is the reasons behind the emptiness of the `"parts": {} `?

**Comment by Slach** [comment]
`clickhouse-backup create_remote` in separate CronJob is wrong way, it not have access to clickhouse disks 
only if you will mount the same PVC which used in clickhouse-server

use API server instead 
look to proper way https://github.com/Altinity/clickhouse-backup/blob/master/Examples.md#how-to-use-clickhouse-backup-in-kubernetes

**Comment by karimennassiri** [comment]
I've already followed this tutorial and everything was good beside the CronJob and particulary this error.

`Code: 60. DB::Exception: Received from clickhouse:9000. DB::Exception: Table system.backup_list doesn't exist. (UNKNOWN_TABLE)
`
Shoud I create this table `backup_list` ?  
As you can see I have the env variable `API_CREATE_INTEGRATION_TABLES: true `setted to true

**Comment by Slach** [comment]
`clickhouse:9000`
this is the exactly what you see in error message or you change hostname?

What do you setup in your CronJob spec for the following fragment?

```
                - name: CLICKHOUSE_SERVICES
                  value: chi-test-backups-default-0-0,chi-test-backups-default-1-0

```

**Comment by Slach** [comment]
please share
```
kubectl get chi --all-namespaces
kubectl get svc -l  clickhouse.altinity.com/app=chop --all-namespaces
```
