### ISSUE TITLE
`clean` API does not work

### ISSUE THREAD

**Issue by kingboung** [Altinity/clickhouse-backup#533]
![image](https://user-images.githubusercontent.com/22000541/195593653-512847fa-956f-4f10-a12d-776f2aaeee0f.png)
API return success state, but actually it does not work.
When time goes, it will waste many storage

VERSION: 1.6.1

**Comment by Slach** [comment]
clickhouse-backup help clean

```
Remove data in 'shadow' folder from all `path` folders available from `system.disks`
```
this command don't clean local backups, this command works as expected

use 
`clickhouse-backup delete local <backup_name>` for remove backups 
use `backups_keep_local: 1` in config,  to delete all local backups excluding in last one

**Comment by kingboung** [comment]
@Slach 
I mean shadow folder instead of local backup. I called /backup/clean API and didnt find clean process, but I can find one when I execute clickhouse-backup clean command.

**Comment by Slach** [comment]
try latest 2.0.0 version

**Comment by Slach** [comment]
> When time goes, it will waste many storage

Actually, it works, which is your `backups_keep_local` config option value?
If zero, then you just contain infinite local backups which contains hard links, and if you have intensive data merging it will allocate disk space after original data part delete.

Could you share  `clickhouse-backup print-config` result without sensitive credentials?

**Comment by kingboung** [comment]
```
general:
  remote_storage: s3
  max_file_size: 0
  disable_progress_bar: true
  backups_to_keep_local: 1
  backups_to_keep_remote: 0
  log_level: info
  allow_empty_backups: false
  download_concurrency: 30
  upload_concurrency: 30
  restore_schema_on_cluster: cluster
  upload_by_part: true
  download_by_part: true
clickhouse:
  username: ***
  password: ***
  host: ***
  port: ***
  disk_mapping: {}
  skip_tables: ***
  timeout: 5m
  freeze_by_part: false
  freeze_by_part_where: ""
  secure: false
  skip_verify: false
  sync_replicated_tables: false
  log_sql_queries: true
  config_dir: ***
  restart_command: systemctl restart clickhouse-server
  ignore_not_exists_error_during_freeze: true
  check_replicas_before_attach: true
  tls_key: ""
  tls_cert: ""
  tls_ca: ""
  debug: false
s3:
  access_key: ***
  secret_key: ***
  bucket: ***
  endpoint: ***
  region: ***
  acl: private
  assume_role_arn: ""
  force_path_style: true
  path: ""
  disable_ssl: true
  compression_level: 6
  compression_format: tar
  sse: ""
  disable_cert_verification: false
  use_custom_storage_class: false
  storage_class: STANDARD
  concurrency: 1
  part_size: 10485760
  max_parts_count: 10000
  allow_multipart_download: false
  debug: false
gcs:
  credentials_file: ""
  credentials_json: ""
  bucket: ""
  path: ""
  compression_level: 1
  compression_format: tar
  debug: false
  endpoint: ""
  storage_class: STANDARD
cos:
  url: ""
  timeout: 2m
  secret_id: ""
  secret_key: ""
  path: ""
  compression_format: tar
  compression_level: 1
  debug: false
api:
  listen: ***
  enable_metrics: true
  enable_pprof: false
  username: ***
  password: ***
  secure: false
  certificate_file: ""
  private_key_file: ""
  create_integration_tables: true
  integration_tables_host: ""
  allow_parallel: true
ftp:
  address: ""
  timeout: 2m
  username: ""
  password: ""
  tls: false
  path: ""
  compression_format: tar
  compression_level: 1
  concurrency: 28
  debug: false
sftp:
  address: ""
  port: 22
  username: ""
  password: ""
  key: ""
  path: ""
  compression_format: tar
  compression_level: 1
  concurrency: 1
  debug: false
azblob:
  endpoint_suffix: core.windows.net
  account_name: ""
  account_key: ""
  sas: ""
  use_managed_identity: false
  container: ""
  path: ""
  compression_level: 1
  compression_format: tar
  sse_key: ""
  buffer_size: 0
  buffer_count: 3
  max_parts_count: 10000
  timeout: 15m
  ```

@Slach

**Comment by Slach** [comment]
> backups_to_keep_local: 1
> backups_to_keep_remote: 0
  
Looks ok
Do you manually delete your local backup after successful upload?

**Comment by kingboung** [comment]
I think that it is because hard link parts in shadow folder were merged?

**Comment by Slach** [comment]
Ok. Could you clarify? what exactly `shadow` folder do you mean?
`/var/lib/clickhouse/shadow` or  `/var/lib/clickhouse/backup/<backup_name>/shadow/`?

**Comment by kingboung** [comment]
/var/lib/clickhouse/shadow
`clickhouse-backup clean` works for this folder, but `POST /backup/clean` not works.

**Comment by Slach** [comment]
@kingboung could you check 2.1.1 version? It should works as expected or return error

**Comment by kingboung** [comment]
@Slach 
hello, I found that `clickhouse-backup clean` command works for `/var/lib/clickhouse/shadow` only when I `cd /var/lib/clickhouse/shadow`

**Comment by Slach** [comment]
@kingboung 
Looks weird, the following code fragment doesn't use relative paths
https://github.com/AlexAkulov/clickhouse-backup/blob/master/pkg/backup/delete.go#L28-L39

could you share the following command results?
`clickhouse-client -q "SELECT * FROM system.disks"`


Could you share result for the following command?
`LOG_LEVEL=debug clickhouse-backup clean`

**Comment by kingboung** [comment]
```
clickhouse-client -q "SELECT * FROM system.disks"
┌─name────┬─path─────────────────┬────free_space─┬────total_space─┬─keep_free_space─┬─type──┐
│ default │ /var/lib/clickhouse/ │ 7777270788096 │ 21388309835776 │               0 │ local │
└─────────┴──────────────────────┴───────────────┴────────────────┴─────────────────┴───────┘
```
```
cd ~; LOG_LEVEL=debug clickhouse-backup clean
It quit quickly
```
![image](https://user-images.githubusercontent.com/22000541/198496165-04c9837f-11c8-4794-a22b-627f8230c9cb.png)
```
cd /var/lib/clickhouse/shadow; LOG_LEVEL=debug clickhouse-backup clean
It stucks and works
```
![image](https://user-images.githubusercontent.com/22000541/198496532-9fd760d4-acbb-4619-853b-7308779c6e5c.png)

**Comment by kingboung** [comment]
Any ideas about this? @Slach

**Comment by Slach** [comment]
could you share
`ls -la /var/lib/clickhouse/shadow` ?

**Comment by Slach** [comment]
@kingboung thanks for bug report
could you try
`docker run -e LOG_LEVEL=debug--rm -v /var/lib/clickhouse:/var/lib/clickhouse altinity/clickhouse-backup:master clickhouse-backup clean`

**Comment by kingboung** [comment]
@Slach  Works!!!! Thanks a lot

**Comment by kingboung** [comment]
When will this issue be merged and released?

**Comment by Slach** [comment]
wait when 2.1.3 released
or use `altinity/clickhouse-backup:master` docker image
