### ISSUE TITLE
switch S3 storage backend to https://github.com/aws/aws-sdk-go-v2/

### ISSUE THREAD

**Issue by Slach** [Altinity/clickhouse-backup#534]
to allow use contexts

**Comment by anikin-aa** [comment]
@Slach , hi
don't you mind if will try to work on this issue ?

how to migrate between versions: https://aws.github.io/aws-sdk-go-v2/docs/migrating/

**Comment by Slach** [comment]
@anikin-aa i will really appreciate if you prepare PR, thanks a lot for your contribution
