### ISSUE TITLE
migrate to clickhouse-go/v2

### ISSUE THREAD

**Issue by Slach** [Altinity/clickhouse-backup#540]

**Comment by anikin-aa** [comment]
@Slach , hi!

Don't you mind if i will try to work on this issue ?

**Comment by anikin-aa** [comment]
I've raised a PR: https://github.com/AlexAkulov/clickhouse-backup/pull/562

**Comment by Slach** [comment]
@anikin-aa oh! Thanks a lot, great, I was on vacation 
will review your PR ASAP
