### ISSUE TITLE
Missing bash from latest clickhouse-backup:master docker image

### ISSUE THREAD

**Issue by empeekdev** [Altinity/clickhouse-backup#542]
Running clickhouse-backup from latest version of clickhouse-backup:master  docker image failing with the error that bash is not found in $PATH. sh is still present in $PATH and can be used as replacement.

**Comment by Slach** [comment]
thanks a lot for reporting, my fault will fix it asap

**Comment by Slach** [comment]
try https://github.com/AlexAkulov/clickhouse-backup/releases/tag/v2.1.1
