### ISSUE TITLE
The backup is off by 8 hours

### ISSUE THREAD

**Issue by bigdata-spec** [Altinity/clickhouse-backup#549]
HI，
when I run `clickhouse-backup create` 
The generated folder name is  2022-10-24T09-19-16  but The current time is 2022-10-24T17-19-16 .A difference of 8 hours
How to solve the problem?

**Comment by Slach** [comment]
What timezone in your server?

What show `date +%Y-%m-%dT%H-%M-%S`?

**Comment by bigdata-spec** [comment]
@Slach  Thank you ，![image](https://user-images.githubusercontent.com/23710717/197656642-85e6efe2-4794-402f-87b4-45d5296ccd2e.png) what can I do？

**Comment by Slach** [comment]
Use backup name explicitly
```
clickhouse-backup create $(date +%Y-%m-%dT%H-%M-%S)
```

**Comment by bigdata-spec** [comment]
> Use backup name explicitly
> 
> ```
> clickhouse-backup create $(date +%Y-%m-%dT%H-%M-%S)
> ```

Thank you. Is there a configuration? I also encountered a time difference of 8 hours in the Chproxy project, and I am not familiar with go language

**Comment by Slach** [comment]
this is no time difference
this is time just in UTC timezone
