### ISSUE TITLE
[Question] Using clickhouse-backup server and api requests for upload

### ISSUE THREAD

**Issue by rjshrjndrn** [Altinity/clickhouse-backup#553]
Hi,
First of all, thank you for this awesome project. It makes the clickhouse backup operation breeze.

I have a question, more like a clarification.

I have a clickhouse container running in Kubernetes cluster, which has a clickhouse-backup sidecar. 
A Kubernetes cronjob will call the `clickhouse.db.svc.cluster.local:7171/backup/create/my_backup` and after 
`curl -XPOST clickhouse.db.svc.cluster.local:7171/backup/upload/my_backup`.

The question is if the backup is not completed, will the upload  API request wait for the backup to complete? I know the API is asynchronous. The question is more like will the underlying server wait for the `my_backup` before start uploading?

**Comment by Slach** [comment]
`create` is asynchronous operation
you need make poll `/backup/status` until it `success`

`upload` operation is also asynchronous
so, you need poll status also

look to 
https://github.com/AlexAkulov/clickhouse-backup/blob/master/Examples.md#how-to-use-clickhouse-backup-in-kubernetes
for example, of one of many possible implementations
