### ISSUE TITLE
Does Support DICTIONARY type backup and restore?

### ISSUE THREAD

**Issue by bigdata-spec** [Altinity/clickhouse-backup#554]
Does Support DICTIONARY type backup and restore?

**Comment by Slach** [comment]
Yes, backup and restore DICTIONARY created with SQL and present in system.tables schema is supported. 
Data backup for dictionary is not supported.
And for some types of dictionary and old clickhouse-server version possible need SYSTEM RELOAD DICTIONARIES after restore
