### ISSUE TITLE
S3 backup directories are not deleted if versioning is enabled

### ISSUE THREAD

**Issue by Tvion** [Altinity/clickhouse-backup#555]
Hi
We faced the problem with remaining empty directories for deleted backup from S3. We use Minio with enabled replication. Versioning is also enabled for buckets. We assume that backup folder cannot be deleted properly because version Id must be provided [here](https://github.com/AlexAkulov/clickhouse-backup/blob/master/pkg/storage/s3.go#L191) in case of versioning enabled.

**Comment by Tvion** [comment]
Something like https://github.com/AlexAkulov/clickhouse-backup/pull/556 should help

**Comment by Slach** [comment]
thank you so much for reporting, will try to review your changes
