### ISSUE TITLE
--restore-database-mapping only changes database.table but not the replica paths

### ISSUE THREAD

**Issue by weusego** [Altinity/clickhouse-backup#557]
--restore-database-mapping is broken in VERSION:   2.1.2

`clickhouse-backup restore prod-URLIPROD_20220602C-prod-view01-20221105_142855  --restore-database-mapping=URLIPROD_20220602C:URLIREF_20221105E`

results in this error

```
[clickhouse][connect=191][process] <- exception
2022/11/05 14:33:52.624322  warn can't create table 'URLIREF_20221105E.EnumType': code: 253, message: Replica /clickhouse/tables/shard01/URLIPROD_20220602C/EnumType/replicas/ref-view01 already exists, will try again backup=prod-URLIPROD_20220602C-lrt>
[clickhouse]host(s)=localhost:9000, database=system, username=default
[clickhouse][dial] secure=false, skip_verify=false, strategy=random, ident=192, server=0 -> 127.0.0.1:9000
[clickhouse][connect=192][hello] -> Golang SQLDriver 1.1.54213
[clickhouse][connect=192][hello] <- ClickHouse 22.8.54460 (Etc/UTC)
```

As you see it wants to 

create table 'URLIREF_20221105E.EnumType'

but with replica holding the old database name still

2022/11/05 14:33:52.624322  warn can't create table '**URLIREF_20221105E**.EnumType': code: 253, message: Replica /clickhouse/tables/shard01/**URLIPROD_20220602C**/EnumType/replicas/ref-view01 already exists, will try again backup=prod-URLIPROD_20220602C-lrt>

**Comment by Slach** [comment]
Duplicate with https://github.com/AlexAkulov/clickhouse-backup/issues/547
