### ISSUE TITLE
Advantage of this tool over built-in clickhouse support

### ISSUE THREAD

**Issue by a-dot** [Altinity/clickhouse-backup#558]
Title says it all... what is the advantage of using clickhouse-backup instead of using the instructions found here: https://clickhouse.com/docs/en/manage/backups/ ?

**Comment by Slach** [comment]
Current BACKUP/RESTORE just not works as expected
look 
https://github.com/ClickHouse/ClickHouse/issues/39416 
https://github.com/ClickHouse/ClickHouse/issues/42709
for example

embedded backup\restore not implements upload and download operation
during backup creation, embedded BACKUP copy data to destination path\disk, clickhouse-backup create hard links, it allow us create snapshot quickly and after it upload to remote storage asynchonously

moreover, on latest version we implements
```yaml
clickhouse:
  user_embedded_backup_restore: true
```
to allow use embedded BACKUP \ RESTORE

**Comment by Alex-Cheng** [comment]
> 

How to backup and restore database with clickhouse-backup rather than built-in command BACKUP/RESTORE?

**Comment by Slach** [comment]
@Alex-Cheng could you read Readme.md ?
https://github.com/Altinity/clickhouse-backup#common-cli-usage
