### ISSUE TITLE
Restore to new server with different disk count, implements least_used for normal disk and roud_robin for Object disks 

### ISSUE THREAD

**Issue by vkrot-innio** [Altinity/clickhouse-backup#561]
There is disk_mapping already, but looks like it can remap disks 1-1. I want to restore a backup at a system that has more disks and distribute parts between the disks. Backup server had only 1 "default" disk, new server has 7 disks. Is that possible and how?

**Comment by Slach** [comment]
sorry for late reply

currently it is not possible automatically

you can manually spread parts
move some `/var/lib/clickhouse/backup/backup_name/shadow/db/table/<disk_name>/<part_name>.<archive_extension>`
to `/other/disk/path/backup/backup_name/shadow/db/table/<new_disk_name>/<part_name>.<archive_extension>`
and changing `/var/lib/clickhouse/backup/backup_name/metadata/db/table.json` `"parts"` section
and try to restore

this is good candidate for feature request, but need formalize how to spread parts between disks
and have lot of corner cases when we have s3 disks

**Comment by Slach** [comment]
Unfortunately, too many corner cases for multi-disk volumes, different storage policies and S3 \ HDFS disks and backwards compatibility, currently we doesn't store inside backup_name/metadata.json full information for volumes, storage_policies and disk types

Need time to think how to implements it properly

**Comment by Slach** [comment]
Unfortunately, fair full implementation requires store data part size and requires rewrite too many parts

I added a partial implementation, which could cover 60-70 percent of use-cases, I hope

**Comment by Slach** [comment]
=(( too hard to implements with combination with object disks ...
