### ISSUE TITLE
Problem with clickhouse-backup upload --diff-from

### ISSUE THREAD

**Issue by nikolasct** [Altinity/clickhouse-backup#566]
So, as the title says.

Just to make everything clear, for this test, first I ran 
`clickhouse-backup create ck-ful`
then I tried to upload only the incremental part, so I ran
`clickhouse-backup upload --diff-from=ck-ful incremental1`

I got this error:
"error can't find local backup: backup 'incremental1' is not found"

I am using the repo to upload to AWS S3, the `create_remote` command works good for the full backup, so no issues with connection to s3.

I need the `upload --diff-from` part, since I want incrementals to only be on the AWS S3.

Is this a bug, or I am just using the command wrong? Though, I don't think that I am using the command wrong, since I've checked multiple times. I even ran `clickhouse-backup upload --help` to clarify the `upload` command, and list its options.

**Comment by Slach** [comment]
> clickhouse-backup upload --diff-from=ck-ful incremental1
>I got this error: "error can't find local backup: backup 'incremental1' is not found"

Because you don't create incremental1 backup
use
```
clickhouse-backup create_remote ck-ful
clickhouse-backup delete local ck-ful

clickhouse-backup create_remote --diff-from-remote=ck-ful incremental1
clickhouse-backup delete local incremental1
```

**Comment by nikolasct** [comment]
@Slach 
So there is a problem with --diff-from-remote as well.

A couple of days ago, I made a backup using the
 `clickhouse-backup create_remote clickhouse-backup-2022-11-15-screen -c "/etc/clickhouse-backup/config.yml"`

So today, I even tried running
`clickhouse-backup upload --diff-from-remote=clickhouse-backup-2022-11-15-screen incremental1`
but I am getting the same error:
"error can't find local backup: backup 'incremental1' is not found"

I am running everything as root.

**Comment by nikolasct** [comment]
I even tried now, since our config.yml is
backups to keep local: 1
backups to keep remote: 2
to remove 1 of the remote backups.
So now `clickhouse-backup list` gives me 1 full local and 1 full remote backup.

**Comment by Slach** [comment]
> clickhouse-backup upload --diff-from-remote=clickhouse-backup-2022-11-15-screen incremental1

Looks like you try to upload incremental1 backup without create it, please read my answer here again
https://github.com/AlexAkulov/clickhouse-backup/issues/566#issuecomment-1318902145

Local backups are always full because it's a just file hard links to existed clickhouse-server data
