### ISSUE TITLE
Refactor codebase to follow go project layout

### ISSUE THREAD

**Issue by przemekd** [Altinity/clickhouse-backup#57]
Right now the code is a little bit disorganized - I suggest to change the code organization to follow a standard go project layout -> https://github.com/golang-standards/project-layout

**Comment by AlexAkulov** [comment]
Yes. @develar started doing this by having moved the code to 'pkg' folder. I think there is a lot of opportunities to improve code organization.

**Comment by przemekd** [comment]
Right now I see the following problems/areas for improvement:

- [ ] there are a lot of exported types/methods in `chbackup` package, have you thought about how API of the `chbackup` library should be structured?
- [x] integration test could be separated into `test/integration` directory.


BTW - Correct me if I am wrong, but it seems that whole backup is archived and stored as one file. There are limits to how big objects can be both in S3 and GCS. Shouldn't the archive be divided into parts first?

**Comment by AlexAkulov** [comment]
I have just accepted PR https://github.com/AlexAkulov/clickhouse-backup/pull/56. You can do refactoring code on your choice.

S3 has limit on number of parts. By this reason default part size in clickhouse-backup is increased to 100MiB instead of 5MiB that is default AWS value. Thus division of large files on parts is made on S3 transparently. I don't known about limits on GCS.

**Comment by przemekd** [comment]
@AlexAkulov Yeah, the upload process uses Multipart Upload API but the archive is still saved as one big object. Both GCP and AWS have a maximum size limit of 5 TB for individual objects. That could be a problem if one has big tables, right?

**Comment by AlexAkulov** [comment]
@przemekd Yes, you're right, the maximum file size is 5 TB.
I will add these restrictions to the readme. I don’t know how critical this is, 5 TB will be uploading almost all day, it seems too long. I think that if you have such a large database, perhaps you should use a different way to upload backups. Maybe better way is to create instance of ClickHouse on another DC and have it fresh by clickhouse-copier and use clickhouse-backup only for backups that will be stored locally.

**Comment by AlexAkulov** [comment]
Closed by 1924974dcb938840834642df7bcf95e48081268e
