### ISSUE TITLE
error restoring backup with Object('json')

### ISSUE THREAD

**Issue by SatyanandKommoju** [Altinity/clickhouse-backup#575]
Seeing an issue when attempting an import with one of the table having a column of type Object('json')

The below error is being reported.

`022/11/30 14:29:58.980666 error can't create table `mydb`.`test_history`: code: 44, message: Cannot create table with column 'payload' which type is 'Object('json')' because experimental Object type is not allowed. Set setting allow_experimental_object_type = 1 in order to allow it after 13 times, please check your schema dependencies`

Have not seen any issues during export itself.

Tried to see if there's any option of setting the allow_experimental_object_type on, but couldn't fine any resources.

Any help is greatly appreciated.

Also, many thanks for building this tool, it has greatly simplified the process of backup/restore.

**Comment by Slach** [comment]
```
echo '<clickhouse><profiles><default><allow_experimental_object_type>1</allow_experimental_object_type></default></profiles></clickhouse>' > /etc/clickhouse-server/users.d/allow_experimental_object_type.xml
```

will help

**Comment by SatyanandKommoju** [comment]
This just worked!
Thank you verymuch @Slach
