### ISSUE TITLE
why /var/lib/clickhouse/store  become small afther backup

### ISSUE THREAD

**Issue by bigdata-spec** [Altinity/clickhouse-backup#577]
@Slach Thank you for you reply. #551 
But I still have a question:
before backup **/var/lib/clickhouse/store** is 191G,after run cmd **clickhouse-backup create** **/var/lib/clickhouse/store** is 63 G.
why **/var/lib/clickhouse/store**  size  become small afther run **backup** command?

**Comment by Slach** [comment]
you already got answer here
https://github.com/AlexAkulov/clickhouse-backup/issues/551#issuecomment-1327061407

**Comment by Slach** [comment]
please read and try to figure out what exactly hard link means
https://en.wikipedia.org/wiki/Hard_link

**Comment by bigdata-spec** [comment]
> please read and try to figure out what exactly hard link means https://en.wikipedia.org/wiki/Hard_link

[Hard_link](https://en.wikipedia.org/wiki/Hard_link) Hard_link just as copy，but it become small，It's very strange

I think  Hard links do not affect the original file.

**Comment by Slach** [comment]
The LINK cannot be a COPY

Hard link it's a link to the same inode as original file
try read about inode here https://en.wikipedia.org/wiki/Inode
