### ISSUE TITLE
Use graymeta/stow package as remote storage abstraction

### ISSUE THREAD

**Issue by przemekd** [Altinity/clickhouse-backup#58]
I suggest using https://github.com/graymeta/stow as remote storage abstraction. That way the project can easily support more object storage solutions.

**Comment by AlexAkulov** [comment]
Good idea! 
I didn't know about this project before. I see it supports upload and download via io.Reader which means we will be able to switch to using this library easily.

**Comment by przemekd** [comment]
I have looked into this and stow library doesn't allow to easily get files/object by object path - one would need to use the full URL to get an `Item`. See https://github.com/graymeta/stow#getting-an-item-by-url

Current implementation doesn't follow this style, so maybe it would be beneficial to refactor the code first (https://github.com/AlexAkulov/clickhouse-backup/issues/57) and then think about if stow library package is really needed.

**Comment by glothriel** [comment]
This becomes slightly less painful with tools like https://docs.min.io/docs/minio-gateway-for-azure.html

**Comment by AlexAkulov** [comment]
I found this project https://github.com/google/go-cloud

**Comment by dcastanier** [comment]
I need also to store backup in Azure. Minio gateway is a workaround, but use a generic cloud API look a better way.
Any progress in the API choice or refactoring ?

**Comment by blafry** [comment]
@AlexAkulov any further info/update regarding the above? I would be grateful if you could provide me with some details.

**Comment by Slach** [comment]
Currently, look like use abstraction external library will restrict us to add new remote storages 
we will need to add a new storage type to SDK fist
and it also restrict implementation of the remote storage specifics options like AWS S3 IAM assume role (role_arn) or `S3_CONCURRENCY`

so. i close issue due inactivity
