### ISSUE TITLE
"ATTACH MATERIALIZED VIEW" is failing

### ISSUE THREAD

**Issue by AlexisDemeaulte** [Altinity/clickhouse-backup#581]
When I'm trying to restore materialized view I have this error : 

```
error can't create table `xxx`.`yyy`: code: 80, message: Incorrect ATTACH TABLE query for Atomic database engine. Use one of the following queries instead:
1. ATTACH TABLE yyy;
2. CREATE TABLE yyy <table definition>;
3. ATTACH TABLE yyy FROM '/path/to/data/' <table definition>;
4. ATTACH TABLE yyy UUID '<uuid>' <table definition>; after 1 times, please check your schema dependencies
```

But it works fine when I'm using "CREATE MATERIALIZED VIEW" instead of "ATTACH MATERIALIZED VIEW". I see that the code does this replacement on purpose and I'm wondering why. Any reason or should we fix the code to use create instead of attach ?

**Comment by Slach** [comment]
Which `clickhouse-server` version do you use?

could you share full log
`LOG_LEVEL=debug clickhouse-backup restore <your-backup-name>` ?

**Comment by AlexisDemeaulte** [comment]
It's on version 21.3.13.9 of clickhouse-server.

**Comment by AlexisDemeaulte** [comment]
Here is the ouput in debug mode (where I had to replace few things) : 

> 2022/12/09 15:34:45.119112  info clickhouse connection prepared: tcp://localhost:9000 run ping logger=clickhouse
> 2022/12/09 15:34:45.120422  info clickhouse connection open: tcp://localhost:9000 logger=clickhouse
> 2022/12/09 15:34:45.120446  info SELECT value FROM `system`.`build_options` where name='VERSION_INTEGER' logger=clickhouse
> 2022/12/09 15:34:45.122365  info SELECT * FROM system.disks; logger=clickhouse
> 2022/12/09 15:34:45.125861  info CREATE DATABASE IF NOT EXISTS `mydb` ENGINE = Ordinary with args [[]] logger=clickhouse
> 2022/12/09 15:34:45.127741  info SELECT engine FROM system.databases WHERE name = 'mydb' logger=clickhouse
> 2022/12/09 15:34:45.129405  info DROP TABLE IF EXISTS `mydb`.`mytable` NO DELAY logger=clickhouse
> 2022/12/09 15:34:45.131677  info CREATE DATABASE IF NOT EXISTS `mydb` logger=clickhouse
> 2022/12/09 15:34:45.134685  info ATTACH MATERIALIZED VIEW mydb.mytable TO mydb.mytable2 (...) logger=clickhouse
> 2022/12/09 15:34:45.136769  info clickhouse connection closed logger=clickhouse
> 2022/12/09 15:34:45.136793 error can't create table `mydb`.`mytable`: code: 80, message: Incorrect ATTACH TABLE query for Atomic database engine. Use one of the following queries instead:
> 1. ATTACH TABLE mytable;
> 2. CREATE TABLE mytable <table definition>;
> 3. ATTACH TABLE mytable FROM '/path/to/data/' <table definition>;
> 4. ATTACH TABLE mytable UUID '<uuid>' <table definition>; after 1 times, please check your schema dependencies

**Comment by Slach** [comment]
> 2022/12/09 15:34:45.134685 info ATTACH MATERIALIZED VIEW mydb.mytable TO mydb.mytable2 (...) logger=clickhouse

Could you provide full SQL request for this line?

Is your `clickhouse-server` for restore have the same `clickhouse-server` version 

look your mydb already exists on restored server with Atomic but Ordinary inside backup 

could you run DROP DATABASE mydb SYNC;

and after it `clickhouse-backup restore --rm <backup_name>`

**Comment by AlexisDemeaulte** [comment]
Yes clickhouse-server are both in the same version.
I'm coming back to you for the others questions.
But as far I can see in the ClickHouse documention, we should use `create` and not `attach` no ?

**Comment by AlexisDemeaulte** [comment]
I made a test with a simple table. This one is working : 

> CREATE MATERIALIZED VIEW default.my_tbl_mv
> (
>     project_id UInt32
> )
> ENGINE = ReplacingMergeTree(project_id)
> ORDER BY project_id AS
> SELECT
>     project_id
> FROM default.src_table
> GROUP BY project_id

While this one is failing with the same error as previously : 

> ATTACH MATERIALIZED VIEW default.my_tbl_mv
> (
>     project_id UInt32
> )
> ENGINE = ReplacingMergeTree(project_id)
> ORDER BY project_id AS
> SELECT
>     project_id
> FROM default.src_table
> GROUP BY project_id

**Comment by Slach** [comment]
Could you make suggestions (DROP DATABASE ... SYNC + clickhouse-backup restore) from my comment? https://github.com/AlexAkulov/clickhouse-backup/issues/581#issuecomment-1345167156

**Comment by AlexisDemeaulte** [comment]
Sorry for the delay, I did what you suggest with the drop database, and yes it works but I don't understand why. I can see that the default DB is with Atomic engine where the restored default DB is with Ordinary engine.

**Comment by Slach** [comment]
When we create backup, then table and materialized views schema dumped directly from
system.tables

root cause failure during restore you create materialized view without separate destination table then inner table have different name conversion for Ordinary and Atomic, so during ATTACH inner table just not found and attach failed.

try create your materialized view in atomic
after it 
run `SHOW CREATE TABLE your_atomic_db.my_tbl_mv`
and compare it with `SHOW CREATE TABLE your_ordinary_db.my_tbl_mv`

also compare `SHOW TABLES FROM your_atomic_db`;  and `SHOW TABLES FROM your_atomic_db`;

**Comment by Programmeris** [comment]
@Slach This issue is also relevant to me. CREATE instead of ATTACH didn't help.

**Comment by Programmeris** [comment]
@Slach I have two MATERIALIZED VIEW which are created by the following queries:

`ATTACH MATERIALIZED VIEW test.vrp_number_view (`vrp_number` String, `id` String, `fixation_at` DateTime64(3, 'UTC'), `device_id` String, INDEX vrp_index vrp_number TYPE bloom_filter GRANULARITY 1, INDEX device_index device_id TYPE bloom_filter GRANULARITY 1) ENGINE = ReplicatedMergeTree('/clickhouse/{installation}/{cluster}/tables/{shard}/test/.inner.vrp_number_view', '{replica}') PARTITION BY toMonth(fixation_at) ORDER BY (vrp_number, fixation_at) SETTINGS index_granularity = 8192 AS SELECT vrp_number, id, fixation_at, device_id FROM test.fact WHERE isNotNull(vrp_number)`

`ATTACH MATERIALIZED VIEW test.fact_ids_view (`id` String, `fixation_at` DateTime64(3, 'UTC')) ENGINE = ReplicatedMergeTree('/clickhouse/{installation}/{cluster}/tables/{shard}/test/.inner.fact_ids_view', '{replica}') PARTITION BY toMonday(fixation_at) ORDER BY id SETTINGS index_granularity = 8192 AS SELECT id, fixation_at FROM test.fact`

When trying to execute `clickhouse restore_remote`, I get data restore error as described in this issue

**Comment by Slach** [comment]
@Programmeris could you read issue from begin?

Especially https://github.com/AlexAkulov/clickhouse-backup/issues/581#issuecomment-1345167156 and 
https://github.com/AlexAkulov/clickhouse-backup/issues/581#issuecomment-1355194122 ?

**Comment by Programmeris** [comment]
@Slach Sorry for the long answer. Yes, your advice helped, the backup was restored without errors. Thank you very much!
