### ISSUE TITLE
Allow not to use credentials.json when running on GCE

### ISSUE THREAD

**Issue by nikon72ru** [Altinity/clickhouse-backup#59]
I want to add opportunity not to use credentials.json with google cloud storage (GCS) when application running on Google compute engine (GCE) because there is a way to use default service account. What do you think about it ?

**Comment by AlexAkulov** [comment]
It would be cool!

**Comment by nikon72ru** [comment]
I'v seen you already have this option to use default service account: 
```
if gcs.Config.CredentialsJSON != "" {
		clientOption = option.WithCredentialsJSON([]byte(gcs.Config.CredentialsJSON))
		gcs.client, err = storage.NewClient(ctx, clientOption)
	} else if gcs.Config.CredentialsFile != "" {
		clientOption = option.WithCredentialsFile(gcs.Config.CredentialsFile)
		gcs.client, err = storage.NewClient(ctx, clientOption)
	} else {
		gcs.client, err = storage.NewClient(ctx)
	}
```
(last else will do it, `storage.NewClient(ctx)` know where to find default key in GCE and GAE )

But this case will never used because if gcs.Config.CredentialsFile isn't set it will be set by default as  "/etc/clickhouse-backup/credentials.json" (but there are no options when this file gets into this folder automatically)

So only way to do it set 
`credentials_file: ""` 
in config explicitly.

I think it's not nice.

But if we will remove default value - it will broke changes for whose set credentials in "/etc/clickhouse-backup/credentials.json".  and not set it in config.

@AlexAkulov what do you think?

**Comment by AlexAkulov** [comment]
I have deleted default value for GCS_CREDENTIALS_FILE
