### ISSUE TITLE
Can I restore to a replicated merge tree table that is under replication?

### ISSUE THREAD

**Issue by ywangtht** [Altinity/clickhouse-backup#591]
I have two replicas, r1 and r2. When I followed the instructions in:
[how-to-make-backup--restore-sharded-cluster ](https://github.com/AlexAkulov/clickhouse-backup/blob/master/Examples.md#how-to-make-backup--restore-sharded-cluster )trying to restore to both replicas, I saw below warning:
2023/01/09 16:43:58.632391  warn dbX.tableY skipped cause system.replicas entry already exists and replication in progress from another replica logger=clickhouse

So the question is do I have to restore to a table that is currently not in replication?

**Comment by Slach** [comment]
It is available, but not recommends without figure out how it works
you can set `check_replicas_before_attach: false` in `clickhouse` config section in `/etc/clickhouse-backup/config.yml`

Could you provide more context?
Do you try to restore on server where you already continue data ingestion to `ReplicatedMergeTree` or you try to restore in r1 and r2 in parallel?
Do you need to keep existing data or need to restore the whole data from backup?

**Comment by ywangtht** [comment]
> Do you try to restore on server where you already continue data ingestion to ReplicatedMergeTree or you try to restore in r1 and r2 in parallel?

I try to restore to server where data ingestion continues. I do not need restore to both r1 and r2 in parallel because based on the document/example if I restore to r1, ClickHouse will replicate data to r2 automatically.

> Do you need to keep existing data or need to restore the whole data from backup?

I want to know if I can do both. I have two use cases:
1. Data is partitioned by date and I do incremental backups daily. I want to restore a particular day's partition while I keep existing data.
2. I just restore the whole data.

**Comment by ywangtht** [comment]
`check_replicas_before_attach: false` works for me in this case.
Thanks!

**Comment by Slach** [comment]
> 1. Data is partitioned by date and I do incremental backups daily. I want to restore a particular day's partition while I keep existing data.

Use `clickhouse-backup restore --partition=YYYYMMDD--data --table db.table` but need to ensure exitst table have the same structure with table in backup


> 2. I just restore the whole data.

use
`clickhouse-backup restore --rm --table db.table`
