### ISSUE TITLE
Can not Restore data backup from clickhouse backup(error can't attach partitions for table 'default.DNS_LOG': code: 16, message: There is no column or subcolumn PacketTime in part 20221129_265339_272772_6)

### ISSUE THREAD

**Issue by HesaMtiPu** [Altinity/clickhouse-backup#592]
I created backup on my click house server from click house-backup and move data to another click house server using this given below process :-
```
destination server

mkdir -p /var/lib/clickhouse/backups/backup_name

source server

clickhouse-backup create backup_name
rsync --rsh=ssh /var/lib/clickhouse/backups/backup_name/ user@dst_server:/var/lib/clickhouse/backups/backup_name

destination server

clickhouse-backup restore --rm backup_name
```

whenever i restore the backup on another click house server it showing error :-

error can't attach partitions for table 'default.DNS_LOG': code: 16, message: There is no column or subcolumn PacketTime in part 20221129_265339_272772_6

ClickHouse server version 22.12.3 

kindly help me out ...

**Comment by Slach** [comment]
looks like duplicates https://github.com/AlexAkulov/clickhouse-backup/issues/529

but, could you compare settings in source and destination server?
https://clickhouse.com/docs/en/operations/settings/settings#flatten-nested have same value?

**Comment by HesaMtiPu** [comment]
Thanks !! resolve for now !!!

**Comment by HesaMtiPu** [comment]
Thanks!! Resolve For Now !!!
