### ISSUE TITLE
BUG IN ENTRYPOINT.SH

### ISSUE THREAD

**Issue by sdarshil** [Altinity/clickhouse-backup#593]
in the entrypoint.sh there is a condition which says if the command is executable it will not run the clickhouse-backup command and will directly execute it :

i was running this command to use watch feature of clickhouse-backup
 clickhouse-backup watch --watch-interval 23h --full-interval 24h --watch-backup-name-template=shard{shard}-{type}-{time:20060102150405} 
 
 now none of the provided condition passes here and i am unable to use the watch functionality in the container of clickhouse-backup 
 
 
i built my image with custom entrypoint.sh which seems to be working :
`#!/bin/bash
if [[ $# -lt 1 ]] || [[ "$1" == "--"* ]] || [[ ! -x  $(command -v "$1") ]] || [[ "$1" == "watch" ]]; then
    exec /bin/clickhouse-backup "$@"
fi
exec "$@"
`

**Comment by Slach** [comment]
Could you provide full docker command which you try to run?

**Comment by sdarshil** [comment]
https://github.com/AlexAkulov/clickhouse-backup/pull/595
i have created PR for this

**Comment by Slach** [comment]
fixed in https://github.com/AlexAkulov/clickhouse-backup/pull/595
