### ISSUE TITLE
Clickhouse backups are failing for the table with ENGINE = TinyLog and ENGINE= ReplacingMergeTree 

### ISSUE THREAD

**Issue by kishorer00** [Altinity/clickhouse-backup#597]
Hi Team,

I have observed that  Clickhouse backups are failing for the table with ENGINE = TinyLog and ENGINE= ReplacingMergeTree 
However, No errors/exceptions were found while taking the backup and Re-stores.

**Is there a list of ENGINE's that click house backup tool supports?** 

- Backup tool version,which, i am using: v1.2.2
- clickhouse Running in Docker container 

 My clickhouse instance is down due to some indexing issue .. its not coming up. (Keep re-booting).

**I have clickhouse Server data in a .bin files . Any way to recover from .bin files?**

Thanks in Advance !!!.

**Comment by Slach** [comment]
`clickhouse-backup` support backup only schema for `ENGINE=TinyLog`

but all shall works for `ENGINE=ReplcaingMergeTree`

could you share
`LOG_LEVEL=debug clickhouse-backup restore --table=your_db_name.your_replacing_merge_tree_table_name`?

**Comment by kishorer00** [comment]
Collecting the logs, i will upload them in a couple of hours.

**Comment by kishorer00** [comment]
@Slach , Here are logs ,

Attachment - 1 -batch-test-1.txt - Failed to restore the table ENGINE=ReplacingMergeTree 
Attachment - 2 -batch-test-2.txt - Failed to restore  the table ENGINE=TinyLog;

Attachment - 3 -sample-test-1.txt - Able to the restore  table ENGINE=ReplacingMergeTree (Data also fine)

Also, provide the DDL for the same.  Suspecting some issues with Datatypes which, I am using for table creation. 

Please check for help on the same.

**Comment by kishorer00** [comment]
[batch-test-2.txt](https://github.com/AlexAkulov/clickhouse-backup/files/10498724/batch-test-2.txt)
[sample-test-1.txt](https://github.com/AlexAkulov/clickhouse-backup/files/10498725/sample-test-1.txt)
[batch-test-1.txt](https://github.com/AlexAkulov/clickhouse-backup/files/10498726/batch-test-1.txt)
![ataching-table](https://user-images.githubusercontent.com/86039112/214550094-c0da97d8-abfc-4304-9d46-16dcd8217479.PNG)

**Comment by Slach** [comment]
`batch-test-1.txt` doesn't contains any error and truncated
are you sure you have data in backup?

Could you share `ls -la /var/lib/clickhouse/backup/01-02-23/shadow/default/batch_test/`?

`batch-test-2.txt` also doesn't contains error
`CREATE TABLE batch.test2 (`Seam` String, `yield_perc` Float32, `updated_time` DateTime DEFAULT now()) ENGINE = TinyLog`
sucessfully created

for tinylog we support only schema metadata backup
not data


try to use
`use_embedded_backup_restore: true` if you want to support TinyLog it requires add separate disk for backup in `storage_policy`
look https://github.com/Altinity/clickhouse-backup/blob/master/test/integration/dynamic_settings.sh#L152-L181
and https://github.com/Altinity/clickhouse-backup/blob/master/test/integration/config-s3-embedded.yml#L22 for details
but embedded backup \ restore could not work for some corner cases and requires fresh clickhouse-server version

**Comment by Slach** [comment]
Closed after author inactivity
