### ISSUE TITLE
hard links in /var/lib/clickhouse/shadow are not treated well

### ISSUE THREAD

**Issue by anuriq** [Altinity/clickhouse-backup#6]
During multiple freeze executions partitions that weren't changed just create an additional hard link to already existing file. These can be seen from command line:

    # find shadow -xdev -samefile shadow/10/data/default/ontime/2009_1_1_0/checksums.txt -print
    shadow/10/data/default/ontime/2009_1_1_0/checksums.txt
    shadow/28/data/default/ontime/2009_1_1_0/checksums.txt

Those hard links pointing to same file should be processed by clickhouse-backup, but current behaviour is as follows:
- for `tree` strategy those are uploaded as duplicates to S3 and during download are created as separate files but with same content
- for `archive` strategy hard links are saved correctly in tar and during download are recreated as hard links, so result will be same structure as in `shadow` directory. N.B. After https://github.com/AlexAkulov/clickhouse-backup/pull/5 merge

But both strategies suffer from `restore` behaviour. It doesn't distinguish those kind of links, so duplicate partitions are copied/moved to `detached` folder multiple times and attached to table. In the end you will end up with duplicate rows in tables.

I plan to work on this, but wanted to discuss the way to fix this:
- Shall we fix this on upload/download part, so we'll have clean 1 copy of data in the `backup` folder
- Or fix on `restore` part - make it understand those links and process them.

P.S. To avoid this issue right now shadow directory should be cleaned after every backup. `clean` command may be used.

**Comment by anuriq** [comment]
https://github.com/AlexAkulov/clickhouse-backup/pull/7 was merged to master. this won't allow freeze, when shadow is not empty. this is a temporary solution to this problem.

**Comment by AlexAkulov** [comment]
Not relevant now.
Since v0.1.0 'create' command exists that creates each new backup in separate path and doesn't have this problem.
