### ISSUE TITLE
how to backup clickhouse to other local directory?

### ISSUE THREAD

**Issue by myabce** [Altinity/clickhouse-backup#603]
how to backup clickhouse to other local directory? it seems can not change it .

**Comment by Slach** [comment]
During backup clickhouse-backup execute ALTER TABLE ...FREEZE which create hard links to exists data parts in `/var/lib/clickhouse/shadow/database/table`
after it, to avoid allocate unnecessary disk space we just move these hard links to `/var/lib/clickhouse/backup/backup_name/shadow/db/table/`

it can't be changed
look https://en.wikipedia.org/wiki/Hard_link to figure out what is file system hard links

if you want copy backup data after creation to other disk
you can use use cp or mv command
