### ISSUE TITLE
Recreate table with uuid macros in zookeeper path

### ISSUE THREAD

**Issue by leqduyvp** [Altinity/clickhouse-backup#615]
Is there an option to change the 'CREATE TABLE' query in the backup to use {uuid} macro in zookeeper path?
My source tables were created with '/clickhouse/tables/{uuid}/{shard}' as zookeeper path parameter, but when I restore these tables, the uuid part is replaced with a fixed string, for example: '/clickhouse/tables/8e314902-c0a0-44a8-9938-7aadf8cccdaf/{shard}'

**Comment by Slach** [comment]
Table tried to restore with the same UUID which used for backup

replace `{uuid}` to string was resolve following clickhouse 22.5+ behavior
https://github.com/AlexAkulov/clickhouse-backup/issues/466
when clickhouse-server can't use `{uuid}` during create Replicated table only in one node without use ON CLUSTER

**Comment by Slach** [comment]
welcome to propose other solution

**Comment by leqduyvp** [comment]
Thank you for your quick response.

Can you add an option to use the {uuid} macros? Or should I use an older version of clickhouse-backup to have this behavior?

**Comment by Slach** [comment]
Could you explain? Which problem do you try to resolve?


Look to `SELECT * FROM system.clusters`

add to /etc/clickhouse-server/config.yml
```yaml
general:
  restore_schema_on_cluster: "your_cluster_name"
```

then `{uuid}` will not be replaced during creation inside clickhouse-backup
you shall understand, then `{uuid}` macro will resolve inside `clickhouse-server` when `CREATE TABLE .. ON CLUSTER ...` will execute on each node in `DDLWorker` thread

**Comment by leqduyvp** [comment]
Thanks a lot, I'll try again
