### ISSUE TITLE
Failed to build image

### ISSUE THREAD

**Issue by umang8223** [Altinity/clickhouse-backup#616]
**Issue**
- Running into error while building the image. Error is mentioned below
```
 => ERROR [image_full 5/6] COPY build/linux/amd64/clickhouse-backup /bin/clickhouse-backup 
 ```

- Looking at the Dockerfile, it seems that the binary is expected to be built in a previous build stage called **builder-docker**, using the make build command, and then copied into the build/linux/amd64 directory. However, it appears that this build stage has not been executed successfully.

**Comment by Slach** [comment]
look to `Makefile`
use
```
make build-docker config 
```
after it
```bash
docker buildx build --progress=plain --platform=linux/amd64,linux/arm64 --tag="your-repo/clickhouse-backup:latest" --target=image_short --pull --push .
docker buildx build --progress=plain --platform=linux/amd64,linux/arm64 --tag="your-repo/clickhouse-backup-full:latest" --target=image_full --pull --push .
```

**Comment by umang8223** [comment]
When i do, 
```
make build-docker config 
```
it exits with the below error
```
make: *** No rule to make target `build//amd64/clickhouse-backup', needed by `clickhouse-backup/clickhouse-backup'.  Stop.
```

So after when i build it using the below command 
```
docker buildx build --progress=plain --platform=linux/amd64,linux/arm64 --tag="your-repo/clickhouse-backup:latest" --target=image_short --pull --push .
docker buildx build --progress=plain --platform=linux/amd64,linux/arm64 --tag="your-repo/clickhouse-backup-full:latest" --target=image_full --pull --push .
```

it will throw below error as shown
```
 ERROR: "/build/linux/amd64/clickhouse-backup" not found: not found
```

**Comment by umang8223** [comment]
Initially when i did 
```
make build-docker config 
```

it was showing 
```
unknown shorthand flag: 'q' in -q
```

I just removed -q from the command in Makefile to solve the issue

**Comment by Slach** [comment]
Which OS do you use for running Makefile?

**Comment by umang8223** [comment]
Doing this locally on MAC terminal

**Comment by Slach** [comment]
Upgrade your docker 
to support `docker cp -q`

**Comment by Slach** [comment]
Current scripts tested only inside Linux

**Comment by umang8223** [comment]
> When i do,
> 
> ```
> make build-docker config 
> ```
> 
> it exits with the below error
> 
> ```
> make: *** No rule to make target `build//amd64/clickhouse-backup', needed by `clickhouse-backup/clickhouse-backup'.  Stop.
> ```
> 
> So after when i build it using the below command
> 
> ```
> docker buildx build --progress=plain --platform=linux/amd64,linux/arm64 --tag="your-repo/clickhouse-backup:latest" --target=image_short --pull --push .
> docker buildx build --progress=plain --platform=linux/amd64,linux/arm64 --tag="your-repo/clickhouse-backup-full:latest" --target=image_full --pull --push .
> ```
> 
> it will throw below error as shown
> 
> ```
>  ERROR: "/build/linux/amd64/clickhouse-backup" not found: not found
> ```

- I will try this steps on linux @Slach 
- Does this steps work successfully in linux ?

**Comment by Slach** [comment]
Yes, it works in everyday routine during development
What exactly you try to do? Just build docker image locally?
What goal?

**Comment by umang8223** [comment]
- Thanks @Slach, i was successfully able to build image on my ubuntu vm.

- My initial goal was to build clickhouse-backuptool image and later on referencing this image in the ibmclickhouse-server-image. 

- Now the plan is changed, i dont need this image anymore. Planning to build the binaries for clickhouse-backuptool for platform= amd64 & power. Later on will reference clickhouse-backuptool binaries in clickhouse-server-image.

I will be using the following below command to build binaries:
```
GOOS=linux GOARCH=amd64 go build -o clickhouse-backup-linux-amd64 ./cmd/clickhouse-backup

GOOS=linux GOARCH=ppc64le go build -o clickhouse-backup-linux-power ./cmd/clickhouse-backup
```
Can you please confirm that this are the right commands i am using. Thanks

**Comment by Slach** [comment]
Something like that

```bash
ENV NAME=clickhouse-backup 
ENV VERSION=$(git describe --always --tags --abbrev=0 2>/dev/null | sed 's/^v//;s/\([^-]*-g\)/c\1/;s/-/./g')
ENV GIT_COMMIT=$(git rev-parse HEAD)
ENV DATE=$(date +%F) 
RUN GOARCH=amd64 go build -buildvcs=false -ldflags "-X 'main.version=${VERSION}' -X 'main.gitCommit=${GIT_COMMIT}' -X 'main.buildDate=${DATE}'" -o clickhouse-backup-amd64 ./cmd/clickhouse-backup
RUN GOARCH=ppc64le go build -buildvcs=false -ldflags "-X 'main.version=${VERSION}' -X 'main.gitCommit=${GIT_COMMIT}' -X 'main.buildDate=${DATE}'" -o clickhouse-backup-ppc64le ./cmd/clickhouse-backup
```

Will ibm/clickhouse-server image contains jdbc bridges and odbc drivers?

**Comment by umang8223** [comment]
I do not think currently we have **jdbc bridges and odbc drivers** in ibm/clickhouse-server image.
