### ISSUE TITLE
remote backup s3 with sse-kms-key-id

### ISSUE THREAD

**Issue by jazz0013** [Altinity/clickhouse-backup#619]
is it possible to explicitly specify sse-kms-key-id for backup on s3?

**Comment by Slach** [comment]
Unfortunately, not. ;(
Currently 
it couldn't  be defined inside clickhouse-backup (only S3_SSE environment and s3->sse config could be setup, it define only SSE algorithm like AES256, aws:kms etc)
 
I will add it on 2.3.0 release

**Comment by jazz0013** [comment]
@Slach  Thank you.

**Comment by Slach** [comment]
@jazz0013 could you try docker image `altinity/clickhouse-backup:master`
