### ISSUE TITLE
Пустые данные при создание бэкапа

### ISSUE THREAD

**Issue by ehadiev** [Altinity/clickhouse-backup#62]
Starting clickhouse-backup
Attaching to clickhouse-backup
clickhouse-backup    | 2019/11/14 13:43:23 Create backup '1223456789'
clickhouse-backup    | 2019/11/14 13:43:23 Freeze `b`.`act`
clickhouse-backup    | 2019/11/14 13:43:23 Freeze `b`.`events`
clickhouse-backup    | 2019/11/14 13:43:23 Freeze `b`.`notifies`
clickhouse-backup    | 2019/11/14 13:43:23 Freeze `b`.`redirect`
clickhouse-backup    | 2019/11/14 13:43:23 Freeze `b`.`url`
clickhouse-backup    | 2019/11/14 13:43:23 Freeze `b`.`actual`
clickhouse-backup    | 2019/11/14 13:43:23 Freeze `m`.`events`
clickhouse-backup    | 2019/11/14 13:43:23 Freeze `m`.`notifies`
clickhouse-backup    | 2019/11/14 13:43:23 Freeze `m`.`op`
clickhouse-backup    | 2019/11/14 13:43:23 Freeze `m`.`redirects`
clickhouse-backup    | 2019/11/14 13:43:23 Freeze `m`.`url`
clickhouse-backup    | 2019/11/14 13:43:23 Copy metadata
clickhouse-backup    | 2019/11/14 13:43:23   Done.
clickhouse-backup    | 2019/11/14 13:43:23 Move shadow
clickhouse-backup    | 2019/11/14 13:43:23   Done.

clickhouse-backup коннектится к базе и видит таблицы (как видно из лога) 
но на выходе папки backup и shadow оказываются пустыми без каких-либо данных
хотя данные в таблицах из длга есть 
в директориях /var/lib/clickhouse/shadow и /var/lib/clickhouse/metadata данные также есть

не могу понять в чем проблема

**Comment by AlexAkulov** [comment]
Нужно смонтировать в контейнер clickhouse-backup папку кликхауса, обычно это /var/lib/clickhouse. При чём монтировать лучше так что-бы путь на хосте и в контейнере был одинаковый. т.е. /var/lib/clickhouse:/var/lib/clickhouse. Если у вас КХ хранит данные например в /mnt/clickhouse/data то монтируем /mnt/clickhouse/data:/mnt/clickhouse/data
