### ISSUE TITLE
check table after restore data

### ISSUE THREAD

**Issue by yuzhichang** [Altinity/clickhouse-backup#63]
https://github.com/ClickHouse/ClickHouse/pull/5865 `CHECK TABLE` checks every part's checksum. clickhouse-backup shall do this check if possible.

**Comment by AlexAkulov** [comment]
Should this be done before the creating backup, or after recovery, or should it be a separate command like `clickhouse-backup check`?

**Comment by aslubsky** [comment]
Hey @AlexAkulov are there any plans for this feature? It would be very helpful for backup post verification. Thanks

**Comment by Slach** [comment]
@aslubsky @yuzhichang 
maybe CHECK TABLE after ATTACH PART is not neccessary, cause during ATTACH PART clickhouse do the same operation with CHECK TABLE (calculate and compare checksums for files) 

please share your oppinion
