### ISSUE TITLE
 backups_to_keep_remote parameter deletes all backups

### ISSUE THREAD

**Issue by zil1** [Altinity/clickhouse-backup#634]
Hi,
if the value backups_to_keep_remote is non-zero, when the specified value is reached, all remote backups are deleted.
remote_storage: s3

clickhouse-backup version: 2.2.1
clickhouse version: 22.7

**Comment by Slach** [comment]
hm,, this function well tested
could you provide more context?

Could you share your
`clickhouse-backup upload` or `clickhouse-backup create_remote` command execution debug logs?

**Comment by Slach** [comment]
@zil1 any news?

**Comment by Slach** [comment]
close issue after topic started inactivity
