### ISSUE TITLE
Add path query parameter to server upload and download

### ISSUE THREAD

**Issue by mskwon** [Altinity/clickhouse-backup#638]
Would it be ok to make it so that the path configuration can be passed to the upload and download APIs of the server?

The use case is that I want to back up multiple instances of clickhouse to a single GCS "directory". The name of this path must be determined at time of backup request to fit my requirements.

**Comment by Slach** [comment]
No, this is a security hole


Your use case could be achieved by using values from `system.macros` in 
```yaml
s3:
  path: prefix/{macro1_name}/{macro2_name} 
```

look https://github.com/AlexAkulov/clickhouse-backup/blob/master/test/integration/config-s3.yml#L29
for example, i will add documentation about this featute

**Comment by mskwon** [comment]
Got it, thank you for the advice
