### ISSUE TITLE
memory leak while upload backup to s3

### ISSUE THREAD

**Issue by mikezsin** [Altinity/clickhouse-backup#65]
rss 4.1g( 4253984), repo size ~150GB

c000000000-c0fc000000 rw-p 00000000 00:00 0
Size:            4128768 kB
KernelPageSize:        4 kB
MMUPageSize:           4 kB
Rss:             3994276 kB
Pss:             3994276 kB
Shared_Clean:          0 kB
Shared_Dirty:          0 kB
Private_Clean:    202380 kB
Private_Dirty:   3791896 kB
Referenced:      3862512 kB
Anonymous:       3994276 kB
LazyFree:         202376 kB
AnonHugePages:         0 kB
ShmemPmdMapped:        0 kB
Shared_Hugetlb:        0 kB
Private_Hugetlb:       0 kB
Swap:                  0 kB
SwapPss:               0 kB
Locked:                0 kB
VmFlags: rd wr mr mw me ac

Version:	 v0.5.0
Git Commit:	 0655043ad69005572221daf6d63ba67aad0875a7
Build Date:	 2019-10-27

**Comment by AlexAkulov** [comment]
I don't see memory leak here, maybe garbage collector has not cleared this memory yet.

You can attach pprof and get detailed info of memory usage in app. Graphs of memory usage by time may be very useful for this too.
