### ISSUE TITLE
After 'clickhouse-backup create' , only find metadata, dont have shadow

### ISSUE THREAD

**Issue by chenshijian73-qq** [Altinity/clickhouse-backup#652]
clickhouse version：22.11.2
clickhouse-backup version: 2.2.5

clickhouse config: one shard two replica

```
CREATE database test2 on CLUSTER default
use csj 

CREATE TABLE Persons2 ON CLUSTER default(
   Id int  NOT NULL,
   LastName varchar(255),
   FirstName varchar(255),
   Address varchar(255),
   City varchar(255),
   PRIMARY KEY (Id)
)
ENGINE = ReplicatedReplacingMergeTree('/clickhouse/tables/{database}/{table}/{shard}', '{replica}');

INSERT INTO Persons2 (Id, LastName, FirstName, Address, City) VALUES (1, 'zhang', 'san', 'xinan', 'shenzhen');
INSERT INTO Persons2 (Id, LastName, FirstName, Address, City) VALUES (2, '2', 'san', 'xinan', 'shenzhen');
INSERT INTO Persons2 (Id, LastName, FirstName, Address, City) VALUES (3, '3', 'san', 'xinan', 'shenzhen');
```
```
clickhouse-backup tables
```
![image](https://github.com/AlexAkulov/clickhouse-backup/assets/116276614/0b0527b6-fce3-4248-b30e-ba3a787695cc)

```
clickhouse-backup create
```
![image](https://github.com/AlexAkulov/clickhouse-backup/assets/116276614/da7e54e2-fb25-4cd1-8545-8beb651e022d)

```
 clickhouse-backup list
```
![image](https://github.com/AlexAkulov/clickhouse-backup/assets/116276614/699b724b-b077-48f4-825b-72b934d19fab)

```
ls 2023-05-12T08-55-01
```
![image](https://github.com/AlexAkulov/clickhouse-backup/assets/116276614/52ea0537-90c5-400a-a852-a7b3626b23c6)

As you can see above, there is only metadata, no shadow, even restore cannot restore data.  So any required config Here?

**Comment by chenshijian73-qq** [comment]
this clickhouse-backup config file
```
general:
    remote_storage: none
    max_file_size: 0
    disable_progress_bar: true
    backups_to_keep_local: 5
    backups_to_keep_remote: 0
    log_level: info
    allow_empty_backups: false
    download_concurrency: 1
    upload_concurrency: 1
    use_resumable_state: true
    restore_schema_on_cluster: ""
    upload_by_part: true
    download_by_part: true
    restore_database_mapping: {}
    retries_on_failure: 3
    upload_retries_pause: 30s
    watch_interval: 1h
    full_interval: 24h
    watch_backup_name_template: shard{shard}-{type}-{time:20060102150405}
    retriesduration: 100ms
    watchduration: 1h0m0s
    fullduration: 24h0m0s
clickhouse:
    username: coding
    password: "coding123"
    host: 10.42.6.172
    port: 9000
    disk_mapping: {}
    skip_tables:
        - system.*
        - INFORMATION_SCHEMA.*
        - information_schema.*
        - _temporary_and_external_tables.*
    timeout: 5m
    freeze_by_part: false
    freeze_by_part_where: ""
    use_embedded_backup_restore: false
    embedded_backup_disk: ""
    secure: false
    skip_verify: false
    sync_replicated_tables: false
    log_sql_queries: false
    config_dir: /etc/clickhouse-server/
    restart_command: systemctl restart clickhouse-server
    ignore_not_exists_error_during_freeze: true
    check_replicas_before_attach: true
    tls_key: ""
    tls_cert: ""
    tls_ca: ""
    debug: false
```

**Comment by Slach** [comment]
>  host: 10.42.6.172

To make backup data `clickhouse-backup` requires access to the same file system as clickhouse-server, so `host` should be `localhost` or address / dns name of another docker container on the same machine, or IP address bound to some network interface on the same host.

**Comment by chenshijian73-qq** [comment]
The clickhouse I run on RKE, is there any specific example to back up the data ?
> > host: 10.42.6.172
> 
> To make backup data `clickhouse-backup` requires access to the same file system as clickhouse-server, so `host` should be `localhost` or address / dns name of another docker container on the same machine, or IP address bound to some network interface on the same host.

**Comment by Slach** [comment]
RKE means Rancher Kubernetes Engine?

How do you deploy clickhouse? Did you use altinity clickhouse-operator?

**Comment by chenshijian73-qq** [comment]
> 

Yes，means Rancher Kubernetes Engine. I deploy it using the helm chart of 'altinity/clickhouse-operator'

**Comment by Slach** [comment]
ok. look to
https://github.com/Altinity/clickhouse-backup/blob/master/Examples.md#how-to-use-clickhouse-backup-in-kubernetes
you should adapt your values.yaml
and improve `Kind: ClickHouseInstallation` manifest to allow custom podTemplate with clickhouse-backup container

**Comment by chenshijian73-qq** [comment]
> ok. look to https://github.com/Altinity/clickhouse-backup/blob/master/Examples.md#how-to-use-clickhouse-backup-in-kubernetes you should adapt your values.yaml and improve `Kind: ClickHouseInstallation` manifest to allow custom podTemplate with clickhouse-backup container

ok, thanks. let me take a try
