### ISSUE TITLE
Is it possible to backup data from clickhouse that not clickhouse-operator  deployed

### ISSUE THREAD

**Issue by MeehanCole** [Altinity/clickhouse-backup#657]
Hello all
cannot deploy clickhouse using operator for other reasons,  use the bitnami chart to deploy the clickhouse , how to use our tools to make the data backup ? any ideas ? 
i am looking forward your reply thanks

**Comment by Slach** [comment]
Yes, this is possible
`clickhiouse-backup` is not part of `clickhouse-operator`

this is a standalone binary which you could use as you wish.

If `bitnami` helm chart allows run `clickhouse-server` pod with a custom container, then you could add backup container with `altinity/clickhouse-backup` image

**Comment by Slach** [comment]
Unfortunatelly, according to 
https://github.com/bitnami/charts/blob/main/bitnami/clickhouse/templates/statefulset.yaml#L144

looks like bitnami helm chart allow run only one container in each Pod 

then you should create your own custom image
something  like that
```
FROM altinity/clickhouse-backup:latest AS backup
FROM bitnami/clickhouse:latest
COPY --from=backup /bin/clickhouse-backup /bin/clickhouse-backup
```
and create custom entrypoint which could run clickhouse-backup server and clickhouse-server binary inside the same container

another case just try to use BACKUP / RESTORE sql commands from modern version of clickhouse
https://clickhouse.com/docs/en/operations/backup#command-summary

**Comment by MeehanCole** [comment]
@Slach hello Slach
I have integrated our tool in bitnami chart ,  two containers in one pod and use the same data volume.  I look up into "How to use clickhouse-backup in Kubernetes" .  i didn't see any clickhouse-backup command or restful api to make the backup in the article  ,if I want to make the incremental backup action . any suggestion for me, documentation refer to  or examples ?  3s2r  mode , just take the data backup for first shard.

**Comment by Slach** [comment]
@KevinLiangX 
look to https://github.com/AlexAkulov/clickhouse-backup/blob/master/Examples.md?plain=1#L286-L381
