### ISSUE TITLE
FREEZE WITH NAME

### ISSUE THREAD

**Issue by yuzhichang** [Altinity/clickhouse-backup#66]
ClickHouse supports freeze a table with given name:
```
ALTER TABLE cdp_tags FREEZE WITH NAME 'abc';

...
2019.11.30 09:47:21.941618 [ 608 ] {a6445f03-179f-4970-bb3c-a57a65af3377} <Debug> default.cdp_tags: Freezing part f6b4ea42fb9c719593aebbee00e5526f_2_835_20_862 snapshot will be placed at /var/lib/clickhouse/shadow/abc/
```

`pkg/chbackup/backup.go Freeze(config Config, tablePattern string)` can be improved not to require shadow directory to empty.

**Comment by AlexAkulov** [comment]
Added in [v1.0.0-alpha1](https://github.com/AlexAkulov/clickhouse-backup/releases/tag/v1.0.0-alpha1)
