### ISSUE TITLE
API response - invalid JSON

### ISSUE THREAD

**Issue by NickStepanov** [Altinity/clickhouse-backup#661]
Clickhosue-backup version used: 2.2.5-2.2.7

**Problem definition:**

1. We're trying to create a Python application which will make a request to Clickhouse-backup API and implement some logic to interact with it.
2. We're using `requests` module to make a get request to `/backup/list` endpoint, like below:

```
import requests
import json

s = requests.Session()
s.auth = ('ch_backup_api_user', 'password')

try:
    r = s.get('https://hostname:7171/backup/list/local')
    print("Printing r.content")
    print(r.content)
    print("Printing r.text")
    print(r.text)
    print("Printing r.json()")
    print(r.json())
    r.raise_for_status()
```

We're getting this output:

```
Printing r.content
b'{"name":"shard01_mappings_schema","created":"2023-05-08 19:19:12","size":42800,"location":"local","required":"","desc":"regular"}\n{"name":"shard01_cubes_schema","created":"2023-05-08 19:24:47","size":1120401654697,"location":"local","required":"","desc":"regular"}\n'
Printing r.text
{"name":"shard01_mappings_schema","created":"2023-05-08 19:19:12","size":42800,"location":"local","required":"","desc":"regular"}
{"name":"shard01_cubes_schema","created":"2023-05-08 19:24:47","size":1120401654697,"location":"local","required":"","desc":"regular"}

Printing r.json()
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/requests/models.py", line 910, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib64/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.6/json/decoder.py", line 342, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 2 column 1 (char 130)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "try.py", line 19, in <module>
    print(r.json())
  File "/usr/local/lib/python3.6/site-packages/requests/models.py", line 917, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: [Errno Extra data] {"name":"shard01_mappings_schema","created":"2023-05-08 19:19:12","size":42800,"location":"local","required":"","desc":"regular"}
{"name":"shard01_cubes_schema","created":"2023-05-08 19:24:47","size":1120401654697,"location":"local","required":"","desc":"regular"}
: 130
```

3. It looks like the json returned by the API call is not valid and when trying to convert it from binary format to json, if fails on the `'\n'` part (character 130 in my example). The only option here is to use `r.text` and parse it manually, I guess.

**Request**
Is it possible to fix this and review the API response JSON formation to make it compatible with the applications?
If I am doing something wrong or misconfigured something - please let me know.

Thank you.

**Comment by Slach** [comment]
This format named as JSONEachRow/ JSONStringEachRow in clickhouse definitions 
https://www.perplexity.ai/search/191ae363-334b-4f6d-a5b1-d26c83884727?s=u
also known as ndjson i
https://www.perplexity.ai/search/708211bd-07e6-46b8-8db6-dd4ca49ad974?s=u
and used to system.backup_list sql table

you easily could read ndjson in streaming mode in Python
https://www.perplexity.ai/search/e25083f5-d5a5-4371-9eab-c2862a6ec84d?s=u
