### ISSUE TITLE
Do we have any api or command to clear the actions record ?

### ISSUE THREAD

**Issue by MeehanCole** [Altinity/clickhouse-backup#664]
hello sir
  Do we have any apis or command to clear the actions records ?

to clear the data as show 
[root@host01 ~]# curl '100.113.21.3:7171/backup/actions'
{"command":"list local","status":"success","start":"2023-06-01 14:19:08","finish":"2023-06-01 14:19:08"}
{"command":"list local","status":"success","start":"2023-06-01 14:20:35","finish":"2023-06-01 14:20:35"}
{"command":"create --tables=\"logs.log_queue_local\" 100-2023-06-01-8203087288","status":"success","start":"2023-06-01 14:20:35","finish":"2023-06-01 14:20:36"}
{"command":"list local","status":"success","start":"2023-06-01 14:20:36","finish":"2023-06-01 14:20:36"}
{"command":"upload --diff-from=\"100-2023-06-01-75591157\" 100-2023-06-01-8203087288","status":"success","start":"2023-06-01 14:20:36","finish":"2023-06-01 14:20:38"}
{"command":"list local","status":"success","start":"2023-06-01 14:21:10","finish":"2023-06-01 14:21:10"}
{"command":"list local","status":"success","start":"2023-06-01 14:28:17","finish":"2023-06-01 14:28:18"}
{"command":"delete local 100-2023-06-01-8203087288","status":"success","start":"2023-06-01 14:28:18","finish":"2023-06-01 14:28:18"}
{"command":"create --tables=\"logs.log_queue_local\" 100-2023-06-01-1627024481","status":"success","start":"2023-06-01 14:28:18","finish":"2023-06-01 14:28:18"}

**Comment by Slach** [comment]
Only restart API server
what the goal for the requested feature?

**Comment by MeehanCole** [comment]
As you known, we integrated our tools with clickhouse in one pod , it need take the backup by cronjob. so  I  developed one http client to do this task by restful api . There are a lot of exceptions that can happen during the procedure of backup.  watch the backup status or upload status to check if it finished. so the actions of upload record is a yardstick. if upload error ,we need to delete the backup automatically. sometime for troubleshooting  ,it need to clear the record  

maybe it just delete pod for clear the record  in my scene, right ?

**Comment by Slach** [comment]
> if upload error, we need to delete the backup automatically. sometime for troubleshooting ,it need to clear the record

ok. right API call sequences for upload

1.
```
POST /backup/actions
{"command":"upload unique-backup-name"}
```

2.
```
GET /backup/actions
```
read each line and check `status` for `"command":"upload unique-backup-name"`, wait when status = in progress

3. if status `success` 
```
POST /backup/actions
{"command":"delete local unique-backup-name"}
```

4. if status `error`, notify user and delete local backup  
```
POST /backup/actions
{"command":"delete local unique-backup-name"}
```

> maybe it just delete pod for clear the record in my scene, right ?

just restart `clickhouse-backup` container will enough (for example exec `pkill clickhouse-backup` inside container)

if you run `clickhouse-backup` separate from `clickhouse-server` you will fail with backup data
