### ISSUE TITLE
Can't FTP and SFTP specify a port other than the default one?

### ISSUE THREAD

**Issue by tri5m** [Altinity/clickhouse-backup#668]
Can't FTP and SFTP specify a port other than the default one?
When using SFTP, I am unable to set the port for the address and it automatically adds :22 as the default.

**Comment by Slach** [comment]
Use
```yaml
sftp:
  port: 2222
```

or
```yaml  
ftp:
 address: "host:2221"   
```

in config
sorry some options is miss in Readme.md
