### ISSUE TITLE
Doc for restore backup data for incremental type

### ISSUE THREAD

**Issue by MeehanCole** [Altinity/clickhouse-backup#671]
hello sir 

i backup the data by incremental way , 
![image](https://github.com/Altinity/clickhouse-backup/assets/40968187/7c434718-2cff-4ef4-ac67-e75156f83247)
if i want to restore all the datas ,  how shoud l do ?
$ clickhouse-backup restore-remote <backup name> 
first: restore the BaseData 
second: restore the next incremental data 
 ...
and so on

i saw  if the table exist , will delete the table first ,then make the backup in the table , if I restore the BaseData ,  is it override the BaseData by next incremental data ?

if we have any incremental backup and restore scenarios?

**Comment by MeehanCole** [comment]
update my output :
the first backupdate 
```
cat /root/BaseData-imp-clickhouse-shard1-0-2023-06-16T17\:00\:00/metadata/logs/log_queue_local.json 
{
	"files": {
		"default": [
			"default_all_0_8008_113.tar.gz",
			"default_all_8010_8528_21.tar.gz",
			"default_all_8529_8573_9.tar.gz",
			"default_all_8574_8574_0.tar.gz"
		]
	},
	"table": "log_queue_local",
	"database": "logs",
	"parts": {
		"default": [
			{
				"name": "all_0_8008_113"
			},
			{
				"name": "all_8010_8528_21"
			},
			{
				"name": "all_8529_8573_9"
			},
			{
				"name": "all_8574_8574_0"
			}
		]
	},
	"query": "CREATE TABLE logs.log_queue_local UUID '3d31f33b-2e6b-468d-b78d-c834cf021511' (`id` UUID DEFAULT generateUUIDv4(), `createdtime` DateTime64(3), `dbcreatedtime` DateTime DEFAULT now(), `expiretime` DateTime DEFAULT now() + toIntervalDay(30), `cluster_name` String, `node_name` String, `pod_name` String, `namespace` String, `container_name` String, `message` String) ENGINE = ReplicatedMergeTree('/clickhouse/tables/{shard}/log_queue_local', '{replica}') ORDER BY toYYYYMMDDhhmmss(createdtime) TTL dbcreatedtime + toIntervalDay(30) SETTINGS index_granularity = 8192",
	"size": {
		"default": 61692208
	},
	"total_bytes": 61688991,
	"metadata_only": false
the second incremetal backup date 
cat /root/imp-clickhouse-shard1-0-2023-06-16T17\:10\:00/metadata/logs/log_queue_local.json 
{
	"files": {
		"default": [
			"default_all_8529_8588_12.tar.gz",
			"default_all_8589_8593_1.tar.gz",
			"default_all_8594_8594_0.tar.gz"
		]
	},
	"table": "log_queue_local",
	"database": "logs",
	"parts": {
		"default": [
			{
				"name": "all_0_8008_113",
				"required": true
			},
			{
				"name": "all_8010_8528_21",
				"required": true
			},
			{
				"name": "all_8529_8588_12"
			},
			{
				"name": "all_8589_8593_1"
			},
			{
				"name": "all_8594_8594_0"
			}
		]
	},
	"query": "CREATE TABLE logs.log_queue_local UUID '3d31f33b-2e6b-468d-b78d-c834cf021511' (`id` UUID DEFAULT generateUUIDv4(), `createdtime` DateTime64(3), `dbcreatedtime` DateTime DEFAULT now(), `expiretime` DateTime DEFAULT now() + toIntervalDay(30), `cluster_name` String, `node_name` String, `pod_name` String, `namespace` String, `container_name` String, `message` String) ENGINE = ReplicatedMergeTree('/clickhouse/tables/{shard}/log_queue_local', '{replica}') ORDER BY toYYYYMMDDhhmmss(createdtime) TTL dbcreatedtime + toIntervalDay(30) SETTINGS index_granularity = 8192",
	"size": {
		"default": 62230884
	},
	"total_bytes": 62227198,
	"metadata_only": false
```

why just name": "all_0_8008_113", "name": "all_8010_8528_21", is required , we saw the first  backupdate , it has  4 parts .

**Comment by Slach** [comment]
Did you read `clickhouse-backup help restore_remote`?

https://github.com/Altinity/clickhouse-backup/blob/master/ReadMe.md?plain=1#L208

just use 
`clickhouse-backup restore_remote <your-backup-name>`

All necessary data will download and restore

> why just name": "all_0_8008_113", "name": "all_8010_8528_21", is required , we saw the first backupdate , it has 4 parts .

Check `cat /root/BaseData-imp-clickhouse-shard1-0-2023-06-16T17\:00\:00/metadata.json`
You will see a `required` backup which was used to create your backup.

`required` means data parts not present in current backup and present in some previous backup, which present in required backup sequence in `metadata.json`

Could you provide more context? 
what are your command sequences for crease `BaseData-*` and `imp-*` backups?

Do you use --diff-from-remote or --diff-from?

**Comment by Slach** [comment]
which clickhouse-backup version do you use?

**Comment by MeehanCole** [comment]
thanks for  your reply 

I've seen how it works.

my thoughouts is :  
If it is the first backup, the name starts with the Base*-XXX, and upload the full backup data , and the others are named the shards name + time.now(). use the --diff-from to upload 
![image](https://github.com/Altinity/clickhouse-backup/assets/40968187/331b69be-36b5-4cf0-9291-f2f5ff3c8166)

![image](https://github.com/Altinity/clickhouse-backup/assets/40968187/c9d84f56-689a-41b7-85d5-5ba215d7e433)

alexakulov/clickhouse-backup       2.2.6

**Comment by Slach** [comment]
change `alexakulov/clickhouse-backup` to `altinity/clickhouse-backup`

don't store all backups local
it will allocate a lot of disk space after mutations and background data part merges

use `diff-from-remote` instead of `diff-from`
