### ISSUE TITLE
Clickhouse password and username security

### ISSUE THREAD

**Issue by nguyenminhduc9988** [Altinity/clickhouse-backup#678]
Currently Clickhouse password and username are available in plaintext in config file. This is not secure.

I suggest we have some layer of security so that password is not available in plaintext and in a file.

**Comment by Slach** [comment]
clickhouse-backup support configure all config via ENVIRONMENT variables

look
https://github.com/Altinity/clickhouse-backup/blob/master/ReadMe.md#default-config

CLICKHOUSE_USERNAME, CLICKHOUSE_PASSWORD

Could you could create pull request for Vault support?

**Comment by Slach** [comment]
Is environment variable is enough secure for you?

**Comment by nguyenminhduc9988** [comment]
thanks
