### ISSUE TITLE
can't create backup with mkdir /mnt: read-only file system

### ISSUE THREAD

**Issue by jsding** [Altinity/clickhouse-backup#68]
Our clickhouse data data path is /mnt/data1/clickhouse, but run
`./clickhouse_backup --config ./config.yml create -t table table_20191216.bin
`
got

`2019/12/16 16:16:43 can't create backup with mkdir /mnt: read-only file system
`

How to pass the correct backup path to the config file?

Thanks

**Comment by AlexAkulov** [comment]
Try to create `/mnt/data1/clickhouse/backup` folder manually.
Make sure that you run clickhouse-backup from root or clickhouse user it is necessary for files interaction.

**Comment by AlexAkulov** [comment]
@jsding Have you solved this issue?

**Comment by jsding** [comment]
Hi, AlexAkulov,

Thanks for your attention.
Not yet, I run clickhouse-backup tool on other machine.

Can I create backup folder on other directory? Worring creating directory in clickhouse data will corrupt the database.

**Comment by AlexAkulov** [comment]
Change of 'backup' directory is not supported now. 
You don’t have to worry about this. Many people created '/var/lib/clickhouse/backup' directory and no one lost the data.

**Comment by empeekdev** [comment]
@AlexAkulov Does changing the destination folder still not supported? We use AWS Lambda to backup clickhouse and only `/tmp` folder is writable.

**Comment by Slach** [comment]
@empeekdev you can't use clickhouse-backup with AWS Lambda
cause clickhouse-backup require direct access to clickhouse server /var/lib/clickhouse folder for move hardlinks from detached to /var/lib/clickhouse/backups/<backup_name>/db/table/
