### ISSUE TITLE
Backup tool is not able to connect to CH server: wrong credentials issue

### ISSUE THREAD

**Issue by artempronevskiy** [Altinity/clickhouse-backup#69]
Hello,

This is weird issue but clickhouse-backup can't connect to clickhouse server. I tried pass credentials via env vars and via config, but no luck.

I have Clickhouse server running on 9001 port with default user and some password let's say 123. I can connect to CH via clickhouse-client w/o any problems:
```
$ clickhouse-client --port 9001 -u default --password 123
ClickHouse client version 19.13.1.11 (official build).
Connecting to localhost:9001 as user default.
Connected to ClickHouse server version 19.13.1 revision 54425.

clickhouse :) exit
Bye.
```
But connection to CH fails if I do it via clickhouse-backup:
```
$ export CLICKHOUSE_USERNAME=default
$ export CLICKHOUSE_PASSWORD=123
$ export CLICKHOUSE_PORT=9001
$ ./clickhouse-backup tables
2019/12/22 22:09:51 can't connect to clickouse with: code: 193, message: Wrong password for user default
```
Clickhouse-backup is the latest build:
```
./clickhouse-backup -v
Version:	 v0.5.1
Git Commit:	 5dc6234a1052c076de409666858bd4c1c6dbb48a
Build Date:	 2019-12-03
```

There is the same behavior if I pass creds and port via config file.
What can be wrong? How can I debug? Thanks.

**Comment by AlexAkulov** [comment]
Maybe your password contains special characters that break format string here https://github.com/AlexAkulov/clickhouse-backup/blob/6160f7f6d90fac0d0ff012231753f5e9411a9e14/pkg/chbackup/clickhouse.go#L77-L78

**Comment by artempronevskiy** [comment]
@AlexAkulov thanks for the reply. I will check this.

**Comment by AlexAkulov** [comment]
Have you resolved your issue?

**Comment by AlexAkulov** [comment]
Fixed in https://github.com/AlexAkulov/clickhouse-backup/releases/tag/v0.5.2
