### ISSUE TITLE
Unable to restore s3 backup authenticated with use_environment_credentials

### ISSUE THREAD

**Issue by chhan-coupang** [Altinity/clickhouse-backup#691]
When CLICKHOUSE_USE_EMBEDDED_BACKUP_RESTORE is enabled and embedded_backup_disk is set, 
create_remote can be backed up normally.
But an error is reported when restoring: `s3 is not present in object_disk.DisksCredentials`

I guess there is a problem with the implementation of the getObjectDisksCredentials function, and s3 cannot be saved to credentials when configuring `use_environment_credentials` authentication.
https://github.com/Altinity/clickhouse-backup/blob/master/pkg/storage/object_disk/object_disk.go#L320

Clickhouse storage configuration:
```xml
<clickhouse>
    <backups>
        <allowed_disk>s3</allowed_disk>
    </backups>
    <storage_configuration>
      <disks>
        <s3>
          <type>s3</type>
          <support_batch_delete>true</support_batch_delete>
          <endpoint>https://xxx.endpoint</endpoint>
          <metadata_path>/var/lib/clickhouse/s3/</metadata_path>
          <use_environment_credentials>true</use_environment_credentials>
        </s3>
      </disks>
      <policies>
        <s3>
          <volumes>
            <main>
              <disk>s3</disk>
            </main>
          </volumes>
        </s3>
      </policies>
    </storage_configuration>
</clickhouse>
```

**Comment by Slach** [comment]
this option is not supported yet

**Comment by chhan-coupang** [comment]
Thanks for your reply!
