### ISSUE TITLE
How to do backup and restore on a clickhouse cluster with 3 instances?

### ISSUE THREAD

**Issue by and1990** [Altinity/clickhouse-backup#692]
Hello. 

Thanks for providing such a great tool. I have installed clickhouse with 3 instances, and data be distributed to each 1 node with 1 replica. Now I wonder if what I do is right or wrong, please give me some advice.

I do **clickhosue-backup create**  on each instance, like this:
on instance 1:
> clickhouse backup create -t events backup_instance_01

on instance 2:
> clickhouse backup create -t events backup_instance_02

on instance 3:
> clickhouse backup create -t events backup_instance_03

Now I want to restore these data to a new clickhouse cluster, the new clickhouse cluster is also 3 instances. so I do **clickhouse-backup restore** on each instance, like this:
on instance 1:
> clickhouse backup restore backup_instance_01 -t events 

on instance 3:
> clickhouse backup create backup_instance_02 -t events 

on instance 3:
> clickhouse backup create backup_instance_03 -t events 

Is this the best practice to do clickhouse backup and restore? If wrong, please let me know. Thanks.

**Comment by Slach** [comment]
if you have 3 shards with only 1 replica in each shard
then your restore sequence looks good

could you share
`SELECT * FROM system.clusters`?
and share
`SHOW CREATE TABLE default.events FORMAT Vertical` ?

**Comment by and1990** [comment]
> SELECT * FROM system.clusters
```
cluster    |shard_num|shard_weight|replica_num|host_name|host_address|port|is_local|user   |default_database|errors_count|slowdowns_count|estimated_recovery_time|
-----------+---------+------------+-----------+-------------+------------+----+--------+-------+----------------+------------+---------------+-----------------------+
cluster_emr|        1|           1|          1|core-1-1|10.30.96.21 |9000|       0|default|                |           0|              0|                      0|
cluster_emr|        2|           1|          1|core-1-2|10.30.96.20 |9000|       0|default|                |           0|              0|                      0|
cluster_emr|        3|           1|          1|core-1-3|10.30.96.19 |9000|       1|default|                |           0|              0|                      0|

```

> SHOW CREATE TABLE default.events FORMAT Vertical
```
 CREATE TABLE default.events
(
    `_customer_id` String ,
    `_prokey` String,
    `_appkey`,
    `_event_name`,
    `_event_id`,
    `_ds` Date ,
    `_os_version`
)
ENGINE = MergeTree
PARTITION BY (_customer_id, _prokey, toYYYYMM(_event_time))
ORDER BY (_prokey, _event_name, _event_time)
SETTINGS index_granularity = 8192
```

What's more, **events** is a local table, and I have a distributed table **d_events** based on **events**, the structure of "d_events" table is below.
```
CREATE TABLE default.d_events
(
    `_customer_id` String ,
    `_prokey` String,
    `_appkey`,
    `_event_name`,
    `_event_id`,
    `_ds` Date ,
    `_os_version`
)
ENGINE = Distributed('cluster_emr', 'default', 'events', rand())
```

When I execute query, I use **d_events**, like this:
```
select count(*) from d_events;
```

**Comment by Slach** [comment]
your restore sequence looks good and shall work

**Comment by and1990** [comment]
OK. Thanks. Another question, how to specify the path of backup data?

**Comment by Slach** [comment]
`clickhouse-backup` creates hard links to exists data parts, it doesn't allocate disk space, only `inodes`

so, you need just delete local backup after upload it to remote storage, to avoid disk space allocation after clickhouse-server background merge data parts
