### ISSUE TITLE
Add support backup to `s3()/azureBlobStorage()` for `use_embedded_backup_restore: true`

### ISSUE THREAD

**Issue by Slach** [Altinity/clickhouse-backup#695]

**Comment by alifirat** [comment]
@Slach is the tool support a backup of an the s3 disk today ?

**Comment by Slach** [comment]
@alifirat 
yes, it support backup for s3 disk for MergeTree data
look details in 
https://github.com/Altinity/clickhouse-backup/blob/master/test/integration/config-s3.yml#L33-L34
and
https://github.com/Altinity/clickhouse-backup/blob/master/test/integration/dynamic_settings.sh#L88-L111

`s3_plain` is just different kind of s3 disk, and currently it not supported
