### ISSUE TITLE
Which version of clickhouse-backup should I use for v21.5.9.4 of clickhouse?

### ISSUE THREAD

**Issue by vnagappan-fiducia** [Altinity/clickhouse-backup#696]
Hi,

I am running Clickhouse cluster v21.5.9.4 and I get a warning that says this version of clickhouse is not supported by this script.
May I know which version of the script works with v21.5.9.4 of clickhouse please?

Thanks,
Venkat

**Comment by Slach** [comment]
This is warnging from clickhouse-go/v2 driver, all works ok. you can use clickhouse-backup:2.3.0

**Comment by vnagappan-fiducia** [comment]
Yes, you're right. Despite the warning everything worked just fine. Thanks.
