### ISSUE TITLE
--data flag should skip any UDF recreation step during restore

### ISSUE THREAD

**Issue by NickStepanov** [Altinity/clickhouse-backup#697]
Clickhouse-backup version: 2.2.7
Clickhouse-server version: 23.3

**Description and steps that lead to the problem:**

1. Source cluster contains UDFs.
2. A backup of data is created with `--data` flag.
3. A backup contains the definition of UDFs, even though it's a data backup.
4. On a destination server, when restoring backup with `--data` key, the restore fails with: 
`Code: 609. DB::Exception: User-defined function 'udfname' already exists. (FUNCTION_ALREADY_EXISTS) `
5. When inspecting the logs, we can see that this sequence of events is occurring:

Running on **host1**:
```
info DROP FUNCTION IF EXISTS `udfname` ON CLUSTER 'dest_cluster' logger=clickhouse
info CREATE FUNCTION udfname ON CLUSTER 'dest_cluster' AS ....
error metrics.ExecuteWithMetrics(restore) return error: code: 609, message: There was an error on [**host2**:9000]: Code: 609. DB::Exception: User-defined function 'udfname' already exists. (FUNCTION_ALREADY_EXISTS)
```

So, in fact, it looks like when restoring it on destination cluster, the function is unable to be dropped in time and the CREATE FUNCTION following right after, is failing? 

This problem is not consistent and we observed it for 10-15 tables out of 50+ tables restored, and it was occurring on different shards when restoring. A retry of a restore solved them.

**Question**

Why do we need to touch any DDL when we are restoring using `--data` key? I do not see the table being dropped and recreated, so why are we doing the recreation of the UDFs in this case? I would say this is an unexpected behaviour in this case.

**Comment by Slach** [comment]
look weird why `DROP FUNCTION ... ON CLUSTER ...` was successful but `CREATE FUNCTION .. ON CLUSTER` return `FUNCTION_ALREADY_EXISTS`

Do you try to run `clickhouse-backup` in parallel on separate hosts?

> Why do we need to touch any DDL when we are restoring using --data key? 

This is a good question!
I think this is a bug, let's fix it in the next release

**Comment by NickStepanov** [comment]
Isn't the drop async? I presume that once we run drop, a UDF on another host is still not being deleted and causes a creation error?

**Comment by NickStepanov** [comment]
And yes, we run restore on 2 nodes of the cluster in parallel, maybe that's causing the issue? But then the --data should only restore data, that's what I expected.

**Comment by Slach** [comment]
as quick workaround
remote from config
`restore_schema_on_cluster:'dest_cluster'`

it should help

**Comment by Slach** [comment]
> And yes, we run restore on 2 nodes of the cluster in parallel

please avoid run ATTACH PART during restore on two nodes in the same SHARD
for `ReplicatedMergeTree` tables you will doubled data and maybe failures during restore 

concurrent ATTACH PART to the replicated table with the same zookeeper path will make race condittion between ATTACH_PART replication event and ATTACH PART local statement

**Comment by NickStepanov** [comment]
> > And yes, we run restore on 2 nodes of the cluster in parallel
> 
> please avoid run ATTACH PART during restore on two nodes in the same SHARD for `ReplicatedMergeTree` tables you will doubled data and maybe failures during restore
> 
> concurrent ATTACH PART to the replicated table with the same zookeeper path will make race condittion between ATTACH_PART replication event and ATTACH PART local statement

Yes, I am restoring backups of shards 1,2,3,4 on shards 1 and 2, but I only restore shard 1 and 3 on shards 1 and 2 at the same time. Then I restore shards 2 and 4 or shards 1 and 2, so they should not compete, if I understood this correctly.

**Comment by Slach** [comment]
I hope you don't miss shards and replicas

**Comment by Slach** [comment]
i think you should read https://github.com/Altinity/clickhouse-backup/blob/master/Examples.md#how-to-make-backup--restore-sharded-cluster for proper use backup / restore command sequences for sharded backup

to avoid concurrency race condition during schema and data restore
if you use 
`restore_schema_on_cluster`
better apply it only for schema restore

during use `--data` you need to ensure your exists table have the same schema stucture with data parts which you try to restore

**Comment by Slach** [comment]
> A backup of data is created with --data flag.

`create` and `create_remote` doesn't have `--data` flags
only `--schema`

`--data` flag present only in `restore` and `restore_remote` commands

**Comment by NickStepanov** [comment]
> > A backup of data is created with --data flag.
> 
> `create` and `create_remote` doesn't have `--data` flags only `--schema`
> 
> `--data` flag present only in `restore` and `restore_remote` commands

Yes, my bad, got confused. I should remove that flag since it does nothing anyway!
