### ISSUE TITLE
JSON column type + check_part_columns, system.parts_column have different data type for different parts

### ISSUE THREAD

**Issue by Sh4yy** [Altinity/clickhouse-backup#699]
Hi folks,

I'm facing an issue with my incremental and full backups, and it's because of using the JSON column with dynamic data.

This is the error that I'm getting right now:

```
error `default`.`events` have inconsistent data types []string{"Tuple(_dummy UInt8)", "Tuple(icon String, notify UInt8, parser String)"} for "meta" column logger=clickhouse
error `default`.`events` have inconsistent data types for active data part in system.parts_columns backup=shard01-full-20230718050807 logger=backuper operation=create table=default.events
```

Any idea what could be causing this and if it's possible for me to fix this?

**Comment by Sh4yy** [comment]
I ran the optimized query on the table, which seemed to fix this issue. However, I continue to sometimes get the following error during incremental updates, which then switches back to a full backup.

```error `default`.`events` have inconsistent data types for active data part in system.parts_columns backup=shard01-full-20230718050807 logger=backuper operation=create table=default.events```

edit: I looked into this a bit further, and it seems like the increment failed because of the same inconsistent data type error on the JSON column. It then threw the following error and attempted another full backup.

```error delete local shard01-full-20230718060340 return error: 'shard01-full-20230718060340' is not found on local storage backup=shard01-full-20230718060340 logger=backuper operation=watch```

**Comment by Slach** [comment]
You could disable this check in `/etc/clickhouse-backup/config.yml`

```yaml
clickhouse:
  check_parts_columns: false
```

but not sure all restore ATTACH PART statements will work as expected during restore

**Comment by Slach** [comment]
similar with https://github.com/Altinity/clickhouse-backup/issues/685

**Comment by Sh4yy** [comment]
In that case, turning it off should be a no-go for anything in production. Do you know of a safer workaround or suggest changing the schema to get this going? Currently, a big blocker.

**Comment by Slach** [comment]
if you use clickhouse 23.3
then try
```
clickhouse:
  use_embedded_backup_restore: true
  embedded_backup_disk: disk_name
  check_parts_columns: false
```

look to https://github.com/Altinity/clickhouse-backup/blob/master/test/integration/dynamic_settings.sh#L164-L190 and 
https://github.com/Altinity/clickhouse-backup/blob/master/test/integration/config-s3-plain-embedded.yml

**Comment by Sh4yy** [comment]
Going to give this a try now!

**Comment by Sh4yy** [comment]
Ok, this took a bit to setup (had to add some fakekey to get S3 disk work with r2). I see backups are in progress, but keep seeing this warning in my logs. Is this something I need to be worried about or is there a way to resolve it?

```
warn can't open /var/lib/clickhouse/backup/shard01-increment-20230718173407/upload.state error: open /var/lib/clickhouse/backup/shard01-increment-20230718173407/upload.state: no such file or directory logger=resumable
warn /var/lib/clickhouse/backup/shard01-increment-20230718173407/upload.state empty, will continue from scratch error: open /var/lib/clickhouse/backup/shard01-increment-20230718173407/upload.state: no such file or directory logger=resumable
```

edit: I am assuming the issue has something to do with the added path for supporting r2 here?. Looking deeper into the logs I am now seeing this:

```
error create_remote shard01-full-20230718175111 return error: backup error: code: 499, message: Message: Unable to parse ExceptionName: InvalidPart Message: All non-trailing parts must have the same length., Key: data/r0000000000000000000000000000000000000000000000000000100101011011-file-lak/fcyhkagmqupifpbovlfbnqndcnpgx, Bucket: <redacted>-backup, Tags: "fc921881330f5e0e032069655060f492" "08b1406dc9ae9d1d02a9990ed3953b3b" "fb8e061c9a3d90d39fd7bb2a8678b2b3" "7ed44e7cc08c0ff2ea5e702e0e42a2a9" backup=shard01-full-20230718175111 logger=backuper operation=watch
```

**Comment by Slach** [comment]
warning about state, just warnings, you could ignore it

could you share

`LOG_LEVEL=debug S3_DEBUG=1 clickhouse-backup create_remote test_backup_name`
output?

and share
`clickhouse-backup print-config`
without sensitive credentials?
