### ISSUE TITLE
Why attach part Is Not Concurrent?

### ISSUE THREAD

**Issue by aoyeye00492654** [Altinity/clickhouse-backup#705]
The attach process is very slow during restore. Check the source code and find that the attach part is not concurrent. Why?

**Comment by Slach** [comment]
Which is your data size? 
How many tables and how many data parts do you have?

Usually, hundreds of tables and hundreds of data parts in each table (10 000 total), attached less then 3-4 minutes, is this slow for you?

We are open to pull requests

**Comment by Slach** [comment]
Any news from your side?

**Comment by aoyeye00492654** [comment]
The service table contains more than 90,000 parts, which may be caused by improper services. Plan to clear data and then migrate it. Thank you.

**Comment by Slach** [comment]
It looks like you have a wrong PARTITION BY expression in your table.

Look https://kb.altinity.com/engines/mergetree-table-engine-family/pick-keys/

**Comment by aoyeye00492654** [comment]
Yes, lack of proper partitioning and missing TTL!
