### ISSUE TITLE
Compatibility between backup from data on disk and Restore to S3MergeTree Engine. 

### ISSUE THREAD

**Issue by alifirat** [Altinity/clickhouse-backup#708]
Hi, 

We are using your solution to run daily backups of our data and our tables data are written on disk so our backups too. 

Recently, we have decided to switch our storage engine by moving to S3 Merge Tree and as expected the backups are not compatible between them. 

Did you already had a such use case ? If yes, is it "possible" to convert one backup on disk to s3 compatible backup ? 

Thanks for reading :)

**Comment by Slach** [comment]
Currently you have only one option to properly backup s3 disks

add backup s3 disk to clickhouse-server settings
look example https://github.com/Altinity/clickhouse-backup/blob/master/test/integration/dynamic_settings.sh#L205-L224 
better use credentials explicitly


```yaml
clickhouse:
  use_embedded_backup_restore: true
  embedded_backup_disk: <backup_s3_disk_name>    
```

look example https://github.com/Altinity/clickhouse-backup/blob/master/test/integration/config-s3-embedded.yml#L23
and add to `/etc/clickhouse-backup/config.yml`

**Comment by Slach** [comment]
`S3MergeTree` unknown engine, did you mean *MergeTree tables over S3 object disks defined in `system.storage_policies` ?

**Comment by Slach** [comment]
Do you want to make backup data from regular disk and restore to S3 disk?

**Comment by Slach** [comment]
If i understood properly, in your case
better will add s3 disks to exists storage policy
and add `TTL expr TO 's3_disk'` for selected tables
https://clickhouse.com/docs/en/engines/table-engines/mergetree-family/mergetree#ttl
https://clickhouse.com/docs/en/integrations/s3#s3-backed-mergetree
https://clickhouse.com/docs/en/engines/table-engines/mergetree-family/mergetree#table_engine-mergetree-s3

after it switch to embedded BACKUP/RESTORE support

https://github.com/Altinity/clickhouse-backup/issues/708#issuecomment-1651214799

**Comment by alifirat** [comment]
> Do you want to make backup data from regular disk and restore to S3 disk?

Exactly.

**Comment by alifirat** [comment]
What if my current storage policy is using the MergeTree with remote s3 disks and I apply a restore on locak disk ?
Do you think it's going to be correctly handle ?

**Comment by Slach** [comment]
No, it will not work, during restore, all local disks will restore as local, all s3 disks shall restore as s3

Because internally, these types of disks have different format.

s3 disks contain local files which contain references to s3 keys in remote s3 storage

**Comment by Slach** [comment]
i would like propose follwing
1) change storage policy
and add TTL to tables
https://github.com/Altinity/clickhouse-backup/issues/708#issuecomment-1651230501

2) change clickhouse-backup settings `use_embedded_backup_restore`

3) make first backup

**Comment by alifirat** [comment]
Hey @Slach 
I may find a different strategy but I'm wondering the following question: can I restore a table in a different database than the one I was for the backup ? 
I don't want to restore in `default` database but a different one like `backfill`, is it possible ?

**Comment by Slach** [comment]
@alifirat 
yes, it possible, but only to the same disk types
i repeat, root reason is different internal format for object disk and normal disk

use 
`clickhouse-backup restore --restore-database-mapping=default:backfill --tables=default.table`
