### ISSUE TITLE
EBS Snapshots and empty or missing files after restoring

### ISSUE THREAD

**Issue by daviddanielarch-nextroll** [Altinity/clickhouse-backup#711]
Hi, we are using clickhouse-backup to create a backup of our CH cluster and then create a snapshot of the EBS volume.
If the snapshot is created near the same time that the create command is performed we are noticing that the metadata.json file is missing once we restore the snapshot. 
Adding a sleep after create and before taking the snapshot seems to fix the issue, although sometimes the file is there but empty once we restore the EBS snapshot.
Is there any way to ensure that the contents of the backup files have been flushed to disk already?

**Comment by Slach** [comment]
How exactly did you execute a `create` command?
Did you use REST API or CLI?

**Comment by daviddanielarch-nextroll** [comment]
I'm inserting directly into the system.backup_actions table

**Comment by Slach** [comment]
Did you poll `system.backup_actions` with `WHERE command='create backup_name' AND status='success'` after execute?

**Comment by daviddanielarch-nextroll** [comment]
Yeah. We ended up calling https://clickhouse.com/docs/en/sql-reference/statements/system#sync-file-cache after the backup creation and before the snapshot generation and the files seem to be complete now.

**Comment by Slach** [comment]
`SYSTEM SYNC FILE CACHE` is not the same as
`SELECT status FROM system.backup_actions WHERE command='create your_backup_name'`
and check status='success'

most of the operations in REST API is async

**Comment by Slach** [comment]
So, any news? 
After adding poll of status from system.backup_actions, metadata.json should be created.

**Comment by daviddanielarch-nextroll** [comment]
We were already polling the status of on system.backup_actions but that did't seem to be enough.
We are calling  `SYSTEM SYNC FILE CACHE` after we see the status of the backup is `success` now, and that seems to do the trick to have the file created consistently

**Comment by Slach** [comment]
ok. glad to see you found a solution, let's close this issue
