### ISSUE TITLE
backup restore issue: tls: failed to verify certificate

### ISSUE THREAD

**Issue by karimennassiri** [Altinity/clickhouse-backup#714]
I followed the doc present here to restore a backup that is present in an S3 bucket. However, I can't do it no matter what method I use.

- Using the restore Job, I got this error

`INSERT INTO system.backup_actions(command) VALUES('restore_remote --schema --rm clickhouse-0.clickhouse.default.svc.cluster.local-full-2023-07-28-08-18-09')
still in progress clickhouse-0.clickhouse.default.svc.cluster.local-full-2023-07-28-08-18-09 on clickhouse-0.clickhouse.default.svc.cluster.local
still in progress clickhouse-0.clickhouse.default.svc.cluster.local-full-2023-07-28-08-18-09 on clickhouse-0.clickhouse.default.svc.cluster.local
SELECT start,finish,status,error FROM system.backup_actions WHERE command='restore_remote --schema --rm clickhouse-0.clickhouse.default.svc.cluster.local-full-2023-07-28-08-18-09'
2023-07-31 08:45:00	2023-07-31 08:45:07	error	\'clickhouse-0.clickhouse.default.svc.cluster.local-full-2023-07-28-08-18-09\' is not found on remote storage`

- Using the follwing command `clickhouse-backup restore_remote

`2023/07/31 08:42:13.774278  warn BackupList bd.Walk return error: operation error S3: ListObjectsV2, exceeded maximum number of attempts, 3, https response error StatusCode: 0, RequestID: , HostID: , request send failed, Get "https://s3.fr-par.scw.cloud/clickhouse-qa-backup?delimiter=%2F&list-type=2&max-keys=1000&prefix=": tls: failed to verify certificate: x509: certificate is valid for *.numericable.fr, numericable.fr, not s3.fr-par.scw.cloud logger=s3`

**Comment by Slach** [comment]
Update `/etc/clickhouse-backup/config.yml`
```
s3:
 disable_cert_verification: true
```

**Comment by Slach** [comment]
`x509: certificate is valid for *.numericable.fr, numericable.fr, not s3.fr-par.scw.cloud `

be careful with this provider, these settings allow make MITM attack for DNS HiJacking (attack your DNS server for example) and got your backuped data as is
