### ISSUE TITLE
Diff Snapshot Problem Consultation

### ISSUE THREAD

**Issue by aoyeye00492654** [Altinity/clickhouse-backup#715]
The last full snapshot already exists. Can I configure parameters to skip the download when downloading the diff snapshot or downloading the last full snapshot again?

**Comment by Slach** [comment]
i don't understand question
do you mean full backup present locally and you try to download or restore diff backup??

provide your clickhouse-backup command sequence for understanding

**Comment by aoyeye00492654** [comment]
On the source side:
```bash
clickhouse-backup -c /etc/clickhouse-backup/config.yml create -t ssb.test2 test0711;
clickhouse-backup -c /etc/clickhouse-backup/config.yml upload test0711;
clickhouse-backup -c /etc/clickhouse-backup/config.yml  create_remote  --diff-from-remote=test0711 test0711_diff; 
```

on the target side: I download test0711 first, then test0711_diff
```
clickhouse-backup -c /etc/clickhouse-backup/config.yml download test0711;
clickhouse-backup -c /etc/clickhouse-backup/config.yml download test0711_diff;
```

When I downloaded test0711_diff, I found that test0711 was also being downloaded. Even if the local backup test0711 already exists.

**Comment by aoyeye00492654** [comment]
As a result, the size of test0711 is more than 500 GB, and the size of test0711_diff is less than 100 MB. During incremental restoration, full data needs to be downloaded again, which is time-consuming.

**Comment by aoyeye00492654** [comment]
These parts {"required": true} already exist,why do I need to download the file again in the download diff backup?

**Comment by Slach** [comment]
you are wrong
according to
https://github.com/Altinity/clickhouse-backup/blob/master/pkg/backup/download.go#L582-L587
and
https://github.com/Altinity/clickhouse-backup/blob/master/pkg/backup/download.go#L633-L635

if requited parts already exist on `<RequiredBackup>` folder, then nothing will download and only hard links will create to allow properly backup restore

**Comment by Slach** [comment]
feel free re-open
if this is not
but provide 
`LOG_LEVEL=debug clickouse-backup download test0711_diff`
in this case
