### ISSUE TITLE
How to restore replicated tables ?

### ISSUE THREAD

**Issue by dcastanier** [Altinity/clickhouse-backup#72]
Hello,

I need to backup all my replicated tables locally, before doing some dangerous operations.
Backup is obvious, with: **clickhouse-backup create my-backup**
After delete or modify some data, how to restore it ?

- Drop database and **clickhouse-backup restore my-backup**
Replicated host will also drop all data and then copy all partitions after the restore. Could be long when database is large.
- No drop, and **clickhouse-backup restore my-backup**
Previous existing data will be duplicated, and also copied on replicas.
- Delete modified partition on database, keep only modified partition in backup folder, then **clickhouse-backup restore my-backup**
Look better since only need partition will be copied on replicas, but manual step is dangerous.
How to do that in an automatic way ?

**Comment by AlexAkulov** [comment]
Hi @dcastanier !
Do you want to be able to create backup of specific partitions? Have I understood that right?

**Comment by dcastanier** [comment]
No, I want a smarter restore, something like :
- for parts existing in backup and in ClickHouse => do nothing
- for parts existing only in backup => attach
- for parts existing only in ClickHouse => delete

**Comment by dcastanier** [comment]
Let me explain a use case.
Imagine a large production installation, with 6 ClickHouse hosts (3shards*2replicas), with 6TB (1 years of data).
Before upgrading all ClickHouse and Application services, we do a backup.
During upgrade, something doing wrongs, and we decide to rollback.
How to do a smart restore ?  (not drop all and restore all)

**Comment by AlexAkulov** [comment]
Sorry, I don't know how to restore backup of replicated database without full re-sync.
If you have ideas share them.

**Comment by Slach** [comment]
@dcastanier `clickhouse-backup` is make backup only data + schema from one node perspective
and can't know about all aspects of underlying table and database engine behaviors

for your use case, I would recommend the following steps:
1. make clickhouse-backup create in each node, stop data ingestion on all nodes 
2. update clickhouse-server in each replica one-by-one in some short period, start data ingestion and look to monitoring
3. if something wrong, stop data ingestion in all nodes
4. rollback clickhouse-server version in all nodes
5. run `clickhouse-backup restore --rm backup_name` only in one node in each shard, you will restore quickly cause local backup it's a just hard-links on the same disk and `attach` statement just move it to `/var/lib/cickhouse/store` or `/var/lib/clickhouse/data` (depends on database engine) after it all data will replicate to other nodes
6. start data ingestion in all nodes again, and insert again data lost between step 2 and step 5

I close issue during we don't have properly solution right now
maybe it should be another tool like "backup-cluster-manager" which can manage this use case

**Comment by suharevA** [comment]
Please specify how all the same it is correct to recover the data? Here is the cluster, 
```
chi-prod-backups-prod-01-0-0	127.0.0.1	1
chi-prod-backups-prod-01-0-1	10.42.190.169	2
chi-prod-backups-prod-01-1-0	10.42.124.63	1
chi-prod-backups-prod-01-1-1	10.42.190.130	2
```
ReplicatedMergeTree tables, 

I make a backup cronjob, an example is from here
https://github.com/AlexAkulov/clickhouse-backup/blob/master/Examples.md#how-to-use-clickhouse-backup-in-kubernetes

Do you need to restore a backup on all nodes? clickhouse-backup restore --rm my_backup
Or are there other requirements?

**Comment by Slach** [comment]
According to 
https://github.com/AlexAkulov/clickhouse-backup/blob/master/Examples.md#how-to-make-backup--restore-sharded-cluster

you need to run backup only on `chi-prod-backups-prod-01-0-0` and `chi-prod-backups-prod-01-1-0`
and `restore_remote --schema --rm <shardnum>-<backup_name>`  on `chi-prod-backups-prod-01-0-0` and `chi-prod-backups-prod-01-1-0`
and `restore_remote --rm <shardnum>-<backup_name>` on all replicas

need separate kind: Job for it

**Comment by suharevA** [comment]
The table is created like this
```
CREATE TABLE app.events_local ON CLUSTER '{cluster}' (
    time DateTime,
    event_id  Int32,
    uuid UUID
)
ENGINE = ReplicatedMergeTree('/clickhouse/tables/{cluster}/{shard}/{table}', '{replica}')
PARTITION BY toYYYYMM(time)
ORDER BY (event_id);
```
An error

```
clickhouse@chi-prod-backups-prod-01-0-0-0:/$ shard_number=$(clickhouse-client -q "SELECT getMacro('{shard}')")
Received exception from server (version 22.3.8):
Code: 62. DB::Exception: Received from localhost:9000. DB::Exception: No macro {shard} in config: While processing getMacro('{shard}'). (SYNTAX_ERROR)
(query: SELECT getMacro('{shard}'))
```

**Comment by Slach** [comment]
getMacro('shard') ?

**Comment by suharevA** [comment]
A. I understand. I have no tables Engine = Distributed.
Is this the correct way to recover?
https://github.com/AlexAkulov/clickhouse-backup/blob/master/Examples.md#how-to-make-backup--restore-sharded-cluster

**Comment by Slach** [comment]
It doesn't matter, engine=Distirbuted backup schema only

`{shard}` macro required for ReplicatedMergeTree to allow sharding (1+ replica in each shard)

during restore `engine=ReplicatedMegreTree` it is important to avoid execute concurrent `ALTER TABLE ... ATTACH PART` from replicas in the same shard

yes this is correct
https://github.com/AlexAkulov/clickhouse-backup/blob/master/Examples.md#how-to-make-backup--restore-sharded-cluster
I will fix documentation, thanks for reporting
