### ISSUE TITLE
invalid cross-device link

### ISSUE THREAD

**Issue by zhuziyuan** [Altinity/clickhouse-backup#726]
Hey, I am trying to use /var/lib/clickhouse/backup mounts a separate /de/vdc, which is not the same disk as clickhouse. 

**Problem:** 
2023/08/22 01:35:28.470267 error rename /var/lib/clickhouse/shadow/508bd7246c0a42f3afa1754257c547d1/store/3b9/3b97e98c-f66e-47d2-86ad-d44e0661261d/20200601_0_0_0/checksums.txt /var/lib/clickhouse/backup/2023-08-22T05-35-28/shadow/default/t_order_rep2/default/20200601_0_0_0/checksums.txt: invalid cross-device link

**Does anyone know why this is happening?**

**Comment by Slach** [comment]
https://github.com/Altinity/clickhouse-backup/issues/690

cross device link means 

`/var/lib/clickhouse/shadow/` and `/var/lib/clickhouse/backup/` mounted from different devices

clickhouse-backup create hard links during create backup, not copy data
it doesn't require a separate device mount
