### ISSUE TITLE
"driver: bad connection " Error during table freeze on table with big amount of partitions

### ISSUE THREAD

**Issue by dekstrin** [Altinity/clickhouse-backup#73]
As I understand, after upgrading Clickhouse on version 19.11.12.69 the clickhouse-backup starts to use FreezeTable method instead of FreezeTableOldWay. Which use `ALTER TABLE `%v`.`%v` FREEZE;`.  (instead of FREEZE PARTITION)
So then I'm trying to freeze table with big amount of partiotions it's takes more time for this operation. 
But after 3 minutes clickhouse-backup fails with error :
"2020/01/24 16:39:46 can't freeze `mydb`.`some_table_local` with: driver: bad connection"
This looks like some timeout from clickhouse-go driver ? 
Maybe we need an option like connection timeout or ability to choose freezing method ( oldway or new ) ?

**Comment by macEar** [comment]
The same behavior, on table with many partitions

**Comment by AlexAkulov** [comment]
'oldway' method use freezing by partition id and it was broken after 19.4.4.33.
I can try to increase timeout in clickhouse-go

**Comment by AlexAkulov** [comment]
I added CLICKHOUSE_TIMEOUT option, default value is 5m. 
Please, let me know if it's works. You can use `alexakulov/clickhouse-backup:master` docker image or build clickhouse-backup from source.

**Comment by AlexAkulov** [comment]
Has the increasing of CLICKHOUSE_TIMEOUT resolved this issue?

**Comment by dekstrin** [comment]
Hi! 
Sorry for late response, yes adding timeout resolved the issue, thank you!
