### ISSUE TITLE
 clickhouse-backup  error，How to solve it。Backup Disk('backups', '2023-08-25T07-31-31'): Path to backup must end with '/', but '2023-08-25T07-31-31' doesn't.

### ISSUE THREAD

**Issue by 774745428** [Altinity/clickhouse-backup#730]
clickhouse-backup create --tables=dba.t '2023-08-25T07-31-31/'
 
 `2023/08/25 16:01:55.451679  info clickhouse connection prepared: tcp://localhost:9000 run ping logger=clickhouse
WARNING: version 22.2.2 of ClickHouse is not supported by this client
2023/08/25 16:01:55.455704  info clickhouse connection open: tcp://localhost:9000 logger=clickhouse
2023/08/25 16:01:55.455833  info SELECT metadata_path FROM system.tables WHERE database = 'system' AND metadata_path!='' LIMIT 1; logger=clickhouse
2023/08/25 16:01:55.468387  info SELECT name, engine FROM system.databases WHERE name NOT IN ('system','INFORMATION_SCHEMA','information_schema','_temporary_and_external_tables') AND name IN ('dba') logger=clickhouse
2023/08/25 16:01:55.475410  info SHOW CREATE DATABASE `dba` logger=clickhouse
2023/08/25 16:01:55.478533  info SELECT name, count(*) as is_present FROM system.settings WHERE name IN (?, ?) GROUP BY name with args [show_table_uuid_in_table_create_query_if_not_nil display_secrets_in_show_and_select] logger=clickhouse
2023/08/25 16:01:55.484138  info SELECT name FROM system.databases WHERE engine IN ('MySQL','PostgreSQL','MaterializedPostgreSQL') logger=clickhouse
2023/08/25 16:01:55.486706  info    SELECT     countIf(name='data_path') is_data_path_present,     countIf(name='data_paths') is_data_paths_present,     countIf(name='uuid') is_uuid_present,     countIf(name='create_table_query') is_create_table_query_present,     countIf(name='total_bytes') is_total_bytes_present    FROM system.columns WHERE database='system' AND table='tables'   logger=clickhouse
2023/08/25 16:01:55.496473  info SELECT database, name, engine , data_paths , uuid , create_table_query , coalesce(total_bytes, 0) AS total_bytes   FROM system.tables WHERE is_temporary = 0 AND match(concat(database,'.',name),'^dba\.t$')  ORDER BY total_bytes DESC SETTINGS show_table_uuid_in_table_create_query_if_not_nil=1 logger=clickhouse
2023/08/25 16:01:55.513540  info SELECT metadata_path FROM system.tables WHERE database = 'system' AND metadata_path!='' LIMIT 1; logger=clickhouse
2023/08/25 16:01:55.518139  info SELECT count() as cnt FROM system.columns WHERE database='system' AND table='functions' AND name='create_query' SETTINGS empty_result_for_aggregation_by_empty_set=0 logger=clickhouse
2023/08/25 16:01:55.522452  info SELECT name, create_query FROM system.functions WHERE create_query!='' logger=clickhouse
2023/08/25 16:01:55.530078  info SELECT value FROM `system`.`build_options` where name='VERSION_INTEGER' logger=clickhouse
2023/08/25 16:01:55.532926  info SELECT count() is_disk_type_present FROM system.columns WHERE database='system' AND table='disks' AND name='type' logger=clickhouse
2023/08/25 16:01:55.537276  info SELECT path, any(name) AS name, any(type) AS type FROM system.disks GROUP BY path logger=clickhouse
2023/08/25 16:01:55.541176  info BACKUP TABLE `dba`.`t` TO Disk(?,?) with args [backups 2023-08-25T07-31-31] logger=clickhouse
2023/08/25 16:01:55.548843  info clickhouse connection closed logger=clickhouse
2023/08/25 16:01:55.549106 error backup error: code: 36, message: Backup Disk('backups', '2023-08-25T07-31-31'): Path to backup must end with '/', but '2023-08-25T07-31-31' doesn't.`

**Comment by 774745428** [comment]
[root@localhost config.d]# cat /etc/clickhouse-server/config.d/backup_disk.xml
<clickhouse>
    <storage_configuration>
        <disks>
            <backups>
                <type>local</type>
                <path>/dbbak/clickhouseBak/</path>
            </backups>
        </disks>
    </storage_configuration>
    <backups>
        <allowed_disk>backups</allowed_disk>
        <allowed_path>/dbbak/clickhouseBak/</allowed_path>
    </backups>
</clickhouse>

**Comment by 774745428** [comment]
[root@localhost config.d]# cat /etc/clickhouse-server/config.d/backup_disk.xml
<clickhouse>
    <storage_configuration>
        <disks>
            <backups>
                <type>local</type>
                <path>/dbbak/clickhouseBak/</path>
            </backups>
        </disks>
    </storage_configuration>
    <backups>
        <allowed_disk>backups</allowed_disk>
        <allowed_path>/dbbak/clickhouseBak/</allowed_path>
    </backups>
</clickhouse>

**Comment by 774745428** [comment]
[root@localhost config.d]# cat /etc/clickhouse-server/config.d/backup_disk.xml
```xml
<clickhouse>
    <storage_configuration>
        <disks>
            <backups>
                <type>local</type>
                <path>/dbbak/clickhouseBak/</path>
            </backups>
        </disks>
    </storage_configuration>
    <backups>
        <allowed_disk>backups</allowed_disk>
        <allowed_path>/dbbak/clickhouseBak/</allowed_path>
    </backups>
</clickhouse>
```

**Comment by Slach** [comment]
Oops, we filtered backup name from `/` to avoid path traversal vulnerability.

`/dbback/clickhouseBack` this is the same disk with /var/lib/clickhouse?
we never tried use local disks with `use_embedded_backup_restore: true`

**Comment by 774745428** [comment]
> /var/lib/clickhouse

/dbback/clickhouseBack and/var/lib/clickhouse are different disks. Due to insufficient space on a single disk, we want to backup to another disk

**Comment by 774745428** [comment]
> Oops, we filtered backup name from `/` to avoid path traversal vulnerability.
> 
> `/dbback/clickhouseBack` this is the same disk with /var/lib/clickhouse? we never tried use local disks with `use_embedded_backup_restore: true`

/dbback/clickhouseBack and/var/lib/clickhouse are different disks. Due to insufficient space on a single disk, we want to backup to another disk

**Comment by 774745428** [comment]
```
localhost :) 
             SELECT 
                 name, 
                 path
             FROM system.disks;

Query id: b135b5c2-6563-4fbd-8be7-b66870a03a74

┌─name────┬─path─────────────────────┐
│ backups │ /dbbak/clickhouseBak/ │
│ default   │ /data/clickhouse/          │
└─────────┴────────────────────────┘
```

**Comment by 774745428** [comment]
> 糟糕，我们过滤了备份名称`/`以避免路径遍历漏洞。
> 
> `/dbback/clickhouseBack`这是与 /var/lib/clickhouse 相同的磁盘吗？ 我们从未尝试过使用本地磁盘`use_embedded_backup_restore: true`

**Comment by 774745428** [comment]
> 过滤了备份名称`/`


Is there any way to not filter the backup name /

**Comment by 774745428** [comment]
> 糟糕，我们过滤了备份名称`/`以避免路径遍历漏洞。
> 
> `/dbback/clickhouseBack`这是与 /var/lib/clickhouse 相同的磁盘吗？ 我们从未尝试过使用本地磁盘`use_embedded_backup_restore: true`

Is there any way to not filter the backup name /

**Comment by Slach** [comment]
> Is there any way to not filter the backup name /

no way, it will security vulnerability (path traversal)

as a workaround, use s3 disk for backup

or use `use_embedded_backup_restore: false`
and just `mv -f /data/clickhouse/backup/backup_name /dbbak/clickhouseBak/` after `clickhouse-backup create backup_name`
