### ISSUE TITLE
Incremental upload time

### ISSUE THREAD

**Issue by liubo-it** [Altinity/clickhouse-backup#738]
What difference does this make？ 
`warn MAX_FILE_SIZE=1073741824 is less than actual 13071715768, please remove general->max_file_size section from your config logger=NewBackupDestination
`

**Comment by Slach** [comment]
old clickhouse-backup versions use manually defined max_file_size, which not allow properly calculate part size for s3 multipart upload

just remove
```
general:
  max_file_size: 1073741824 
```
from your config

**Comment by liubo-it** [comment]
@Slach    If I change it to 13071715768, what impact will it have and what cost will it increase? The Internet?

**Comment by Slach** [comment]
could impact to upload speed, but main impace only memory allocation buffers will increase
no need to change value
just remove it from config

it calculates in runtime from `system.parts`

**Comment by Slach** [comment]
what is your original question?

**Comment by liubo-it** [comment]
> what is your original question?

I am worried that this WRAN will cause my data to be lost，However, I do not know how much to adjust the MAX FILE SIZE

`warn MAX_FILE_SIZE=1073741824 is less than actual 13071715768, please remove general->max_file_size section from your config logger=NewBackupDestination`

The size is calculated automatically after the configuration is removed directly from the configuration file

Thank you very much for your support
