### ISSUE TITLE
S3 max_parts_count not respected may result in TotalPartsExceeded

### ISSUE THREAD

**Issue by rodrigargar** [Altinity/clickhouse-backup#739]
Because of the way the S3 part size is computed for a multipart upload, the resulting number of parts can exceed the value specified in max_parts_count.

In our case, max_parts_count is set to 10,000 (the maximum S3 value) and max_file_size is set to 1 TiB. When the backup size of a table reaches the max_file_size for uploading, the computed number of parts is more than 10,000 (I suspect it is 10,001) and the upload of the backup fails:
```
2023/09/01 06:52:24.444085 error UploadCompressedStream return error: MultipartUpload: upload multipart failed
upload id: LdghgFb82TZzmCc...
caused by: TotalPartsExceeded: exceeded total allowed configured MaxUploadParts (10000). Adjust PartSize to fit in this limit logger=uploadTableData`
```

config.yml
```
general:
  max_file_size: 1099511627776
  remote_storage: s3
  disable_progress_bar: True
  backups_to_keep_local: 2
  backups_to_keep_remote: 0
  log_level: error
  allow_empty_backups: False
  upload_by_part: False
  download_by_part: False
  download_concurrency: 32
  upload_concurrency: 16
clickhouse:
  username: default
  password:
  host: localhost
  port: 9000
  data_path: /var/lib/clickhouse
  skip_tables: ['system.*', 'information_schema.*', 'INFORMATION_SCHEMA.*']
  timeout: 5m
  freeze_by_part: False
  sync_replicated_tables: False
  log_sql_queries: False
  config_dir: /etc/clickhouse-server
  restart_command: systemctl restart clickhouse-server
s3:
  access_key:
  secret_key:
  bucket: backups-...-us-east-1-main
  endpoint:
  region: us-east-1
  acl: private
  force_path_style: False
  path: clickhouse
  disable_ssl: False
  compression_level: 1
  compression_format: tar
  sse: AES256
  disable_cert_verification: False
  storage_class: STANDARD
  part_size: 0
  max_parts_count: 10000
  debug: False
  concurrency: 16
  allow_multipart_download: True
``` 

As a workaround, we have decreased the max_parts_count to 5,000 to avoid exceeding the S3 maximum.

**Comment by Slach** [comment]
don't use too many small parts, upload speed will degrage

try implements another solution

**Comment by Slach** [comment]
please just remove max_part_size from config
currently it calculates from sytem.parts

**Comment by rodrigargar** [comment]
If I am not wrong, with max_file_size set to 1 TiB and max_parts_count set to 10000, the computed S3 part size is around 100 MB (with the count set to 5000 as workaround, part size is around 200 MB). Is that small for you? Which size would you recommend?

Note that we are not using the setting to upload / download by (clickhouse) part.
I forgot to mention we are using clickhouse-backup version 2.1.3. We may need to upgrade.

**Comment by Slach** [comment]
200 MB is enough

I mean when data size less 1Tb often part_size inside s3 section calculated as 2Mb

**Comment by rodrigargar** [comment]
> please just remove max_part_size from config currently it calculates from sytem.parts

Do you mean max_file_size or part_size (there is no max_part_size)? We set part_size to zero because of this comment:
`part_size: 0  # S3_PART_SIZE, if less or eq 0 then it is calculated as max_file_size / max_parts_count, between 5MB and 5Gb`

So I assume that part_size is always calculated 200 MB with our config.

**Comment by Slach** [comment]
yes, i mean max_file_size which calculated from system.parts
