### ISSUE TITLE
clickhouse-backup list output scalability and usability

### ISSUE THREAD

**Issue by vnagappan-fiducia** [Altinity/clickhouse-backup#749]
Hi, 

At the moment, I am running daily backups for around 10 tables in a database. I use the clickhouse-backup create_remote command to create and upload the backup which is working fine. 
This will produce 10 backups every day for the 10 tables. So if i run clickhouse-backup list, it lists 10 entries. I have a requirement to keep the daily backups for the last 12 months. Which means, 10 backups each day for 365 days. So the clickhouse-backup list command's output gradually grows and at the end of the year, the output will show 3650 entries.
My question is, 
1. is there any limitation on the number of backups we can store or this script can keep track of?
2. will the `clickhouse-backup list` command work fine with 1000s of entries to produce?

Thanks,
Venkat

**Comment by Slach** [comment]
> is there any limitation on the number of backups we can store or this script can keep track of?

No limits
3650 `backup_name/metadata.json` items will cache in `/tmp/.clickhouse-backup-cache.<remore_storage_type>`

**Comment by Slach** [comment]
fill free to reopen issue if your 3000 backups list command will slow
