### ISSUE TITLE
clickhouse-backup tool  support to stdout?

### ISSUE THREAD

**Issue by zouwenjie00** [Altinity/clickhouse-backup#759]
Hi:
   my clickhouse deploy on k8s,and want to come true backup ，the pod agent is  other team ，so i need realize the backup to stdout

**Comment by Slach** [comment]
clickhouse-bakcup make physical backup and don't support backup to stdout

if you want to make logical not phisical backup and search something like `mysqldump`
try to use stantard clickhouse-client and look details here
https://clickhouse.com/docs/en/integrations/data-formats/sql
