### ISSUE TITLE
clickhouse-backup stops when an error occures

### ISSUE THREAD

**Issue by Angel0r** [Altinity/clickhouse-backup#761]
Hey!

We faced a situation where we changed the data type of a table in our production ClickHouse and the clickhouse_backup stopped due to the error of inconsistent data types.
```
error `shard`.`table` have inconsistent data types []string{"UInt16", "Nullable(UInt16)"} for "col1" column logger=clickhouse
```

I assume we can remove the frozen parts and this will be fixed but if we need to keep the data, how should this be handled?

/Angelos

**Comment by Slach** [comment]
Which `clickhouse-backup` version do you use?
try to 2.4.2

look details in https://github.com/Altinity/clickhouse-backup/issues/747

if upgrade to 2.4.2 will not help
try setup
```yaml
clickhouse:
  check_parts_columns: false
```
in `/etc/clickhouse-backup/config.yml`

**Comment by AntonFriberg** [comment]
Will just leave a comment here on how we solved similar issue.

You can run OPTIMIZE FINAL command which removes old parts with incorrect types.
```sql
OPTIMIZE TABLE db_name.table_name ON CLUSTER '{cluster}' FINAL
```

Although if your tables are large you probably do not want to do it for the entire table and just for partitions that contain the parts causing the conflict. https://clickhouse.com/docs/en/optimize/avoidoptimizefinal

**Comment by Angel0r** [comment]
@Slach thank you for the answer!
When are you going to update [dockerhub](https://hub.docker.com/r/alexakulov/clickhouse-backup)?
We use docker in production and it is crucial for us.

**Comment by Slach** [comment]
@Angel0r did you read and understand https://github.com/Altinity/clickhouse-backup/issues/761#issuecomment-1764587255?

2.4.2 already released in docker

**Comment by Angel0r** [comment]
@Slach Yeap!
But I cannot update first so I can then set the "check_parts_columns" to false.
```
docker pull alexakulov/clickhouse-backup:2.4.2
Error response from daemon: manifest for alexakulov/clickhouse-backup:2.4.2 not found: manifest unknown: manifest unknown
```
The docker seems outdated: https://hub.docker.com/r/alexakulov/clickhouse-backup/tags

**Comment by Slach** [comment]
@Angel0r use `altinity/clickhouse-backup:2.4.2` instead

project moved to altinity organization 4 month ago after 2.3.0 release
look details 
https://altinity.com/blog/open-source-software-at-altinity

**Comment by Angel0r** [comment]
Oh! I see thanks!

**Comment by supnobita** [comment]
Hi, i got this issue when backup. 
` error db.table have inconsistent data types []string{"Array(Tuple(_id String, amount Float64, api String, percent Float64, providerId String, type String, unlockDate String))", "Array(Tuple(_id String, amount Float64, api String, lockId String, percent Float64, providerId String, type String, unlockDate String))"} for "locks" column logger=clickhouse
2023/11/20 09:51:35.881549 error db.table have inconsistent data types for active data part in system.parts_columns `. 
I already have run latest 2.4.5 version, but useless, temporary I use `check_parts_columns: false` to overcome it :(
