### ISSUE TITLE
Unable to restore single table from remote backup 

### ISSUE THREAD

**Issue by pivenappq** [Altinity/clickhouse-backup#763]
Greetings ! 

We are experiencing troubles restoring just one table from backup using restore_remote or just restore with --tables flag.
I've made 3 attempts:
1. clickhouse-backup restore_remote --tables=validator.validator_logs ocean_01_2023q3
2. clickhouse-backup restore_remote --tables=validator.validator_logs --data ocean_01_2023q3
3. clickhouse-backup download --tables=validator.validator_logs ocean_01_2023q3 + clickhouse-backup restore --tables=validator.validator_logs ocean_01_2023q3

All of them fell with error:
`2023/10/18 06:56:41.733357 error can't attach data parts for table 'validator.validator_logs': code: 233, message: Detached part "202304_1_8_2" not found`

Previous steps with creating tables and checks passed, the table appeared, and there are no detached parts in clickhouse since the command runs. Are we missing something?

clickhouse-backup version == 2.4.0
clickhouse-server == 23.3.13.7.altinitystable

**Comment by Slach** [comment]
could you share?
```
ls -la /var/lib/clickhouse/backup/ocean_01_2023q3/shadow/validator/validator_logs/default/202304_1_8_2
```

**Comment by pivenappq** [comment]
<img width="996" alt="image" src="https://github.com/Altinity/clickhouse-backup/assets/111285146/78e51f44-38d2-47ea-aead-2a8c5fd2c724">

**Comment by Slach** [comment]
could you share as text (not picture)
`SELECT * FROM system.disks` on destination server?

and share as text (not picture)
```
LOG_LEVEL=debug clickhouse-backup restore --tables=validator.validator_logs --data --partitions=202304 ocean_01_2023q3
```

if error still present
could you share:
```
ls -la /var/lib/clickhouse/data/validator/validator_logs/detached
```

**Comment by pivenappq** [comment]
SELECT * FROM system.disks

```
+-------+--------------------+------------+------------+----------------+---------------+-----+------------+------------+-------------+---------+---------+----------+
|name   |path                |free_space  |total_space |unreserved_space|keep_free_space|type |is_encrypted|is_read_only|is_write_once|is_remote|is_broken|cache_path|
+-------+--------------------+------------+------------+----------------+---------------+-----+------------+------------+-------------+---------+---------+----------+
|default|/var/lib/clickhouse/|450985254912|940497096704|431096540444    |0              |local|0           |0           |0            |0        |0        |          |
+-------+--------------------+------------+------------+----------------+---------------+-----+------------+------------+-------------+---------+---------+----------+
```

debug log: 
[debug.log](https://github.com/Altinity/clickhouse-backup/files/12999349/debug.log)

error is still present:
`ls: cannot access '/var/lib/clickhouse/data/validator/validator_logs/detached': No such file or directory`

**Comment by Slach** [comment]
looks weird
logs show us
```
2023/10/18 08:33:50.214323 debug Link /var/lib/clickhouse/backup/ocean_01_2023q3/shadow/validator/validator_logs/default/202304_1_8_2/partition.dat -> /var/lib/clickhouse/store/256/256b950b-3c64-4d21-afd4-152290c170e8/detached/202304_1_8_2/partition.dat operation=HardlinkBackupPartsToStorage
2023/10/18 08:33:50.214333 debug Link /var/lib/clickhouse/backup/ocean_01_2023q3/shadow/validator/validator_logs/default/202304_1_8_2/primary.idx -> /var/lib/clickhouse/store/256/256b950b-3c64-4d21-afd4-152290c170e8/detached/202304_1_8_2/primary.idx operation=HardlinkBackupPartsToStorage
```

it means hard links successfully created
could you share as text
```
ls -la /var/lib/clickhouse/store/256/256b950b-3c64-4d21-afd4-152290c170e8/detached/
```

and 
```
SELECT * FROM system.detached_parts WHERE database='validator' AND table='validator_logs' FORMAT Vertical
```

**Comment by pivenappq** [comment]
yes, sure

ls -la /var/lib/clickhouse/store/256/256b950b-3c64-4d21-afd4-152290c170e8/detached/
```
total 68
drwxr-x--- 17 clickhouse clickhouse 4096 Oct 17 11:06 .
drwxr-x---  3 clickhouse clickhouse 4096 Oct  3 12:15 ..
drwxr-x---  2 clickhouse clickhouse 4096 Oct  3 12:15 202304_1_8_2
drwxr-x---  2 clickhouse clickhouse 4096 Oct  3 12:15 202305_9_166_57
drwxr-x---  2 clickhouse clickhouse 4096 Oct  3 12:15 202306_1047_1047_0
drwxr-x---  2 clickhouse clickhouse 4096 Oct  3 12:15 202306_167_1046_373
drwxr-x---  2 clickhouse clickhouse 4096 Oct  3 12:15 202307_1048_9230_539
drwxr-x---  2 clickhouse clickhouse 4096 Oct  3 12:15 202308_14769_15717_496
drwxr-x---  2 clickhouse clickhouse 4096 Oct  3 12:15 202308_15718_15720_1
drwxr-x---  2 clickhouse clickhouse 4096 Oct  3 12:15 202308_9231_14768_563
drwxr-x---  2 clickhouse clickhouse 4096 Oct 17 11:06 202309_15721_16452_320
drwxr-x---  2 clickhouse clickhouse 4096 Oct  3 12:15 202309_15721_19055_894
drwxr-x---  2 clickhouse clickhouse 4096 Oct  3 12:15 202309_19056_21267_387
drwxr-x---  2 clickhouse clickhouse 4096 Oct  3 12:15 202309_21268_21485_54
drwxr-x---  2 clickhouse clickhouse 4096 Oct  3 12:15 202309_21486_21486_0
drwxr-x---  2 clickhouse clickhouse 4096 Oct  3 12:15 202309_21487_21487_0
drwxr-x---  2 clickhouse clickhouse 4096 Oct  3 12:15 202309_21488_21488_0
```

SELECT * FROM system.detached_parts WHERE database='validator' AND table='validator_logs' FORMAT Vertical;
returns 0 rows

**Comment by Slach** [comment]
```
SELECT uuid FROM system.tables WHERE  database='validator' AND table='validator_logs'
```

**Comment by pivenappq** [comment]
256b950b-3c64-4d21-afd4-152290c170e8

**Comment by Slach** [comment]
could you share 
`cat /var/lib/clickhouse/backup/ocean_01_2023q3/metadata.json` ?

**Comment by Slach** [comment]
```
ls -la /var/lib/clickhouse/store/256/256b950b-3c64-4d21-afd4-152290c170e8/detached/202304_1_8_2/
```

**Comment by pivenappq** [comment]
metadata:
[metadata.json](https://github.com/Altinity/clickhouse-backup/files/13008219/metadata.json)


ls result: 
```
total 44
drwxr-x---  2 clickhouse clickhouse 4096 Oct  3 12:15 .
drwxr-x--- 17 clickhouse clickhouse 4096 Oct 17 11:06 ..
-rw-r--r--  2 clickhouse clickhouse  246 Oct 17 11:06 checksums.txt
-rw-r--r--  2 clickhouse clickhouse  661 Oct 17 11:06 columns.txt
-rw-r--r--  2 clickhouse clickhouse    1 Oct 17 11:06 count.txt
-rw-r--r--  2 clickhouse clickhouse 3262 Oct 17 11:06 data.bin
-rw-r--r--  2 clickhouse clickhouse  880 Oct 17 11:06 data.mrk3
-rw-r--r--  2 clickhouse clickhouse   10 Oct 17 11:06 default_compression_codec.txt
-rw-r--r--  2 clickhouse clickhouse    8 Oct 17 11:06 minmax_created_at.idx
-rw-r--r--  2 clickhouse clickhouse    4 Oct 17 11:06 partition.dat
-rw-r--r--  2 clickhouse clickhouse    8 Oct 17 11:06 primary.idx
```

**Comment by Slach** [comment]
could you share
`SELECT * FROM system.storage_policies`?

**Comment by Slach** [comment]
How did you upload metadata.json?
It miss quotes and doesn't look like valid json

ok
you create backup on following versions
```
	version: 2.4.0,
	clickhouse_version: v22.3.12.20.altinitystable,
```

And try to restore on `clickhouse-server == 23.3.13.7.altinitystable`? Am I right?

**Comment by Slach** [comment]
could you share
`cat /var/lib/clickhouse/backup/ocean_01_2023q3/metadata/validator/validator_logs.json`

**Comment by Slach** [comment]
do you run clickhouse-backup with access on the same disks as clickhouse-server?
is this standalone server? or docker container?

**Comment by pivenappq** [comment]
> is this standalone server? or docker container?

your question helped me to resolve that issue, the clickhouse-server was in container on this machine, but it was an issue with hardlinks
problem solved, i've successfully recovered data

thank you for your help
