### ISSUE TITLE
Backup metadata for disaster recovery cluster

### ISSUE THREAD

**Issue by Shankara-git** [Altinity/clickhouse-backup#764]
In our deployment data is stored at GCS bucket and we want to take backup only metadata part and reuse the data in GCS bucket.

I have tried 'clickhouse-backup create_remote --schema --rbac --configs' command but it is not backing up metadata at
/var/lib/clickhouse/disks/{disk_name}/store
/var/lib/clickhouse/metadata/{db}/{table}.sql
we are using GCS as a storage and we don't want to take backup of data again. so, we want to take only metadata as a backup   (/var/lib/clickhouse/disks/{disk_name}/store and /var/lib/clickhouse/metadata/{db}/{table}.sql)

is it possible with clickhouse-backup ? or is it possible to use rclone command as a custom command is clickhouse-backup ?

Thanks

**Comment by Slach** [comment]
duplicated with https://github.com/Altinity/clickhouse-backup/issues/762

look answers in original issue
