### ISSUE TITLE
example on how to implement rclone

### ISSUE THREAD

**Issue by schalekamp** [Altinity/clickhouse-backup#766]
can you give some examples of how to implement rclone please?

**Comment by Slach** [comment]
no example, try to figure out with rsync examples 
https://github.com/Altinity/clickhouse-backup/tree/master/test/integration/rsync

and you are welcome to make a pull request

**Comment by schalekamp** [comment]
Thank you for the pointer.

I have modified config.yml and added these custom commands that seem to work with rclone.

```custom:
  upload_command: "rclone sync /var/lib/clickhouse/backup/{{ .backupName }} dropbox:clickhouse-backups/{{ .backupName }}"

  download_command: "rclone sync dropbox:clickhouse-backups/{{ .backupName }} /var/lib/clickhouse/backup/{{ .backupName }}"

  delete_command: "rclone delete dropbox:clickhouse-backups/{{ .backupName }}"

  list_command: "rclone lsd dropbox:clickhouse-backups"
```

**Comment by Slach** [comment]
Thanks for sharing, not sure `list_command` will work properly, cause required json output with format each line json looks like that
```json
{"backup_name":"backup-name","creation_date":"YYYY-MM-DD HH:MI:SS","data_size":12312313,"metadata_size":1234}
```

so it should something like that 

list backup names and after it cat backup_name/metadata.json as single line json
```yaml
 list_command: "rclone lsd dropbox:clickhouse-backups | while IFS= read -r backup_name ; do rclone cat dropbox:clickhouse-backups/${backup_name}/metadta.json | jq -c -r -M \'.\'; done' "
```
