### ISSUE TITLE
CH Backup / Restore - Restoration works partially If inflow of records are not stopped

### ISSUE THREAD

**Issue by karthik-thiyagarajan** [Altinity/clickhouse-backup#783]
We are using this backup / restore container to create ClickHouse Backup. I found an issue where the restore is happening only partially in a specific case and i thought i should report here. Here are the steps to replicate.

1. We have a 3 shards 3 replica setup. 
2. Create table X with "date" field as your partition key and with millions of records inserted for every date range for the last one week or two week. Use rand() for your parition key distribution. 
3. Create a backup of this table
4. Create a pod, that will keep inserting records to this table continuously.

Use Case 1: 
Now when i drop the table and run the restore process, it restores the data partially only for partial dates.

Use Case 2 : 
When i stop the inflow of records to this table "X" by shutting down the respective pod and then initiate the restoration, it restores for all dates correctly.

Is this the expected behaviour or is it due to some bugs ?

**Comment by Slach** [comment]
> Now when i drop the table and run the restore process, it restores the data partially only for partial dates.

could you explain step by step
which is your restore process actually?

did you read https://github.com/Altinity/clickhouse-backup/blob/master/Examples.md#how-to-back-up--restore-a-sharded-cluster ?

**Comment by Slach** [comment]
Which Engine have your table `X` ?

**Comment by karthik-thiyagarajan** [comment]
I am using replicated merge tree for the table X. And yes, i did read the documentation and i am using the same script that was given in the backup-restore example where the schema restore is happening in all the shards and all the replicas and then restoration of data is happening only on first replica of each shard.

My point is that my restoration is not happening completely for all the days, when some other pods are trying to write the data into the same table X. However, if i stop the inflow , it seems to be working. 

I gave a simplest example above, and in my real use case, we have some 10 tables, and each table is a replicated merge tree, with date as the partition key. There are some 5 application pods which are reading from kafka and writing to clickhouse as and when the data is coming in. Each pod writes to 2 tables.

Working use case : 
1. Run a backup process which takes backup of each shard and each replica and store in s3 bucket. 
2. Run a query against each table and see the count of records inserted per date. 
3. Shut down all the above application pods (~5 pods)  writing to those 10 tables (replicated merge tree). 
4. Run the restore process to (i) restore schema in all the shards and all the replicas (ii) run the restore data process in the first replica of each shard.
5. Verified the count to see if the counts are approximately matching and it does match the count.
6. Bring up those 5 application  pods back. 


Failing test case : 
1. Run a backup process which takes backup of each shard and each replica and store in s3 bucket. 
2. Run a query against each table and see the count of records inserted per date. 
3. Let the app pods run continuously when the restoration is happening and dont shut down those pods. 
4. Run the restore process to (i) restore schema in all the shards and all the replicas (ii) run the restore data process in the first replica of each shard.
5. Verified the count to see if the counts are approximately matching and it appears that the backup process restores data partially. In some tables tables, it restores only today's data and yesterday's data and where as in other tables.


I guess in the first use case, somehow the process is unable to freeze those partitions successfully. However for those tables that are undisturbed, the records are restored successfully. 

Even though the restoration is partially successful, still the overall status in the backup_actions table is still updated "Success", which is making me to think that it is success which is not actually true.

Is there a log file that i can find in the clickhouse-backup side car that can check ?

**Comment by Slach** [comment]
> My point is that my restoration is not happening completely for all the days, when some other pods are trying to write the data into the same table X.

This shall be not impact, your inserting pod will just add new data parts blocks which not intersected with restored blocks from `ALTER TABLE ... ATTACH PART`

but if you insert the same data blocks it could be skipped by ReplicationMergeTree block deduplication

> Working Use case
> 5. Verified the count to see if the counts are approximately matching and it does match the count.

Does it look something like that?
```sql
SELECT hostName() h, toDate(date_field) dt, count() FROM cluster('all-sharded',db.table) GROUP BY h, dt ORDER BY dt, h
``` 

> Not worked use case
> 4. Run the restore process to (i) restore schema in all the shards and all the replicas (ii) run the restore data process in the first replica of each shard.

(i) Restore schema will DROP + CREATE TABLE will your inserting pod handle errors when table not exists?

(ii) restore data will execute `ALTER TABLE ... ATTACH PART...` statement which will replicate to  other replicas if you use *ReplicatedMergeTree

it shall be not affected with INSERT INTO new data blocks

Could you share `clickhouse-backup` container log during backup restore operation?
And provide SHOW CREATE TABLE structure for the affected table?

**Comment by karthik-thiyagarajan** [comment]
Can you give me the log path of clickhouse-backup container?

**Comment by Slach** [comment]
clickhouse-backup container write logs to stdout

use `kubectl logs` for access log

**Comment by Slach** [comment]
@karthik-thiyagarajan 
any news from your side about logs?
is issue still present?

**Comment by karthik-thiyagarajan** [comment]
Will send today.

**Comment by Slach** [comment]
@karthik-thiyagarajan 
Is issue still present or you figure out?

**Comment by Slach** [comment]
closed after topic starter inactivity

**Comment by Slach** [comment]
ափսոս, որ մանրամասն տեղեկություններ չեք տրամադրել
