### ISSUE TITLE
Cleaner support for S3 buckets with ACL disabled

### ISSUE THREAD

**Issue by vitaliyf** [Altinity/clickhouse-backup#785]
AWS changed S3 defaults in April 2023 so that all new buckets have ACL disabled: https://aws.amazon.com/blogs/aws/heads-up-amazon-s3-security-changes-are-coming-in-april-of-2023/

They also recommend that ACLs are disabled: https://docs.aws.amazon.com/AmazonS3/latest/userguide/ensure-object-ownership.html

But right now clickhouse-backup always passes an ACL when uploading objects: https://github.com/Altinity/clickhouse-backup/blob/f9a78943da5796e6358861ccf42fa3b5bd9e14c0/pkg/storage/s3.go#L265-L267 which will result in `api error AccessControlListNotSupported: The bucket does not allow ACLs` errors.

It looks like you can get around this using `acl: ""` in config.xml, but it would be simpler if it was just completely optional.

**Comment by Slach** [comment]
thanks a reporting, 
looks weird, we add private ACL by default, because backup shall not be available from public
and for old s3 bucket it sill shall works

maybe properly solution here will handle ACL related error and retry

**Comment by vitaliyf** [comment]
Right, of course - but Amazon has been steering everyone away from using S3 ACLs at all (those articles explain why - it's mainly because someone can accidentally use acl=public, and disabling ACLs completely prevents any chance of any files being exposed).

Maybe you should only document `acl: ""`, or make that the default. Retry could 2x number of requests to S3 which aren't free, BTW 🥲

**Comment by Slach** [comment]
ok. agree, let's make acl: "", by default and document available values with document references

**Comment by Slach** [comment]
Don't sure will it work good for other s3 compatible providers ;(
