### ISSUE TITLE
Backup stoped with error "have inconsistent data types"

### ISSUE THREAD

**Issue by supnobita** [Altinity/clickhouse-backup#789]
Hi, I facing with issue when backup my cluster.
`error db.table have inconsistent data types []string{"Array(Tuple(_id String, amount Float64, api String, percent Float64, providerId String, type String, unlockDate String))", "Array(Tuple(_id String, amount Float64, api String, lockId String, percent Float64, providerId String, type String, unlockDate String))"} for "locks" column logger=clickhouse 2023/11/20 09:51:35.881549 error db.table have inconsistent data types for active data part in system.parts_columns`

I've already install latest version 2.4.5, but it didn't work.
temporary I use check_parts_columns: false to overcome it, but seem it's not safe method.

**Comment by Slach** [comment]
You have two options here:
check `SELECT * FROM system.mutations WHERE is_done=0 AND database='db' AND table='table' FORMAT Vertical`
and wait when your array of tuple will changed in all parts

or run
```sql
SELECT DISTINCT partition FROM system.parts_columns WHERE column='locks' AND type='Array(Tuple(_id String, amount Float64, api String, lockId String, percent Float64, providerId String, type String, unlockDate String))
```
and try to restore backuped single table 
something like that
```
clickhouse-backup restore --restore-database-mapping=db:test_restore_db --table=db.table --partition=<partition> <backup_name>
```

if restore will success i can add `Array(Tuple(%` to exclude list

**Comment by supnobita** [comment]
I run query 

> SELECT DISTINCT partition FROM system.parts_columns WHERE column='locks' AND type='Array(Tuple(_id String, amount Float64, api String, lockId String, percent Float64, providerId String, type String, unlockDate String))

And I saw no result. So I think all mutation has been done.
I successfully restored this table (using incremental backup also full backup)

> clickhouse-backup restore --restore-database-mapping=db:test_restore_db --table=db.table  <backup_name>

**Comment by supnobita** [comment]
What will happen if we skiss all type=Array% ?

**Comment by Slach** [comment]
> What will happen if we skiss all type=Array% ?

We skipp 'Array(Tuple(%' not Array% 

mutation for conversion Array(String) to Array(Int) 
could stuck if some of resource contains `['A']` and some `['0']`
and you will have inconsistent state between different parts, which not allow restore

but changing Array(Tupple(

better ensure your schema migration complete between backups
