### ISSUE TITLE
Backup failed with permission denied

### ISSUE THREAD

**Issue by farodin91** [Altinity/clickhouse-backup#792]
```
2023/11/24 16:03:46.517104 error metrics.ExecuteWithMetrics(create_remote) return error: unlinkat /var/lib/clickhouse/backup/chi-sentry-clickhouse-sentry-0-0-full-2023-11-02-00-42-01/shadow/default/search_issues_local_v2/default/30-20231009_2719_2719_0/default_compression_codec.txt: permission denied logger=metrics
2023/11/24 16:03:46.517135 error API /backup/actions error: unlinkat /var/lib/clickhouse/backup/chi-sentry-clickhouse-sentry-0-0-full-2023-11-02-00-42-01/shadow/default/search_issues_local_v2/default/30-20231009_2719_2719_0/default_compression_codec.txt: permission denied logger=server
```

Version:
* Clickhouse: clickhouse/clickhouse-server:23.8.5.16-alpine
* altinity/clickhouse-backup:2.4.6

Any idea? 

RunAsUser: 101
RunAsGroup: 101

**Comment by Slach** [comment]
Could you share:

`ls -la /var/lib/clickhouse/backup/chi-sentry-clickhouse-sentry-0-0-full-2023-11-02-00-42-01/shadow/default/search_issues_local_v2/default/30-20231009_2719_2719_0/default_compression_codec.txt`
and
`ls -la /var/lib/clickhouse/backup/chi-sentry-clickhouse-sentry-0-0-full-2023-11-02-00-42-01/shadow/default/search_issues_local_v2/default/30-20231009_2719_2719_0/`

**Comment by Slach** [comment]
@farodin91 any news from your side?

**Comment by farodin91** [comment]
@Slach I had to reset the database. Due a different reason now it is solved.
