### ISSUE TITLE
Support backup and restore of join tables

### ISSUE THREAD

**Issue by acmeguy** [Altinity/clickhouse-backup#794]
In a previous version, it creates the metadata and zip file with SQL creation commands only, but no data.
That is massively misleading. (I'm verifying that this is still the case)

**Comment by Slach** [comment]
currently only MergeTree tables allow backup data

you could try use modern clickhouse-server:23.10+ version and change `/etc/clickhouse-backup/config.yml`
```
clickhouse:
 use_embedded_backup_restore: true
```

and check will it works for `BACKUP / RESTORE` statements

with following command sequence
```bash
clickhouse-backup create --table=db.join_table_name 
clickhouse-client -q "DROP TABLE db.join_table_name SYNC"
clickhouse-backup restore --table=db.join_table_name
```

**Comment by Slach** [comment]
moreover you need modify clickhouse-server config to add Backup S3 disk for properly backup
look example here
https://github.com/Altinity/clickhouse-backup/blob/master/test/integration/dynamic_settings.sh#L202-L228

**Comment by acmeguy** [comment]
Thank you @Slach, I will try that :)

**Comment by acmeguy** [comment]
@Slach - are you in a position to tell me if this supports backup from a cluster to a dingle node and vice versa?
(Replecated*)

**Comment by Slach** [comment]
@acmeguy do you mean merge multi-node data into single node? 
and spread single node data into multiple nodes?

no, this is not possible and require a lot of prepare work

**Comment by acmeguy** [comment]
cluster/replicas without sharding.  Is the "Replicated" not the only difference? (The whole data is backed up)

**Comment by Slach** [comment]
`ReplicatedMergeTree` also supported with `use_embedded_backup_restore: true`
please look https://github.com/Altinity/clickhouse-backup/blob/master/Examples.md#how-to-back-up--restore-a-sharded-cluster for more details

**Comment by Slach** [comment]
"no sharding" means minimum one shard, actually

**Comment by acmeguy** [comment]
splitting hairs. thank you.

**Comment by acmeguy** [comment]
The point is that the table descriptions do not match between clustered and non-clustered environment and restore - using the clickhouse-backup tool - fails on converting ReplicatedXTree to XTree and vice versa)

**Comment by Slach** [comment]
`clickhouse-backup` doesn't translate anything and doesn't change engines in table
because this is out of scope for this tool

if you will try to restore in environment which have lot of difference then source environment where you create cluster, you need adapt backup content manually, we can't solve and make workaround to all possible invariants
