### ISSUE TITLE
restore backup on different server name vs server name used for backup creation

### ISSUE THREAD

**Issue by 1Const1** [Altinity/clickhouse-backup#797]
Hello

After successfully created backup i see problem with restore backup on different server (in our case different namespace). We are using Altinity clickhouse operator. So that means clickhouse installation can be in different namespaces (for example restore backup created on namespace `demo` to namespace `newdemo`)

Arter creation backup on s3 (clickhouse-backup / backup / shard-0) i see objects like:
clickhouse.demo.svc-full-2023-12-06-13-49-00
clickhouse.demo.svc.cluster.local-increment-2023-12-06-21-05-07

In table backup_list i see

|name|created|size|location|required|desc|
|----|-------|----|--------|--------|----|
|clickhouse.demo.svc.cluster.local-full-2023-12-06-14-11-44|2023-12-06 17:12:12|16059828|remote||tar, regular|
|clickhouse.demo.svc.cluster.local-increment-2023-12-06-21-05-07|2023-12-07 00:05:14|16057747|remote|clickhouse.demo.svc.cluster.local-full-2023-12-06-14-11-44|tar, regular|

in restore job on k8s cluster there is queries like this:
LAST_FULL_BACKUP=$(clickhouse-client -q "SELECT name FROM system.backup_list WHERE location='remote' **AND name LIKE '%${SERVER}%'** AND name LIKE '%full%' AND desc NOT LIKE 'broken%' ORDER BY created DESC LIMIT 1 FORMAT TabSeparatedRaw" --host="$SERVER" --port="$CLICKHOUSE_PORT" --user="$BACKUP_USER" $BACKUP_PASSWORD);

so in this case i can't restore backup that created in namesapce demo on namespace newdemo because name LIKE '%${SERVER}%'** will be different

Please could you provide some help or ideas how backup can be restored on different namespace that it was originally created?

It's typical task that if something happened you restored you data in other place, check it, than switch clients to restored version

**Comment by Slach** [comment]
looks like you changed creation backup `CronJob` manifest

and use a full service name instead of service name without `demo.svc.cluster.local`

You can change logic in this case, restore `kind: Job`, for example remove 
`AND name LIKE '%${SERVER}%' ` part

But instead of it, i suggest you figure out and make backup properly
read
https://github.com/Altinity/clickhouse-backup/blob/master/Examples.md#how-to-back-up--restore-a-sharded-cluster

and https://github.com/Altinity/clickhouse-backup/blob/master/Examples.md#how-to-use-clickhouse-backup-in-kubernetes



```
                - name: CLICKHOUSE_SERVICES
                  value: chi-test-backups-default-0-0,chi-test-backups-default-1-0

```

**Comment by 1Const1** [comment]
> looks like you changed creation backup `CronJob` manifest

Yes, you are correct. 
It was convert from jobcron to job give me this sideeffect
After change kind to CronJob backup was created like this
INSERT INTO system.backup_actions(command) VALUES('upload  clickhouse-full-2023-12-11-10-08-00')

thank you for answer I will follow your recommendations
