### ISSUE TITLE
how  clickhouse-backup works?

### ISSUE THREAD

**Issue by haiya512** [Altinity/clickhouse-backup#806]
as the title, how  clickhouse-backup works?
i am a newer to clickhouse and clickhouse-backup, i have read the README.md carefully, and did not find the describtion.
is there any papers to describe how the clickhouse-backup work?

**Comment by haiya512** [comment]
it confused me
when i use `du -sh *`  to check the directory's size, the output is:
> 116G	backup
30M	shadow
13G	store
382M	tmp


when i use `du -h -d 1` to check the directory's size, the output is:
> 128G	./store
382M	./tmp
30M	./backup
30M	./shadow
129G	.

**Comment by Slach** [comment]
@haiya512 do you know about hard links?

Brief description how clickhouse-backup works

Data files is immutable in `clickhouse-server`.
During backup operation `clickhouse-backup` create file system hard-links to exists `clickhouse-server` data parts via executing `ALTER TABLE ... FREZZE` query. 
During restore operation `clickhouse-backup` copy hard-links to `detached` folder and execute `ALTER TABLE ... ATTACH PART` query for each data part and each table in backup.
More detailed description available here https://www.youtube.com/watch?v=megsNh9Q-dw

**Comment by haiya512** [comment]
> @haiya512 do you know about hard links?
> 
> Brief description how clickhouse-backup works
> 
> Data files is immutable in `clickhouse-server`. During backup operation `clickhouse-backup` create file system hard-links to exists `clickhouse-server` data parts via executing `ALTER TABLE ... FREZZE` query. During restore operation `clickhouse-backup` copy hard-links to `detached` folder and execute `ALTER TABLE ... ATTACH PART` query for each data part and each table in backup. More detailed description available here https://www.youtube.com/watch?v=megsNh9Q-dw

thank you for reply!
Tips for others:  from 30mins the video begins to describle how it works.
