### ISSUE TITLE
check_parts_columns failing on Enum8 types - regression in 2.4.24

### ISSUE THREAD

**Issue by vortura** [Altinity/clickhouse-backup#823]
Hi,

I think 2.4.24 may have introduced a regression in `check_parts_columns` with respect to sized Enum types, i.e. Enum8/Enum16. This is the error I'm getting in my `clickhouse-backup` logs:

    2024/02/04 09:20:03.572179 error `prod_voz`.`optimised_viewing_rnf_bvod_local` have incompatible data types []string{"Enum8('ABC' = 1, 'TEN' = 2, 'SBS' = 3, 'NINE' = 4, 'SEVEN' = 5, 'FOXTEL' = 6, 'OTHER' = 7)", "Enum8('ABC' = 1, 'TEN' = 2, 'SBS' = 3, 'NINE' = 4, 'SEVEN' = 5, 'FOXTEL' = 6, 'OTHER' = 7, 'SKYNEWSREGIONAL' = 8)"} for "network" column logger=clickhouse
    2024/02/04 09:20:03.572207 error b.AddTableToBackup error: `prod_voz`.`optimised_viewing_rnf_bvod_local` have inconsistent data types for active data part in system.parts_columns backup=foo logger=backuper operation=create table=prod_voz.optimised_viewing_rnf_bvod_local

The change in behaviour is introduced in 5be9d48c2 where the type check changes from:

    type NOT LIKE 'Enum%'

to:

    type NOT LIKE 'Enum(%'

Consequently the check no longer matches `Enum8` or `Enum16`

**Comment by Slach** [comment]
thanks a lot for reporting
