### ISSUE TITLE
upload doesn't work for S3 when object lock turned on by default

### ISSUE THREAD

**Issue by Slach** [Altinity/clickhouse-backup#829]
```
InvalidRequest: Content-MD5 OR x-amz-checksum- HTTP header is required for Put Object requests with Object Lock parameters
```

**Comment by UnamedRus** [comment]
https://github.com/aws/aws-sdk-go-v2/issues/1689
https://github.com/aws/aws-sdk-go-v2/pull/2040

Looks like, it just matter of setting value to `ChecksumAlgorithm` parameter
