### ISSUE TITLE
how to backup to other local disk

### ISSUE THREAD

**Issue by zoudongdongdong** [Altinity/clickhouse-backup#838]

**Comment by zoudongdongdong** [comment]
ln -s /data/backup/ /var/lib/clickhouse/backup

1 root       root        13 Feb 18 17:40 backup -> /data/backup/
drwxr-x---  3 clickhouse clickhouse  33 Feb 18 17:38 backup_bak
drwxr-x---  2 clickhouse clickhouse   6 Feb 18 16:21 cores
drwxr-x---  5 clickhouse clickhouse  49 Feb 18 17:31 data
drwxr-x---  2 clickhouse clickhouse   6 Feb 18 16:21 dictionaries_lib
drwxr-x---  2 clickhouse clickhouse   6 Feb 18 16:21 flags
drwxr-x---  2 clickhouse clickhouse   6 Feb 18 16:21 format_schemas
drwxr-x---  2 clickhouse clickhouse 164 Feb 18 17:31 metadata
drwxr-x---  2 clickhouse clickhouse   6 Feb 18 17:43 metadata_dropped
drwxr-x---  2 clickhouse clickhouse  41 Feb 18 16:21 preprocessed_configs
drwxr-x---  2 clickhouse clickhouse   6 Feb 18 17:49 shadow
-rw-r-----  1 clickhouse clickhouse  59 Feb 18 16:21 status
drwxr-x--- 13 clickhouse clickhouse 127 Feb 18 17:36 store
drwxr-x---  2 clickhouse clickhouse   6 Feb 18 16:21 tmp
drwxr-x---  2 clickhouse clickhouse   6 Feb 18 16:21 user_defined
drwxr-x---  2 clickhouse clickhouse   6 Feb 18 16:21 user_files
drwxr-x---  2 clickhouse clickhouse   6 Feb 18 16:21 user_scripts
-rw-r-----  1 clickhouse clickhouse  36 Feb 18 16:21 uuid
[root@ovsmpdb clickhouse]# clickhouse-backup create 
2024/02/18 17:54:18.434618 error rename /var/lib/clickhouse/shadow/3df03478c06744dd87be1442f3c101dd/store/1e7/1e70b8b0-f81f-4c4e-b4cd-6448b8cad1c7/all_1_1_0/checksums.txt /var/lib/clickhouse/backup/2024-02-18T09-54-18/shadow/testdb/test_tab/default/all_1_1_0/checksums.txt: invalid cross-device link backup=2024-02-18T09-54-18 logger=backuper operation=create table=testdb.test_tab
2024/02/18 17:54:18.437980  info done                      backup=2024-02-18T09-54-18 duration=3ms location=local logger=RemoveBackupLocal operation=delete
2024/02/18 17:54:18.453732  info /var/lib/clickhouse/shadow logger=Clean
2024/02/18 17:54:18.453850 error rename /var/lib/clickhouse/shadow/3df03478c06744dd87be1442f3c101dd/store/1e7/1e70b8b0-f81f-4c4e-b4cd-6448b8cad1c7/all_1_1_0/checksums.txt /var/lib/clickhouse/backup/2024-02-18T09-54-18/shadow/testdb/test_tab/default/all_1_1_0/checksums.txt: invalid cross-device link
[root@ovsmpdb clickhouse]#

**Comment by Slach** [comment]
`clickhouse-backup` is physical backup utilty
it requires access to the same disk which used for `clickhouse-server`

`clickhouse-backup` make hard links and not copy data files
it allows us to create local backup without allocate disk space, look details
https://en.wikipedia.org/wiki/Hard_link


moreover, look to 
https://github.com/Altinity/clickhouse-backup/tree/master/test/integration/rsync
and
https://github.com/Altinity/clickhouse-backup/blob/master/test/integration/config-custom-rsync.yml
for integration with rsync which allows you copy local backup to your backup disk
