### ISSUE TITLE
lightweight delete - backup restore failed - error can't attach data parts for table 'lbtest.lbtable': code: 16, message: There is no column with name _row_exists. There are columns: UserID, Name, Age, CityName, Birthday, CreateTime

### ISSUE THREAD

**Issue by zxl-wangwang** [Altinity/clickhouse-backup#839]
When I use lightweight deletion of data on clickhouse's data table, the backup is successful, but the backup and recovery fails. The error reason is as follows:

```
error can't attach data parts for table 'lbtest.lbtable': code: 16, message: There is no column with name _row_exists. There are columns: UserID, Name, Age, CityName, Birthday, CreateTime
```

**Comment by zxl-wangwang** [comment]
Backup and restore are also successful without lightweight deletion

**Comment by Slach** [comment]
Which `clickhouse-server` version do you use?

**Comment by zxl-wangwang** [comment]
clickhouse-server version is 22.8.

**Comment by Slach** [comment]
could you try with 23.8 and 24.1? 
Lightweight delete experimental feature and i not sure it will work in 22.8

as workaround
you could try to use embedded BACKUP / RESTORE wrapper
with `/etc/clickhouse-backup/config.yml`
```
clichouse:
  use_embedded_backup_restore: true
```
which also requires object disk for backup

look https://github.com/Altinity/clickhouse-backup/blob/master/test/integration/config-s3-embedded.yml#L22-L23
and
https://github.com/Altinity/clickhouse-backup/blob/master/test/integration/dynamic_settings.sh#L216-L237
for details

**Comment by zxl-wangwang** [comment]
Lightweight deletion is available in version 22.8, but it needs to be turned on manually. 
Recovery still fails using the method you provided. The restore on my backup instance was successful, but the restore on the new instance failed. 
The error reason is still the same: “**There is no column with name _row_exists.**”

**Comment by Slach** [comment]
I mean, you need to try to backup from scratch with `use_embedded_backup_restore: true` and after that try to restore it

issue is not related with `clickhouse-backup` itself

looks like `clickhouse-server` has inconsistent behavior when trying to execute
```
ALTER TABLE ... ATTACH PART 'part_name'
```

**Comment by zxl-wangwang** [comment]
Feel sorry. I tried setting `use_embedded_backup_restore` from scratch, but the backup was successful and the restore still failed.

**Comment by zxl-wangwang** [comment]
I have initially found the reason. The 22.8 version of clickhouse-server needs to manually enable lightweight deletion settings. However, when I used another instance to restore, lightweight deletion was not automatically enabled. Tried through the 23.x version of clickhouse-server, the backup and recovery is normal.

**Comment by Slach** [comment]
do you mean it successfull with standard backup approach? or with `use_embedded_backup_restore: true` ?

**Comment by zxl-wangwang** [comment]
I succeeded via standard backup methods. I found that I need to use clickhouse with lightweight deletion enabled to restore successfully.

**Comment by zxl-wangwang** [comment]
Thank you very much for reminding me to use a higher version of clickhouse-server.

**Comment by Slach** [comment]
great, let's close issues
