### ISSUE TITLE
Add delete function for backups older than specific days

### ISSUE THREAD

**Issue by unix196** [Altinity/clickhouse-backup#84]
clickhouse-backup has a delete command for specific backup, but may be add new function like that?
```
clickhouse-backup -delete -days 30 - delete backups older than 30 days
```
IT specialist can write scripts, which would be parse listing command
```
clickhouse-backup list
```
and than delete backups, but in most cases enough to delete backup older than N days.
(in my case we now use local backup)

**Comment by AlexAkulov** [comment]
Thank you!
Good proposal.

**Comment by AlexAkulov** [comment]
You can use these options for enable auto cleaning feature
```
general:
  backups_to_keep_local: 0       # BACKUPS_TO_KEEP_LOCAL
  backups_to_keep_remote: 0      # BACKUPS_TO_KEEP_REMOTE
```
Local backups will be cleaned after creating a new backup.
Remote backups will be cleaned after uploading.
