### ISSUE TITLE
Kubernetes workload identity to GCS does not work, defaulting to anonymous user 

### ISSUE THREAD

**Issue by VytautasRuk** [Altinity/clickhouse-backup#848]
New improvements for custom GCS endpoint have broken backup jobs.
https://github.com/Altinity/clickhouse-backup/blob/v2.4.32/pkg/storage/gcs.go#L104

This logic adds new function, which forces anonymous user to be used for authorization (if CredentialsJSON is null) and it fails on GCP side. 
`can\'t upload: googleapi: Error 401: Anonymous caller does not have storage.objects.get access to the Google Cloud Storage object. Permission \'storage.objects.get\' denied on resource`

And we only have token, so it does not meet json format reqs. 
Before this change has been introduced, Kubernetes workload identity worked with default settings to GCS, now it's defaulting to anonymous user.

**Comment by Slach** [comment]
thanks for reporting
look https://github.com/Altinity/clickhouse-backup/pull/847
will fix ASAP in 2.4.33
