### ISSUE TITLE
--table parameter does not seem to work

### ISSUE THREAD

**Issue by marrrcin** [Altinity/clickhouse-backup#850]
Hi,
thanks again for creating this tool, it really helps!

I have a problem with `--table` / `--tables` / `-t` parameter - it does not seem to work.

**How to reproduce:**
```
Clickhouse version: 23.8
Clickhouse-Backup version: 2.4.32
```

My setup for testing that is simple:
1. Create CH cluster with 2 shards, 1 replicas each
2. Create 2 tables in each shard:
```sql
create database test;

create table test.yolo_table
(
    col1 Int32,
    col2 Int32,
    data String,
    id LowCardinality(String)
)
    engine = ReplicatedSummingMergeTree('/clickhouse/tables/{shard}/yolo_table', '{replica}', (col1, col2))
        PRIMARY KEY id
        ORDER BY (id, col2);

create table test.awesome_table
(
    col1 Int32,
    col2 Int32,
    col3 Int32,
    data String,
    id LowCardinality(String)
)
    engine = ReplicatedSummingMergeTree('/clickhouse/tables/{shard}/awesome_table', '{replica}', (col1, col2, col3))
        PRIMARY KEY id
        ORDER BY (id, col1);
```
3. Put some data in both shards.
4. Create distributed table (this one is probably not relevant)
```sql
CREATE OR REPLACE TABLE test.awesome_table_d ON CLUSTER '{cluster}' AS test.awesome_table ENGINE = Distributed('{cluster}', 'test', awesome_table, cityHash64(`id`));
```

Perform full backup of each shard:
```bash
# on shard 0
clickhouse-backup create_remote shard0-backup

# on shard 1
clickhouse-backup create_remote shard1-backup
```

5. `drop database test`
6. Perform restoration on shard0, but I want only `test.awesome_table` to be restored:
```bash
clickhouse-backup restore_remote --rm --schema --tables=test.awesome_table shard0-backup
```
(I have also tried variants with `-t test.awesome_table`, `--table test.awesome_table`, with quotations, with equal signs etc. 

**Actual result:**
None of those seem to work. Every time I run the command, **ALL tables** are getting restored.

**Expected result:**
Only `test.awesome_table` is getting restored.

**Additional info:**
On the other hand, using environment variable `CLICKHOUSE_SKIP_TABLES=test.yolo_table,test_awesome_table_d` seem to work fine and effectively only `test.awesome_table` gets restored.

**Comment by Slach** [comment]
Could you share results of
```
LOG_LEVEL=debug clickhouse-backup restore_remote --rm --schema --tables=test.awesome_table shard0-backup
```

**Comment by marrrcin** [comment]
I cannot reproduce it anymore, I don't know why TBH - seems like some kind of weird issue with the setup, because sometimes I get error that `/var/lib/clickhouse/flags/force_drop_table` does not exist.
