### ISSUE TITLE
improve RBAC restore when /var/lib/clickhouse/access is already contains .sql

### ISSUE THREAD

**Issue by Slach** [Altinity/clickhouse-backup#851]
* need parse exists /var/lib/clickhouse/access/*.sql to find conflict type and name
* merge backup_name/access/*.sql and /var/lib/clickhouse/access/*.sql
* thinks about `jsonl` zookeeper data

**Comment by minguyen9988** [comment]
thanks, it will smoothen the rbac process a lot, ultimately, this should be able to clone clickhouse like for like in use case like prod to dev rebuild, host rebuild, etc ...

**Comment by Slach** [comment]
duplicated with https://github.com/Altinity/clickhouse-backup/issues/793
