### ISSUE TITLE
x-amz-content-sha256 header error during upload

### ISSUE THREAD

**Issue by spoofedpacket** [Altinity/clickhouse-backup#86]
Hello,

I've been using clickhouse-backup for the last while to back up a large (3.5TB) database to S3 and it works well. However I encountered this error today during the upload phase:

```
 1.27 TiB / 3.47 TiB [========================>-------------------------------------------]  36.60% 39m58s
2020/04/08 10:14:12 can't upload with MultipartUpload: upload multipart failed
        upload id: XXXXXXXXXXXXXXX
caused by: XAmzContentSHA256Mismatch: The provided 'x-amz-content-sha256' header does not match what was c
omputed.
        status code: 400, request id: XXXXXXXXX, host id: XXXXXXXXX
```
Any ideas what might be wrong? Has the database grown too large that it's hitting some kind of upload limit in S3? 

I'm using version 0.5.1.c7.g47fc8c0 with version 19.16.12.49 of clickhouse, here's my config:

```
---
general:
  remote_storage: s3
clickhouse:
  password: XXXXXXX
  host: 127.0.0.1
  data_path: "/var/lib/clickhouse"
  skip_tables:
  - system.*
s3:
  bucket: XXXXXX
  region: XXXXXX
  acl: private
  force_path_style: false
  path: 'clickhouse'
  disable_ssl: false
  disable_progress_bar: true
  overwrite_strategy: always
  part_size: 419430400
  delete_extra_files: false
  strategy: archive
  backups_to_keep_local: 0
  backups_to_keep_s3: 2
```

**Comment by spoofedpacket** [comment]
Odd, I removed one older backup from S3 and then re-ran the upload and it worked this time.

**Comment by AlexAkulov** [comment]
I no have ideas, sorry.

**Comment by Slach** [comment]
I close the issue due to inactivity 
@spoofedpacket 
if the issue is still relevant for you, please comment and we will try to figure out
