### ISSUE TITLE
backup restore job didnt update materialized views data

### ISSUE THREAD

**Issue by negahsol** [Altinity/clickhouse-backup#869]
I restored clickhouse from s3 and backup files contain some tables and materialized views.
I created some materialized views from the restored table but after restoring new data (as we know inserting new data in the source table will also add to the materialized view table ) my new data hasn't been added to my materialized view.
but when I add some new data in restored tables manually they will be added.
I think the process of restoring new data is not like inserting new data in one table and materialized view cant understand the changes.
this is my commands to restore data.
 `clickhouse-backup list > /tmp/backup_list
BASE=$(cat /tmp/backup_list | grep remote | awk '{print $1}' | grep base | sort | tail -n 1)
until [ -z "$BASE" ]; do
	echo --- "$BASE"
	if [ -z "$ALL" ]
	then
		ALL="$BASE"
	else
		ALL="$ALL\|$BASE"
	fi
	clickhouse-backup download --resume --tables=$tables_with_comma "$BASE"
	LAST="$BASE"
	DAILY=$(cat /tmp/backup_list | grep remote | grep "$BASE" | awk '{print $1}' | grep daily | grep -v "$BASE" | sort)
	BASE="$DAILY"
done
BASE=$LAST
until [ -z "$BASE" ]; do
	echo --- "$BASE"
	ALL="$ALL\|$BASE"
	clickhouse-backup download --resume --tables=$tables_with_comma "$BASE"
	LAST=$BASE
	HOURLY=$(cat /tmp/backup_list | grep remote | grep "$BASE" | awk '{print $1}' | grep hourly | grep -v "$BASE" | sort)
	BASE=$HOURLY
done`

**Comment by Slach** [comment]
Restoring from backup this is not INSERT, this is `ALTER TABLE ... ATTACH PART ` and it will not trigger materialized view

**Comment by negahsol** [comment]
do you have a suggestion on how can i use the data from restored tables like the materialized view?
one solution that came to my mind is creating cronjobs to move updated data to other tables but at a bigger scale, it may cause some difficulties.

**Comment by Slach** [comment]
When you create backup you also create backup destination table for your materialized view
during restore you will restore state of MV destination table 

(look to `TO db.table` clause in CREATE MATERIALIZED VIEW query , or `.inner.{uuid}` table if you created MV without TO clause)

I don't understand what you exactly trying to do, looks like you don't understand what is Materialized View and how it works
