### ISSUE TITLE
Possibility to change default local backup path.

### ISSUE THREAD

**Issue by freemanlutsk** [Altinity/clickhouse-backup#87]
Hello!
Thank You for great tool!

I would like to change my strategy of backup from "all tables in one big archive" (in my case about 4TB per shard) to "one table per archive". In order to do this I need different path per table. I can try to play with symlinks for changing local path per table, but I think would be better to set path in the config or with CLI help.

Thank You!

**Comment by AlexAkulov** [comment]
Hi @freemanlutsk!

You can set backup name that contains table name. For example:
```
clickhouse-backup create --table "db.table1" table1_backup_16042020
```
Or you can set backup name as a relative path. `create` and `restore` will work correctly but you will face issues with `list` and `upload`/`download` commands
```
clickhouse-backup create --table "db.table1" table1/16.04.2020
```

**Comment by freemanlutsk** [comment]
Thank You for answer.
Yes, you are correct `list` and `upload/download` commands don't work properly. :(
Is it possible to add to those commands something like `--backup_dir` ?

**Comment by DrissiReda** [comment]
I also had a usecase where I needed to save the backups outside `/var/lib/clickhouse/` I opened a pull request to separate data path and backup path #97

**Comment by Slach** [comment]
@freemanlutsk version 1.0.0+ is changed backup fomat to "one or more archive per table"
and allow setup option, just setup it to 10737418240 bytes

```yaml
general:
  max_file_size:
```
  
  
 @DrissiReda sorry, change the default backup path is strongly depends on your current `system.disks` configuration
 cause hardlink which used on `ALTER TABLE .. FREEZE` command require source and destination have the same block device
 
 I close issue as irrelevant
