### ISSUE TITLE
are there any ways to speed "partition attach"?

### ISSUE THREAD

**Issue by and1990** [Altinity/clickhouse-backup#875]
I have a table with numerous partitions, and restoring it using `clickhouse-backup` takes a considerable amount of time. 

Is it possible to perform `attach partition` in parallel using `clickhouse-backup`, or are there any other methods to accomplish this?

**Comment by Slach** [comment]
v2.5 will run ATTACH PART in parallel for each table, but sequentially on one table

you can try to use
```yaml
clickhouse:
  restore_as_attach: true
```

which will use `ATTACH TABLE` instead of `ALTER TABLE ... ATTACH PART ...`

but please avoid run on the parallel replicas in the same shard

How many parts do you have on your table?

**Comment by and1990** [comment]
It has 144 parts. Can v2.5 run FREEZE PARTITION in parallel? Because I noticed FREEZE PARTITION ran slowly too.

**Comment by Slach** [comment]
No, v2.5 will still use `ALTER TABLE ... FREEZE ...` for consistent table snapshot

144 parts this is not so much

Why do you think, restore will slow?
Could you provide logs for restoration?

**Comment by and1990** [comment]
It will take 30 seconds to do `ATTACH PART` with 144 parts, maybe it isn't slow. 

But I use `clickhouse-backup` to relaunch a new clickhouse cluster in time, which is based on the original cluster. So, it's slow for me. I wonder if there are any ways to speed this up.

**Comment by Slach** [comment]
@and1990 did you read
https://github.com/Altinity/clickhouse-backup/issues/875#issuecomment-2019539969?

**Comment by and1990** [comment]
Yes, I have read it. My target is that it takes 30 seconds or less to relaunch a new `clickhouse` cluster, but `FREEZE PARTITION` and `ATTACH PART` take up 30 seconds respectively, so it will consume 1 minute or more in total.

**Comment by and1990** [comment]
The log of `FREEZE PARTITION` is below.

2024/03/27 15:00:28.576777  info clickhouse connection prepared: tcp://127.0.0.1:9000 run ping logger=clickhouse
2024/03/27 15:00:28.577170  info clickhouse connection open: tcp://127.0.0.1:9000 logger=clickhouse
2024/03/27 15:00:28.577193  info SELECT metadata_path FROM system.tables WHERE database = 'system' AND metadata_path!='' LIMIT 1; logger=clickhouse
2024/03/27 15:00:28.578858  info SELECT name, engine FROM system.databases WHERE name NOT IN ('system','INFORMATION_SCHEMA','information_schema','_temporary_and_external_tables','default') AND name IN ('solar') logger=clickhouse
2024/03/27 15:00:28.579885  info SHOW CREATE DATABASE `solar` logger=clickhouse
2024/03/27 15:00:28.580381  info SELECT name, count(*) as is_present FROM system.settings WHERE name IN (?, ?) GROUP BY name with args [show_table_uuid_in_table_create_query_if_not_nil display_secrets_in_show_and_select] logger=clickhouse
2024/03/27 15:00:28.582674  info SELECT name FROM system.databases WHERE engine IN ('MySQL','PostgreSQL','MaterializedPostgreSQL') logger=clickhouse
2024/03/27 15:00:28.583377  info    SELECT     countIf(name='data_path') is_data_path_present,     countIf(name='data_paths') is_data_paths_present,     countIf(name='uuid') is_uuid_present,     countIf(name='create_table_query') is_create_table_query_present,     countIf(name='total_bytes') is_total_bytes_present    FROM system.columns WHERE database='system' AND table='tables'   logger=clickhouse
2024/03/27 15:00:28.585527  info SELECT database, name, engine , data_paths , uuid , create_table_query , coalesce(total_bytes, 0) AS total_bytes   FROM system.tables WHERE is_temporary = 0 AND match(concat(database,'.',name),'^solar\.events$')  ORDER BY total_bytes DESC SETTINGS show_table_uuid_in_table_create_query_if_not_nil=1 logger=clickhouse
2024/03/27 15:00:28.641329  info SELECT metadata_path FROM system.tables WHERE database = 'system' AND metadata_path!='' LIMIT 1; logger=clickhouse
2024/03/27 15:00:28.642327  info SELECT count() as cnt FROM system.columns WHERE database='system' AND table='functions' AND name='create_query' SETTINGS empty_result_for_aggregation_by_empty_set=0 logger=clickhouse
2024/03/27 15:00:28.643766  info SELECT name, create_query FROM system.functions WHERE create_query!='' logger=clickhouse
2024/03/27 15:00:28.648038  info SELECT value FROM `system`.`build_options` where name='VERSION_INTEGER' logger=clickhouse
2024/03/27 15:00:28.648743  info SELECT count() is_disk_type_present FROM system.columns WHERE database='system' AND table='disks' AND name='type' logger=clickhouse
2024/03/27 15:00:28.650339  info SELECT path, any(name) AS name, any(type) AS type FROM system.disks GROUP BY path logger=clickhouse
2024/03/27 15:00:28.651853 debug create data               backup=test logger=backuper operation=create table=solar.events
2024/03/27 15:00:28.651894  info SELECT count() is_parts_column_present FROM system.tables WHERE database='system' AND name='parts_columns' logger=clickhouse
2024/03/27 15:00:28.653322  info SELECT column, groupUniqArray(type) AS uniq_types FROM system.parts_columns WHERE active AND database=? AND table=? GROUP BY column HAVING length(uniq_types) > 1 with args [solar events] logger=clickhouse
2024/03/27 15:00:32.933666 debug   partition '06ce6b3dcd478fc0589906dc91683d9a' logger=clickhouse
2024/03/27 15:00:32.933693  info ALTER TABLE `solar`.`events` FREEZE PARTITION ID '06ce6b3dcd478fc0589906dc91683d9a' WITH NAME '87f7d080938b42d7ad45d6bee80297c5'; logger=clickhouse
2024/03/27 15:00:33.541270 debug   partition '0effd50222362faaa6c0fe150e87d730' logger=clickhouse
2024/03/27 15:00:33.541299  info ALTER TABLE `solar`.`events` FREEZE PARTITION ID '0effd50222362faaa6c0fe150e87d730' WITH NAME '87f7d080938b42d7ad45d6bee80297c5'; logger=clickhouse
2024/03/27 15:00:33.560721 debug   partition '22f9b8e21b85eef6edbc4e3cfc9d0d9b' logger=clickhouse
2024/03/27 15:00:33.560739  info ALTER TABLE `solar`.`events` FREEZE PARTITION ID '22f9b8e21b85eef6edbc4e3cfc9d0d9b' WITH NAME '87f7d080938b42d7ad45d6bee80297c5'; logger=clickhouse
2024/03/27 15:00:35.150604 debug   partition '23bce7a10e77900d3602be64c0329d84' logger=clickhouse
2024/03/27 15:00:35.150631  info ALTER TABLE `solar`.`events` FREEZE PARTITION ID '23bce7a10e77900d3602be64c0329d84' WITH NAME '87f7d080938b42d7ad45d6bee80297c5'; logger=clickhouse
2024/03/27 15:00:35.190339 debug   partition '32fd04eedd6e97da6f7cc1ba5c774a93' logger=clickhouse
2024/03/27 15:00:35.190368  info ALTER TABLE `solar`.`events` FREEZE PARTITION ID '32fd04eedd6e97da6f7cc1ba5c774a93' WITH NAME '87f7d080938b42d7ad45d6bee80297c5'; logger=clickhouse
2024/03/27 15:00:37.469200 debug   partition '36ca894da4cb1d4a77e07c49f6a2360f' logger=clickhouse
2024/03/27 15:00:37.469229  info ALTER TABLE `solar`.`events` FREEZE PARTITION ID '36ca894da4cb1d4a77e07c49f6a2360f' WITH NAME '87f7d080938b42d7ad45d6bee80297c5'; logger=clickhouse
2024/03/27 15:00:39.746531 debug   partition '36f051e2fb2d21618acd084f22754ce3' logger=clickhouse
2024/03/27 15:00:39.746558  info ALTER TABLE `solar`.`events` FREEZE PARTITION ID '36f051e2fb2d21618acd084f22754ce3' WITH NAME '87f7d080938b42d7ad45d6bee80297c5'; logger=clickhouse
2024/03/27 15:00:40.532485 debug   partition '3724b892212b0a332ed30d179b4c48af' logger=clickhouse
2024/03/27 15:00:40.532515  info ALTER TABLE `solar`.`events` FREEZE PARTITION ID '3724b892212b0a332ed30d179b4c48af' WITH NAME '87f7d080938b42d7ad45d6bee80297c5'; logger=clickhouse
2024/03/27 15:00:40.554926 debug   partition '48790945443db8b97a930fa38df1643a' logger=clickhouse
2024/03/27 15:00:40.554944  info ALTER TABLE `solar`.`events` FREEZE PARTITION ID '48790945443db8b97a930fa38df1643a' WITH NAME '87f7d080938b42d7ad45d6bee80297c5'; logger=clickhouse
2024/03/27 15:00:43.600741 debug   partition '555a0a01bae916fed2536b00d47d6d2e' logger=clickhouse
2024/03/27 15:00:43.600771  info ALTER TABLE `solar`.`events` FREEZE PARTITION ID '555a0a01bae916fed2536b00d47d6d2e' WITH NAME '87f7d080938b42d7ad45d6bee80297c5'; logger=clickhouse
2024/03/27 15:00:44.460936 debug   partition '58b57840df26ff055570f2488942796c' logger=clickhouse
2024/03/27 15:00:44.460964  info ALTER TABLE `solar`.`events` FREEZE PARTITION ID '58b57840df26ff055570f2488942796c' WITH NAME '87f7d080938b42d7ad45d6bee80297c5'; logger=clickhouse
2024/03/27 15:00:46.177126 debug   partition '6878ecde396369c3d67c78ab1252289a' logger=clickhouse
2024/03/27 15:00:46.177158  info ALTER TABLE `solar`.`events` FREEZE PARTITION ID '6878ecde396369c3d67c78ab1252289a' WITH NAME '87f7d080938b42d7ad45d6bee80297c5'; logger=clickhouse
2024/03/27 15:00:46.204690 debug   partition '6a9f8b33c00c1f90cd985a9dcf2763f3' logger=clickhouse
2024/03/27 15:00:46.204717  info ALTER TABLE `solar`.`events` FREEZE PARTITION ID '6a9f8b33c00c1f90cd985a9dcf2763f3' WITH NAME '87f7d080938b42d7ad45d6bee80297c5'; logger=clickhouse
2024/03/27 15:00:48.698971 debug   partition '6e3875d6da0f9b88140de87582608878' logger=clickhouse
2024/03/27 15:00:48.699000  info ALTER TABLE `solar`.`events` FREEZE PARTITION ID '6e3875d6da0f9b88140de87582608878' WITH NAME '87f7d080938b42d7ad45d6bee80297c5'; logger=clickhouse
2024/03/27 15:00:48.741024 debug   partition '7631695441a1b01790cfa5a61a0e3167' logger=clickhouse
2024/03/27 15:00:48.741055  info ALTER TABLE `solar`.`events` FREEZE PARTITION ID '7631695441a1b01790cfa5a61a0e3167' WITH NAME '87f7d080938b42d7ad45d6bee80297c5'; logger=clickhouse
2024/03/27 15:00:48.765481 debug   partition '7ae2fb038a6625ad5ff7e606c9461f63' logger=clickhouse
2024/03/27 15:00:48.765505  info ALTER TABLE `solar`.`events` FREEZE PARTITION ID '7ae2fb038a6625ad5ff7e606c9461f63' WITH NAME '87f7d080938b42d7ad45d6bee80297c5'; logger=clickhouse
2024/03/27 15:00:50.395148 debug   partition '7c5c1e42c444322d081c24cdcea25d27' logger=clickhouse
2024/03/27 15:00:50.395173  info ALTER TABLE `solar`.`events` FREEZE PARTITION ID '7c5c1e42c444322d081c24cdcea25d27' WITH NAME '87f7d080938b42d7ad45d6bee80297c5'; logger=clickhouse
2024/03/27 15:00:50.416542 debug   partition '7d6a1a1b082f98cb08b560608ec8a5ea' logger=clickhouse
2024/03/27 15:00:50.416563  info ALTER TABLE `solar`.`events` FREEZE PARTITION ID '7d6a1a1b082f98cb08b560608ec8a5ea' WITH NAME '87f7d080938b42d7ad45d6bee80297c5'; logger=clickhouse
2024/03/27 15:00:52.184029 debug   partition '831e47122fa07b065d9e9ae57128aeb6' logger=clickhouse
2024/03/27 15:00:52.184059  info ALTER TABLE `solar`.`events` FREEZE PARTITION ID '831e47122fa07b065d9e9ae57128aeb6' WITH NAME '87f7d080938b42d7ad45d6bee80297c5'; logger=clickhouse
2024/03/27 15:00:52.211388 debug   partition '83a6b08e2fc478b51877522727819040' logger=clickhouse
2024/03/27 15:00:52.211409  info ALTER TABLE `solar`.`events` FREEZE PARTITION ID '83a6b08e2fc478b51877522727819040' WITH NAME '87f7d080938b42d7ad45d6bee80297c5'; logger=clickhouse
2024/03/27 15:00:52.239634 debug   partition '8542fee04cc5f9ff11e580b836a620f0' logger=clickhouse
2024/03/27 15:00:52.239646  info ALTER TABLE `solar`.`events` FREEZE PARTITION ID '8542fee04cc5f9ff11e580b836a620f0' WITH NAME '87f7d080938b42d7ad45d6bee80297c5'; logger=clickhouse
2024/03/27 15:00:52.262366 debug   partition '86339b34354df1dfed1505f07d533d7b' logger=clickhouse
2024/03/27 15:00:52.262378  info ALTER TABLE `solar`.`events` FREEZE PARTITION ID '86339b34354df1dfed1505f07d533d7b' WITH NAME '87f7d080938b42d7ad45d6bee80297c5'; logger=clickhouse
2024/03/27 15:00:52.283391 debug   partition '8f4e088b36547086464381d74dd5ffab' logger=clickhouse
2024/03/27 15:00:52.283402  info ALTER TABLE `solar`.`events` FREEZE PARTITION ID '8f4e088b36547086464381d74dd5ffab' WITH NAME '87f7d080938b42d7ad45d6bee80297c5'; logger=clickhouse
2024/03/27 15:00:52.322798 debug   partition '8faef30ad0c48143a315bba053fb7e06' logger=clickhouse
2024/03/27 15:00:52.322812  info ALTER TABLE `solar`.`events` FREEZE PARTITION ID '8faef30ad0c48143a315bba053fb7e06' WITH NAME '87f7d080938b42d7ad45d6bee80297c5'; logger=clickhouse
2024/03/27 15:00:52.367374 debug   partition '939655da47b3a3809d47e016ab93963d' logger=clickhouse
2024/03/27 15:00:52.367389  info ALTER TABLE `solar`.`events` FREEZE PARTITION ID '939655da47b3a3809d47e016ab93963d' WITH NAME '87f7d080938b42d7ad45d6bee80297c5'; logger=clickhouse
2024/03/27 15:00:54.604901 debug   partition '9a1d34c9d8166c4a213a3832bba17717' logger=clickhouse
2024/03/27 15:00:54.604926  info ALTER TABLE `solar`.`events` FREEZE PARTITION ID '9a1d34c9d8166c4a213a3832bba17717' WITH NAME '87f7d080938b42d7ad45d6bee80297c5'; logger=clickhouse
2024/03/27 15:00:54.625072 debug   partition 'a442a868e7bbe3dccab0a968b474c880' logger=clickhouse
2024/03/27 15:00:54.625088  info ALTER TABLE `solar`.`events` FREEZE PARTITION ID 'a442a868e7bbe3dccab0a968b474c880' WITH NAME '87f7d080938b42d7ad45d6bee80297c5'; logger=clickhouse
2024/03/27 15:00:54.643259 debug   partition 'a57fc2ad2c4d1a08bfde1b316815aa02' logger=clickhouse
2024/03/27 15:00:54.643269  info ALTER TABLE `solar`.`events` FREEZE PARTITION ID 'a57fc2ad2c4d1a08bfde1b316815aa02' WITH NAME '87f7d080938b42d7ad45d6bee80297c5'; logger=clickhouse
2024/03/27 15:00:54.660216 debug   partition 'a6e95ae8deea48b02842062512309baa' logger=clickhouse
2024/03/27 15:00:54.660227  info ALTER TABLE `solar`.`events` FREEZE PARTITION ID 'a6e95ae8deea48b02842062512309baa' WITH NAME '87f7d080938b42d7ad45d6bee80297c5'; logger=clickhouse
2024/03/27 15:00:55.443742 debug   partition 'aed82f7b50b1ff312f43fe7a38331bac' logger=clickhouse
2024/03/27 15:00:55.443766  info ALTER TABLE `solar`.`events` FREEZE PARTITION ID 'aed82f7b50b1ff312f43fe7a38331bac' WITH NAME '87f7d080938b42d7ad45d6bee80297c5'; logger=clickhouse
2024/03/27 15:00:58.884313 debug   partition 'b007c7e0620ca28ffad21b7e5ab527fa' logger=clickhouse
2024/03/27 15:00:58.884357  info ALTER TABLE `solar`.`events` FREEZE PARTITION ID 'b007c7e0620ca28ffad21b7e5ab527fa' WITH NAME '87f7d080938b42d7ad45d6bee80297c5'; logger=clickhouse
2024/03/27 15:01:02.548625 debug   partition 'b354dfc2e93c0e67355c96d67c4d9050' logger=clickhouse
2024/03/27 15:01:02.548657  info ALTER TABLE `solar`.`events` FREEZE PARTITION ID 'b354dfc2e93c0e67355c96d67c4d9050' WITH NAME '87f7d080938b42d7ad45d6bee80297c5'; logger=clickhouse
2024/03/27 15:01:04.098891 debug   partition 'b388653bba5defbb15652c69910e06dd' logger=clickhouse
2024/03/27 15:01:04.098935  info ALTER TABLE `solar`.`events` FREEZE PARTITION ID 'b388653bba5defbb15652c69910e06dd' WITH NAME '87f7d080938b42d7ad45d6bee80297c5'; logger=clickhouse
2024/03/27 15:01:04.147845 debug   partition 'c57562f39e56228d1b3df6fd10162584' logger=clickhouse
2024/03/27 15:01:04.147882  info ALTER TABLE `solar`.`events` FREEZE PARTITION ID 'c57562f39e56228d1b3df6fd10162584' WITH NAME '87f7d080938b42d7ad45d6bee80297c5'; logger=clickhouse
2024/03/27 15:01:04.167286 debug   partition 'c713afdcd78e3b12e5b87f2b41de9bbe' logger=clickhouse
2024/03/27 15:01:04.167304  info ALTER TABLE `solar`.`events` FREEZE PARTITION ID 'c713afdcd78e3b12e5b87f2b41de9bbe' WITH NAME '87f7d080938b42d7ad45d6bee80297c5'; logger=clickhouse
2024/03/27 15:01:04.195654 debug   partition 'cac9767281b77814290e4161f6ccc36d' logger=clickhouse
2024/03/27 15:01:04.195678  info ALTER TABLE `solar`.`events` FREEZE PARTITION ID 'cac9767281b77814290e4161f6ccc36d' WITH NAME '87f7d080938b42d7ad45d6bee80297c5'; logger=clickhouse
2024/03/27 15:01:04.214719 debug   partition 'cdeb7fc14f86fb53de472e7443eade74' logger=clickhouse
2024/03/27 15:01:04.214742  info ALTER TABLE `solar`.`events` FREEZE PARTITION ID 'cdeb7fc14f86fb53de472e7443eade74' WITH NAME '87f7d080938b42d7ad45d6bee80297c5'; logger=clickhouse
2024/03/27 15:01:06.829779 debug   partition 'cff670095963164eff2aaef3bc31271b' logger=clickhouse
2024/03/27 15:01:06.829804  info ALTER TABLE `solar`.`events` FREEZE PARTITION ID 'cff670095963164eff2aaef3bc31271b' WITH NAME '87f7d080938b42d7ad45d6bee80297c5'; logger=clickhouse
2024/03/27 15:01:10.417164 debug   partition 'd7b5dd22c4dbc28b5826dfe61d3321b9' logger=clickhouse
2024/03/27 15:01:10.417195  info ALTER TABLE `solar`.`events` FREEZE PARTITION ID 'd7b5dd22c4dbc28b5826dfe61d3321b9' WITH NAME '87f7d080938b42d7ad45d6bee80297c5'; logger=clickhouse
2024/03/27 15:01:12.575869 debug   partition 'db87cb0c4ca16451eb9456b61af22826' logger=clickhouse
2024/03/27 15:01:12.575895  info ALTER TABLE `solar`.`events` FREEZE PARTITION ID 'db87cb0c4ca16451eb9456b61af22826' WITH NAME '87f7d080938b42d7ad45d6bee80297c5'; logger=clickhouse
2024/03/27 15:01:14.079665 debug   partition 'dcf5baabf2154bb9deab35a9b60cd656' logger=clickhouse
2024/03/27 15:01:14.079695  info ALTER TABLE `solar`.`events` FREEZE PARTITION ID 'dcf5baabf2154bb9deab35a9b60cd656' WITH NAME '87f7d080938b42d7ad45d6bee80297c5'; logger=clickhouse
2024/03/27 15:01:15.574743 debug   partition 'decc616e7e01889b93b8d7061bfe0c10' logger=clickhouse
2024/03/27 15:01:15.574778  info ALTER TABLE `solar`.`events` FREEZE PARTITION ID 'decc616e7e01889b93b8d7061bfe0c10' WITH NAME '87f7d080938b42d7ad45d6bee80297c5'; logger=clickhouse
2024/03/27 15:01:17.763189 debug   partition 'e58bb10eb98f8bb878a0fa3f05596ec5' logger=clickhouse
2024/03/27 15:01:17.763214  info ALTER TABLE `solar`.`events` FREEZE PARTITION ID 'e58bb10eb98f8bb878a0fa3f05596ec5' WITH NAME '87f7d080938b42d7ad45d6bee80297c5'; logger=clickhouse
2024/03/27 15:01:19.270063 debug   partition 'e5c7029e8e182709298ffa3b3f54d0c5' logger=clickhouse
2024/03/27 15:01:19.270089  info ALTER TABLE `solar`.`events` FREEZE PARTITION ID 'e5c7029e8e182709298ffa3b3f54d0c5' WITH NAME '87f7d080938b42d7ad45d6bee80297c5'; logger=clickhouse
2024/03/27 15:01:19.293976 debug   partition 'e9593089d6d067268c2882ae82ebf8fa' logger=clickhouse
2024/03/27 15:01:19.294000  info ALTER TABLE `solar`.`events` FREEZE PARTITION ID 'e9593089d6d067268c2882ae82ebf8fa' WITH NAME '87f7d080938b42d7ad45d6bee80297c5'; logger=clickhouse
2024/03/27 15:01:20.908973 debug   partition 'edb9b7ca31c8bf4318eb4a73658681fd' logger=clickhouse
2024/03/27 15:01:20.909004  info ALTER TABLE `solar`.`events` FREEZE PARTITION ID 'edb9b7ca31c8bf4318eb4a73658681fd' WITH NAME '87f7d080938b42d7ad45d6bee80297c5'; logger=clickhouse
2024/03/27 15:01:24.388195 debug   partition 'f4094a7c70b96acca558359d067280d0' logger=clickhouse
2024/03/27 15:01:24.388235  info ALTER TABLE `solar`.`events` FREEZE PARTITION ID 'f4094a7c70b96acca558359d067280d0' WITH NAME '87f7d080938b42d7ad45d6bee80297c5'; logger=clickhouse
2024/03/27 15:01:24.413876 debug   partition 'fa6c94e70bcd5328e093592ab9c4c982' logger=clickhouse
2024/03/27 15:01:24.413905  info ALTER TABLE `solar`.`events` FREEZE PARTITION ID 'fa6c94e70bcd5328e093592ab9c4c982' WITH NAME '87f7d080938b42d7ad45d6bee80297c5'; logger=clickhouse
2024/03/27 15:01:24.470238 debug frozen                    backup=test logger=backuper operation=create table=solar.events
2024/03/27 15:01:24.500798 debug shadow moved              backup=test disk=disk1 logger=backuper operation=create table=solar.events
2024/03/27 15:01:24.980133 debug shadow moved              backup=test disk=s3 logger=backuper operation=create table=solar.events
2024/03/27 15:01:24.980178  info ALTER TABLE `solar`.`events` UNFREEZE WITH NAME '87f7d080938b42d7ad45d6bee80297c5' logger=clickhouse
2024/03/27 15:01:24.986205 debug done                      backup=test logger=backuper operation=create table=solar.events
2024/03/27 15:01:24.986231 debug get in progress mutations list backup=test logger=backuper operation=create table=solar.events
2024/03/27 15:01:24.986248  info SELECT mutation_id, command FROM system.mutations WHERE is_done=0 AND database=? AND table=? with args [solar events] logger=clickhouse
2024/03/27 15:01:24.992407 debug create metadata           backup=test logger=backuper operation=create table=solar.events
2024/03/27 15:01:24.993213  info done                      backup=test logger=backuper operation=create table=solar.events
2024/03/27 15:01:24.993244  info SELECT value FROM `system`.`build_options` where name='VERSION_DESCRIBE' logger=clickhouse
2024/03/27 15:01:24.994083  info done                      backup=test duration=56.417s logger=backuper operation=create
2024/03/27 15:01:24.994118  info clickhouse connection closed logger=clickhouse

**Comment by Slach** [comment]
Could you share your `clickhouse-backup print-config` without sensitive credentials

And which command exactly did you execute?

**Comment by Slach** [comment]
@and1990 did you solve your issue?

**Comment by and1990** [comment]
Yes, I solved.
