### ISSUE TITLE
 code: 62, message: No macro layer in config

### ISSUE THREAD

**Issue by iceran** [Altinity/clickhouse-backup#88]
when i restore database, this error message i received.What happened?
how can i restore it correctly

**Comment by AlexAkulov** [comment]
I think this issue related to ClickHouse, not to clickhouse-backup.
Where do you see this error? In clickhouse.log or on executing clickhouse-backup? When you connect to clickhouse using clichouse-client command, does it work? Do you can executing selects?

**Comment by iceran** [comment]
i just want to restore all database in other server.i cancot find any method to solve it. how to use restore command ,if it can help me .

**Comment by AlexAkulov** [comment]
I think you have a typo in clickhouse configs. Check that xml-structure of config files is valid.

**Comment by iceran** [comment]
already solved，thanks
