### ISSUE TITLE
Why use --watch vs a cron job?

### ISSUE THREAD

**Issue by BoweFlex** [Altinity/clickhouse-backup#883]
Trying to understand how to build our local implementation of using clickhouse-backup - looks like a great tool.

Are there any downsides to using something like `clickhouse-backup server --watch` vs writing a cron job to take full and incremental backups on the same interval? It seems to me like --watch just handles most of that logic for us, but I saw the example of running clickhouse-backup in kubernetes provides a cron job: https://github.com/Altinity/clickhouse-backup/blob/master/Examples.md#how-to-use-clickhouse-backup-in-kubernetes

**Comment by Slach** [comment]
`watch` implements only one command sequence
* create_remote full/increment
* delete local
* wait watch interval
it will stop if something wrong too many times and backup will fail... 
and will never start again, only manually (i think about how properly change this behavior)

`cronjob` could be more flexible

for example, you could watch job execution via https://github.com/sukeesh/k8s-job-notify
or improve different storage classes for different type of backup
or implements different backup retention policy for different subset of tables
