### ISSUE TITLE
`create` and `upload` succeeded but file empty

### ISSUE THREAD

**Issue by fanshi118** [Altinity/clickhouse-backup#89]
I used the [latest release](https://github.com/AlexAkulov/clickhouse-backup/releases) to make a backup for a table. I ran `./clickhouse-backup create -t=db.table <my_backup>` and `./clickhouse-backup upload <my_backup>` with the modified config file. Both commands ran okay, but files in both local and remote were empty. What did I miss?

> 2020/05/13 17:52:42 Create backup 'my_backup'
> 2020/05/13 17:52:42 Freeze `db`.`table`
> 2020/05/13 17:52:42 Copy metadata
> 2020/05/13 17:52:42   Done.
> 2020/05/13 17:52:42 Move shadow
> 2020/05/13 17:52:42 open my_path/shadow: no such file or directory

**Comment by AlexAkulov** [comment]
Hello!
This is not okay
>  2020/05/13 17:52:42 open my_path/shadow: no such file or directory 

It seems that `clickhouse.data_path` in config file is not correct. Try to remove `data_path` option if you have set it manually.

**Comment by fanshi118** [comment]
> Hello!
> This is not okay
> 
> > 2020/05/13 17:52:42 open my_path/shadow: no such file or directory
> 
> It seems that `clickhouse.data_path` in config file is not correct. Try to remove `data_path` option if you have set it manually.

Thanks for getting back to me quickly. I've actually tried using the default data_path too, but there's this other issue:
> can't create backup with `/var/lib/clickhouse/backup/<backup_name>` already exists

regardless of which backup name I pick. Any idea on what could've gone wrong here?

**Comment by AlexAkulov** [comment]
Maybe it is related to permissions on /var/lib/clickhouse/backup/. Do you run clickhouse-backup from 'root' or 'clickhouse' user?

**Comment by AlexAkulov** [comment]
I fixed this wrong error message in https://github.com/AlexAkulov/clickhouse-backup/commit/dbf9c546f482955cdbe3df67c4b93975fd7170e8

**Comment by fanshi118** [comment]
> Maybe it is related to permissions on /var/lib/clickhouse/backup/. Do you run clickhouse-backup from 'root' or 'clickhouse' user?

yes…working now. thanks for the fix
