### ISSUE TITLE
The range of support for the BACKUP functionality

### ISSUE THREAD

**Issue by dxygit1** [Altinity/clickhouse-backup#891]
Does the BACKUP functionality support protocols like FTP in addition to S3?

```
clickhouse>
    <storage_configuration>
        <disks>
            <backups>
                <type>local</type>
                <path>/backups/</path>
            </backups>
        </disks>
    </storage_configuration>
    <backups>
        <allowed_disk>backups</allowed_disk>
        <allowed_path>/backups/</allowed_path>
    </backups>
</clickhouse>
```

**Comment by Slach** [comment]
no, this is part of `clickhouse-server` configuration, and `clickhouse-server` have no reason why they need to use FTP for "object disks"


if you want use clickhouse-backup with FTP use standard relular approach withtout `use_embedded_backup_restore: true`
