### ISSUE TITLE
Upload backup not ended

### ISSUE THREAD

**Issue by lars301** [Altinity/clickhouse-backup#90]
Привет Alex.

clickhouse-backup -v
Version:         v0.5.1

clickhouse-backup list
Local backups:
- '2020-05-19T08-38-16' (created at 19-05-2020 11:38:16)
Remote backups:
no backups found

clickhouse-backup upload 2020-05-19T08-38-16
2020/05/19 19:17:43 Upload backup '2020-05-19T08-38-16'
 1.21 GiB / 1.21 GiB [===.....==] 100.00%
^C
Upload зависает на 100% и больше ничего не происходит. 
На стороне S3 естественно пусто.
С чем может быть связано такое поведение?
Заранее спасибо!

**Comment by AlexAkulov** [comment]
Привет!
Я полагаю он не завис, если подождать то он докачает. 
Там проценты вычисляются по тому сколько данных фактически с диска считано, а не сколько отправлено. Он прочитал все файлы с диска, но ещё отправляет последний кусок по сети.
Думаю можно увидеть активность через такие утилиты как nethogs или tcpdump.

**Comment by lars301** [comment]
Уже 4 часа висит. 
Учитывая по сути мизерный объем данных(1,2 Gb), это не нормально.

tcpdump на обоих концах:
0 packets captured
0 packets received by filter
0 packets dropped by kernel

В качестве S3 пробовал Minio и Scality.
Результат один и тот же.
Обычные файлы загружаются.

**Comment by AlexAkulov** [comment]
Да, 4 часа это не нормально. 
Странно, minio я использую в интеграционных тестах и вроде всё работает нормально.  
Какая у вас версия minio и какие настройки clickhouse-backup?

**Comment by lars301** [comment]
Minio VERSION
2020-05-16T01:33:21Z

general:
  remote_storage: s3
  disable_progress_bar: false
  backups_to_keep_local: 0
  backups_to_keep_remote: 1
clickhouse:
  username: default
  password: ""
  host: localhost
  port: 9000
  data_path: ""
  skip_tables:
  - system.*
s3:
  access_key: "minioadmin"
  secret_key: "minioadmin"
  bucket: "clickhouse-backup"
  endpoint: "http://X.X.X.X:9000/"
  acl: private
  force_path_style: true
  path: ""
  disable_ssl: false
  part_size: 104857600
  compression_level: 1
  compression_format: tar
  sse: ""
  disable_cert_verification: false


На стороне minio:
pwd
/mnt/data/.minio.sys/tmp/8386e9d1-ca92-49df-b6c4-c21c201079e3

ls -ltha
total 12G
-rw-r--r-- 1 root root 1000M May 20 11:51 89afc952-1a5c-4e51-bb47-d68dbf0d1569.1e8c039c-36e5-459c-9033-b22bbb524540

Все временные файлы одного размера 1000M
Судя по всему, срабатывает ограничение на размер файла и upload виснет.

Файлы меньшего размера через clickhouse-backup загружаются.

**Comment by lars301** [comment]
Добрый день Александр.
Извините за настойчивость.
Удалось ли Вам  воспроизвести проблему?
Спасибо.

**Comment by AlexAkulov** [comment]
Добрый день!

С ходу не получилось, сегодня вечером постараюсь ещё попробовать.

**Comment by AlexAkulov** [comment]
Попробовал на образе `minio/minio:RELEASE.2020-05-16T01-33-21Z` всё работает нормально, файлы больше гигабайта успешно закачиваются, скачиваются, удаляются.
Вы уверены что проблема не на стороне сервера с minio? Другие утилиты нормально закачивают большие файлы, например s3cmd?

**Comment by lars301** [comment]
Использовал S3Browser. Закачивает без проблем. На Scality та же проблема. А Вы бинарную версию тестировали?

**Comment by AlexAkulov** [comment]
Получилось решить проблему?

**Comment by lars301** [comment]
Да. Она была на стороне S3.  Спасибо. Извините за беспокойство.
