### ISSUE TITLE
clickhouse is fail to start

### ISSUE THREAD

**Issue by yaswanthmedisetti** [Altinity/clickhouse-backup#909]
Hi @Slach 
i increased instance type and disk size. After that clickhouse is not working.
before it worked.

 clickhouse client
ClickHouse client version 21.10.2.15 (official build).
Connecting to localhost:9000 as user default.
Code: 210. DB::NetException: Connection refused (localhost:9000). (NETWORK_ERROR)

[nodejs@ip-172-31-54-11 centos]$  systemctl status clickhouse-server
● clickhouse-server.service - ClickHouse Server (analytic DBMS for big data)
   Loaded: loaded (/etc/systemd/system/clickhouse-server.service; enabled; vendor preset: disabled)
   Active: activating (auto-restart) (Result: exit-code) since Thu 2024-05-02 10:05:17 UTC; 16s ago
  Process: 21255 ExecStart=/usr/bin/clickhouse-server --config=/etc/clickhouse-server/config.xml --pid-file=/run/clickhouse-server/clickhouse-server.pid (code=exited, status=70)
 Main PID: 21255 (code=exited, status=70)

**Comment by Slach** [comment]
issue is not related to `clickhouse-backup`
your `clickhouse-server` is not running

look to something like that `journalctl -xue --no-pager clickhouse-server.service`

**Comment by Slach** [comment]
also look to
`/var/log/clickhouse-server/clickhouse-server.err.log`

**Comment by yaswanthmedisetti** [comment]
(version 21.10.2.15 (official build))
2024.05.02 10:48:01.266771 [ 2462 ] {} <Error> Application: Coordination::Exception: All connection tries failed while connecting to ZooKeeper. nodes: 172.31.42.152:2181
Poco::Exception. Code: 1000, e.code() = 0, Timeout: connect timed out: 172.31.42.152:2181 (version 21.10.2.15 (official build)), 172.31.42.152:2181
Poco::Exception. Code: 1000, e.code() = 0, Timeout: connect timed out: 172.31.42.152:2181 (version 21.10.2.15 (official build)), 172.31.42.152:2181
Poco::Exception. Code: 1000, e.code() = 0, Timeout: connect timed out: 172.31.42.152:2181 (version 21.10.2.15 (official build)), 172.31.42.152:2181
 (Connection loss): Cannot attach table `default`.`test_user_local` from metadata file /var/lib/clickhouse/store/889/889aad3d-55fa-499d-889a-ad3d55fa299d/test_user_local.sql from query ATTACH TABLE default.test_user_local UUID 'b35cdd81-6f1d-4407-b35c-dd816f1da407' (`tenant_id` String, `username` String, `user_id` String, `email` String, `joining_date` Date) ENGINE = ReplicatedMergeTree('/clickhouse/all_replicated/xxxxx_test/tables/test_user_local/shard1', 'replica') PARTITION BY toYYYYMM(joining_date) ORDER BY username SETTINGS index_granularity = 8192: while loading database `default` from path /var/lib/clickhouse/metadata/default

**Comment by yaswanthmedisetti** [comment]
-- The start-up result is done.
May 02 10:49:40 ip-172-31-54-11.us-west-2.compute.internal clickhouse-server[3055]: Processing configuration file '/etc/clickhouse-server/config.xml'.
May 02 10:49:40 ip-172-31-54-11.us-west-2.compute.internal clickhouse-server[3055]: Merging configuration file '/etc/clickhouse-server/config.d/cluster.xml'.
May 02 10:49:40 ip-172-31-54-11.us-west-2.compute.internal clickhouse-server[3055]: Merging configuration file '/etc/clickhouse-server/config.d/config.xml'.
May 02 10:49:40 ip-172-31-54-11.us-west-2.compute.internal clickhouse-server[3055]: Merging configuration file '/etc/clickhouse-server/config.d/macros.xml'.
May 02 10:49:40 ip-172-31-54-11.us-west-2.compute.internal clickhouse-server[3055]: Merging configuration file '/etc/clickhouse-server/config.d/zookeeper.xml'.
May 02 10:49:40 ip-172-31-54-11.us-west-2.compute.internal clickhouse-server[3055]: Logging trace to /var/log/clickhouse-server/clickhouse-server.log
May 02 10:49:40 ip-172-31-54-11.us-west-2.compute.internal clickhouse-server[3055]: Logging errors to /var/log/clickhouse-server/clickhouse-server.err.log
May 02 10:49:41 ip-172-31-54-11.us-west-2.compute.internal clickhouse-server[3055]: Processing configuration file '/etc/clickhouse-server/config.xml'.
May 02 10:49:41 ip-172-31-54-11.us-west-2.compute.internal clickhouse-server[3055]: Merging configuration file '/etc/clickhouse-server/config.d/cluster.xml'.
May 02 10:49:41 ip-172-31-54-11.us-west-2.compute.internal clickhouse-server[3055]: Merging configuration file '/etc/clickhouse-server/config.d/config.xml'.
May 02 10:49:41 ip-172-31-54-11.us-west-2.compute.internal clickhouse-server[3055]: Merging configuration file '/etc/clickhouse-server/config.d/macros.xml'.
May 02 10:49:41 ip-172-31-54-11.us-west-2.compute.internal clickhouse-server[3055]: Merging configuration file '/etc/clickhouse-server/config.d/zookeeper.xml'.
May 02 10:49:41 ip-172-31-54-11.us-west-2.compute.internal clickhouse-server[3055]: Saved preprocessed configuration to '/var/lib/clickhouse/preprocessed_configs/config.xml'.
May 02 10:49:41 ip-172-31-54-11.us-west-2.compute.internal clickhouse-server[3055]: Processing configuration file '/etc/clickhouse-server/users.xml'.
May 02 10:49:41 ip-172-31-54-11.us-west-2.compute.internal clickhouse-server[3055]: Saved preprocessed configuration to '/var/lib/clickhouse/preprocessed_configs/users.xml'.
May 02 10:49:45 ip-172-31-54-11.us-west-2.compute.internal systemd[1]: clickhouse-server.service: main process exited, code=exited, status=70/n/a
May 02 10:49:45 ip-172-31-54-11.us-west-2.compute.internal systemd[1]: Unit clickhouse-server.service entered failed state.
May 02 10:49:45 ip-172-31-54-11.us-west-2.compute.internal systemd[1]: clickhouse-server.service failed.

**Comment by Slach** [comment]
run your zookeeper / keeper on 172.31.42.152:2181

**Comment by Slach** [comment]
clickhouse-server cant' attach ReplicatedMergeTree tables cause can't connect to zookeeper
look <zookepeer> section in your configs

**Comment by yaswanthmedisetti** [comment]
one I increased only disk - but why change these things I am not under stand.




<yandex>
    <zookeeper>
        <node>
            <host>ip-172-31-42-152.us-west-2.compute.internal</host>
            <port>2181</port>
        </node>
    </zookeeper>
</yandex>

**Comment by Slach** [comment]
172.31.42.152:2181
 is this IP of your server?
 is this the same server with clickhouse-server?
 if yes
 what show
`systemctl status zookeeper.service` ?

**Comment by yaswanthmedisetti** [comment]
> is this the same server with clickhouse-server

above IP server is different
 and this clickhouse server is different
here onlynodejs user only. its not user also I think.

**Comment by yaswanthmedisetti** [comment]
● zookeeper.service - Zookeeper Service
   Loaded: loaded (/usr/lib/systemd/system/zookeeper.service; enabled; vendor preset: disabled)
   Active: active (running) since Thu 2024-05-02 09:13:56 UTC; 2h 11min ago
 Main PID: 3089 (java)
   CGroup: /system.slice/zookeeper.service
           └─3089 java -Dzookeeper.log.dir=/opt/zookeeper/apache-zookeeper-3.7.0-bin/bin/../logs -Dzookeeper.log.file=zookeeper-zookeeper-server-ip-172-31-54-11.us-west-2.compute.interna...

May 02 09:13:56 ip-172-31-54-11.us-west-2.compute.internal systemd[1]: Started Zookeeper Service.
May 02 09:13:57 ip-172-31-54-11.us-west-2.compute.internal zookeeper[2810]: /usr/bin/java
May 02 09:13:57 ip-172-31-54-11.us-west-2.compute.internal zookeeper[2810]: ZooKeeper JMX enabled by default
May 02 09:13:57 ip-172-31-54-11.us-west-2.compute.internal zookeeper[2810]: Using config: /opt/zookeeper/apache-zookeeper-3.7.0-bin/bin/../conf/zoo.cfg

**Comment by yaswanthmedisetti** [comment]
2024.05.02 11:36:08.795947 [ 13169 ] {} <Information> Application: starting up
2024.05.02 11:36:08.795968 [ 13169 ] {} <Information> Application: OS name: Linux, version: 3.10.0-957.10.1.el7.x86_64, architecture: x86_64
2024.05.02 11:36:08.994423 [ 13169 ] {} <Information> Application: Calculated checksum of the binary: 902F2F159F07FEEC02834AEF44CBFB70, integrity check passed.
2024.05.02 11:36:08.994692 [ 13169 ] {} <Trace> Application: Will do mlock to prevent executable memory from being paged out. It may take a few seconds.
2024.05.02 11:36:09.010801 [ 13169 ] {} <Trace> Application: The memory map of clickhouse executable has been mlock'ed, total 211.02 MiB
2024.05.02 11:36:09.011213 [ 13169 ] {} <Error> Application: DB::Exception: Effective user of the process (root) does not match the owner of the data (clickhouse). Run under 'sudo -u clickhouse'.
2024.05.02 11:36:09.011241 [ 13169 ] {} <Information> Application: shutting down
2024.05.02 11:36:09.011251 [ 13169 ] {} <Debug> Application: Uninitializing subsystem: Logging Subsystem
2024.05.02 11:36:09.011347 [ 13170 ] {} <Trace> BaseDaemon: Received signal -2
2024.05.02 11:36:09.011399 [ 13170 ] {} <Information> BaseDaemon: Stop SignalListener thread

**Comment by Slach** [comment]
```
2024.05.02 11:36:09.011213 [ 13169 ] {} Application: DB::Exception: Effective user of the process (root) does not match the owner of the data (clickhouse). Run under 'sudo -u clickhouse'.
```

this is part of clickhouse-server logs
how did you exactly try to run it?

use
`sudo systemctl start clickhouse-server.service`

**Comment by yaswanthmedisetti** [comment]
> sudo systemctl start clickhouse-server.service

![image](https://github.com/Altinity/clickhouse-backup/assets/155810198/df61edca-08cd-4537-8c45-761387da577e)

**Comment by Slach** [comment]
`telnet 172.31.42.152 2181`

**Comment by Slach** [comment]
> ```
> Loaded: loaded (/usr/lib/systemd/system/zookeeper.service; enabled; vendor preset: disabled)
> Active: active (running) since Thu 2024-05-02 09:13:56 UTC; 2h 11min ago
> ```

is this result of systemctl status from 172.31.42.152? or from the server where run clickhouse-server?

**Comment by yaswanthmedisetti** [comment]
> telnet 172.31.42.152 2181

from click house server

![image](https://github.com/Altinity/clickhouse-backup/assets/155810198/aeb69638-b0ba-4f0c-84e5-91d245da2657)

**Comment by Slach** [comment]
can you login to ssh  172.31.42.152

Do you know what is `172.31.42.152` address?

check your clickhouse zookeeper settings

`grep -C 10 zookeeper -r /etc/clickhouse-server/`

is these settings still actual?

**Comment by yaswanthmedisetti** [comment]
> grep -C 10 zookeeper -r /etc/clickhouse-server/

![image](https://github.com/Altinity/clickhouse-backup/assets/155810198/902d1560-38b8-416d-9d63-4272e6f3f610)
in both servers

**Comment by Slach** [comment]
check your AWS console, and ask your devops to check network policies which restricted access to your zookeeper server

after change EC2 instance type you could change your internal IP address

could you please stop write here, i'm not free AWS support, your troubles is unrelated to clickhouse-backup, completelly

**Comment by yaswanthmedisetti** [comment]
> ge EC2 instance type you could change your internal IP address

private ips right no need to change.

ok
