### ISSUE TITLE
EKS Irsa doesnt work

### ISSUE THREAD

**Issue by manishtradebyte** [Altinity/clickhouse-backup#911]
I folowed this example https://github.com/Altinity/clickhouse-backup/blob/master/Examples.md#how-to-use-aws-irsa-and-iam-to-allow-s3-backup-without-explicit-credentials

I get this error when i try to backup  using the sample cron job.
```
error   can\'t upload chi-test-backups-default-0-0-full-2024-05-03-12-15-00/metadata.json: operation error S3: PutObject, https response error StatusCode: 400, RequestID: VZ1M3WRZ9RDPQBCK, HostID: ITvn4MddacTz4zDnpordJYDYsFnz/4lyW0m2BHSvgjZxTrHp1WoWWE1q9FF28hilZ0YHRdNClVc=, api error AuthorizationHeaderMalformed: The authorization header is malformed; the region \'us-east-1\' is wrong; expecting \'eu-central-1\'

```
My bucket  and cluster are both in eu-central-1

**Comment by Slach** [comment]
It works, setup `S3_REGION` inside `clickhouse-backup` container
or iside /etc/clickhouse-backup/config.yml
```
s3:
 region: eu-central-1
```
