### ISSUE TITLE
Create_remote results in `error: data in objects disks` (Azure Blob)

### ISSUE THREAD

**Issue by fbloo** [Altinity/clickhouse-backup#912]
We have upgraded our clickhouse-backup image from `2.4.0` to `2.5.3` and now face errors when backups are being created.

```
error metrics.ExecuteWithMetrics(create_remote) return error: data in objects disks, invalid azblob->object_disk_path config section, shall be not empty and shall not be prefix for gcs->path logger=metrics
error API /backup/actions error: data in objects disks, invalid azblob->object_disk_path config section, shall be not empty and shall not be prefix for gcs->path logger=server
```

The main issue is, we are not able to get this reproduced consistently, for example:
- Emptied our remote destination (Azure Blob)
- Run backup: with success
- Run the backup few times (5 times): with success 
- Run it again: and it fails

The number of times after which it fails with the errors ranges from 2 to 6; it could be related to actual data changes in our ClickHouse database, but I can't rule that out.

Am I missing something obvious, are there any other tools/tricks to debug this?

**Context:**
- ClickHouse Version: 24.3.2
- ClickHouse Backup: 2.5.3
  - `ALLOW_EMPTY_BACKUPS` = `true`
  - `REMOTE_STORAGE` = `azblob
  - `USE_EMBEDDED_BACKUP_RESTORE` not set

**Comment by Slach** [comment]
please upgrade to 2.5.6
duplicated with https://github.com/Altinity/clickhouse-backup/issues/910

**Comment by romaka** [comment]
This has happened to us on 2.6.1 (ClickHouse server version 23.4.2 revision 54462) with remote storage gcs after adding a disk of s3 type to <storage_configuration> section of clickhouse-server configuration. The disc has been added for moving rows from a couple of tables to s3 using ttl mechanism so it has nothing to do with backups at all.

```
SELECT
    name,
    path,
    type,
    is_remote
FROM system.disks

Query id: 3778802f-5f03-48d3-87bf-d6388c5b29a2

Row 1:
──────
name:      default
path:      /var/lib/clickhouse/
type:      local
is_remote: 0

Row 2:
──────
name:      gcs
path:      /var/lib/clickhouse/disks/gcs/
type:      s3
is_remote: 1

SELECT *
FROM system.storage_policies

Query id: 9f6c8aba-5be8-4264-ae04-aedde4860ba3

Row 1:
──────
policy_name:                default
volume_name:                default
volume_priority:            1
disks:                      ['default']
volume_type:                JBOD
max_data_part_size:         0
move_factor:                0
prefer_not_to_merge:        0
perform_ttl_move_on_insert: 1
load_balancing:             ROUND_ROBIN

Row 2:
──────
policy_name:                gcs_main
volume_name:                main
volume_priority:            1
disks:                      ['gcs']
volume_type:                JBOD
max_data_part_size:         0
move_factor:                0.1
prefer_not_to_merge:        0
perform_ttl_move_on_insert: 1
load_balancing:             ROUND_ROBIN

Row 3:
──────
policy_name:                gcs_main
volume_name:                default
volume_priority:            2
disks:                      ['default']
volume_type:                JBOD
max_data_part_size:         0
move_factor:                0.1
prefer_not_to_merge:        0
perform_ttl_move_on_insert: 1
load_balancing:             ROUND_ROBIN

```

**Comment by Slach** [comment]
@romaka could you provide full error message?

and share
`clickhouse-backup print-config` without sensitive credentials?

**Comment by romaka** [comment]
sure:

`ERR pkg/backup/create.go:139 > backup failed error: data in objects disks, invalid gcs->object_disk_path config section, shall be not empty and shall not be prefix for gcs->path`

The `clickhouse-backup print-config` output is in attachment. We're using `GCS_*` env variables to define credentials file, bucket name and path.

[cfg.txt](https://github.com/user-attachments/files/18111992/cfg.txt)

**Comment by Slach** [comment]
If you have gcs disk, then you can't create only local backup

in shared config you defined
```yaml
general:
    remote_storage: gcs
```

but
```yaml
gcs:
    credentials_file: ""
    credentials_json: ""
    credentials_json_encoded: ""
    bucket: ""
    path: ""
    object_disk_path: ""
```

so, define css credentials to allow access backup bucket and your gcs disk bucket
and define following parameters
```
  bucket: your-bucket-name
  path: "backup/{cluster}/{shard}"
  object_disk_path: "object_disks/{cluster}/{shard}"
```

**Comment by romaka** [comment]
we have the following set of ENV variables that are defined for `clickhouse-backup server` daemon via systemd unit file:

```
GCS_CREDENTIALS_FILE=/root/.secrets/XXXXXXXXX-XXXXX-XXXXXX-XXXXXXXXXXXX.json
GCS_BUCKET=XXXXX-XXXXXXXXX-XXXXXXX
GCS_PATH=XXXXX-XXXXXXXXXX-XX
```

once it's started, we place the `watch` task via clickhouse-backup http api setting `full_interval` and `watch_interval` through GET params

so clickhouse-backup certainly knows where to store data. the problem arose after addition of gcs disk along with appropriate storage_policy in clickhouse-server configuration. the gcs disk uses different bucket and access credentials. the tables that have ttl settings for moving data to s3-backed volumes are listed in `skip_tables` .

**Comment by Slach** [comment]
ok. in this case you need to add in systemd unit
```
GCS_OBJECT_DISK_PATH=YYYYYY
```
and apply `systemctl restart clickhouse-backup`
