### ISSUE TITLE
Not starting the upload on qnap s3

### ISSUE THREAD

**Issue by EmPRio93** [Altinity/clickhouse-backup#92]
Hi, i have tried to backup and restore and it works great. But now i need to save the backup on my qnap object storage and when I'm starting the upload command it's stucks at the start, how could i get some logs from the app ? Or some any debug flag. 
![image](https://user-images.githubusercontent.com/55250036/83610855-4fcbc880-a5aa-11ea-9bb7-f836741c490a.png)

**Comment by AlexAkulov** [comment]
Hello!
A progress bar should be shown here, but before that, calculate the size of all the files, and if there are a lot of files, it can take a lot of time.
How big is your backup and how long do you wait?

**Comment by EmPRio93** [comment]
![image](https://user-images.githubusercontent.com/55250036/84354869-d3f5ff80-abeb-11ea-9311-d303177a65d3.png)
I waited for an hour for that error message :) I think its an qnap s3 error.
