### ISSUE TITLE
How to backup replica clickhouse cluster correctly ?

### ISSUE THREAD

**Issue by lamnh02** [Altinity/clickhouse-backup#920]
i have a replica clickhouse cluster include 2 rep:

```
<yandex>
    <remote_servers>
        <production>
            <shard>
                <replica>
                    <host>ch-test1</host>
                    <port>9000</port>
                    <user>default</user>
                    <password>admin</password>
	        </replica>
		<replica>
                    <host>ch-test2</host>
                    <port>9000</port>
                    <user>default</user>
                    <password>admin</password>
                </replica>
            </shard>
        </production>
    </remote_servers>
</yandex>
```

I am trying to restore the tables using clickhouse-backup and restore in the new cluster with the same config.
But it seems that after restoring in both 2 new clickhouse nodes: (clickhouse-backup restore --rm pmm1)
I can still insert new records to each node but they can no longer replicate each other

Can someone tell me the correct way to backup and restore a clickhouse replica cluster?

**Comment by Slach** [comment]
check command sequence in https://github.com/Altinity/clickhouse-backup/blob/master/Examples.md#how-to-back-up--restore-a-sharded-cluster

> I can still insert new records to each node but they can no longer replicate each other


Do your tables have `ReplicatedMergeTree` engine?
Do your destination cluster have the same Zookeeper settings?
