### ISSUE TITLE
URL is getting malformed while running restore_remote command with azure_blob_store

### ISSUE THREAD

**Issue by rishi-cds** [Altinity/clickhouse-backup#931]
We have setup clickhouse-backup CLI in our Clickhouse installation in Azure Kubernetes Service. after that using Clickhosue bakcup CLI we were able to take the backup of our Clickhouse cluster and files were uploaded successfully in the Azure container.

While restoring the same backup with same config, we are getting below error.

```
2024/06/07 13:03:12.276382 error one of restoreDataRegular go-routine return error: can't restore object_disk server-side copy data parts 'default.<table-name>': -> github.com/Azure/azure-pipeline-go/pipeline.NewError, /home/runner/go/pkg/mod/github.com/!azure/azure-pipeline-go@v0.2.3/pipeline/error.go:157
HTTP request failed

Put "https://<account-name>.blob.<storage-account-name>.blob.core.windows.net/<container-name-here>?restype=container&timeout=14401": dial tcp: lookup <storage-account-name>.blob.<storage-account-name>.blob.core.windows.net on 10.0.0.10:53: no such host
```

looks like it is appending an additional `account_name.blob` in the URL.

here is the config file we used.

```
general:
    remote_storage: azblob
    log_level: info
    allow_empty_backups: false
    upload_by_part: true
    download_by_part: true

clickhouse:
    username: "<ch-user>"
    password: "<ch-password>"
    host: localhost
    port: 9000
    disk_mapping: {}

azblob:
    account_name: "<storage-account-name>"
    use_managed_identity: true
    container: "<container-name>"
    debug: true
```

**Comment by Slach** [comment]
actually it looks like DNS issue and maybe not related to clickhouse-backup itself
hostname created inside SDK

need more context for reproducing

do you have object disks data?

could you share?
```sql
SELECT * FROM system.disks
SELECT * FROM system.storage_policies
```

**Comment by Slach** [comment]
also could you check log erorrs near
`AZBLOB->CopyObject`

**Comment by Slach** [comment]
is any news from your side?

**Comment by Slach** [comment]
closing due issue reporter inactivity
