### ISSUE TITLE
Implementation --restore-table-mapping

### ISSUE THREAD

**Issue by raspreet-vunet** [Altinity/clickhouse-backup#937]
It looks like the tool doesn't support restoring a table backup to a table with a different name. In clickhouse, we can do this by using the `[AS [db.]table_name_in_backup]` clause in the `RESTORE TABLE`. For the restore related commands, we can have an option similar to `--restore-database-mapping` which can be used to accomplish this.

**Comment by Slach** [comment]
you are welcome to make pull request

**Comment by raspreet-vunet** [comment]
sure
