### ISSUE TITLE
`clean` command does not work with POST /backup/actions. 

### ISSUE THREAD

**Issue by joelbandi** [Altinity/clickhouse-backup#945]
```bash
# curl -X POST -d '{"command":"clean"}' localhost:7171/backup/actions
{"status":"error","operation":"clean","error":"unknown command"}

# clickhouse-backup version
Version:	 2.4.2
Git Commit:	 8f6fe6b26fad2390dd9d7223b86296cba57b22e8
Build Date:	 2023-10-12
```

clickhouse-server version: 23.8.3.48

Looks like were missing a case for `clean` in this switch statement in the api response handler 
https://github.com/Altinity/clickhouse-backup/blob/e111dc47f449ac92ca9291f0daf836c543b78009/pkg/server/server.go#L347

**Comment by Slach** [comment]
thanks for reporting
