### ISSUE TITLE
Restore RBAC on cluster 

### ISSUE THREAD

**Issue by Soterix** [Altinity/clickhouse-backup#948]
Hey, 

As I can see right now ClickHouse-Backup embeds information about users, roles and grants into backup.
Also this information can be restored using `--rbac` flag while restore. But restored RBAC information will not be replicated to other replicas in shard automatically. 

So, it will be needed to run restore on each replica individually in case of RBAC. 

What is in opposite to restoration of scheme and data, as here enough to run restore on single replica and restored scheme and data will be automatically replicated between replicas.

Is everything described above is correct and with ClickHouse-Backup 2.5.20 it is not possible to restore RBAC on all replicas by restoring backup only on one of them?

Is there any plans to support such a case?

Thanks in advance.

**Comment by Slach** [comment]
by default, `RBAC` objects is not replicated on ClickHouse side

to replicate `RBAC` objects during restore you need to use user directories which stored in zookeeper/keeper

**/etc/clickhouse-server/config.d/replicated_user_directories.xml**

```xml
<clickhouse>
  <user_directories replace="replace">
    <users_xml>
      <path>users.xml</path>
    </users_xml>
    <replicated>
        <zookeeper_path>/clickhouse/access</zookeeper_path>
    </replicated>
  </user_directories>
</clickhouse>
```

Unfortunately, I don't know solution to convert /var/lib/clickhouse/access to zookeeper/keeper
