### ISSUE TITLE
Not able to restore backups - no such file or directory

### ISSUE THREAD

**Issue by LukaszMarchewka** [Altinity/clickhouse-backup#951]
restore_remote operation isn't deterministic and sometimes throws errors like:
- `open /bitnami/clickhouse/..../metadata.json: no such file or directory`
- downloadWithDiff -> RemoveBackupLocal cleaning error: ... is not found on local storage`

These errors happen sometimes, the second execution is sometimes successful (from the same backup). Maybe the problem is related to https://github.com/Altinity/clickhouse-backup/issues/950

More logs:
![image](https://github.com/user-attachments/assets/45033e49-941a-4308-a45d-682f519019b6)
![image](https://github.com/user-attachments/assets/ac749ad7-c3db-49cb-9f55-45f981f689f5)

(sorry, I don't have more info just now, mostly I have different issues, these one are more seldom).

**Comment by Slach** [comment]
let's close issue, maybe two separate clickhouse-backup instance 
but need more logs corresponding to shared screen time period
