### ISSUE TITLE
Can't change I/O priority

### ISSUE THREAD

**Issue by joserocha** [Altinity/clickhouse-backup#953]
Every time I try to execute clickhouse-backup using clickhouse user, I receive this warning:

`sudo -u clickhouse /usr/local/bin/clickhouse-backup clean`
`2024/07/12 18:18:15.240341  warn can't set i/o priority idle, error: operation not permitted`

This warning does not occur when I use root user, so it's obvious that I have some problems involving permission, but I'm not sure what to do here, and I don't want to change the permissions that Clickhouse has. Any ideas?

I use Rocky Linux as my oficial distro:
`cat /etc/redhat-release`
`Rocky Linux release 9.4 (Blue Onyx)`

**Comment by Slach** [comment]
This is just a warning

you can use
`sudo setcap cap_sys_nice=+ep /usr/local/bin/clickhouse-backup`

and warning should gone away
