### ISSUE TITLE
metadata не бэкапится при установке data_path

### ISSUE THREAD

**Issue by nikulin-anton** [Altinity/clickhouse-backup#96]
Здравствуйте!

В Clickhouse я использую два разных диска. Их путь отличается от стандартного `/var/lib/clickhouse/`. Количество дисков в данном случае значения не имеет, поэтому я расскажу на примере одного. Допустим, путь - это `/some/path/`.

- Я указываю в конфигурации `data_path: /some/path/`
- Делаю бэкап через `./clickhouse-backup create %backup_name%` и все проходит отлично:
```
2020/06/09 21:08:04 Create backup '%backup_name%'
2020/06/09 21:08:04 Freeze `%db_name%`.`%table_name%`
2020/06/09 21:08:04 Copy metadata
2020/06/09 21:08:04   Done.
2020/06/09 21:08:04 Move shadow
2020/06/09 21:08:04   Done.
```
- Делаю восстановление через `./clickhouse-backup restore %backup_name%`
- Получаю ошибку:
```
2020/06/09 21:09:04 stat /some/path/backup/%backup_name%/metadata: no such file or directory
```

Если я не ошибаюсь, то путь до `metadata` берется относительно `data_path`: https://github.com/AlexAkulov/clickhouse-backup/blob/dbf9c546f482955cdbe3df67c4b93975fd7170e8/pkg/chbackup/backup.go#L379

При использовании отдельных дисков метаданные Clickhouse всегда остаются в директории по умолчанию. В документации, к сожалению, не нашел, но есть пример: https://www.altinity.com/blog/2019/11/29/amplifying-clickhouse-capacity-with-multi-volume-storage-part-2. Поиск по строке `Note that the table metadata remains on the default disk. `.

Отсюда вопрос. Это ошибка или есть какой-то другой способ сделать бэкап со всех дисков разом с помощью одного конфигурационного файла?

**Comment by AlexAkulov** [comment]
Добрый день! 
clickhouse-backup пока не поддерживает storage policies.

**Comment by nikulin-anton** [comment]
Понял, спасибо)
В таком случае, вероятно, можно закрывать.

**Comment by 404notfoundhard** [comment]
@AlexAkulov 
А в роадмапе есть такое? Очень хочется

**Comment by AlexAkulov** [comment]
Можете попробовать собрать код из ветки dev. Там есть create/restore с поддержкой нескольких дисков но пока нет upload/download. 
Ну и пока возможны баги, конечно же.
