### ISSUE TITLE
Logs of CLI commands should go to stderr?

### ISSUE THREAD

**Issue by lainiwa** [Altinity/clickhouse-backup#969]
Currently clickhouse-backup logs everything to stdout.
This makes it harder to script.

An example:

```sh
# Otherwise `clickhouse-backup list` will contaminate stdout
export LOG_LEVEL=error

# ...
# Override S3_PATH: we cannot do that in a http request
LATEST_BACKUP_SHARD_5=$(S3_PATH=clickhouse/shard-5 clickhouse-backup list remote latest)
```

This works, but it will swallow all the non-error info, that might be valuable otherwise.

**Comment by Slach** [comment]
currently not, could you help us with race conditions when switching to zerolog
https://github.com/Altinity/clickhouse-backup/pull/670, this log library can write different log level to different steams

**Comment by lainiwa** [comment]
Unfortunately I don't think I could help as my golang experience is none.

Anyways, maybe #670 is only tangentially related to this issue:
writing different log levels to different streams might be useful for daemon-like services, like `clickhouse-backup server` or `clickhouse-backup watch`,
but I think CLI utils should redirect strictly **all logs** to stderr, as opposed to the actual return value.

**Comment by Slach** [comment]
ok. let's change current behavior
