### ISSUE TITLE
Typo in error message

### ISSUE THREAD

**Issue by browseman** [Altinity/clickhouse-backup#98]
Hello

Found this typo "clickouse" -> "click**h**ouse":
`pkg/chbackup/backup.go:153:		return fmt.Errorf("can't connect to clickouse with: %v", err)
pkg/chbackup/backup.go:200:		return fmt.Errorf("can't connect to clickouse with %v", err)
pkg/chbackup/backup.go:313:		return fmt.Errorf("can't connect to clickouse with: %v", err)
pkg/chbackup/backup.go:450:		return fmt.Errorf("can't connect to clickouse with: %v", err)`

**Comment by AlexAkulov** [comment]
Thank you!
