### ISSUE TITLE
error no have found schemas by *

### ISSUE THREAD

**Issue by vasylkolomiets** [Altinity/clickhouse-backup#982]
Hi.
clickhouse-backup create_remote -t 'test.*' test_full.backup - on the main clickhouse server
clickhouse-backup download test_full.backup - on the reserv server
clickhouse-backup restore test_full.backup - on the reserv server -> error no have found schemas by * in test_full.backup

I also tried clickhouse-backup restore_remote but some partitions data folders not was copied from remote backup however in metadata this partitions exists and in backup on the main backup server all is fine exists metadata and data.
Please advice what need to do with this.

**Comment by Slach** [comment]
why you close issue? issue still present or you just solve your problem?
