### ISSUE TITLE
What amount of space should be reserved for backup data for local and remote backups? 

### ISSUE THREAD

**Issue by honobi** [Altinity/clickhouse-backup#983]
For example, my ClickHouse instance occupies 1.5TB of disk space

**Comment by Slach** [comment]
during create operation local backup created via file system hard links
https://en.wikipedia.org/wiki/Hard_link

and will allocate space only when `clickhouse-server` will perform background merges / mutations and eventual delete original data

remote backup usually size equivalent of your current data 1.5TB (could be a little bit less if you use compression_format, but i would like use tar to use less CPU)

during download to exists server you need free 1.5Tb space
restore also happens via hard-links

so restored data will allocate space only when `clickhouse-server` will perform background merges / mutations and eventual delete original data
