### ISSUE TITLE
Add operationId in callback

### ISSUE THREAD

**Issue by manasmulay** [Altinity/clickhouse-backup#995]
Building on top of this [635](https://github.com/Altinity/clickhouse-backup/issues/635) would it be possible to have a operation id in the payload once the operation is complete? This would be useful in case parallel operations are allowed to progress.

Thanks!

**Comment by Slach** [comment]
don't be shy to make pull request

**Comment by manasmulay** [comment]
I have created a [pull request](https://github.com/Altinity/clickhouse-backup/pull/997) for this

This does not provide operation_id in the status API yet, will need to modify the db schema for the same. Would that be ok ? Sorry, its my first time contributing to OSS, would appreciate the review comments and any info on processes to be followed :)
